### ISSUE TITLE
progress bar - size and position

### ISSUE THREAD

**Issue by mneitz** [vimeo/player.js#101]
I need to write an overlay showing the video chapters on the progress bar.
To calculate the correct position I would need to know the position and size of the progress bar. What is the best way to acomplish this request?

many thx - Martin

**Comment by bdougherty** [comment]
Hi, Martin. This is not something that would really be possible. I’d suggest showing some additional UI next to the player to show chapters. You can also use the cuepoint api to be notified when each chapter starts.
