### ISSUE TITLE
Set a start time for embedded videos

### ISSUE THREAD

**Issue by RobertBoes** [vimeo/player.js#103]
### Expected Behavior
When I use the JS player I expect the video to start at 0, or I should be able to toggle the current behaviour or start from 0.

### Actual Behavior
The video starts at a certain time, I think this is to restart the video at the time the viewer stopped the video. This is logical behaviour when you view a video on a Vimeo page, but not always when you're embedding a video.

### Steps to Reproduce
It seemed like it was more likely to happen when I'm logged in to Vimeo. I think it has to do with the cookie  "continuous_play_v3" which is, for me, set to 1.

**Comment by RobertBoes** [comment]
Any update on this? Or what could be the reason of this behaviour?

**Comment by bdougherty** [comment]
You’re seeing the resume playback functionality (has nothing to do with that cookie). It only applies if you’re logged in. There’s no way to turn it off at the moment, but this is definitely a legitimate issue, so we’ll try to figure out what we can do.

**Comment by luwes** [comment]
I think the best option will be to add a setCurrentTime(0) call initially to ensure the player always starts from 0. To keep the API as minimal and clear as possible, a configuration option for this behaviour can't be added. I hope you understand. Thanks!
