### ISSUE TITLE
Changing quality setting causes setInterval to accelerate

### ISSUE THREAD

**Issue by peejallegiance** [vimeo/player.js#1030]
### Expected Behavior
Count the seconds the player has been playing 

### Actual Behavior
Changing quality setting on the Vimeo player causes setInterval to accelerate

### Steps to Reproduce
Consider the following code.  This will count the seconds as the player plays.  However, changing the quality setting in the embedded player will make this count faster each time a new quality setting is selected.
```
//calculate watchtime
players[i].on('playing', function(data) {
    paused = false;
    timer = setInterval(totalWatchTime, 1000);

});

function totalWatchTime(){
    if(!paused){
        console.log("watchTime" + watchTime);
        watchTime += 1;
        localStorage.setItem("watchTime", watchTime);
    }
}
```

**Comment by bdougherty** [comment]
This code does not account for any of the cases where playback is paused, including when the quality is switched.

The easiest thing would be to use [`getPlayed()`](https://github.com/vimeo/player.js?tab=readme-ov-file#getplayed-promisearray-error) instead, but that only counts the sections of the video played, not the total time. If you need the total time, you will have to account for pauses, so you want to look at computing the difference with the currentTime on `timeupdate` and excluding cases where it changes from seeking or buffering.

If you need more assistance with it, the discussions here would be more appropriate, or contact Vimeo support.

**Comment by peejallegiance** [comment]
Thanks Brad! I ommited some of my code in the example above that dealt with pausing.   What I ended up doing is using clearInterval on qualitychange event as well.  Leaving this here in case it helps anyone. 

```
 //check for paused
 players[i].on('pause', function(data) {
    paused = true;
    clearInterval(timer);
});

//calculate watchtime
players[i].on('playing', function(data) {
    paused = false;
    timer = setInterval(totalWatchTime, 1000);

});

function totalWatchTime(){
    if(!paused){
        console.log("watchTime" + watchTime);
        watchTime += 1;
        localStorage.setItem("watchTime", watchTime);
    }
}

//clear interval when quality changes
players[i].on('qualitychange', function(data) {
    clearInterval(timer);
});
```
