### ISSUE TITLE
Events don't work, again!!!!

### ISSUE THREAD

**Issue by jrglaber** [vimeo/player.js#1035]
The problem that occurred did not #1031  happen again. Any plans for fixing it?

**Comment by frausto** [comment]
Also seeing this!!!

**Comment by roemermt** [comment]
@rkrishnan8594 We're also seeing this  again with Vuejs + ionic within iOS devices.

**Comment by rkrishnan8594** [comment]
Thanks all for reporting. We just rolled back a change that may have incidentally caused this. Please re-test and let me know if you're still experiencing the issue.

**Comment by frausto** [comment]
Fixed, thanks!

**Comment by jrglaber** [comment]
Thanks
