### ISSUE TITLE
External player links take over webview in cordova app

### ISSUE THREAD

**Issue by cclobo2** [vimeo/player.js#1036]
### Expected Behavior
Player links open in system browser

### Actual Behavior
Player links take over webview, replacing the cordova app

### Steps to Reproduce
Use the player sdk to load a video in a cordova app. Click the vimeo icon or any other icon that opens an external url. It takes over the webview, effectively replacing the cordova app.

I understand this isn't necessarily a bug but it would be useful to be able to either change the target of the links so they open in the system browser or be able to set the sandbox attribute in sdk generated iframe before setting the source so those links are blocked,

Best regards

**Comment by rkrishnan8594** [comment]
Thanks for reporting, @cclobo2. I don't believe that this is a bug with the Player.js library, so would you mind providing this feedback directly to [Vimeo Support](https://vimeo.com/help/contact)?
