### ISSUE TITLE
Bitrate Selection API

### ISSUE THREAD

**Issue by danrossi** [vimeo/player.js#104]
Hi there I noticed in regards to #39 there is a "background" option to provide "chromeless" features. Something people have been asking for years. 

I have noticed however there is no feature to select or get bitrates like Youtube so still requires the player ui to do such things. 

Is there any plans to add this into the api similar to text track selection ? 

Is there no plans at all for a proper chromeles feature similar to the background feature ?

**Comment by bdougherty** [comment]
This is not something we are planning on offering right now.

**Comment by danrossi** [comment]
:O
