### ISSUE TITLE
Set the audio track

### ISSUE THREAD

**Issue by thibautvdu** [vimeo/player.js#1041]
Since Vimeo doesn't auto-select the audio track based on the user's browser language, I expected we could select the audio track to play manually from the library. However I couldn't find any clue.

Is it possible ?

**Comment by rkrishnan8594** [comment]
Hi @thibautvdu - we will soon be adding support for a new `?audio_track` parameter that embedders can use to set a default audio track for all users. Eventually, we also plan to add support for a `player.setAudioTrack()` method that allows for programmatic selection.
