### ISSUE TITLE
Controls option doesn't work with Events

### ISSUE THREAD

**Issue by DrHyde01** [vimeo/player.js#1043]
Hi,

I have an issue with my custom video player (using React 18).

When the app is playing Vimeo events, most of the options from the SDK don't work.
For instance, when I set controls to false to display only my custom controls, the native controls still appear.

<img width="777" alt="Capture d’écran 2024-07-30 à 16 50 41" src="https://github.com/user-attachments/assets/09cfa515-28c4-4855-80c6-2efd99454cc5">

The player declaration is good, appart from event case the video player run proprely with this options : 

```
  const options = {
      url: "https://vimeo.com/event/4478706",
      width: 1280,
      autoplay: false,
      controls: false,
      background: false,
    };
```
Moreover i have exactly the same issue with the streaming app from my company, who use React 17 with this fork : 
https://github.com/u-wave/react-vimeo
Video player in this case is more complex but options follows same schema.

![353513382-e69242cd-cfec-40a3-951e-9c4ae327f559](https://github.com/user-attachments/assets/dddd488e-9f03-46b1-b618-18d55af5208a)

Has anyone else encountered the same issue?

Thanks for your help ! ;)

**Comment by rkrishnan8594** [comment]
Hi @DrHyde01 - unfortunately this library has limited support for live event embeds at this time. If you'd like to disable controls for an event embed, my suggestion would be to append the query parameter `?controls=0` to an iframe embed code URL. Expanding Player.js support for event embeds so that they're at parity with video embeds is on our roadmap.

**Comment by DrHyde01** [comment]
Hi @rkrishnan8594 
Thanks for your reply ! Unfortunately, our application does not allow integrating the player in this way. I will eagerly await the next update that allows hiding the controls :)
