### ISSUE TITLE
Vimeo videos display balck screen on IPhone devices

### ISSUE THREAD

**Issue by MarwanEsm** [vimeo/player.js#1046]
### Expected Behavior
Click on play, the video will be displayed in full screen

### Actual Behavior
Click on play, full screen will be opened but it's black screen.
I had to stop the video and minimize the screen, then play the video again, 
only then the video will be played properly

Using React Player in React Project

### Steps to Reproduce

Install React Player via npm i react-player then use this as the url

**Comment by rkrishnan8594** [comment]
Hi @MarwanEsm - this sounds similar to an issue I've seen, but in order to confirm, can you share a page or test environment where this can be reproduced?

**Comment by MarwanEsm** [comment]
[Hi @rkrishnan8594 - thank you for getting back to me on this.
Enclosed is a video displays the issue we faced on iPhone mobile device
Appreciate your feedback](
https://github.com/user-attachments/assets/5791c967-9d4e-4482-bc91-7a49004debac
)

**Comment by rkrishnan8594** [comment]
Hi @MarwanEsm - thanks for sharing a screen recording. This looks like an active iOS bug that we have prioritized for investigation. Something appears to have regressed in the browser in a recent release (I believe 17.4). I'll follow up on this ticket when we have a solution or update on that issue.

**Comment by MarwanEsm** [comment]
@rkrishnan8594 thank you for taking the time to investigate the issue. Much appreciated

**Comment by rkrishnan8594** [comment]
No updates to share, just that we'll be looking into this issue soon.

**Comment by truongnv98** [comment]
I'm using react-native-webview to play the Vimeo video. Same issue

**Comment by MarwanEsm** [comment]
@rkrishnan8594 could you please let's know if there is any udpate on this ? appreciate your effort

**Comment by rkrishnan8594** [comment]
@MarwanEsm We ended up fixing this issue recently. Are you still experiencing it?

**Comment by MarwanEsm** [comment]
@rkrishnan8594, thanks for the feedback, here's a show-case video

https://github.com/user-attachments/assets/756c2b91-6923-4b1d-bcf1-0da5817f29c0

**Comment by MarwanEsm** [comment]
@rkrishnan8594 suddenly it starts working properly :) . I really appreciate your reply and effort
