### ISSUE TITLE
player.vimeo.com video not playing on iOS

### ISSUE THREAD

**Issue by marco2216** [vimeo/player.js#1054]
### Expected Behavior
Video plays when play is pressed.

### Actual Behavior
Video does not play.

### Steps to Reproduce
Very easy to reproduce by just opening this link in Safari on iOS. 
https://player.vimeo.com/video/751264965
We're also having the problem in our React Native app which uses a WebView to show videos.
It seems like the player js tries to load some sort of config from https://player.vimeo.com/video/751264965/config but that URL returns a 403.
This link work on every other platform. As far as I can see this issue occurs with all videos.

**Comment by rkrishnan8594** [comment]
Hi @marco2216 - I'm unable to reproduce the issue with the clip you shared when visiting the player URL directly on my iPhone. Is it a different issue than the one that's occurring in your React Native app?

**Comment by marco2216** [comment]
OK, so it seems to work on a physical device, but only in Safari. In the WebView, it doesn't play unless you first seek to any point in the video before playing it. You can also seek after starting playing, and then play it, and that will also work. If you don't seek, it just shows the loading spinner forever.
