### ISSUE TITLE
Vimeo Infinite Buffering in Webview on iOS

### ISSUE THREAD

**Issue by frausto** [vimeo/player.js#1059]
### Expected Behavior
Public, embeddable videos load consistently on iOS emulator. Videos load and play inside of a webview on iOS emulator

### Actual Behavior
Videos are not loading inside our React native app on iOS, which uses a webview and the player.js library to play videos.

### Steps to Reproduce
have a webview that uses player.js in iOS emulator, try to load a video.

**Comment by ajisakson** [comment]
Having the same issue on our Cordova app using a Webview on iOS. First reported yesterday at 9:17am EST by a user and reproducible in all instances of iOS and video embed. We are using the bundle from this link: https://player.vimeo.com/api/player.js

**Comment by jdreetz** [comment]
@frausto @ajisakson I tried to reproduce the issue in our Capacitor test app, which places a Vimeo embed in a Webview, but wasn't able to reproduce the issue. 

Can you provide more details about what plaform/device/library/embed url you saw the issue on? Would it be possible to share a test app that reproduces the issue?

**Comment by ajisakson** [comment]
Yes of course, though not limited to this device here's what I'm using:

Platform - Cordova iOS v7.1.0
Device - iPhone 12 Pro Max, iOS 18.1.1
Library - https://player.vimeo.com/api/player.js
Embed URL - 
`<iframe allowfullscreen="allowfullscreen" name="iframe-listener" src="https://player.vimeo.com/video/332296549?h=44a73b1703&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" width="100%" height="100%" data-mce-fragment="1"></iframe>`

I'll work on setting up a test app. I'll note that the same iframe is working just fine on the Android version of our app which shares code used by the Webview, but obviously uses a distinct engine (Android using Chromium and iOS using Webkit).

**Comment by frausto** [comment]
Same behavior here. We have a webview with an iframe embedded in it in our React Native App. It was working fine before in the same version of our iOS app, and it still works fine on the Android version of our app.

**Comment by jdreetz** [comment]
@frausto @ajisakson have you received any reports of the issue from versions of iOS earlier than 18.1.1?

**Comment by frausto** [comment]
> @frausto @ajisakson have you received any reports of the issue from versions of iOS earlier than 18.1.1?

We see it happening in 17.4

**Comment by ChrisMICDUP** [comment]
I have the same issue here, and across many iOS devices (iPhone 15 Simulator iOS 17.2, iPhone XS iOS 18.1.1, iPhone 13 mini iOS 17.6.1), we also see the issue with some differences on Android. We are using flutter with a webview and embedded iframe. 

This has been working on our app for a long time but broke sometime in the last couple of months. I thought I had found the fix with adding &playsinline=0 to URL, but this seemed to be only temporary...

Embed Code:       <iframe id="vimeoPlayer" src="https://player.vimeo.com/video/1029861442?h=6cb51aeac5" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

I have a test app that I can supply.

**Comment by jdreetz** [comment]
@ChrisMICDUP would you mind emailing your app to james.reetzke@vimeo.com? thanks

**Comment by jdreetz** [comment]
We're working on a potential fix for this issue. I'll post here when we have more details.

**Comment by ChrisMICDUP** [comment]
Hey @jdreetz you still want the test app?

**Comment by mcintyrehh** [comment]
Hi everybody, just pushed out a fix if you don't mind confirming! 

There is still some flakiness on iOS 17.4/17.5 sims, but that looks like an issue in the simulator itself.

@ChrisMICDUP, the test app would still be great if you don't mind sending it. We're working on making our WebView compatibility more robust and it would be a great resource.

**Comment by ChrisMICDUP** [comment]
Hey @mcintyrehh I emailed James a link to the testapp. Give me your email and I'll send it to you

**Comment by ChrisMICDUP** [comment]
Still seeing issue on iPhone XS iOS 18.1.1 and iPhone Mini 13 iOS 17.6.1. Also failing on my TestApp iPhone 15 Pro simulator iOS 17.2
I'm assuming the fix will work on previously stored Vimeo files?

**Comment by ChrisMICDUP** [comment]
hah, works on a iPhone 6s IOS 15.8.3

**Comment by ajisakson** [comment]
I'm no longer seeing issues on my Cordova app using a Webview on iOS 18.1.1. I'll pass forward the message and confirm with other users that this is fixed for them as well.

**Comment by mcintyrehh** [comment]
Sorry to hear that @ChrisMICDUP! James just forwarded me your test app, I'm going to get testing now. For reference, my email is henry.mcintyre@vimeo.com. The fix will be player side so it will work for any Vimeo clip.

I appreciate the effort, will keep you updated!

**Comment by ajisakson** [comment]
Well I may have spoke too soon because they are now buffering infinitely again on both my device and all of my team's devices.

**Comment by ethanneff** [comment]
It is still broken on all of our iOS devices as well.

**Comment by mcintyrehh** [comment]
Hi all, I appreciate the updates. We're actively looking into this and I'll keep this thread updated. 

Are all the affected sessions on physical devices running Flutter or Cordova on a physical iPhone? Working to narrow down the culprit.

**Comment by ChrisMICDUP** [comment]
I'm testing on: 
Physical devices: iPhone XS iOS 18.1.1, iPhone Mini 13 iOS 17.6.1. iPhone 6S iOS 15.8.1.
Simulator: iPhone 15 Pro iOS 17.2

As mentioned above, all fail except the 6S

**Comment by jdreetz** [comment]
Thanks for the info and for sending the debug info. We've had a few reports
of failure not in Webviews, not sure if they're related. Most reports are
from Webviews containers (Cordova, Capacitor, Flutter) on iOS 17+.

**Comment by ajisakson** [comment]
All of my failures in Cordova are on physical iPhones and simulators.

**Comment by mcintyrehh** [comment]
Hi all, I've identified a fix and am putting it up for review now. I'll keep this thread in the loop!

**Comment by ethanneff** [comment]
We already have allowsInlineMediaPlayback enabled in all our webviews; however, the issue still persists.

Something broke in the last two weeks. All of our iOS emulators, from iOS 17.4 to iOS 18.1.1, no longer load Vimeo videos, even though they have been working fine for months.

Was there a recent backend configuration change that could have caused this change in behavior?

**Comment by ChrisMICDUP** [comment]
Going to have to agree with Ethan here. And also possibly agree that something broke in last two weeks and before that as well.

When we saw the issue a month ago (prior to 18Nov24) after years without issue, I added a playsinline=0 parameter to the https://player.vimeo.com URL. This seemed to fix things on iOS albeit in full screen mode, and I had to add a JS function that did not add it for Android. By 21Nov24, it had seemingly broken again.

Can you share the code to your test Flutter app? This is what mine has currently:

`
    // #docregion platform_features
    late final PlatformWebViewControllerCreationParams params;
    if (WebViewPlatform.instance is WebKitWebViewPlatform) {
      params = WebKitWebViewControllerCreationParams(
        allowsInlineMediaPlayback: true,
        mediaTypesRequiringUserAction: const <PlaybackMediaTypes>{},
      );
    } else {
      params = const PlatformWebViewControllerCreationParams();
    }

    final WebViewController controller =
    WebViewController.fromPlatformCreationParams(params);
`

and the Vimeo URL in the web page

'
    <div style="padding:88.82% 0 0 0;position:relative;">
        <iframe id="vimeoPlayer" src="https://player.vimeo.com/video/1029861442?h=6cb51aeac5&playsinline=1&badge=0&autopause=0&player_id=0&app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe><script src="https://player.vimeo.com/api/player.js"></script>
    </div>
'
Also tried playsinline=1 and various other tweaks to URL params

I do note the buffering circular animation doesn't show now.

**Comment by mcintyrehh** [comment]
Hi both,

We added support for MSE playback with Apple’s ManagedMediaSource at the end of November, it lines up with your issue timelines. Tomorrow morning we’ll deploy the inline fix and a new query parameter to allow for disabling of MMS in favor of native playback. This flag will be handy for iOS simulator testing, as there is a known issue with `isTypeSupported` on MSE playback in iOS 17 sims. (More context here in this HLS.js issue: https://github.com/video-dev/hls.js/issues/6161)

@ethanneff, would you mind sending a source to reproduce the issue so we can investigate further? Even a video reproducing the issue would be great.

@ChrisMICDUP, the snippet we’re using looks almost identical to the one you are using. When I tested out the app that you sent us I noticed that playback does jump right into full screen when I seek and re-initiate playback. If you don’t mind sending the source to my email above I’m happy to do a little more debugging. Again, we really appreciate you taking the time to send that to us!

**Comment by ChrisMICDUP** [comment]
Thanks Henry,

I'll wait for the deployment and try a bunch of stuff again, then send you the source (it's pretty much the example from flutter webview) if I haven't seen any difference. Fortunately in production we send the webpage from a backend service so no new app deployment required for additional parameters.

PS: I see you have joined MIC'D UP!, welcome

**Comment by mcintyrehh** [comment]
Hi @ChrisMICDUP, 

The non-inline fix is out and I confirmed that playback is looking good in the app! 
It does enter directly into fullscreen so I don't think the `allowsInlineMediaPlayback` config is being recognized properly. I'm curious to know if this was the same behavior you were seeing previously.

Thanks so much for your responsiveness and the help to find a solution!

**Comment by ChrisMICDUP** [comment]
Thanks @mcintyrehh,

Can confirm working across all physical test platforms Android and iOS. Playback goes fullscreen because I put in some JS snippet to turn off playsinline in a bid to get things working before. I will test with this param removed. Maybe an issue with iOS Simulator? still testing, but if production is working then I'm happy.

Thanks for all your teams help

**Comment by ChrisMICDUP** [comment]
Also, production app 1.3.4 does not have the allowsInlineMediaPlayback parameter

**Comment by mcintyrehh** [comment]
Amazing, glad to hear it Chris! 

If you run into trouble with the iOS sim again (I'm seeing the simulator bug in iOS 17.2), we just rolled out support for a new query param that allows for disabling MMS in favor of native HLS playback via: `prefer_mms=0` or `prefer_mms=false`. 

cc: @ethanneff

**Comment by frausto** [comment]
thanks all going to close this issue!
