### ISSUE TITLE
pausing a video, go to begin of video and start playing again

### ISSUE THREAD

**Issue by flori27** [vimeo/player.js#106]
### Expected Behavior
Start playing a video. Pause the video after x seconds, go to the beginning of the video and start playing the video again.

### Actual Behavior
This doesn't work in Firefox. The video doesn't start playing after the pause.

### Steps to Reproduce
https://jsfiddle.net/flori27/8d6n38yz/

**Comment by bdougherty** [comment]
I believe this was fixed by a recent player release. I tested in Firefox and it appeared to be working correctly. Let me know if you are still seeing the issue and I can re-open the ticket.
