### ISSUE TITLE
Remotely/programmatically playing a Vimeo video with API

### ISSUE THREAD

**Issue by jacoblindgren** [vimeo/player.js#107]
I'm trying to find a way to begin playing an embedded Vimeo video (via its API) on iOS other than the press of its play button. I understand the limitations set by iOS that prevent a video from playing unless triggered by the user. Unfortunately in my setup the iframe that holds the video isn't clickable (it's set to pointer-events: none; for unrelated reasons, so I'm looking for another way to have the video play without user input. An example of what I've attempted is [here](url), but as expected it doesn't cause anything to happen in mobile. Is anyone familiar with a workaround?

**Comment by luwes** [comment]
This is now possible in our latest release thanks to `playsinline`!
See https://player.vimeo.com/api/demo
