### ISSUE TITLE
Player event listeners fire twice when triggered on instance of an existing player

### ISSUE THREAD

**Issue by tedw** [vimeo/player.js#108]
**UPDATE 1/24/17**
Original feature request already existed but has a bug (see below). Title changed to reflect the real issue.

**~Ehancement~**
~Is it possible to get the instance of an existing player similar to YouTube’s `YT.get('video-id')`?~

**~Use Case~**
~I have a script that creates my players and attaches event listeners for analytics purposes. I also have a modal window script that checks for any videos and autoplays them when the modal is opened. I’d like to be able to control the video without creating a new player instance, which would cause the play event to be fired twice and mess up my analytics. My current solution is to pass the player instance to the modal script using custom events. This works, but I’d prefer to not have them so closely tied together.~

Thanks!

**Comment by bdougherty** [comment]
You'll get back the same player instance for the same iframe, so you should be able to call `new Vimeo.Player(iframe);` any time you need to get it without any issues.

https://github.com/vimeo/player.js/blob/e264aa12d5686e4df0a22e77a3b0890fb06fb8bf/src/player.js#L58-L61

**Comment by tedw** [comment]
Thanks for the quick reply!

That’s actually the first thing I tried, but calling `player.play()` seemed to trigger the `play` event callback twice.

I'll make a simple demo to rule out my code and post here.

**Comment by tedw** [comment]
Here’s a demo http://jsbin.com/yukomij/edit?html,js,console,output

**Comment by bdougherty** [comment]
Yep, definitely a bug! The player itself is only sending out a single message, so it must be something in the library somewhere that's doubling up.

**Comment by tedw** [comment]
Ok, will update title to better reflect the issue. Thanks again for the quick response!

**Comment by tedw** [comment]
Awesome, thanks! 🎉

**Comment by bdougherty** [comment]
Will do a release in the next couple of days.

**Comment by adrielwerlich** [comment]
This issue is from 2017. But currently I´m facing the same issue with the `ended` event listener. I´m using "@vimeo/player": "^2.12.2". Is the double fire of the `ended` event at the end of the video the standard behaviour? Or it is a bug?

**Comment by alexbudin** [comment]
This still seems to be an issue today. The play event fires twice.

**Comment by agnesmeri-olio** [comment]
Unfortunately this is still an issue, the play event fires twice on replay.
I'm having issues with mixpanel tracking that I want to fire on play.

**Comment by rkrishnan8594** [comment]
@agnesmeri-olio Please file this as a new issue with a reproducible example - thank you!
