### ISSUE TITLE
Add type definitions for typescript

### ISSUE THREAD

**Issue by macliems** [vimeo/player.js#109]
angular-cli:

After npm install @vimeo/player, import fails with 'Cannot find module '@vimeo/player'.

I tried:

import Player from '@vimeo/player'
import Player from '@vimeo/player/dist/player'
import * as Player from '@vimeo/player'

**Comment by bdougherty** [comment]
Sounds like this might be an issue with angular-cli not being able to resolve scoped packages. Probably best to file an issue on `angular-cli`.

**Comment by macliems** [comment]
angular-cli wants typings

I installed @typings/vimeo but that didn't work either

**Comment by bdougherty** [comment]
So it sounds like you’re using typescript? Happy to accept a pull request that adds whatever metadata is needed for that.

**Comment by bdougherty** [comment]
Also looks like you can request that they add definitions for this library to https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by denisyilmaz** [comment]
Hi @bdougherty, I've created the typings for @vimeo/player following your README.md file. I've created a pull request at DefinitelyTyped >> https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15593

I don't know how to implement it in the API itself, but maybe somebody else could take it from here?

**Comment by denisyilmaz** [comment]
Types are now available via @types 
>> DefinitelyTyped/DefinitelyTyped@a209273

**Comment by philcockfield** [comment]
Would be nice if this were re-opened and the types included directly in the project.  

TypeScript is now arguably as mainstream as we can get, and this would definately provide a level of confidence that Vimeo was "onto it" if the player client libs "just worked" with types!

Love you guys!
