### ISSUE TITLE
Feature request: add warning when using api=1

### ISSUE THREAD

**Issue by BernsteinA** [vimeo/player.js#111]
related issues:
https://github.com/vimeo/player.js/issues/58
https://github.com/vimeo/player.js/issues/33

**Comment by LoveIsGrief** [comment]
I'd like to add here that it would great to actually remove `api=1` from the generated oEmbed stuff.

[Here](https://codepen.io/anon/pen/veZwzV)'s an example of it failing because of api being in the options passed to `Vimeo.Player`. It should be lib's job to clean up options like this.

**Comment by luwes** [comment]
The warning has been added 🎉 
You can view it in the console of https://player.vimeo.com/playground
