### ISSUE TITLE
Mobile: Video still plays after close and locks up safari/chrome

### ISSUE THREAD

**Issue by kewalter** [vimeo/player.js#113]
On just a basic player I should be able to press play, then press done to close the video and have it stop.

When playing a video on mobile it plays as expected.  However, when closing the video, it occasionally shrinks back down to the size of the play, but continues to play.  When it does this, it locks up safari and I'm unable to refresh, change tabs, etc.  I am still able to close safari or swipe on the phone.

We've seen this happen on at least 5 separate devices when testing.  Both on iOS Safari and iOS Chrome.

Demo Page:
http://codepen.io/kewalter/pen/KaRJZy

Video of it happen on iPhone 7 plus, iOS 10.2.1
http://i.imgur.com/A5hOBoR.gifv

**Comment by lolo34140** [comment]
I can confirm this issue also.

This issue also appears if you click on pause on IOS device, it will somtimes re-start to play automatically after some milliseconds. Like if the pause method is ignored because the video is still loading (or because a timer is not cleared). It doesn't appear if you wait that the whole video load (before to pause or quit the video player).

**Comment by kewalter** [comment]
I think I may have found the trigger for the bug, but not the reason.   If I include both the height and width in the player options, instead of leaving one out, the bug never seems to occur.

Bug occurring: 
http://codepen.io/kewalter/full/KaRJZy/

Bug NOT occurring: 
http://codepen.io/kewalter/full/MJBJJB/

**Comment by kewalter** [comment]
Any ideas on this issue? We're ready to move off of Vimeo because of this and issue #115

**Comment by jilykate** [comment]
I also have this issue. Not sure this is caused by vimeo or player js or some other plugin I am using

**Comment by luwes** [comment]
I couldn't reproduce this issue anymore on my end.
Please let us know if it happens again. Thanks.
