### ISSUE TITLE
responsive player or just absolute width?

### ISSUE THREAD

**Issue by macliems** [vimeo/player.js#114]
I'm trying to get my player to be responsive, but nothing seems to work.
It is easy when I HAVE a player on the page, but when I create one with new Player, I can not figure out what to do.
Any suggestions?

**Comment by bdougherty** [comment]
We have an experimental `responsive` parameter that you can pass as one of the options.

```js
const player = new Vimeo.Player(76979871, {
    responsive: true
});
```

**Comment by macliems** [comment]
Thanks!

**Comment by cWillow** [comment]
Is this still experimental or can it be added to the documentation?

**Comment by rodolfobarretoweb** [comment]
Works very well ! This has to be in the documentation!!!!!
