### ISSUE TITLE
Player occasionally reopens by itself when closing on mobile.

### ISSUE THREAD

**Issue by kewalter** [vimeo/player.js#115]
On mobile, the player should open into the full screen control and when pressing "Done", return to the iframe.   

Occasionally, when closing the video, the player will reopen without any further user interaction and continue to play.

Demo Page:
http://codepen.io/kewalter/full/MJBJJB/

**Comment by bdougherty** [comment]
Is this different from #113?

**Comment by kewalter** [comment]
Yes, I'm seeing two separate issues.  The demo page I included for this issue is the example used for the fix on #113.

**Comment by kewalter** [comment]
Any ideas on this issue?  We're ready to move off of Vimeo because of this and issue #113

**Comment by jilykate** [comment]
I also see this issue almost on every embeded vimeo video page
