### ISSUE TITLE
player.loadVideo() method resets player options to its defaults

### ISSUE THREAD

**Issue by csrcreative** [vimeo/player.js#116]
### Expected Behavior
Player settings persist each time player.loadVideo() is called.

### Actual Behavior
After the first time player.loadVideo() is called, default settings are used by the player.

### Steps to Reproduce
See demo here:
https://codepen.io/romerocs/pen/bgjexv

If you click the 2 video links at the bottom you will see the second click loads a player with the settings overridden.

**Comment by einwang** [comment]
+1 Unfortunately I can totally agree with that, I'm having exactly the same issue on my setup like i also mentioned in #71

**Comment by jbnj** [comment]
+1 Experiencing the same issue here. I would expect the player settings persist each time player.loadVideo() is called.

**Comment by gavrochelegnou** [comment]
+1 I noticed too that setting the "color" in the options is overriden after the second loadVideo call.
And event worst, calling SetColor() even after the player is ready doesn't change the color anymore.

**Comment by luwes** [comment]
This is fixed in the newest Vimeo player release. Thanks for your patience.
