### ISSUE TITLE
Hash is required to initialize a player with a video that has "only people with the private link" privacy

### ISSUE THREAD

**Issue by bdougherty** [vimeo/player.js#122]
### Expected Behavior

The following should initialize the player properly:

```js
const player = new Vimeo.Player(element, {
    id: 202284380
});
```

That video is set to "only people with the private link".

### Actual Behavior

Gives a privacy error.

### Steps to Reproduce

Works properly if the full url is used:

```js
const player = new Vimeo.Player(element, {
    url: 'https://vimeo.com/202284380/dfddc03daf'
});
```

See #120 for some more details.
/cc @tedw

**Comment by bdougherty** [comment]
This is because oEmbed does not accept urls without a hash even though it should. We have an internal issue filed to fix it.

(for my reference, it's api#600)

**Comment by luwes** [comment]
Closing for now, api#600 has still not resolved this issue.
