### ISSUE TITLE
Playing and pausing the player too quickly will occasionally cause "This video is not supported in this browser" errors

### ISSUE THREAD

**Issue by brainkim** [vimeo/player.js#125]
### Expected Behavior
When you load several players and call the play method immediately followed by the pause method, the player should work.

### Actual Behavior
Once in a while, the player stalls interminably and an error is logged to the error callback stating "This video is not supported in this browser." and there is a swallowed exception on the page stating: "Uncaught (in promise) DOMException: Failed to load because no supported source was found."

### Steps to Reproduce

Reloading the page a couple times will allow you to see it. 
https://jsfiddle.net/tnk4Lvut/4/

This is a finicky bug on Chrome which will only happen once in a while. I needed to call play and pause on each players just cause I needed players to play at a certain point in time and the first playback would usually take too long. In any case, it doesn't make sense why the player would say the video type is not supported, especially when there are other videos that play the same video just fine. I'm not sure if this is the root cause or minimal reproducible case. Thanks!

**Comment by luwes** [comment]
I think this should be resolved, let me know if not!
