### ISSUE TITLE
Plans for hiding controls

### ISSUE THREAD

**Issue by oyeanuj** [vimeo/player.js#127]
Hi @bdougherty! I know this is a topic which was kinda sorta discussed earlier but without any resolution of any sort - so hence a new topic.

So, I am wondering if there are any plans to allow hiding of controls, now that you allow programmatic control of the critical functions. 

In our usecase, we have custom control bar (with icons, different UX, etc) that we can use for Youtube, Vid.me, Wistia but not for Vimeo since one can't hide the native controls on Vimeo.

Based on comments in the suggestion forums, seems like it has been a long requested topic and now that we have programmatic controls - it makes much more sense!

Thank you!

**Comment by bdougherty** [comment]
There are still no plans to offer hiding of the controls via the API. Plus and PRO members can remove everything but the play button in their embed settings. PRO members also have access to video file urls that they can use in their own player.

**Comment by v3nt** [comment]
We have a pro account but want different settings in different places on the same site.

can we hide the playbar when using

````
var player = new Vimeo.Player(container,{id:vimeoId});
````

somehow ?
