### ISSUE TITLE
Refused to execute script from 'https://player.vimeo.com/api/player.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled

### ISSUE THREAD

**Issue by lukeyouell** [vimeo/player.js#128]
Same issue is occurring as flagged before [here](https://github.com/vimeo/player.js/issues/85)

> https://player.vimeo.com/api/player.js is a broken link that is redirecting to vimeo.com. Please update your documentation with an updated URL.

**Comment by jigsawsoul** [comment]
Happening across two of my sites also.

**Comment by Augl** [comment]
Same problem on my sites.

**Comment by jigsawsoul** [comment]
Has this issue been fixed?
