### ISSUE TITLE
Issue with Fancybox

### ISSUE THREAD

**Issue by thomasbrodin** [vimeo/player.js#130]
I have been playing with the new Vimeo Player API. Basically, I just like to be able to start the player after a Fancybox has opened. I am using the fancybox inline type as I am customizing the elements inside the fancybox.

Check out [JSFIDDLE](https://jsfiddle.net/photous/8brfq2oe/)

The following works in Firefox;

```
$(document).ready(function($) {
  var idPlayer = new Vimeo.Player('my-video');
  $(".fancybox-media").fancybox({
    type: 'inline',
    openEffect: 'none',
    closeEffect: 'none',
    padding: 0,
    margin: 0,
    width: '75%',
    height: 'auto',
    autoSize: false,
    afterShow: function() {
      idPlayer.ready().then(function() {
        console.log('the Player is ready');
        idPlayer.play();
      });
    },
    beforeClose: function() {
      idPlayer.pause();
    }
  });
});
```

But in Safari or Chrome, I get the following error and the Video doesn't start.
What I am doing wrong here?...

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided does not match the recipient window's origin.`

Many thanks in advance!

**Comment by bdougherty** [comment]
Looks like it's because it's taking the existing `<iframe>` and moving it into a different element. If you create the player object inside the `afterShow` callback, it seems to work.

**Comment by Soullighter** [comment]
I must reopen this one because @thomasbrodin didn't see the same issue when he close modal box, same message appear in console. Also when you want to open another time same modal box, you can't auto play video for second time

**Comment by Soullighter** [comment]
@thomasbrodin didn't see the same error when he close modal box, same message appear in console. Also when you want to open another time same modal box, you can't auto play video for second time.
@bdougherty
