### ISSUE TITLE
setCurrentTime issue

### ISSUE THREAD

**Issue by capbussat** [vimeo/player.js#131]
### Expected Behavior
I expect to load video and immediately set current time.

### Actual Behavior
setCurrentTime works when it is run from on click event, but not when executed immediately after LoadVideo.

### Steps to Reproduce
See code here [https://codepen.io/capbussat/details/EWeJVW/]

`<iframe id="iframe_1" src="https://player.vimeo.com/video/115466828"
    data-ready="true" width="640" height="360" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
<input id="previous" style="display: none;" type="submit" value="Anterior" /><input id="next" type="submit" value="Siguiente" /></span><input id="resume" type="submit" value="Resume" /></span>
<input id="id_video" type="hidden" value="1" /><input id="id_last" type="hidden" value="2" />`

`

jQuery(document).ready(function () {
console.log("LOG!");
var frame = document.getElementById('iframe_'+ 1);
var player = new Vimeo.Player(frame);
var video = parseInt(jQuery('#id_video').val(), 10);
var last = parseInt(jQuery('#id_last').val(), 10); // el primer és 1
var currentTime;
var videos = {  
    "videos":["115466828","209245314"],
	"posicion":["30", "60"]
 };

idPlay(1);
idSetCurrent(1);

function idPlay(video){	 
    player.loadVideo(videos.videos[video - 1]).then(function(id) {
// the video successfully loaded
}).catch(function(error) {  switch (error.name) {
                                            case 'TypeError':
                                                // the id was not a number
                                                break;

                                            case 'PasswordError':
                                                // the video is password-protected and the viewer needs to enter the
                                                // password first
                                                break;

                                            case 'PrivacyError':
                                                // the video is password-protected or private
                                                break;

                                            default:
                                                // some other error occurred
                                                break;
                                        }
                                    });
                                   
}
 
function idSetCurrent(video){
        var time = Number(videos.posicion[video - 1]); 
		try {
			player.setCurrentTime(time);
            console.log('time',time);	
			player.pause();
		} catch (e) {
              return {};
            }
}

 
 player.on('pause', function () {
  var floor = Math.floor(currentTime.seconds);
  console.log('paused the video!', floor );
  videos.posicion[video - 1] = floor.toString();
 });
 
 player.on('timeupdate', function (data) {
  currentTime = data;
 });

 jQuery("#resume").click(function (evento) {
  evento.preventDefault();
  idSetCurrent(video);
 });

 jQuery("#previous").click(function (evento) {
  evento.preventDefault();
  video = parseInt(jQuery('#id_video').val(), 10);
  if (video > 1) {
   video = video - 1;
  }
  if (video === 1) {
   jQuery("#previous").hide();
  }
  if (video <= last) {
   jQuery("#next").show();
  }
  jQuery("#id_video").val(video); // actualitzem l'id_video
  idPlay(video);// mostrem el VIDEO que toca
  idSetCurrent();
  console.log('id:', videos.videos[video - 1]);
  console.log("mostra video",video);
 
 }); // previous
    
jQuery("#next").click(function (evento) {
  evento.preventDefault();
  video = parseInt(jQuery('#id_video').val(), 10);
  last = parseInt(jQuery('#id_last').val(), 10); 
  if (video < last) {
   video = video + 1;
  }
  if (video > 1) {
   jQuery("#previous").show(); // mostrem el botó anterior
  }
  if (video === last) {
   jQuery("#next").hide(); // mostrem el botó anterior
  }
  jQuery("#id_video").val(video);
  idPlay(video); // mostrem el  VIDEO que toca
  idSetCurrent();
  console.log('id:', videos.videos[video - 1]);
  console.log("mostra video",video);
 
 }); // next  
});`

**Comment by capbussat** [comment]
Has any one found a good solution? 
I have several other issues because I work with two or more videos . Sometimes when I switch videos too fast  the player will fail to load the video for a while or at all. Usually I end refreshing the page to get the videos to work properly again.

**Comment by beverlytang** [comment]
It seems that the issue is with loadVideo(). Nothing else works after loadVideo(), not even play().

**Comment by capbussat** [comment]
Yes, you are correct. For lack of documentation on this issue I have left this approach and just use setCurrentTime on a click event .

**Comment by beverlytang** [comment]
I finally found a workaround by passing the player object and seconds to a function like so:
```
function setVideoTime(player, seconds) {
	player.setCurrentTime(seconds);
	playVideo(player);
}
function playVideo(player) {
	player.play();
}
```
For some reason, it only works if you trigger play in another function.

**Comment by bdougherty** [comment]
Did you try waiting for the `setCurrentTime()` promise to resolve?

```js
function setVideoTime(player, seconds) {
	player.setCurrentTime(seconds).then(function() {
		return player.play();
	});
}
```

**Comment by beverlytang** [comment]
Ah, I didn't use "return" before. Thanks, that'll keep things simpler.

**Comment by capbussat** [comment]
Thanks, this works much better.
