### ISSUE TITLE
display: none element unload never resolves in firefox 52.0.2

### ISSUE THREAD

**Issue by benjamincerigo** [vimeo/player.js#133]
### Expected Behavior
unload called on a player that has a element that is display none should resolve (maybe with an error)
### Actual Behavior
unload is never resolved in firefox 52.0.2
### Steps to Reproduce
click 'Load'
then click 'UnLoad'
should then see the 'UNLOADRESOLVED'
https://jsfiddle.net/1uzk71p0/

You can see that with chrome (56.0.29), safari (10.0.3) this resolve works but with firefox 52.0.2 it dose not

**Comment by luwes** [comment]
sorry we never got to this. in the mean time it is working in the latest Firefox browsers I believe.
