### ISSUE TITLE
Question: Detect if embedded video is supported (i.e. IOS device or not)

### ISSUE THREAD

**Issue by trafiq** [vimeo/player.js#135]
What is the best method of checking whether the embedded video is playing (and therefore playback is supported) or whether the fallback image is showing instead? For example, on IOS devices where embedded video is not available.

I'm more familiar with the Wistia API which has a state method for this very purpose. Is there anything similar in player.js?

**Comment by bdougherty** [comment]
In practice, the only time where that would happen is because of the video privacy settings (there is an open issue for that: #56). Older browsers have the possibility of getting a fallback page, but I don't think you'd really ever see that in browsers that this library is supported in.

Do you have a specific case where this is happening?

**Comment by trafiq** [comment]
In my case I have a background video embedded in an iframe that is started via the API `play()` method. I know this is 'unsupported' in iOS and I'm OK with that. By default the Vimeo player shows the static video thumbnail instead which is my preferred behaviour for iOS devices (or those lacking inline playback).

However, I have a custom method that fire as the video reaches a certain point. Obviously, since inline playback is not supported in iOS this custom method never get executed. I therefore need to detect for this lack of support and fire the method immediately instead. I know its possible to detect iOS via the `userAgent` string though just wondered if there was a best practice way using the JS Player API?

**Comment by luwes** [comment]
sorry, this is indeed not possible. we will soon add support for inline playback.
closing see #210
