### ISSUE TITLE
player.getCurrentTime() doesn't work when video stuck

### ISSUE THREAD

**Issue by kmehmoodkhan** [vimeo/player.js#136]
Normally, we expect "player.getCurrentTime()" to give us current video time.

Unfortunately, when the video start playing down initially in Android, iOS browsers, sometimes it get stuck. In that case "getCurrentTime" method doesn't work properly, it doesn't return any time at all. Similarly, we have also used "updatetime" event which also doesn't work either. Please let us know how to solve this issue.

We are tracking video progress, so in order to do this, we poll the video player current time every 400 ms. This works pretty well in normal conditions, however the issue is occasionally produced on slow internet and the video get stuck in buffering at very beginning. In this case "getCurrentTime" doesn't return any data.

**Comment by skynet** [comment]
In this case a buffering event could help. But it's not implemented yet.

**Comment by reckoner165** [comment]
a `timeupdate` event is fired every 250ms that tracks video progress. It might be useful to call `getCurrentTime()` only when this event is fired.

**Comment by EugeneButusov** [comment]
Hi everyone, does anyone have info about when this feature (buffering event) may appear in Vimeo JS Player roadmap? Thanks in advance!

**Comment by luwes** [comment]
I think in the very beginning it's safe to say if `getCurrentTime()` returns nothing, current time is zero.

**Comment by leonioron** [comment]
> I think in the very beginning it's safe to say if `getCurrentTime()` returns nothing, current time is zero.

no! when the time is zero, the `getCurrentTime()` returns zero!

The problem is, sometimes, `getCurrentTime()` is not called and i dont know why!
(sometimes I watch the whole video and when I add up all the returns of `getCurrentTime()` it counts only half of the video)

Because of that, is impossible to tracking the user progress in the video!
