### ISSUE TITLE
Video only plays intermittently in desktop Safari when triggered by the play method

### ISSUE THREAD

**Issue by trafiq** [vimeo/player.js#137]
### Expected Behavior

When the player is triggered by the `play()` method the video should play as expected.

### Actual Behavior

The video only plays intermittently. The `play` method returns success, the `progress` event fires initially but the video doesn't start playing. This is evident as the `timeupdate` event never fires.

This only seems to occur intermittently and only in Safari AFAIK. I'm running Safari 10.1 on MacOS Sierra. I've included a codepen below highlight the issue. You may need to reload the browser a handful of times before the problem occurs. It usually happens within 10 reloads and its seems to be more common with a cold cache.

### Steps to Reproduce

http://codepen.io/trafiq/pen/MmYQmb

UPDATE:
This occurs when viewing the video on vimeo.com so appears to be not related to player.js but rather the standard Vimeo player. This issue can be closed.

**Comment by peterschmiz** [comment]
I have the same issue :( Would be nice to have a solution or an explanation, because right now the player on Safari is buggy.

**Comment by luwes** [comment]
Thanks for the update! This issue has in the mean time been fixed and was specific to Safari 10.1.

**Comment by developerant** [comment]
This is still happening on Safari 12.0 for me. Exactly the same - intermittent. Otherwise works great.
