### ISSUE TITLE
programmatically changing iframe source

### ISSUE THREAD

**Issue by hoshmn** [vimeo/player.js#138]
In order to load a new video, I am programmatically changing the src of the iframe. This successfully loads the appropriate video, but event emitters cease to fire (I'm listening specifically for timeupdate). This happens whether or not I create a new instance of Vimeo.Player wrapping the iframe (and even happens if I don't change the src programmatically, but rather set that attribute of the iframe via JavaScript from the beginning). Not sure how to avoid this so that events will continue to emit properly?

**Comment by Rikcon** [comment]
Don't change src of the iframe, use player.loadVideo(videoId)

**Comment by bdougherty** [comment]
This is somewhat related to #126, but yes, the proper solution here is to use [`loadVideo()`](https://github.com/vimeo/player.js#loadvideoid-number-promisenumber-typeerrorpassworderrorerror).
