### ISSUE TITLE
Calling .play() on user-interaction using Android Stock Browser does not start video

### ISSUE THREAD

**Issue by ClemensSchneider** [vimeo/player.js#139]
### Expected Behavior
As the call is initiated by a user-interaction (touch/click), a call to .play() should start the video as it does on other platforms, too.

### Actual Behavior
The video does not start playing. The loading-indicator (progress-bar) moves endlessly. After starting the video once by touching/clicking the embedded players play-control, following calls to .play() do work, too.

### Steps to Reproduce
Open https://player.vimeo.com/api/demo and try starting the video using 'Play' button.

User-Agent of browser is:
Mozilla/5.0 (Linux; Android 4.4.2; LIFETAB_S831X Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36

**Comment by boboldehampsink** [comment]
Same here

**Comment by JSteunou** [comment]
that's because vimeo does not support playsinline
we are all waiting for this support sadly :(

**Comment by luwes** [comment]
closing see #210.
