### ISSUE TITLE
WWW in url is invalid

### ISSUE THREAD

**Issue by Redmega** [vimeo/player.js#140]
### Expected Behavior

When url is passed as `https://www.vimeo.com/12345` it should fetch and display the proper video

### Actual Behavior

The following error is thrown:

`Uncaught (in promise) TypeError: “https://www.vimeo.com/12345” is not a vimeo.com url.`

### Steps to Reproduce

Attempt to load a video with `www` in the url. This can be through the `data-*` api or otherwise. It is recreated in this codepen: https://codepen.io/Redmega/pen/dWeMBE

**Comment by bdougherty** [comment]
Should be easy to fix, but I'm curious why you have urls with the `www.`? We have redirected to the top-level `vimeo.com` for a very long time now.

**Comment by Redmega** [comment]
I actually didn't know that. Just started using the player.js. Our video managing system saves the urls like that, I'll see if we can go about changing it if omitting the www is the standard.

At the very least I believe that there should be a small note in the documentation about the www redirect and that www is not valid in the vimeo url. Gave us quite a headache copy pasting the url from our console and having it show the proper video, yet not work in the embed.

**Comment by Redmega** [comment]
Awesome, thanks!
