### ISSUE TITLE
Expose Playback Rate Setting

### ISSUE THREAD

**Issue by jehartzog** [vimeo/player.js#141]
It seems there is some [interest](https://vimeo.com/forums/topic:43742) from customers on this, myself included. I was able to adjust the tag `video.playbackRate` via console but won't be able to do it via JS running on my own domain without this lib supporting.

I'd be interested in doing a PR for this but would like to know if there is any interest in accepting it prior to putting in the work. I've already agreed to the Vimeo CLA before (although this repo seems to have [moved away](https://github.com/vimeo/player.js/commit/f15b99791db21d63cb97022c134a71c5efec28a2) from that?) when I made a [small PR](https://github.com/vimeo/vimeo.js/pull/54) for the Vimeo Node repo.

I'm not 100% yet, but it seems like it would be simple enough to expose the functionality to adjust playback rate inside an iframe embed using `postMessage`.

**Comment by luwes** [comment]
Thanks for the feedback! This will be out very soon.
