### ISSUE TITLE
Cuepoint event is not fired when player seeked

### ISSUE THREAD

**Issue by pmkhoa** [vimeo/player.js#142]
### Expected Behavior
When user seeks pass the cuepoint timeline, the cuepoint event should be fired.

### Actual Behavior
cuepoint event isn't fired.

### Steps to Reproduce
Use the addCuePoint function to add cue at 5s, then use the player control to seek the player to second 10. The cuepoint event doesn't fire the cue point being set that 5s.

Not sure if this is the limit of using cuepoint, or it's actually a bug. Please advise.

Thanks.

**Comment by luwes** [comment]
@pmkhoa thanks for the feedback however a `cuepoint` event only triggers when it is actually played over.
