### ISSUE TITLE
Please add support for Typescript

### ISSUE THREAD

**Issue by rugdealer** [vimeo/player.js#144]
### Expected Behavior

Expected the Typescript project to resolve the import statement and not have the app crash during runtime. Will compiles, but during runtime the `Player` constructor is not defined correctly.

Current repo at : 

[vimeo__player typescript project here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/vimeo__player)
[Issue on github here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15593)

Current typescript project does not work, it would be really cool if it did.

player.js is incompatible with Typescript at the moment or vice versa.

### Actual Behavior

Crashes on runtime with error:

> Uncaught (in promise): TypeError: undefined is not a constructor (evaluating 'new __WEBPACK_IMPORTED_MODULE_2__vimeo_player__["Player"]('handstick', { id: 173449968, width: 640 })') PlayerComponent@http://localhost:8100/build/main.js:74712:80 createClass@http://localhost:8100/build/main.js:11148:34 createDirectiveInstance@http://localhost:8100/build/main.js:10979:48 createViewNodes@http://localhost:8100/build/main.js:12342:72 createRootView@http://localhost:8100/build/main.js:12247:20 callWithDebugContext@http://localhost:8100/build/main.js:13462:47 create@http://localhost:8100/build/main.js:10168:60 _viewInit@http://localhost:8100/build/main.js:43859:50 http://localhost:8100/build/main.js:43651:32 onInvoke@http://localhost:8100/build/main.js:4406:43 run@http://localhost:8100/build/polyfills.js:3:4146 http://localhost:8100/build/polyfills.js:3:13734 onInvokeTask@http://localhost:8100/build/main.js:4397:47 runTask@http://localhost:8100/build/polyfills.js:3:4841 o@http://localhost:8100/build/polyfills.js:3:1898 invoke@http://localhost:8100/build/polyfills.js:3:10674

produced by this component:

```
import {Component} from '@angular/core';
import {NavController} from "ionic-angular/index";

import {Player} from "@vimeo/player";


@Component({
  selector: 'player-component',
  templateUrl: 'player.html'
})
export class PlayerComponent {

  private player: Player;

  constructor(public navCtrl: NavController){

    this.player = new Player('handstick', {
      id: 173449968,
      width: 640
    });

  }

}

```

### Steps to Reproduce

For quickest set-up: [Create an angular project](https://angular.io/guide/quickstart)

1. Root project `npm install --save @vimeo/player` and `npm install --save-dev @types/vimeo__player` (second part not actually required since the typescript project doesn't work)
2. Create the above component and add the import statement. `import {Player} from "@vimeo/player"`
3. Will compile, but crashes at runtime.

**Comment by rugdealer** [comment]
This is my solution.

```
import {Component, ViewChild} from '@angular/core';
import {NavController} from "ionic-angular/index";

//noinspection TypeScriptCheckImport,TypeScriptCheckImport
import Player from "@vimeo/player";


@Component({
  selector: 'player-component',
  templateUrl: 'player.html'
})
export class PlayerComponent {

  @ViewChild('player_container') playerContainer;
  private player: Player;

  constructor(public navCtrl: NavController){}

  ngAfterViewInit() {
    this.player = new Player(this.playerContainer.nativeElement, {
        id: 19231868,
        width: 640
    });
  }

}

```

**Comment by rugdealer** [comment]
For a simple typescript project, this import solution also works:

`import * as Player from "@vimeo/player/dist/player.js";`

[SO post](https://stackoverflow.com/questions/44589936/how-do-i-get-vimeo-player-to-work-on-my-angular2-typescript-project/44972280#44972280)

**Comment by nikitagaba** [comment]
I was trying the same thing for password protected vimeo videos as seen in the screen, one video asking for password refreshes screen each time i am trying to enter password. Could u please let me know what could be the possible issue  and how to resolve it.
![passwordprotectvideo_edit](https://user-images.githubusercontent.com/24774004/36538178-6a5b9230-17f8-11e8-98d8-80e3b9468d86.png)

**Comment by alpersilistre** [comment]
> 
> 
> For a simple typescript project, this import solution also works:
> 
> `import * as Player from "@vimeo/player/dist/player.js";`
> 
> [SO post](https://stackoverflow.com/questions/44589936/how-do-i-get-vimeo-player-to-work-on-my-angular2-typescript-project/44972280#44972280)

Hey,

I am having the Cannot find module '@vimeo/player' issue. I guess you also experienced something like this since you wrote this comment. I installed '@types/vimeo__player' and '@vimeo/player' for an Angular 2 project but I can't build the project. These are my attempts to use the package;
```
import Player from '@vimeo/player';
import { Player } from '@vimeo/player';
import Player from 'vimeo__player/index';
import * as Player from '@vimeo/player/dist/player.js'
```

None of the above was able to compile the project.

Maybe you have solved this problem before. Thanks for advance.
