### ISSUE TITLE
Listen to `unload` method

### ISSUE THREAD

**Issue by bravokiloecho** [vimeo/player.js#145]
There doesn't seem to be any way to listen to the `unload` method on a video.

On the demo, triggering an `unload` event causes two events to be fired

```
pause event: 15.4 seconds (24.9%)
seeked event: 0 seconds (0.0%)
```

but I don't this is not specific enough to target specific `unload` calls.

Is there a way to achieve this? Or can it be added?

Many thanks!

**Comment by luwes** [comment]
I don't think it's needed if it's only called with using the API.
it's easy to add a pre or post function call after you call the unload method.
