### ISSUE TITLE
loadVideo does not resize player to new video dimensions

### ISSUE THREAD

**Issue by davekiss** [vimeo/player.js#148]
### Expected Behavior
Calling `loadVideo` with a new video id should load the video into the existing player on the page, with the embed conforming to the new video dimensions.

### Actual Behavior
The new video is loaded into the player utilizing the same dimensions from the previous video.

### Steps to Reproduce
1.) Load a video with irregular dimensions into the player.
2.) Call loadVideo using a video with different dimensions.

https://codepen.io/anon/pen/WOYpjJ

Alternatively, perhaps there can be an explicit `player.resize()` method that can be used to adjust the embed after loading the new video.

**Comment by luwes** [comment]
@davekiss I don't think that is the expected behaviour. The sizing of the embedded iframe is left to the developer of the webpage. It would be easy to get the new video width and height and resize the iframe accordingly.

**Comment by joseduin** [comment]
> ### Expected Behavior
> Calling `loadVideo` with a new video id should load the video into the existing player on the page, with the embed conforming to the new video dimensions.
> 
> ### Actual Behavior
> The new video is loaded into the player utilizing the same dimensions from the previous video.
> 
> ### Steps to Reproduce
> 1.) Load a video with irregular dimensions into the player.
> 2.) Call loadVideo using a video with different dimensions.
> 
> https://codepen.io/anon/pen/WOYpjJ
> 
> Alternatively, perhaps there can be an explicit `player.resize()` method that can be used to adjust the embed after loading the new video.

Hey @davekiss could you find a solution?
