### ISSUE TITLE
How to set quality via api

### ISSUE THREAD

**Issue by smokezp** [vimeo/player.js#149]
How to set quality via api or embed? i talk about playback, 360p....

**Comment by luwes** [comment]
You can pass in url parameters when you initialise the Vimeo player.
https://github.com/vimeo/player.js#embed-options

For Vimeo plus and up users there is a `quality` param as well.
https://help.vimeo.com/hc/en-us/articles/224983008-Setting-default-quality-for-embedded-videos?flash_digest=b98f58789298b3a141c74c634770d25c5bdfab46

**Comment by leolux** [comment]
The quality parameter is still not available in the SDK: https://developer.vimeo.com/player/sdk/embed

**Comment by jonaseltes** [comment]
Any update on this?
