### ISSUE TITLE
Mousemove event does not work

### ISSUE THREAD

**Issue by mibisc** [vimeo/player.js#153]
Instead of the normal cursor I want to use a image, which is following the mouse movement. On the whole page and all other div's it works, but not when the cursor is on the vimeo video. The event doesn't fire and the mouseimage doesn't appear. Does someone know why? 

This is my code:

```
> <img src="imgs/maus.png" class="follow3" style="position: absolute; z-index: 100000; height: 3vh; width: auto;" />
> 
> <div id="playervimeo" class="videoplayer"></div>
> 
> <script>
> 	    var options = {
> 	        id: 229816426, width: videobreite,height: videohoehe, loop: false, background: true
> 	    };
> 	    var player = new Vimeo.Player('playervimeo', options);
> 	    player.on('play', function() { });
> 
> 	    $('#playervimeo').mousemove(function(e){
> 		follow3.css({'top': e.pageY+10, 'left': e.pageX});
> 	    });
> </script>
```

Thanks for your help!

**Comment by luwes** [comment]
This is not really related to the player specific but more an iframe question I believe.

**Comment by rharriso** [comment]
For posterity. Solution can be found here: https://stackoverflow.com/a/5722122/615533

Add the following property to the iframe styles.

```
pointer-events: none;
```
