### ISSUE TITLE
Preload whole video

### ISSUE THREAD

**Issue by Fauphi** [vimeo/player.js#154]
### Expected Behavior

Is it possible to preload the whole video? With a callback or event when the preloading has finished?
Something like this:

```
player.preload().then(function() {
      // whole video was preloaded, continue with what you want to do
});

```
### Actual Behavior

There is currently no such preload-function.

**Comment by luwes** [comment]
This is not possible and will probably not be implemented in the Vimeo player.

**Comment by DATEx2** [comment]
It is 2024, we need this!
