### ISSUE TITLE
Play event doesn't fire when setting autoplay to true.

### ISSUE THREAD

**Issue by jhkerschner** [vimeo/player.js#155]
### Expected Behavior
play event will fire when using autoplay
### Actual Behavior
play event does not fire when using autoplay
### Steps to Reproduce
Video opens in a modal. When the modal opens, JavaScript gets the Vimeo ID from a data attribute and uses the JS API to create the player. Video loads and plays, but no play event. Can be seen here, http://butcherjoseph.staging.wpengine.com/resources/

**Comment by jhkerschner** [comment]
Solve this issue but not using the auto play setting and instead playing the video once the player is ready. This allows for the play event to fire.

**Comment by luwes** [comment]
great @jhkerschner! Yes I believe if autoplay is in the options the event will be attached after autoplay is triggered.

**Comment by giannif** [comment]
Unless it's clear somewhere in the docs that `vimeo/player.js` doesn't work with autoplay, this should probably be reopened. 

I was using autoplay and assumed events would work, a tough bug to track down since they _did_ work periodically.

@luwes

**Comment by blakewilson** [comment]
I would also like to note that the `background` embed option doesn't fire the `play` event like the `autoplay` option.

I second @giannif opinion that this should be reopened. As I would imagine, a lot of users use the `autoplay` and `background` options; there is no real way for them to utilize the `play` event.

**Comment by blakewilson** [comment]
For those that may need it, I've made a simple gist on how to make a makeshift play event for the API that will fire once the video is played and works with the `autoplay` and `background` embed options.

You can find the gist here:
https://gist.github.com/blakewilson/6a80b0dea9c0b5c25cb95ca8d09bbca1
