### ISSUE TITLE
API Doesn't Seem to Work in IE9/10

### ISSUE THREAD

**Issue by joshuapease** [vimeo/player.js#158]
I'm having trouble getting the API to work in Internet Explorer 9 o 10 (tested using Browserstack). 

Initially came across this issue because events weren't working in older IEs when using the [pre-existing player method](https://github.com/vimeo/player.js#pre-existing-player)

I switched to the [create with URL/ID method](https://github.com/vimeo/player.js#create-with-a-video-id-or-url) to see if that would work. Turns out that player.js just silently fails. 

No error messages, no video player. 

### Steps to Reproduce

I used the following example code from the readme. 

Here is a Codepen as well. 

https://codepen.io/anon/pen/YxdNyX

```
  <div id="made-in-ny"></div>

   <script src="https://player.vimeo.com/api/player.js"></script>
   <script>
       var options = {
           id: 59777392,
           width: 640,
           loop: true
       };

       var player = new Vimeo.Player('made-in-ny', options);

       player.setVolume(0);

       player.on('play', function() {
           console.log('played the video!');
       });
   </script>
```

**Comment by luwes** [comment]
The player API is only supported from IE11 from now on. Sorry.

**Comment by kojilab** [comment]
I'm on IE11 and am having the same error
