### ISSUE TITLE
Player object disappears after page load

### ISSUE THREAD

**Issue by jeffreyroberts** [vimeo/player.js#160]
### Expected Behavior
    <script src="https://player.vimeo.com/api/player.js"></script>
    <script>
        var iframe = document.querySelector('#vid1');
        var player = new Vimeo.Player(iframe);
    
        player.on('play', function() {
            
    	console.log('played video');
    
    	(function ($) {
    
    		console.log('started function');
    
    		var api = $.pixelentity.themeSlider.getSlider();
    		api.pause();
    		api.destroy();
    
    		console.log('finished function');
    
    	}(jQuery));
    
    	console.log('finished on play');
        });
    
        player.on('ended', function() {
    
            console.log('ended the video!');
    
    	(function ($) {
    		console.log('started function');
    
    		var api = $.pixelentity.themeSlider.getSlider();
    		api.resume();
    
    		console.log('ended function');
    	}(jQuery));
    
    	console.log('finished ended video');
        });
    
        player.getVideoTitle().then(function(title) {
            console.log('title:', title);
        });
    </script>
### Actual Behavior
Console Log Output:

     title: Circle F

### Steps to Reproduce

Visit and push play on the either one of the videos, for me there is no console.log output
     
     https://www.circlefduderanchcamp.com/

**Comment by luwes** [comment]
I hope you found a solution to this. Seems not related to player.js initially, maybe something with the slider. Closing for now.
