### ISSUE TITLE
not working on iOS - no player - no controls

### ISSUE THREAD

**Issue by Lenndev** [vimeo/player.js#162]
### Expected Behavior
working video player added in iframe in set div by id
loading the video, waiting for the play() to be fired
### Actual Behavior
iframe is appended in app but the player.ready() method doesn't seem to be fired neither is the video loaded. 
### Steps to Reproduce
```
import Player from '@vimeo/player'
let videoplayer = new Player('elementid',[options]);
videoplayer.ready().then(()=>{
//do something 
}).catch((error)=>{
//handle error
});

button.onclick = videoplayer.play();

```
using cordova 7.0.1 + vueJS 2.2.1  + cordova ios 4.4.0

on android this works... on ios nothing seems to happen. no errors thrown as well

**Comment by JSteunou** [comment]
that's because vimeo does not support playsinline
we are all waiting for this support sadly :(

**Comment by luwes** [comment]
@JSteunou is correct. `playsinline` will be added by March!
closing see #210.
