### ISSUE TITLE
.play() is full screen on mobile, even when muted and background 

### ISSUE THREAD

**Issue by CooperSystems** [vimeo/player.js#163]
### Expected Behavior
player.play() should let the video play in situ just as with desktop, if the mobile device allows videos playing without user interaction (which has been possible since iOS 10 so long as the video is muted)

We're a pro user attempting to simply autoplay low bandwidth embedded, muted videos on mobile. The reason not to use gif's is because the compression is now so poor compared to mp4/webm, they actually use more bandwidth

This works with the html ```<video>``` tag. There's no technical reason Vimeo couldn't do it, in the mean time we're migrating back to our own CDN

### Actual Behavior
The video attempts to play full screen, which is correctly blocked by the operating system

### Steps to Reproduce
```
<script type="text/javascript">
var wrapper = document.getElementById("vimeoVideo")
var options = {
  id: xxxx,
  width: 400,
  autoplay: true,
  background: true,
  muted: true,
  loop: true,
  byline: false,
  portrait: false,
  title: false
};
var player = new Vimeo.Player(wrapper, options);
player.play()

</script>
```

**Comment by JSteunou** [comment]
that's because vimeo does not support `playsinline`
we are all waiting for this support sadly :(

**Comment by luwes** [comment]
closing see #210.
