### ISSUE TITLE
Loading private video triggering wrong error type

### ISSUE THREAD

**Issue by rijk** [vimeo/player.js#164]
### Expected Behavior

Error with `name: 'PrivacyError'` as per https://github.com/vimeo/player.js/#loadvideoid-number-promisenumber-typeerrorpassworderrorerror

### Actual Behavior

```
{
  message: "Because of its privacy settings, this video cannot be played here.", 
  name: "NotFoundError", 
  method: "loadVideo"
}
```

Note that the name is "NotFoundError", while the message clearly states that the problem is a privacy error. Name property should be "PrivacyError".

### Steps to Reproduce

Call `player.loadVideo( PRIVATE_VIDEO_ID ).catch( console.log )`.

**Comment by luwes** [comment]
This is resolved in the latest release. Can be verified here:
https://jsfiddle.net/luwes/50vp9god/

Thanks for your patience.
