### ISSUE TITLE
Player unusable after error at instantiation

### ISSUE THREAD

**Issue by LoveIsGrief** [vimeo/player.js#166]
Maybe related to #165 

### Expected Behavior

The player should be able to call all its methods after instantiating a bad player, but their promises should all be caught.

### Actual Behavior

Promises are never fullfilled.

### Steps to Reproduce

[Codepen](https://codepen.io/anon/pen/wrqvpW?editors=1010)

1. Create a new player with an invalid URL
2. Try to load a valid video

### Possible source

`callMethod` in [player.js](https://github.com/vimeo/player.js/blob/master/src/player.js#L136). It only tries to do its stuff when the player is ready, but if it never started out ready, then it just won't do anything.

**Comment by mirague** [comment]
Also running into this problem, are there any known workarounds until this gets solved?

**Comment by mirague** [comment]
After looking into this I see that the `element` is cached inside a `WeakMap`, and returned if it already exists: https://github.com/vimeo/player.js/blob/master/src/player.js#L59

This poses a problem if you're trying to reuse the element inside for example React. Perhaps if the instantiation fails we should also remove the element from the WeakMap? Now users wanting to use Vimeo on a mounted React component are forced to use a hacky workaround to unmount the element from the DOM and re-insert it.

**Comment by luwes** [comment]
When loading an invalid clip the ready promise will now reject and in turn all getters, setters and methods as well.
