### ISSUE TITLE
Errors from ready() promise do not contain status code

### ISSUE THREAD

**Issue by rijk** [vimeo/player.js#168]
More info in #165.

While trying to find a way to catch errors during instantiation of the player, we found the following workaround:

```javascript
player = new Vimeo.Player( ... )
player.ready().catch(...)
```

However, the [errors thrown](https://github.com/vimeo/player.js/blob/master/src/lib/embed.js#L69-L76) here are of appalling quality; they just contain a message, no code, no name. Therefore, attempting to interpret these errors to produce a more understandable error message for the user would force us to use a brittle system of running a regex on the error message.

### Expected Behavior

The errors thrown by the `ready()` method follow the [`loadVideo()` API](
https://github.com/vimeo/player.js/#loadvideoid-number-promisenumber-typeerrorpassworderrorerror).

### Actual Behavior

Useless error.

### Steps to Reproduce

```javascript
player = new Vimeo.Player( ... ) // with private or deleted video (403/404)
player.ready().catch(...)
```

**Comment by luwes** [comment]
The `player.ready()` method should now have promise rejections with more detailed error messages during initialization. NotAllowedError, PrivacyError, for the rest Error.
