### ISSUE TITLE
How to end the fullscreen mode in the "on pause" event?

### ISSUE THREAD

**Issue by leolux** [vimeo/player.js#169]
### Expected Behavior
The user watches the video in fullscreen mode und presses the pause button. This triggers the pause event which should stop the fullscreen mode when implemented like this::
`videoPlayer.on('pause', function () {
    videoPlayerContainer.style.display = 'none';
  });`

### Actual Behavior
After hiding the video in the on pause function the fullscreen mode is still active which stops the ability of the user to scroll the page.

### Steps to Reproduce
set allowfullscreenon the iframe and implement the on pause function as given above.

**Comment by adventurist** [comment]
Has anyone else looked into solutions for programmatically closing/hiding the video?

**Comment by luwes** [comment]
@leolux have you found a solution? 
`videoPlayerContainer.style.display = 'none';` seems not correct for the wanted behavior.

@davekiss 's solution will probably do it.

closing for now.

**Comment by leolux** [comment]
Yes, the solution from davekiss works!
