### ISSUE TITLE
Problem to switch video

### ISSUE THREAD

**Issue by KelvynCarbone** [vimeo/player.js#17]
### Steps to Reproduce

I'am using loadVideo but he dont work:

player.loadVideo(27855315).then(function(id) {
                    console.log("work");
                });

He don't switch iframe src.

**Comment by bdougherty** [comment]
Just to clarify, the video loads properly but the `src` attribute on the iframe isn't changing, correct?

**Comment by bdougherty** [comment]
The iframe src is always going to remain the same as it was originally.

The library could change the `src` to load the new video, but it's not as smooth as using the API to do it. As far as I can tell, there's no way to tell the browser to change the `src` attribute from within the iframe, even when we update the location with `history.replaceState` (which is what we do).
