### ISSUE TITLE
Speed controls sometimes disappear after running loadVideo()

### ISSUE THREAD

**Issue by jeffreybiles** [vimeo/player.js#171]
### Expected Behavior

I have set the speed option to `true` when instantiating `Player`, so that the speed controls show up for the user.  The speed controls should continue to display even when I load other videos.

### Actual Behavior

When I load another video into the instantiated player via `loadVideo`, the speed controls *sometimes* disappear.

### Steps to Reproduce

1. Create a player with the initial video

```js
    let player = new Vimeo.Player($('#vimeo-vid'), {
      id: this.get('videoId'),
      speed: true
    });
    player.play();
```

At this point the speed controls are shown.

2. User selects a new video, so load that video into the player

```js
  player.loadVideo(this.get('videoId')).then(function(){
    player.play();
  });
```

At this point the new video will load, but sometimes the speed controls will have disappeared.

Is there a step or option I'm missing?

**Comment by luwes** [comment]
This is fixed in the newest Vimeo player release. Thanks for your patience.
