### ISSUE TITLE
can I remove "Vimeo" logo

### ISSUE THREAD

**Issue by shigg1120** [vimeo/player.js#173]
As the title says, there is the Vimeo logo at the right side of the control. No offense, but how can I remove it?

<img width="913" alt="screen shot 2017-10-13 at 5 26 37 pm" src="https://user-images.githubusercontent.com/15307586/31537046-c7c834a2-b03b-11e7-8966-ad783a4c11a3.png">

**Comment by danaburger** [comment]
You need to remove the Vimeo logo in your embed settings on Vimeo. Only paid members can control the look of the embedded player. https://help.vimeo.com/hc/en-us/articles/224972808-Customizing-the-embedded-player

**Comment by gcascbt** [comment]
Login into your vimeo account and click on video then on check vimeo logo on vimeo the

**Comment by CyberCyclone** [comment]
It would be a good feature to be able to override this using this plugin. It has "Embed Options" but it's not all the embed options that the Vimeo dashboard provides and it's specifically lacking control for the Vimeo logo removal.
