### ISSUE TITLE
iOS enableTextTrack not working to enable captions (mobile player)

### ISSUE THREAD

**Issue by AshtonSanders** [vimeo/player.js#175]
### Expected Behavior
Use .enableTextTrack() to turn on captions.

### Actual Behavior
Works in all browsers, except for iOS (mobile) 11.0.3's player.

### Steps to Reproduce
I use this code to turn on English Subtitles, which works well in all browsers, except for on the latest iOS player:
player.enableTextTrack('en').then(function(track) {
track.language = 'en';
track.kind = 'subtitles';
track.label = 'English (United States)';
});

Test page : https://www.frontsight.com/test.asp
(This video has captions for the first 10 seconds)

**Comment by luwes** [comment]
This is fixed according to our tests 🎉. Please let us know if not!
