### ISSUE TITLE
player.setCurrentTime does not work on load in iOS

### ISSUE THREAD

**Issue by plainjoe** [vimeo/player.js#176]
### Expected Behavior
Video in iframe should auto forward to time spot on load using setCurrentTime method.
### Actual Behavior
Video in iframe loads but does not forward.
### Steps to Reproduce
Go here on an iOS device - http://go.mediasocial.tv/pages/vimeoembed.htm?offset=1729933&cid=4&vid=239288349 - the video will try to forward to a predetermined offset but does not.  It is calling player.setCurrentTime method in a jQuery(window).load() event handler.   autoplay is set to 0.  FYI, this works correctly on desktop and Android devices.  
Some additional information, after the video loads, you tap on the video to play, and then you manually forward the video, the video will then sync to the predetermined offset as it should.  There is code in the iframe that detects if the user forwards/rewinds the video, and will force the user back to the proper time spot.

Please advise.

Thanks

**Comment by fisherinnovation** [comment]
@plainjoe This issue should be corrected now. Can you re-test and reopen this ticket pending you are still noticing the issue? Thanks for your patience.
