### ISSUE TITLE
Events are not firing while changing vimeo URL.

### ISSUE THREAD

**Issue by psiva017** [vimeo/player.js#177]
### Expected Behavior
events like timeupdate, pause should fire when changing the video URL.
### Actual Behavior
Events are firing for only first video (Which is loading for the first time). If I change the URL dinamically then the events are not firing.
### Steps to Reproduce

https://jsfiddle.net/siva_p/wsao9jbd/12/

For the first video, events are triggering. 
Click change video.
Then no events are triggering.

Thanks.

**Comment by fisherinnovation** [comment]
@psiva017 I have put together a [simplified version](https://jsfiddle.net/984ydept/) of what you were trying to accomplish in your JSFiddle, hopefully it can shed some light on the issue. My example avoids rebuilding the player for each video and instead uses the loadVideo promise. This will ensure that the event listeners are connected to the player instance at all times.

**Comment by psiva017** [comment]
It works :)

Thanks @fisherinnovation
