### ISSUE TITLE
Videos not playing, loading forever with setCurrentTime(0)

### ISSUE THREAD

**Issue by codebykyle** [vimeo/player.js#178]
### Expected Behavior
The video should auto-play at the beginning of the video, or pick up where the user left off. Passing 0 into setCurrentTime should start the video at zero seconds in, and start playing.

### Actual Behavior
 This was working up until a couple of days ago. Currently, if setCurrentTime is 0, it will forever load and will not play until a user moves the current time slightly into the video

### Steps to Reproduce

```js
            let vimeoOptions = {
                url: this.content.video_url,
                player_id: "player"
            };

            let vimeoPlayer = new Player(this.$el, vimeoOptions);
            let startPlayerAt = this.videoStartTime; // 0 if the user hasnt started, or picking up where the user previous left off
            vimeoPlayer.setCurrentTime(startPlayerAt);
```

Issue JS Fiddle:
https://jsfiddle.net/xk4gwh39/

Passing 1 in will work correctly:
https://jsfiddle.net/xspor5mt/

**Comment by littlevahn** [comment]
I think if you download the latest changes it should fix this issue. The event seekTo was changed to seeked. Might be the issue you are seeing.

**Comment by codebykyle** [comment]
Thanks for the reply. If you have a look at the jsfiddle, I am using the version of player.js in the documentation via the CDN.

**Comment by littlevahn** [comment]
Weird, yea it appears since vimeo started feeding content in fragments, to be friendly with Chrome's new standards the seekTo function is bombing. The player seeks to the time location but then stops accepting events... Very strange. Hopefully the dev will figure it out.

Sorry i couldn't be more help.

**Comment by frumbert** [comment]
> Setting the current time before playback has started will cause playback to start.

    // including https://player.vimeo.com/api/player.js

    var ts = 30, player=new Vimeo.Player(document.querySelector('#player1'));
    player.ready().then(function() {
	player.setCurrentTime(ts).then(function(seconds) {
		player.play();
	}).catch(function(error) {
		console.log('setCurrentTime.catch', error);
	});
    });

This puts my video in a forever seeking mode at the start of the media. If I pull the cue point ahead, _then_ press play (it won't go by itself), it plays from that point - as if the initial _setCurrentTime()_ didn't do anything.

**Comment by psoluch** [comment]
I have the same issue. What is weird, it works with some videos, it doesn't with other. 

e.g. here it doesn't: https://thefour.com/ch/#1
here it does: https://thefour.com/ch/#2

it used to work fine. Version of player.js does not matter. Tried with current and older ones.

any help?

**Comment by alexandremaeda** [comment]
Same issue here. Loading script via CDN.

**Comment by frumbert** [comment]
I've had to modify mine so that I store a `played` flag, then put the setCurrentTime after the play event. 

    var played=!1,
        ts = 90,
	player=new Vimeo.Player(document.querySelector('#player1')); 
    player.on('play',function(data) {
	if (!played && ts>0) {
		player.setCurrentTime(init.timestamp);
	}
	played=!0;
    });

**Comment by lucasmoeskops** [comment]
For me, it will load the video up until the requested second, but start playing from the start anyway this way.

**Comment by fisherinnovation** [comment]
This should be fixed now, thanks for your patience everyone. Can you retest and reopen this ticket pending you can still replicate?

**Comment by raymondnexsoftech** [comment]
The problem seem happen again in version 2.16.4

here is my code used in vue with vimeo player npm version 2.16.4:
```
async createVimeoPlayer(vimeoId, offset) {
  let that = this;
  let isBeginPlayVideo = true;
  const options = {
      id: vimeoId,
      width: this.iframeWidth,
      height: this.iframeHeight,
      autopause: true,
      keyboard: false,
      // controls: false,
      quality: this.quality || "1080p"
  };
  this.showVideo = false;
  this.vimeoPlayer = new Player('vimeo-live-player', options);
  console.log("before calling setCurrentTime()");
  await this.vimeoPlayer.setCurrentTime(offset);    // <-- (1) program will stop here
  console.log("after calling setCurrentTime()");
  this.timeWatched = offset;
  this.isPause = false;
  this.vimeoPlayer.on('play', async function() {
    if (that.isPause) {
      await that.vimeoPlayer.pause();
      await that.loadNewVideo();
    }
    that.showVideo = true;
  });
  this.vimeoPlayer.on('pause', function() {
    if (!isBeginPlayVideo) {
      that.isPause = true;
    }
  });
  this.vimeoPlayer.on('ended', async function() {
    await that.loadNewVideo();
  });
  this.vimeoPlayer.on("timeupdate", function(data) {
    if (data.seconds - 1 < that.timeWatched && data.seconds > that.timeWatched) {
      that.timeWatched = data.seconds;
    }
  });
  this.vimeoPlayer.on("seeking", async function(data) {
    console.log("before calling setCurrentTime() at seeking");
    await that.vimeoPlayer.setCurrentTime(that.timeWatched);  // <-- (2) will works fine even I replace "that.timeWatched" to 0
    console.log("after calling setCurrentTime() at seeking");
  });
  await this.playVimeoPlayer();
  isBeginPlayVideo = false;
  return;
},
```

When I pass offset = 0 to the function, the program will stop at marked position (1) (Just after the vimeo player is created).
But it seems works normally at marked position (2) even I replace the "that.timeWatched" there.
Seems somehow the function not works properly if the video is not yet playing I guess.

**Comment by saraedum** [comment]
Using `setCurrentTime(Math.max(value, Number.EPSILON))` seems to work. I guess 0 being false is a problem somewhere down the line.
