### ISSUE TITLE
player.play() does not work on iOS when triggered from jQuery click on an overlay

### ISSUE THREAD

**Issue by jmp909** [vimeo/player.js#18]
### Expected Behavior
player.play() should cause the video to play. 

### Actual Behavior
the video does not play on iOS. it works fine on desktop

### Steps to Reproduce
1. go here http://codepen.io/jmp909/full/dXWwoO/
2. wait for an overlay to turn green (vimeo player ready)
3. click the overlay to hide it and trigger the player.play()
4. video does not play on iOS, user has to click play on the actual vimeo play button

```javascript
$container.on("click", function() {
  player.play();              
  $container.addClass("played"); // hides the overlay
})
```

**Comment by bdougherty** [comment]
This is a limitation of iOS. If you add a `.catch` to the play call you should get an error.
