### ISSUE TITLE
'background' option isn't truly implemented

### ISSUE THREAD

**Issue by VickyKoblinski** [vimeo/player.js#181]
### Expected Behavior
'background' option permameter to have the same behavior as `https://player.vimeo.com/video/{id}?background=1`

### Actual Behavior
It doesn't do anything because `https://vimeo.com/api/oembed.json?url=https://player.vimeo.com/video/{id}&background=1` doesn't handle the background parameter.

### Steps to Reproduce
See here: [JSFiddle](https://jsfiddle.net/c2kz094v/)

**Comment by rsichel107** [comment]
Hi @VickyKoblinski, 
I fixed the `background` and `transparent` options officially. If you open your JSFiddle it will function as you expect. Apologies for the confusion. And thanks for your contribution with a temporary fix. I am closing your pull request.
