### ISSUE TITLE
Event : ended does not fired

### ISSUE THREAD

**Issue by l2aelba** [vimeo/player.js#183]
Since the doc show we are able to use **[ended event](https://github.com/vimeo/player.js#ended)**

But this does not fired and **I do not see ended event in source code**

``` javascript
var player = new Vimeo.Player($html);

player.on('ended', function () {
   console.log('ended'); // Nothing fired
});
player.on('pause', function () {
   console.log('pause'); // It's work
});

$('.element').append($html);
```

**Comment by mirague** [comment]
You may wish to include what version you're using to make it easier for someone to try and replicate this behaviour. I'm seeing the `ended` event being fired just fine on my end!

**Comment by fisherinnovation** [comment]
I have created a [JSFiddle](https://jsfiddle.net/4dbx7z90/) with a working example for you to review. Feel free to reach out again pending you are still having issues.
