### ISSUE TITLE
When playing and then loading an invalid video, an unstoppable flood of exceptions is thrown

### ISSUE THREAD

**Issue by mirague** [vimeo/player.js#184]
When you're playing a video and try to `loadVideo(id)` with an `id` that is not a valid video (or not allowed for embeds), you will see a stream of `Uncaught TypeError: Cannot read property 'sentry' of undefined` thrown (observable in DevTools console) about every 1 second or so. This cannot be stopped by calling `unload()` or `pause()` either.

### Expected Behavior
A `catch()`able exception is thrown once when trying to `loadVideo(id)` with an `id` of an invalid video. No other uncaught errors should be triggered.

### Actual Behavior
A stream of `Uncaught TypeError: Cannot read property 'sentry' of undefined` is thrown (observable in DevTools console) about every 1 second or so.

![image](https://user-images.githubusercontent.com/178117/32699203-46403ac2-c7b2-11e7-8bbb-ffc54a74bd48.png)

### Steps to Reproduce

Checkout this [CodePen](https://codepen.io/mirague/pen/YEVQwQ?editors=1010#0) 

_..or follow these steps manually:_
1. Go to https://player.vimeo.com/api/demo
2. Press play on the pre-loaded video (id: `76979871`)
3. Wait until it's playing, then load an invalid video (id: `1`)
4. Checkout the developer console for a flood of `Uncaught TypeError: Cannot read property 'sentry' of undefined`

**Comment by rsichel107** [comment]
Hi @mirague, in our latest release we corrected our error behavior so now there is a "catchable error" when load video fails. However, the sentry errors still remain. We are working on a fix now. Thank you for your patience.

**Comment by luwes** [comment]
This should be fixed in our latest release!
