### ISSUE TITLE
Get Videos description from the player

### ISSUE THREAD

**Issue by jdsiddon** [vimeo/player.js#186]
### Expected Behavior
* I have access to a videos description on the player object

### Actual Behavior
* Only titles available

**Comment by fisherinnovation** [comment]
@jdsiddon Can you provide an example of your implementation? Are you using [getVideoTitle](https://github.com/vimeo/player.js/#getvideotitle-promisestring-error)? If so, that method will only return the title.

**Comment by frumbert** [comment]
You can use the oembed api to get the description - https://developer.vimeo.com/apis/oembed

**Comment by bewards** [comment]
@frumbert this is true for the most part, but if your video is set to anything but private, the description will not be returned, per the doc:

> If a video’s privacy is set to anything other than public, private or password protected, only the embed code, width, and height will be returned. Private videos are never accessible through the Simple API.

**Comment by luwes** [comment]
this will not be implemented here I believe.

it's possible to get that info with the advanced API which works with authentication. 
https://developer.vimeo.com/api/endpoints/videos#GET/videos/{video_id}

**Comment by jhedmendoza** [comment]
It's pretty late but I want to show how I got the description. You can get the description or any metadata you want by using https://developer.vimeo.com/api/oembed/videos

var iframe = $('iframe');
var player = new Vimeo.Player(iframe );

player.getVideoId().then(function(id) {
   $.get('https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/'+id, function(data, status){
           console.log(data.description);
     });
});
