### ISSUE TITLE
"Transparent" Embed Option Not Working

### ISSUE THREAD

**Issue by adeeb1** [vimeo/player.js#187]
### Expected Behavior

When the `transparent` embed option is set to `false`, the responsive player and transparent background are disabled.

<img width="937" alt="vimeo player - transparent option expectations" src="https://user-images.githubusercontent.com/4312320/32987572-618d7fbe-cca4-11e7-82cb-c35fcff912d2.PNG">

### Actual Behavior

The responsive player and transparent background are enabled regardless of the value of the `transparent` embed option.

<img width="938" alt="vimeo player - transparent option not working" src="https://user-images.githubusercontent.com/4312320/32987573-6508cf4a-cca4-11e7-813a-341f82c77db5.PNG">

### Steps to Reproduce

```
var playerOptions = {
  id: "68401939",
  byline: false,
  portrait: false,
  transparent: false
};

var player = new Vimeo.Player("player", playerOptions);
```

JSFiddle: https://jsfiddle.net/7gnrxc2w/2

### Additional Information

Browser: Google Chrome 62.0.3202.94 (Official Build) (64-bit)
Player JS Version: Latest (I am using the CDN)

The `transparent` parameter is not present in the `iframe` `src` when it is specified. This is the `src` value generated using the options in the reproduction steps: `https://player.vimeo.com/video/68401939?byline=0&portrait=0`

The player in the screenshot of the Expected Behavior section above renders correctly because I manually modified the `src` value of the `iframe` using Google Chrome's DOM explorer. I changed the `src` value to the following: `https://player.vimeo.com/video/68401939?byline=0&portrait=0&transparent=false`

**Comment by rsichel107** [comment]
@adeeb1 Apologies for the delay. This has been fixed officially. If you look at your JSfiddle it performs as expected.

**Comment by adeeb1** [comment]
@rsichel107 Great, thank you for the quick fix!
