### ISSUE TITLE
[Question] How to keep Player object?

### ISSUE THREAD

**Issue by Med-All** [vimeo/player.js#189]
I'm trying to retain some user data when someone was watching Vimeo video and left of at X minute and went to another "view" (it is AngularJS one page app).

I'm spawning new Vimeo player with

`var player = new Vimeo.Player('player');`

then getting current time of a watched video

```
player.on('play', function() {
  player.getCurrentTime()
  .then(function(seconds) {
      $scope.currentTime = seconds;
  });
});
```
but when user will switch a "view" and come back to a view with Vimeo player it starts as another (new) video Player not updating existing one.

Any tips on that?

**Comment by luwes** [comment]
I'm sorry but this is more a programming question.

A potential solution would be using the singleton pattern or keeping a global reference to the player instance and not creating a new instance every time.
