### ISSUE TITLE
autopause does not work when videos are triggered with player.play()

### ISSUE THREAD

**Issue by jmp909** [vimeo/player.js#19]
### Expected Behavior
triggering one video with player.play() should pause the other by default

### Actual Behavior
other video did not pause. this only seems to work when interacting with the actual vimeo UI, not using player.play()

### Steps to Reproduce
1) go here http://codepen.io/jmp909/full/dXWwoO/
2) wait for an overlay to turn green (vimeo player ready)
3) click the overlay to hide it and trigger the player.play()
4) click on another overlay to play another video
5) note first video does not pause.

**Comment by bdougherty** [comment]
I've filed an internal issue to get this fixed and I'll update the ticket when it's resolved. Thanks!

**Comment by bdougherty** [comment]
We've updated the player so that autopause will work with the api, but you'll have to remove the `?api=1` parameter from each embed (or explicitly call `setAutopause(true)`).

http://codepen.io/bdougherty/full/YWOZJO

**Comment by cascornelissen** [comment]
@bdougherty, this problem seems to be back again? Your codepen isn't working for me in Chrome/FF, anyways.

Any ideas?

**Comment by ofmarconi** [comment]
No solution for that @bdougherty?

Thanks
