### ISSUE TITLE
Getting error “e.data.split is not a function” on attaching listener to 'play' events

### ISSUE THREAD

**Issue by omeryousaf** [vimeo/player.js#191]
### Expected Behavior
The code given below should run without any errors.
### Actual Behavior
I get the error when the following code gets executed
`player = new Vimeo.Player(vimeo_iframe_id);`
`player.on('play', function() { // gives error e.data.split is not a function in browser console`
    `isVimeoPlaying = true;`
`});`
Having said that, the listener does get attached to the player and subsequent play events are captured by it but why does that error get thrown every time an event is fired ?
### Steps to Reproduce
Just run the code above on any page with an embedded vimeo iframe in it.

**Comment by fisherinnovation** [comment]
Hey @omeryousaf I have created a JSFiddle (https://jsfiddle.net/4umg0fp1/) in an attempt to replicate your issue but I am unable to do so. Could you test that out and let me know if that demo is of any help?

**Comment by omeryousaf** [comment]
@fisherinnovation thank you so much for following up. after looking at your fiddle it occurred to me that the issue was being caused by our own code (we have implemented handler for PostMessages which had these lines `window.addEventListener('message', function (e) {

        var action = e.data.split(':')[0];
    ...}`
which was assuming e.data would always be a string and that was breaking with error because in case of postmessages sent by vimeo e.data is a json. so i have modified the code to `var action = typeof e.data === 'string' ? e.data.split(':')[0] : null;` and am not getting errors anymore. Thank you again for reaching out. Do let me know if you have other thoughts on modification i made. Appreciate your help!!!

**Comment by fredlee0109** [comment]
You can close your issue
