### ISSUE TITLE
After loading a new video, the playbackRate property is set to 1

### ISSUE THREAD

**Issue by olegpolyakov** [vimeo/player.js#192]
### Expected Behavior
After a new video is loaded into the player, it uses the previously set value for playbackRate property.

### Actual Behavior
After a new video is loaded into the player, it changes the playbackRate property back to 1.

### Example
https://jsfiddle.net/47kqphv1/

**Comment by luwes** [comment]
this is intended behaviour, after the `loadVideo` call we reset it back to 1 internally.

**Comment by olegpolyakov** [comment]
It is not very convinient because the user has to change the playback speed for every video.
