### ISSUE TITLE
In Android (or other mobile), when user taps on "play", it automatically goes to full screen

### ISSUE THREAD

**Issue by fredlee0109** [vimeo/player.js#194]
### Expected Behavior
Video plays, without affecting fullscreen behavior.
Allow developer to handle fullscreen behavior in mobile useragent
### Actual Behavior
When not in full screen, the video plays and goes into full screen.
### Steps to Reproduce
Go to: https://player.vimeo.com/api/demo
1) Open chrome console
2) Go to Network conditions
3) Unselect "Select automatically" and choose Android
4) Refresh
5) Hit play
6) Watch it go fullscreen

https://codepen.io/anon/pen/VyaEvZ?editors=1011

**Comment by luwes** [comment]
closing see #210

**Comment by fredlee0109** [comment]
Will this also affect Android?

**Comment by luwes** [comment]
that's a good point. right now the player forces the player to go fullscreen on all small mobile devices.
I think with the addition of `playsinline` we can unify this behaviour across all browsers and devices and have the player play inline by default everywhere.
@fisherinnovation
