### ISSUE TITLE
setPlaybackRate doesn't work when background=true

### ISSUE THREAD

**Issue by itgeorge** [vimeo/player.js#195]
### Expected Behavior
```setPlaybackRate``` should resolve/reject the returned promise and (if successful) change the player's playback rate on both ```background: false``` and ```background: true``` players
### Actual Behavior
```setPlaybackRate``` does not resolve or reject if the player has ```background: true``` in it's options

I couldn't find anything directly mentioning such behavior in the readme, or in this post: https://help.vimeo.com/hc/en-us/articles/115011183028-Embedding-background-videos, or in this help article: https://help.vimeo.com/hc/en-us/articles/115011183028-Embedding-background-videos, so I'm assuming this is not intended behavior, but please excuse me if I am missing something.
### Steps to Reproduce
Simply attempt to change the playback rate of a player which has ```background: true``` in options or ```background=true``` in the iframe url

Here is a modified version of the fiddle in #159 which reproduces the issue
http://jsfiddle.net/qrmkw18s/

### Use-Case
The use-case for this is implementing custom UI for the Vimeo player (which is synced-up with other UI elements on the page, e.g. charts with a time axis) with speed (playback rate) controls.

**Comment by simchaba** [comment]
Same behavior happen also when using `controls: false`

I guess both issue are related.

**Comment by luwes** [comment]
this works in the mean time when `controls=false`
