### ISSUE TITLE
Question: is it possible to resize the embed after it was loaded?

### ISSUE THREAD

**Issue by francoisromain** [vimeo/player.js#198]
Hello, 

Is there an api function like 'setVideoWidth' to re-set the video size after it was loaded (on window resize for example)?
If not, how would you handle a resize? 

Thank you

**Comment by fisherinnovation** [comment]
The player.js API does not allow for manually changing the quality of playback. Resizing the player can be completed by updating the dimensions of the iframe or div you have used to place it in. Take a look [at this example](https://jsfiddle.net/wcwdbs62/) for additional help. I hope this helps.

**Comment by francoisromain** [comment]
perfect thank you
