### ISSUE TITLE
Start/End Time Embed Options

### ISSUE THREAD

**Issue by adeeb1** [vimeo/player.js#20]
I love that Vimeo has made the JavaScript Player API open source; thank you! Are there any embed options to start/end a video at certain second values (ex: start at 60 and end at 180)? I would love to be able to specify when a video starts and when it ends.

**Comment by bdougherty** [comment]
This is something we've thought about adding, but there aren't any official options as of now and it's not specifically on our roadmap.

For now, you could either trigger the play yourself by calling `player.setCurrentTime(60)` or you can listen for the `play` event and then call it if the time is 0:

```js
player.on('play', function(data) {
    if (data.seconds === 0) {
        player.setCurrentTime(60);
    }
});
```

Then for the ending, listen for a `timeupdate` that's `>= 180`, pause the video, and show an overlay over the player or something.

**Comment by adeeb1** [comment]
Thank you for the prompt reply and the code sample!

Is there anywhere to request features? I know that this specific feature has been requested 4 years ago on your forums, and it is surprising that it has not even been backlogged: https://vimeo.com/forums/topic:49396

I work in education, where it is common to show specific portions of a video rather than the entire video. As a result, YouTube is our go-to platform because it supports start/end times in the embed code. As I am technical, this solution works great for me, but it does not work for many others.

**Comment by fisherinnovation** [comment]
Moving to internal roadmap. Thanks again for the feedback.

**Comment by udidol** [comment]
Any news on this?

**Comment by smartasc** [comment]
Same as @adeeb1 I work in education and while this is a solution for me, it is not for many others. I can definitely second the need for a start AND end time available in Vimeo. (It is the reason I ended up here).
Thanks!

**Comment by jodinathan** [comment]
why would they close the issue (while it is open somewhere in their system) and let us wait in the void?

**Comment by aledc7** [comment]
AGO 2020 any news?
