### ISSUE TITLE
Options not being applied to the third autoload video

### ISSUE THREAD

**Issue by martinmorando** [vimeo/player.js#204]
### Expected Behavior
Autoplay one video (entirely) after another.

### Actual Behavior
The problem appears on the third video, it loads correctly but doesn't autoplay. To autoplay the videos I set the option 'autoplay' to '1' at the beginning. Seems like the player suddenly stops applying the options in the third video. That also explains why the color red I set also disappears. I can't understand why **the player loads the third video correctly but not the options**. Is this a bug on JavaScript API or is my mistake? Thanks.

### Steps to Reproduce
See the problem in action https://jsfiddle.net/58aoLmeg/

**Comment by luwes** [comment]
This is fixed in the newest Vimeo player release. Thanks for your patience.
