### ISSUE TITLE
Uncaught (in promise) console error when background=1

### ISSUE THREAD

**Issue by leetoufong** [vimeo/player.js#205]
### Expected Behavior
No console errors on any platform or device.

### Actual Behavior
iframe embed throws a `Uncaught (in promise) TypeError: Cannot read property 'on' of undefined` console error when `background=1`on mobile/touch devices. Works fine on desktops. Am i missing something here?

### Steps to Reproduce
https://jsfiddle.net/mas10p64/3/

**Comment by rogerburkhard** [comment]
I have the same problem on Mobile/Touch Devices.

**Comment by man0ffire** [comment]
Same here. Happens even if I only turn on the Device Toolbar in Chrome.

**Comment by rsichel107** [comment]
We have fixed this behavior. There are no console errors appearing in mobile with the `background` param. 
However, it is worth noting that currently background videos do not autoplay on mobile devices.
