### ISSUE TITLE
Feature request: Event 'speedchange'

### ISSUE THREAD

**Issue by kospl** [vimeo/player.js#206]
### Expected Behavior
player.on('speedchange', function(data) {
    // data is an object containing properties specific to that event
});

For now there is no event is dispatched when speed changed via player's UI.

As a workaround I use `setInterval` combined with `getPlaybackRate`, but it would be nice to have player's `speedchange` event.

**Comment by reckoner165** [comment]
`playbackratechange` accomplishes what you are describing,.

**Comment by kospl** [comment]
@reckoner165 thanks for letting know! 

Then this feature request should be read as "add info about `playbackratechange ` to documentation" :)

**Comment by rsichel107** [comment]
Thanks @reckoner165, nice catch.
