### ISSUE TITLE
FeatureRequest: startTime option in embed-options

### ISSUE THREAD

**Issue by fredlee0109** [vimeo/player.js#208]
### Expected Behavior

https://jsfiddle.net/kjkcrz12/1/

I want to be able to give `startTime` option in constructing the player.

https://github.com/vimeo/player.js#create-an-embed
https://github.com/vimeo/player.js#embed-options

As a workaround, we are currently doing a one-time .setCurrentTime() on timeUpdate event

**Comment by luwes** [comment]
Closing as it is a duplicate of #20.
