### ISSUE TITLE
enableTextTrack is not resolving the promise with error

### ISSUE THREAD

**Issue by cougil** [vimeo/player.js#209]
### Expected Behavior
When the language does not exist and you try to enable the text track, the vimeo player should return an error.

### Actual Behavior
The vimeo player appears and the Promise is not resolved abnormally so it is not possible to manage the error in any case.

### Steps to Reproduce
Add a vimeo player with an unexisting subtitles

**Comment by rsichel107** [comment]
Hi @cougil, Thank you for surfacing this issue. It was fixed in our latest release.

**Comment by cougil** [comment]
We're using the 2.2.1 version and it seems that it is not working...

**Comment by rsichel107** [comment]
Hm, Are you sure? In this jsfiddle(https://jsfiddle.net/bcp6qyb5/1/) I see the error being caught in the `.catch()`. Perhaps I misunderstood what you are looking to see?
