### ISSUE TITLE
Invisible fullscreen button and play bar in Android WebView

### ISSUE THREAD

**Issue by jaehong-hwang** [vimeo/player.js#21]
I added Vimeo player in [website](http://saeroun.smartmake.net/main/view?type=W&idx=20) using Vimeo Player API,
it works very well in web browser, but it does not work in Chrome WebView.

I need some help!

**Comment by bdougherty** [comment]
I think this seems like something better handled through our official support channels: https://vimeo.com/help/contact

**Comment by spencermefford** [comment]
@bdougherty @jaehong-hwang Did anything come of this? I am having the same issue and would love some guidance. Thank you!

**Comment by jaehong-hwang** [comment]
@spencermefford I solved this problem with Javascript, translate rotate (CSS) and Android tilt sensors.
Please see http://saeroun.godohosting.com/main/view?type=W&idx=394.
