### ISSUE TITLE
Create player with Existing embed fails if you don't put a src attribute

### ISSUE THREAD

**Issue by hmontes** [vimeo/player.js#216]
According to docs.

```
// Select with the `<iframe>`’s id
// Assumes that there is an <iframe id="player1"> on the page.
var idPlayer = new Vimeo.Player('player1');
```

But that don't work except if you use a src.

```
<iframe id="player1" src="some_url_video">
 var idPlayer = new Vimeo.Player('player1');
```

I don't want to load a VIdeo in the first render (Because the Player is in a modal). I want to initiate the player and then, when the modal is open, put a video with loadVideo.

Can you fix that issue, please?

Thank you

React example

```
class Test extends Component {
  render() {
    return(
      <div>
        <iframe ref={iframe => this.iframe = iframe} />
      </div>
     )
  }

  componentDidMount() {
    this.player = new Player(this.iframe);
  }
}
```

That component will fail, except if you add to <iframe ref={iframe => this.iframe = iframe} /> a src attribute with a video address.

Thanks

**Comment by luwes** [comment]
@hmontes would it be possible to set the src right before the new Player() ? like so

```js
  componentDidMount() {
    this.iframe.src = 'https://player.vimeo.com/yourvideoID';
    this.player = new Player(this.iframe);
  }
```

**Comment by hmontes** [comment]
@luwes Maybe. But i don't want to set the src. That is the issue.

**Comment by luwes** [comment]
You can also use a plain div like explained in the readme. would that work?

```js
<div id="made-in-ny"></div>

<script src="https://player.vimeo.com/api/player.js"></script>
<script>
    var options = {
        id: 59777392,
        width: 640,
        loop: true
    };

    var player = new Vimeo.Player('made-in-ny', options);

    player.setVolume(0);

    player.on('play', function() {
        console.log('played the video!');
    });
</script>
```

**Comment by luwes** [comment]
Unless you see otherwise, I believe this can be solved by either of the examples I posted. Thanks!
