### ISSUE TITLE
Video embeds not defaulting to fullscreen anymore on mobile (iOS)

### ISSUE THREAD

**Issue by tmaximini** [vimeo/player.js#218]
### Expected Behavior
until yesterday the videos automatically switched to fullscreen mode on mobile iOS. Did anything change here lately?

```
      <iframe
        id={`vimeo_${video.id}`}
        title={video.title || 'video'}
        src={`https://player.vimeo.com/video/${video.id}`}
        width={video.width}
        height={video.height}
        frameBorder="0"
        allowFullScreen
      />
```
this is how we embed the videos.

```
    this.player = new Player(`vimeo_${video.id}`, {
      id: video.id,
      maxheight: window.innerHeight,
      maxwidth: window.innerWidth,
      title: false,
    });
```

this is how I change / open the video.

### Actual Behavior
Video should enter fullscreen on mobile by default.

### Steps to Reproduce

you can check the implementation here: https://development.fleek.de/ (video stories on second paragraph)

**Comment by luwes** [comment]
@tmaximini thanks for your response. In our latest player release all mobile devices will now play inline by default. we chose this to have a consistent behaviour across browsers/devices where possible.

Of course this can still be disabled by adding `playsinline: false` to the options or `?playsinline=0` to the iframe URL.

Please let me know if you have any more questions. Thanks.

**Comment by tmaximini** [comment]
thanks so much, that was it. the gotcha here was to use `?playsinline=0` on the initial iframe, otherwise the `playsline: false` option later on was ignored!

**Comment by olets** [comment]
Great catch. In my tests `?playsinline=0` in the iframe URL is all it took — without it `playsinline: false` didn't result in the video opening in fullscreen, and with it `playsinline: false` was unnecessary.

Possible that in both cases the option is being ignored? Wonder if there's a bug in the `playsinline` option

**Comment by DavitVosk** [comment]
I have problem with `playsinline` option too. By default it is true, but it again opens full screen video on IOS device
