### ISSUE TITLE
Muted option/param?

### ISSUE THREAD

**Issue by Webcreations907** [vimeo/player.js#220]
Hello,

Is there a muted param that can be put on the url or options?  I don't see any info on that, I know I can set volume to 0, but to autoplay on mobile with playsinline it would need the muted to autoplay.

Thanks

**Comment by Webcreations907** [comment]
Also to add, it doesn't seem you can change the volume on mobile(iPhone) device either using ```setVolume()```. The volume controls don't even show on the player controls like on desktop.

**Comment by RiccardoZaffalon** [comment]
This would be very useful, especially to enable autoplay on mobile devices.
https://webkit.org/blog/6784/new-video-policies-for-ios/
