### ISSUE TITLE
Video is not auto playing in fullsceen mode

### ISSUE THREAD

**Issue by harish-coditas** [vimeo/player.js#221]
I am trying to autoplay a Vimeo video in fullscreen mode. It is auto-playing the video but not in fullscreen mode. Following is the warning I am getting on the console:
`
[Deprecation] 'HTMLVideoElement.webkitDisplayingFullscreen' is deprecated. Please use 'Document.fullscreenElement' instead.`

`Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.`

I tried all the three ways to embed the video but none of them is working. Following is the link to my fiddles:

- https://jsfiddle.net/z6mzcz3h/7/
- https://jsfiddle.net/7kba1uce/2/
- https://jsfiddle.net/3edrhe9s/2/

**Comment by luwes** [comment]
This is to my best knowledge not possible with any video player. To go fullscreen a user interaction is always needed, so either a click/tap or a keyboard press. Closing as this is not possible.
