### ISSUE TITLE
Click on video navigates to Vimeo website

### ISSUE THREAD

**Issue by harish-coditas** [vimeo/player.js#223]
A single click on the upper left corner of the video navigates to Vimeo website where the video is uploaded when played in fullscreen mode.
And it happening only on Android. In iOS, it's working normally.

**Comment by luwes** [comment]
Is this without a title in that place?

**Comment by harish-coditas** [comment]
It seems like when the player is turned into fullscreen and then played, the element with class vp-title or title is having both the class hidden and invisible which is making title to display none. As the opposite of this when the video is directly played keeping playsinline false, it goes into fullscreen and the same element has only invisible class not hidden. It is invisible but still there making it click and navigate the Vimeo.

**Comment by harish-coditas** [comment]
@luwes Any update on the issue?

**Comment by luwes** [comment]
According to my tests this is resolved. Please let us know if it persists on your end. Thank you!
