### ISSUE TITLE
Outro screen does not hide when loading a new video into player

### ISSUE THREAD

**Issue by davekiss** [vimeo/player.js#224]
### Expected Behavior
When a video has ended in a player, the outro screen shows. If loadVideo is then called on that player with a different video ID, the outro screen hides and the new video is shown.

### Actual Behavior
The new video does seem to be loading in the iframe, but the outro screen is not hidden, and due to the absolute positioning and z-index of the outro div, the newly loaded video is never seen.

### Steps to Reproduce
1.) Visit http://www.tianxu.co.uk/commercial/
2.) Click the first thumbnail and seek ahead/allow video to play through end.
3.) Once outro screen appears, click the next thumbnail to attempt to load the next video in the player.

**Comment by rsichel107** [comment]
That link no longer works, would it be possible to get another working example?

**Comment by luwes** [comment]
This is resolved in the latest release. Thank you for your patience on this one.
