### ISSUE TITLE
Missing function - exit full screen on iOS.

### ISSUE THREAD

**Issue by lukasilestam** [vimeo/player.js#225]
### Expected Behavior

in the lib should be a function: `exitfullscreen()`. why? in all browsers you can close the fullscreen by the functions `document.exitFullscreen ();` unfortunately, it does not work on iOS browsers.

### Actual Behavior

it is not possible to close (programmatically) the fullscreen only on iOS devices.

### Steps to Reproduce

I checked in the script - there is the function of closing the fullscreen after the movie ends. just copy and name.

---
example: https://codepen.io/lukasilestam/pen/VXbbwL
working for all browsers except ios browsers. to test just turn on the fullscreen and wait 5 seconds

**Comment by luwes** [comment]
Thanks for your feedback. I'm not sure we can fix this on our end. Does this work on a regular html5 video element?

**Comment by lukasilestam** [comment]
@luwes yes. any vimeo player in iframe:
`document.getElementsByTagName('video')[0].webkitExitFullScreen()`
closing the fullscreen, even on iphone safari ;)

**Comment by RoboBurned** [comment]
Users just reported about a JS error. Is it related to vimeo player? If so, please fix it.
```
TypeError: undefined is not an object (evaluating 'document.getElementsByTagName('video')[0].webkitExitFullScreen')
```

**Comment by luwes** [comment]
this was solved, there are now fullscreen API methods available.

**Comment by Stupidism** [comment]
> Users just reported about a JS error. Is it related to vimeo player? If so, please fix it.
> 
> ```
> TypeError: undefined is not an object (evaluating 'document.getElementsByTagName('video')[0].webkitExitFullScreen')
> ```

Hi @RoboBurned. I met the [same error](https://sentry.io/share/issue/8f4f9b1ca3144457baa3abb7ceea15cd/) as you recently. How did you solve it? We're using an embedded Vimeo player script.

I guess the main problem is this user using old version of firefox.
![image](https://user-images.githubusercontent.com/5801015/127419148-37646f0b-c2d4-4ad2-89fe-b9bda0eccd97.png)

@luwes  Is this version covered by Vimoe player?

**Comment by Stupidism** [comment]
Looks like [Firefox doesn't support this method](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide#prefixing) at all:
![image](https://user-images.githubusercontent.com/5801015/127419397-4947e57a-741a-48c3-82e5-0923b374b23a.png)

**Comment by RoboBurned** [comment]
Hi, @Stupidism. We did nothing to solve this problem. I actually don't remember on what page the error was. I just don't see this error in logs anymore.

**Comment by Stupidism** [comment]
> @luwes yes. any vimeo player in iframe:
> `document.getElementsByTagName('video')[0].webkitExitFullScreen()`
> closing the fullscreen, even on iphone safari ;)

Have you tried iOS Firefox?

We have 3 events for now. All on iOS Firefox.

![image](https://user-images.githubusercontent.com/5801015/128796627-3097d329-fa86-465a-bdcd-5d5d6ab1c0e6.png)

**Comment by joker-777** [comment]
Hi, we are seeing the same error as well in our tracking system. Mostly for Safari.

**Comment by stefkudla** [comment]
Seeing this error on Firefox Focus IOS (iPhone 12 pro max) when exiting and re entering the mobile browser
