### ISSUE TITLE
referrer querystring is gone after an error

### ISSUE THREAD

**Issue by timc13** [vimeo/player.js#226]
### Expected Behavior
After an error occurs with `loadVideo`, any subsequent `loadVideo` fails because of privacy settings.
I suspect this is because although the `app_id` querystring parameter is passed, the `referrer` querystring is now missing.

### Actual Behavior
If one video errors while loading, it should not stop other videos from loading.

### Steps to Reproduce

1. call `loadVideo` on an existing video ID. Notice `referrer` in the querystring
1. call `loadVideo` on a non-existent video ID.  This should throw an error that can be safely caught.
1. call `loadVideo` on the existing video ID again.  Notice `referrer` is NOT in the querystring anymore.

**Comment by timc13** [comment]
may be related to #166

**Comment by luwes** [comment]
this should be resolved! please let us know if you see otherwise. thanks

**Comment by timc13** [comment]
hi can you point to the PR or release that fixed this ?

**Comment by luwes** [comment]
@timc13 sorry, it was an internal player issue so we can't provide that.
