### ISSUE TITLE
getPaused() in play() success returns incorrectly

### ISSUE THREAD

**Issue by evvvritt** [vimeo/player.js#227]
### Expected Behavior

`getPaused()` on successful `play()` promise should return `paused=false`

### Actual Behavior

returns `paused=true`

### Steps to Reproduce

https://codepen.io/evvvritt/pen/rdwbRJ?editors=0011

### Background

I'm trying to autoplay a vimeo in `background:true` mode. Per [Webkit's recent recommendation](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/), autoplay videos should start from paused state, then attempt to play programmtically – if blocked, show play button:

> Don’t assume a media element will play, and don’t show the pause button from the start. Look at the Promise returned by the play function on HTMLMediaElement to see if it was rejected:

```
var promise = document.querySelector('video').play();

if (promise !== undefined) {
    promise.catch(error => {
        // Auto-play was prevented
        // Show a UI element to let the user manually start playback
    }).then(() => {
        // Auto-play started
    });
}
```

**Comment by reckoner165** [comment]
@evvvritt The `player.play()` promise resolves as soon as the async play request has been triggered in the player. However, this does not ensure that the playback has begun. 
When the player actually starts playing back video, it fires the `play` event. Adding your `getPaused()` check in the handler for that event is more reliable.

```
player.on('play', function() {
  player.getPaused().then(function(paused) {
    console.log('paused? ', pausedState);
  }
});
