### ISSUE TITLE
moving to es modules broke CommonJS modules in webpack

### ISSUE THREAD

**Issue by CreaturesInUnitards** [vimeo/player.js#229]
### Expected Behavior
`const Player = require('@vimeo/player')` should be all that is needed to bring the player into my build system, As It Has Always Been ©️ 

### Actual Behavior
I'm using `const Player = require('@vimeo/player/dist/player.min')` to bring in the player for now.

### Steps to Reproduce
Use webpack. Try "Expected Behavior" from above :)

**Comment by luwes** [comment]
I think this isn't bug after all, the `main` property in package.json still points to a UMD module which supports common js require. This must be something with your webpack configuration.

I don't doubt that the es module change broke something but it's still possible to make it work correctly I think. Maybe it's possible to force webpack to use the `main` property as entry.
