### ISSUE TITLE
Sharing via Facebook does not close pop-up window

### ISSUE THREAD

**Issue by fredlee0109** [vimeo/player.js#230]
### Expected Behavior
After I complete share via Facebook, the popup window should close

### Actual Behavior
After I complete share via Facebook, the popup window does not close, stuck at url="https://player.vimeo.com/share_confirmation#_=_" with console error message:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://f.vimeocdn.com". Either the 'unsafe-inline' keyword, a hash ('sha256-FWMrdBF3MfRuEUscjPJLAGYU51YAE8NCuE/oNzkrgRo='), or a nonce ('nonce-...') is required to enable inline execution.

### Steps to Reproduce
Method 1)
1) Go to https://player.vimeo.com/video/236241664
2) Share to Facebook
3) Observe popup window not closing after completing the share

Method 2)
1) Go to https://jsfiddle.net/Lk2zycn8/27/
2) Share to Facebook
3) Observe popup window not closing after completing the share

I'm using useragent of: 

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by rsichel107** [comment]
Our recent release should have fixed this. I am closing this issue but please feel free to reopen if it is still a problem.
