### ISSUE TITLE
catch all events and log to console

### ISSUE THREAD

**Issue by v3nt** [vimeo/player.js#232]
### Expected Behavior
Trying to debug a few issues but want to see what events are firing or not.

### Actual Behavior

can't see how to catch every event to the console log

### Steps to Reproduce

```
                    player.on(ALL_EVENTS, function(data) {
                        // data is an object containing properties specific to that event
                        // 
                        console.log(event_name);

                    });


```

**Comment by reckoner165** [comment]
I think this can be easily done using a loop on the app side to attach all the events that need to be tracked.
