### ISSUE TITLE
background set to true makes video loop?

### ISSUE THREAD

**Issue by v3nt** [vimeo/player.js#233]
### Expected Behavior

Video to stop at end and not loop.

### Actual Behavior

Video loops indefinitely and event "ended" not fired.

### Steps to Reproduce

There are listeners setup to catch events which that fires functions.

It doesn't seem these are being fired when background:1 is set.
ie http://2amdev.jynk.net

````
                        player.on("play", videoPlayHandler);
                        player.on("ended", videoEndedHandler); 
                        player.on("pause", videoPauseHandler);
                        player.on("timeupdate", updateVideoProgress);
````

are there any options or listeners i can use to address this?

thanks, D.

**Comment by reckoner165** [comment]
`?background=1&loop=0` should prevent the video from looping in background mode.

**Comment by reckoner165** [comment]
@v3nt this was reported and dicussed in #200. Closing this issue as it is a duplicate
