### ISSUE TITLE
Muting through API on mobile

### ISSUE THREAD

**Issue by AdrianMrn** [vimeo/player.js#236]
Since `player.setVolume(0)` doesn't work on mobile (actually, it'll unmute the video if it was muted before), is there a way to mute the video through the API?

Edit: `player.setVolume(0)` works as expected on Android, but not on iOS (Chrome and Safari).

Edit2: I'm using pause instead of mute on iOS for now, if anyone has a better solution, please let me know.

**Comment by rsichel107** [comment]
As we note in our [docs](https://github.com/vimeo/player.js#setvolumevolume-number-promisenumber-rangeerrorerror)

> Most mobile devices (including iOS and Android) do not support setting the volume because the volume is controlled at the system level.

Therefore, this may just be an IOS problem that we are unable to change.

**Comment by AdrianMrn** [comment]
Yeah I was just hoping there'd be a hidden `mute()` function 😞

By the way: `setVolume(0)` and `setVolume(1)` seems to work on Android 8.0.0

**Comment by rsichel107** [comment]
We do have a muted parameter but I am unsure if it will solve your issue.

You can see it in use here(https://jsfiddle.net/p13tae89/2/) or just adding it as a param on the embed url(https://player.vimeo.com/video/76979871?muted=1)

**Comment by sampotts** [comment]
Also seeing this. A `toggleMute()` method or something like that would be useful as you *can* toggle mute on iOS but not set volume. It works fine on HTML5 and YouTube.

**Comment by luwes** [comment]
In the meantime `setVolume(0)` and `setVolume(1)` will work on iOS.
We made some internal changes that fixed this issue.

**Comment by satishVekariya** [comment]
in iOS using  `setVolume(0)` and `setVolume(1)`
cause may app audio interrupt!!!!
