### ISSUE TITLE
Version 2.6.0 broke require importing

### ISSUE THREAD

**Issue by aartrost** [vimeo/player.js#238]
Hi all,

It seems like the latest 2.6.0 release of the player.js code broke RequireJS importing. To reproduce, simply import the player.js file with require as done in this [JSFiddle](https://jsfiddle.net/vahL743o/) (see console for error).

The issue can be traced back to the latest commit here: https://github.com/vimeo/player.js/commit/6b8d6c938b5ed0882afdb3737617a3dde61bd9c9#diff-29cfd888e32c875acb1a2dd113e516db. 

We patched this temporarily by adding `window.Vimeo = {};` before the API is imported, but without this the API will not load.

**Comment by fisherinnovation** [comment]
Thanks for the feedback. We are actively working to resolve this.

**Comment by dseif** [comment]
Is there an ETA for this fix?

**Comment by fisherinnovation** [comment]
This should be resolved in https://github.com/vimeo/player.js/releases/tag/v2.6.1
