### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by iamdimitar** [vimeo/player.js#240]
### Expected Behavior
Clean console

### Actual Behaviord
I get 6 of these errors in the console
```
player.js:16 POST https://fresnel.vimeocdn.com/add/player-stats?session-id=7ddd39ed4f710dc1a65728b641ef51e35b8b4b0a1525334190 0 ()
```

Expanded:
```
POST https://fresnel.vimeocdn.com/add/player-stats?session-id=412c0fb04afd5c8f6695fef72c1c4f1b5ef834511525334055 0 ()
value @ player.js:16
(anonymous) @ player.js:16
Promise.then (async)
value @ player.js:16
e @ player.js:16
f @ player.js:5
l @ player.js:5
(anonymous) @ player.js:5
Promise.then (async)
init @ player.js:5
Di @ player.js:8
f.(anonymous function) @ 267745745?autoplay=1&loop=1&background=1:1
load (async)
(anonymous) @ 267745745?autoplay=1&loop=1&background=1:1
(anonymous) @ 267745745?autoplay=1&loop=1&background=1:1
player.js:16
```

### Steps to Reproduce
This is the code I use:

```
<iframe src="https://player.vimeo.com/video/267745745?autoplay=1&loop=1&background=1" style="width: 100vw;height: 56.25vw;"  frameborder="0"></iframe>
<script src="https://player.vimeo.com/api/player.js"></script>
<script>
    var iframed = document.querySelector('iframe');
    var playerd = new Vimeo.Player(iframed);
    playerd.on('play', function() {
        playerd.setVolume(1);
    });
</script>
```

**Comment by Eelsie** [comment]
I get exactly the same problem, 6 of these errors:
```
player.js:16 POST https://fresnel.vimeocdn.com/add/player-stats?session-id=611edc4578312f86dc9a302507a2bc417c00e06a1525685778 0 ()
value @ player.js:16
(anonymous) @ player.js:16
Promise.then (async)
value @ player.js:16
e @ player.js:16
f @ player.js:5
l @ player.js:5
(anonymous) @ player.js:5
Promise.then (async)
init @ player.js:5
qi @ player.js:8
f.(anonymous function) @ 107044824?&loop=1:1
load (async)
(anonymous) @ 107044824?&loop=1:1
(anonymous) @ 107044824?&loop=1:1
```

**Comment by rsichel107** [comment]
Hi guys, 

Can I have more details on your setup? I am running @iamdimitar 's code here (https://jsfiddle.net/04osovp8/) and don't see any of the errors you describe.

**Comment by iamdimitar** [comment]
Works well in FF and I can only replicate the error in my Chrome. Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by Eelsie** [comment]
Hi and thank you for your answer! I also get errors only in chrome, I see them also in your fiddle example (https://jsfiddle.net/04osovp8/).

**Comment by luwes** [comment]
@Eelsie the error in jsfiddle seems to be from jsfiddle itself
<img width="1396" alt="screen shot 2018-05-14 at 7 48 55 pm" src="https://user-images.githubusercontent.com/360826/40028964-dcc1bf4c-57af-11e8-9c45-6a5cbf8a7033.png">

**Comment by luwes** [comment]
It could be that our service was temporarily down. Currently on our end there are no request errors visible in the console. Closing for now. Please re-open if it occurs again. Thanks

**Comment by Eelsie** [comment]
Hello and thanks! I see also other errors in your fiddle, and same errors appears in my code
![screen shot 2018-05-22 at 10 38 43](https://user-images.githubusercontent.com/11568278/40348477-7c684028-5dac-11e8-8339-f52a57b94485.png)
