### ISSUE TITLE
played video property, question

### ISSUE THREAD

**Issue by jybleau** [vimeo/player.js#245]
Is there a way to get the video element `played` property ?
[https://www.w3schools.com/jsref/prop_video_played.asp](w3schools)

If not, is it something that can be added?
Does it concern more that the player.js api?

I'm working on a way to block the seeking unless the video has been entirely watched (and not only by hiding the controls).
It's working fine so far when dealing directly with the video object, like this:
[https://jsfiddle.net/jybleau/zes4hbdd/](jsFiddle)

**Comment by luwes** [comment]
Hi @jybleau, sorry that's currently not supported via this API.
Not ideal but I could imagine a workaround with some events like `timeupdate`, `seeked`, etc. Or maybe adding cuepoints, and checking them off when the playhead passed them.
