### ISSUE TITLE
{background:true} before setVolume(1)

### ISSUE THREAD

**Issue by mhoogstraten** [vimeo/player.js#247]
### Expected Behavior
Background video with auto play and with sound

### Actual Behavior
Background video on pause

### Steps to Reproduce
use the following code:
`//player.vimeo.com/api/player.js`
```
var player = new Vimeo.Player('js-vimeo-video', {
    background:true
});
player.ready().then(function() {
    player.setVolume(1);
});
//player.play(); // i tryed to use this to test if it works after it is pauzed, still does not work.

//HTML
//<div data-vimeo-id="76979871" data-vimeo-defer id="js-vimeo-video"></div>
```

If you delete the ready state with setVolume(1), it works.

**Comment by fisherinnovation** [comment]
@mhoogstraten Embeds with `background == true` are unable to have their volumes set back to a value > 0 prior to playback as this doesn't follow the auto play policy. Unfortunately your request to have 'Background video with auto play and with sound' is not possible.
