### ISSUE TITLE
option quality not working on mobile

### ISSUE THREAD

**Issue by nimoatwoodway** [vimeo/player.js#248]
### Expected Behavior
If I set the option quality: 360p, quality should be set to 360p and not to 1080p on video load.

### Actual Behavior
Works correct on Desktop (tested on latest macOS with latest Safari and Chrome)
Not working for iOS Devices e.g. iPhone 7 (latest iOS Version). 
Quality is always set to 1080p

My client told me that he found the same incorrect behaviour on Apple and Android Tablets.

### Steps to Reproduce
Try to include Video with latest player.js (2.6.1) and set option quality: 360p:
`
var options = {
  autoplay: true,
  speed: true,
  quality: '360p'
}
`
`
var player = new Vimeo.Player('player', options);
`

Checkout: https://wunderwerk.io/tmp/vimeo-quality-mobile-bug.html In this example, the video quality on mobile (iOS, iPhone 7) is set to 720p and not to 360p as should be.

Would be great to get a solution for this problem, since we have many users having problems with streaming on there devices and want to set a lower quality by default.

**Comment by luwes** [comment]
Sorry the quality option is not supported on mobile devices.

Please visit this link for more info:
https://help.vimeo.com/hc/en-us/articles/224983008-Setting-default-quality-for-embedded-videos

**Comment by nimoatwoodway** [comment]
Thanks for the info! 
Is there a chance we see this in future since we would have to change our player or provider if theres totally no plan to adjust this.

**Comment by nimoatwoodway** [comment]
Any chance to get feedback on this since I have to switch to another provider. The Quality selector on iOS is already there and works. Switch from hls to mp4 when quality is changed. Should be not that complex to preselect this option. Kind regards, chris
