### ISSUE TITLE
Not work on iOS device.

### ISSUE THREAD

**Issue by StanislavSergeev** [vimeo/player.js#252]
> ionViewDidLoad() {
    const player = new Player('handstick', {
      id: 223885224,
      width: 300
    });
    player.on('play', function () {
      console.log('played the video!');
    });
}

This works on web browser but, not work on ios device
ionic version: 3.20.0
I am using this plugin now,

**Comment by luwes** [comment]
Please re-open if this is still an issue. Thanks
