### ISSUE TITLE
play() doesn't work in a cordova app running on iOS 9

### ISSUE THREAD

**Issue by iwan-uschka** [vimeo/player.js#253]
### Expected Behavior
Start playback after calling play().

### Actual Behavior
Get "Error: The viewer must initiate playback first."

### Steps to Reproduce
Call play() in JS initially :)

### Environment
Cordova App running on an iPad with iOS 9. Cordova iOS preferences:

        <preference name="AllowInlineMediaPlayback" value="true" />
        <preference name="MediaPlaybackRequiresUserAction" value="false" />

Other players like YouTube and SoundCloud does work.
The player does work on other devices running other iOS versions > 9.
The player does work on other devices running Android.

**Comment by luwes** [comment]
We've removed this restriction so should be resolved. Please re-open if you don't see the fix.

**Comment by iwan-uschka** [comment]
Oh, did i miss to say thank you? Thank you :) everything is working now as expected
