### ISSUE TITLE
Mobile autoplay does not work with background: true

### ISSUE THREAD

**Issue by linuxbastard** [vimeo/player.js#254]
### Expected Behavior
On mobile with a setting of `background: true`, expected video will autoplay, be muted and loop
### Actual Behavior
On safari and chrome, video is paused. Anroid and iOS devices. Have not tested on firefox mobile.
### Steps to Reproduce
[https://jsfiddle.net/linuxbastard/fb0c46xr/](https://jsfiddle.net/linuxbastard/fb0c46xr/)

Additional info: Account is vimeo plus. Tried doing this a couple of different ways, even using the embed code from the sharing link.

**Comment by rsichel107** [comment]
As I answered here (https://github.com/vimeo/player.js/issues/257#issuecomment-391836392) I am seeing proper autoplay behavior on the mentioned devices with your provided JSFIddle. Let's consolidate the discussion on that issue (#257) and you can provide more details if you have.
