### ISSUE TITLE
re-opening #240 Errors in the console

### ISSUE THREAD

**Issue by Eelsie** [vimeo/player.js#255]
I'm continuing the discussion in this issue, I couldn't reopen it myself.. https://github.com/vimeo/player.js/issues/240

Hello and thanks! I see also other errors in your fiddle, and same errors appears in my code
![screen shot 2018-05-22 at 10 38 43](https://user-images.githubusercontent.com/11568278/40348735-2ecafc10-5dad-11e8-91db-b96ac82705c3.png)

**Comment by maarten2424** [comment]
I also have the same error, concurring with multiple video's on the same page. 
<img width="848" alt="screen shot 2018-05-22 at 13 52 52" src="https://user-images.githubusercontent.com/9212793/40360767-760b3f3a-5dc7-11e8-86f2-0e72bd19ba5f.png">

**Comment by Eelsie** [comment]
Ohh.. now I'm embarrassed by my question... it was it! Thanks a lot!
