### ISSUE TITLE
Captions responds with a 404 server status

### ISSUE THREAD

**Issue by friday** [vimeo/player.js#256]
Captions respond with a 404 server error and html: "Sorry This video does not exist."

It seems to happen to all video in all browsers via the embed links, ex: https://player.vimeo.com/video/76979871

But the main site works: https://vimeo.com/76979871

**Comment by fisherinnovation** [comment]
Thanks for reporting. We are reviewing this issue and are working to have it resolved ASAP.

**Comment by fisherinnovation** [comment]
This should be corrected now. Please reopen if you are still experiencing this issue. Thanks again for reporting.
