### ISSUE TITLE
Play method is blocked by Safari 11.1 in most cases

### ISSUE THREAD

**Issue by cmstuning** [vimeo/player.js#258]
### Expected Behavior
Play video via custom button
### Actual Behavior
video stopped immediately after play
### Steps to Reproduce
check own demo page on safari 11.1 and see events log
<img width="894" alt="vimeo player api demo 2018-05-28 10-58-25" src="https://user-images.githubusercontent.com/6927583/40604064-85a36762-6266-11e8-8a56-6a3f360b5b0f.png">

https://player.vimeo.com/api/demo

**Comment by rsichel107** [comment]
I tested this on my Safari Version 11.1.1 and did not see this behavior. I am closing this issue but if you are still seeing it please feel free to reopen and give more details about the issue and we will attempr to fix it. 
![apipage](https://user-images.githubusercontent.com/17985323/41255616-1d01be2c-6d95-11e8-97aa-be676927a18c.gif)
