### ISSUE TITLE
Get proportions of video height/width

### ISSUE THREAD

**Issue by kostozy** [vimeo/player.js#259]
### Expected Behavior
I have used getVideoWidth and getVideoHeight and expected to receive actual width and height to know proportion height/width. Tested video = 1728/4096
### Actual Behavior
However, in 1 of 10 cases there is 1154/4096. I suppose there are sizes of different qualities and the propotion is wrong in this case. So can I get the proportions in one method? or make requests to width and height at the same quality (if problem in it).
### Steps to Reproduce
player.on('loaded', function() {
	player.getVideoWidth().then(function(width) {
   		player.getVideoHeight().then(function(height) {
   				console.log(height, width);
	    });
	});
});

**Comment by fisherinnovation** [comment]
Are you only seeing this for specific resolutions? What video ID are you testing this on and have you noticed this on more than just one video?

**Comment by andreasoby** [comment]
I'm experiencing the same issue, both after the ready and loaded events are dispatched. I'm suspecting it might have something to do with qualities, as @GBcrimson suggests. Maybe a solution where we can retrieve width and height in a single call could solve the issue?

**Comment by sampotts** [comment]
Have you tried this? Still not as ideal as one call but at least both requests will happen at the same time...

```javascript
Promise.all([player.getVideoWidth(), player.getVideoHeight()]).then(dimensions => {
    const [width, height] = dimensions;
    ... do something ... 
});
```

**Comment by joshdavenport** [comment]
I'm seeing this too. About 1/10 times seems about right. Doesn't seem to be specific to any resolution.

**Comment by amarizaty** [comment]
can we set with to 100%? cause when i set width to 100% look like 100px not 100%. any solution about this issue?

**Comment by daviddfm** [comment]
For me using 

```Promise.all([player.getVideoWidth(), player.getVideoHeight()]).then(dimensions => {
    const [width, height] = dimensions;
    // do something here
});```

worked but I worry I'm just not hitting a race condition like this that exists.  Honestly - the design of this API isn't the best.  There should be a separate API for getting the original video width/height vs getting the current one post play.  The other API that should exist is a getAspectRatio API which I think is what most people need to help resize the elements the video lives in or the controls over the video

**Comment by luwes** [comment]
@sampotts post is the solution here 👍 

```js
Promise.all([player.getVideoWidth(), player.getVideoHeight()]).then(dimensions => {
    const [width, height] = dimensions;
    // do something here
});
```

I'm closing this issue as a getAspectRatio method or the like will not be implemented.

it's worth mentioning that video dimensions will change across the playback session because of the changing qualities (ABR). The dimensions change even going from `ready` to `loadedmetadata`, and or `loadstart`.

We might consider adding a `resize` event which is how the HTML video element works as well.
 https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoWidth#About_intrinsic_width_and_height

**Comment by SilviaMalavasi** [comment]
You should use a get request:
        $.getJSON(
          "https://vimeo.com/api/oembed.json?url=https://vimeo.com/" +
            vimeoVideoID,
          { format: "json" },
          function (data) {
            console.log(data.width);
            console.log(data.height);
          }
        );
