### ISSUE TITLE
vp-preview-invisble not added.

### ISSUE THREAD

**Issue by Pozix** [vimeo/player.js#260]
### Expected Behavior
Adding vp-preview-invisible to <div class="vp-preview vp-preview-cover> when playing the video.

### Actual Behavior
Doesn't add it. Video plays and the opacity of vp-preview is still 1. 
Adds the class when scrubbing.

**Comment by luwes** [comment]
This was recently resolved. Please re-open if you don't see the fix. Thanks.

**Comment by Pozix** [comment]
Perfect, it's working.
