### ISSUE TITLE
timeupdate and progress events are now playProgress and loadProgress

### ISSUE THREAD

**Issue by danrossi** [vimeo/player.js#262]
For some strange reason these events are mapped differently, but the same code and sdk uses the original events implemented elsewhere. 

https://jsfiddle.net/danrossi303/omcvv1z9/20/

Only playProgress and loadProgress are called. I had to debug the window messages to get what event is called. 

```
	vimeoPlayer.on('playProgress', function(e) {
			console.log("time", e);
});



	vimeoPlayer.on('timeupdate', function(e) {
			console.log("time1", e);
});



	vimeoPlayer.on('loadProgress', function(e) {
			console.log("progress", e);
});


vimeoPlayer.on('progress', function(e) {
			console.log("progress1", e);
});
```

**Comment by luwes** [comment]
@danrossi the reason for the different naming is because of the `api: 1` I think.
The latest api version is 3. If you're using this library best is to not set that api attribute.

Api 1 and 2 were in the froogaloop days...

**Comment by danrossi** [comment]
You are correct sorry about that. I am porting one feature over from Froogaloop dayz indeed I missed that param compared to another one I have with the new api.
