### ISSUE TITLE
IE11 Player Object error

### ISSUE THREAD

**Issue by Vinsanity** [vimeo/player.js#265]
### Expected Behavior
`player.play()` or `player.on()` should be firing as expected.

### Actual Behavior
All player functions are producing an object error in IE11. For instance, `player.play()` is producing a console error `expected Object`
I also tried using `.catch()` on these function and that isn't firing either.

If I console log the player I created with `player = new Vimeo.Player(iframe);` it is, in fact, an object.
even delaying the call to `player.play()` is not working.

The script error says it is coming from this function `return setImmediate(fn);` on line 373 player.js

This works fine in all other browsers I'm testing in.

**Comment by rsichel107** [comment]
Can you provide a JSFiddle to test with?

**Comment by luwes** [comment]
@Vinsanity I can't seem to reproduce on my end. Does the API demo page work for you?
https://player.vimeo.com/api/demo
