### ISSUE TITLE
"Play" event is not firing for autoplaying videos

### ISSUE THREAD

**Issue by danaburger** [vimeo/player.js#268]
### Issue Description
The console is not generating a message for autoplaying video (using ?autoplay or ?background params)

### Expected Behavior
Console log displays play event

### Actual Behavior
"Played the video!” string is not firing in the console

### Steps to Reproduce

1) Open Console
2) Visit https://codepen.io/esedeerre/pen/MXmXBV

cc/// @fisherinnovation

**Comment by dmitrykiselyov** [comment]
Yep, I have the same issue.

**Comment by fisherinnovation** [comment]
So this seems to be related to the setup and usage of a player specifically in the iframe embed setup you are using. To get around this for the time being (while we figure out the best method to solve this proper) you can utilize the API to create the player for you which will ensure the listener will created in time. Here is an example https://jsfiddle.net/nmy5qdkv/

**Comment by dmitrykiselyov** [comment]
@fisherinnovation Hey, thanks for advice, but this is exactly how my code is setup and the play event not working.

**Comment by fisherinnovation** [comment]
Do you see the event firing with the demo I provided (https://jsfiddle.net/nmy5qdkv/)?

**Comment by dmitrykiselyov** [comment]
No, I don't, the demo doesn't work (Uncaught ReferenceError: Vimeo is not defined at window.onload)

**Comment by fisherinnovation** [comment]
@dmitrykiselyov Sorry about that, updated the link, can you try once more?

**Comment by dmitrykiselyov** [comment]
No problem. The demo is working :) Thanks!

**Comment by dmitrykiselyov** [comment]
With this video 84708837 it not working.

**Comment by esedeerre** [comment]
Hi, can we expect this to be solved this week? Thanks!

**Comment by dmitrykiselyov** [comment]
@fisherinnovation Hey, I tried another video 84708837 (Chrome 67.0.3396.87) with your demo and it dosn't work http://jmp.sh/vDwRDVi. This is a big issue for me. Can you please look at this problem. Thanks!

**Comment by fisherinnovation** [comment]
Hoping to have this resolved ASAP. Thanks for your patience everyone.

**Comment by rnpgeo** [comment]
This is causing big problems on our site too. Thanks for looking into it fisherinnovation 👍

**Comment by fisherinnovation** [comment]
Thanks again for your patience everyone. This should be resolved now. Example https://jsfiddle.net/0zqo5yrc/

Please reopen if you are still encountering issues.
