### ISSUE TITLE
Cannot determine if background video is compatible

### ISSUE THREAD

**Issue by lnpbk** [vimeo/player.js#27]
On a mobile device, a Vimeo video with background mode on does not play, which is great. The trouble is, I cannot see any way to determine if the video will be played or not, using the existing methods/events.

I currently display fallback content, then on the play event hide it. It'd be nicer to determine whether the video is going to play or not, then display the fallback content if required.

**Comment by bdougherty** [comment]
That makes a lot of sense. We'll see what we can do if/when background video becomes an officially-supported feature (it's still "experimental" right now).

**Comment by RoyalFlushever** [comment]
@lnpbk Could you solve that problem? Now I need to play background video in the mobile device.
But background video is not working. 
error:
In chrome mobile,
 Uncaught (in promise) TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (player.js:formatted:6759)
    at Object.e.fire (player.js:formatted:513)
    at player.js:formatted:5240
    at <anonymous>

In firefox mobile,
TypeError: e.telecine is undefined

Thanks

**Comment by rsichel107** [comment]
@RoyalFlushever The error no longer appears (https://github.com/vimeo/player.js/issues/205), however background autoplay on mobile still is not supported yet.

**Comment by luwes** [comment]
I don't believe there will be any API methods added to check this behaviour.
However this is simply checked by a user agent check for iOS and Android, on these devices background play is disabled.
