### ISSUE TITLE
Vimeo oembed API should return the iframe with allow attribute

### ISSUE THREAD

**Issue by nextend** [vimeo/player.js#271]
[https://vimeo.com/api/oembed.json?url=https://player.vimeo.com/video/76979871&domain=a.com](https://vimeo.com/api/oembed.json?url=https://player.vimeo.com/video/76979871&domain=a.com)

Returned iframe code on the previous endpoint should return extended iframe tag with the following attribute:
`allow="autoplay; encrypted-media"`

Related doc change: #266 

@zwickmueller

**Comment by rsichel107** [comment]
`allow="autoplay` is there and that doc change you put out is there. Closing thing 😄
