### ISSUE TITLE
Play() promise should be rejected when Chrome does not allow autoplay

### ISSUE THREAD

**Issue by nextend** [vimeo/player.js#273]
The promise returned by vimeo's play() should get rejected when Google chrome rejects the HTML5 video element's play().

Currently Vimeo resolves its promise, but it should be rejected with error.

Example code:
[https://gist.github.com/nextend/245243c297abcdd75cdd3d58bacc4149](https://gist.github.com/nextend/245243c297abcdd75cdd3d58bacc4149)

Chrome docs: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

```
var promise = document.querySelector('video').play();
if (promise !== undefined) {
  promise.then(_ => {
    // Autoplay started!
  }).catch(error => {
    // Autoplay was prevented.
    // Show a "Play" button so that user can start playback.
  });
}
```

**Comment by pxwee5** [comment]
Any updates here @luwes ?

**Comment by itgeorge** [comment]
This also happens on iOS Safari, and even a "play" event is fired (whereas on desktop Chrome only the promise resolves, no event is fired there), but the video remains not playing (possibly it gets paused right after playing, but no such event is fired if so).

Here's a repro:
http://jsfiddle.net/dt5s1yaf/

**Comment by firewaller** [comment]
+1

**Comment by ahmadawais** [comment]
Same here. The video will autoplay and then stop for no reason. I can't figure out how to keep it autoplaying

**Comment by luwes** [comment]
This is added in the latest release. Please take a look at the below link to verify.
https://jsfiddle.net/luwes/6cpzoqst/

Thanks for your patience.

**Comment by ThatGuySam** [comment]
Seems like that jsfiddle references a local domain vimeo.dev. 
Here's a working version with the current live script. 
https://jsfiddle.net/thatguysam/4ombuyvL/
