### ISSUE TITLE
Hide Controls

### ISSUE THREAD

**Issue by na86** [vimeo/player.js#28]
Hi there,

there's a way to hide control bar using player.js? 

Any help would be appreciated! 

Na86

**Comment by bdougherty** [comment]
There is not a way to do that at the moment. What is your use case?

**Comment by na86** [comment]
i'm developing a "screensaver", when user didn't touch anything an overlay video cover the website. it works really fine, player.js is so fast and the quality is very good. 

Control bar appears only for 3 second, is not a big deal really, but anyway i'm trying to remove it. 
Thanks @bdougherty

**Comment by chrisberthe** [comment]
Has this ever been worked on/implemented? I assume, based on the number of Google search results, this is a pretty wanted feature. Unlike @na86, unfortunately this is a big deal for our team and would need a way to remove the controls.

**Comment by gabrielstuff** [comment]
Same here. Found this http://www.cssplay.co.uk/menu/cssplay-vimeo-hide-control-bar.html but very hackish. 
I guess it must be related to https://vimeo.com/XXXX/settings/embed, and the pro feature that allows to set the way a video is embed ? See bellow.

however this would be a must !

<img width="699" alt="screen shot 2016-11-21 at 23 35 54" src="https://cloud.githubusercontent.com/assets/285033/20503580/73cff702-b043-11e6-9c15-27d91313fbdc.png">
