### ISSUE TITLE
Vimeo Player not being initialized in version 2.6.1 

### ISSUE THREAD

**Issue by danaburger** [vimeo/player.js#283]
### Summary

The Vimeo player is using var `VimeoPlayer = require("@vimeo/player")`; we added a reference to the jquery api so it initializes the vimeo player. There is NO error because of null reference checks.

It is not displaying any video because it is passing this condition if `(!isNode && window.Vimeo && !window.Vimeo.Player) {` < The `window.Vimeo player` is nothing. In the previous version there was a check for if `(!isNode) `and not for `Window.Vimeo.`

### Steps to Reproduce

Right now it is a working state but if you go to the following page https://www.brother-usa.com/products/ads1000w and view the source code of that page, you can see that there is a reference to the following `<script src="https://player.vimeo.com/api/player.js"></script>`, if the reference is removed, the video in the product carousel will not load.

@fisherinnovation @luwes

**Comment by tenacex** [comment]
@danaburger could you provide a broken example? Have you tried other versions of player.js?

**Comment by danaburger** [comment]
@tenacex Can you provide a list of improvements/fixes made in the latest version (v2.6.3)? The client would like to know before committing to an update.
