### ISSUE TITLE
SetCurrentTime does not autoplay on iOS

### ISSUE THREAD

**Issue by danaburger** [vimeo/player.js#284]
### Issue

In custom built controller, on iOS10+11 the Vimeo player will **not** autoplay (it's muted). On iOS+Chrome the video will not play inline. On iOS+Safari video will play after some user action, it will accept `play() `and `setCurrentTime(t)` methods but then puts up a large blue pause button that does not fade out. There are no messages of any kind in the console.

On iOS, the video queues up but does not start. You can see the player start then stop immediately. external play (the buttons) starts the video and also unmutes the video. At no point does the process request an unmute.

Also, the following happens intermittently on iOS:

The play button appears to have progress below it and it will not go away unless the user taps on it a few times. (Does not happen on demand)

![image](https://user-images.githubusercontent.com/33134472/42228460-0b413892-7eb2-11e8-8d42-1245326f5b42.png)

![image](https://user-images.githubusercontent.com/33134472/42228467-0f437892-7eb2-11e8-8ca4-b1b5de1f5b6f.png)

### Steps to Reproduce

- Visit https://tokyo.videogram.com/vimeo.html
- Press buttons to jump ahead in video on iOS (Chrome and Safari) 

(notes on page)

@fisherinnovation @luwes

**Comment by luwes** [comment]
I see the `muted` flag but I'm getting sound

**Comment by luwes** [comment]
On my end setting the current time on iOS now works like expected.
Please let us know if it's not the case.

Thanks @danaburger
