### ISSUE TITLE
Vimeo 360 videos cannot be panned when background=1

### ISSUE THREAD

**Issue by aproni34f** [vimeo/player.js#287]
### Expected Behavior

1. 360 videos cannot be panned when background=1

2. second but related issue:
You cannot click to pause/play video as well (this applied to normal videos as well, not just 360)

### Steps to Reproduce

Example:

https://jsfiddle.net/u7cs3jhf/

**Comment by fisherinnovation** [comment]
@aproni34f Thanks for the feedback. At the moment 'background' video configurations remove all controls visible or not. Therefore the control of 360 videos is, by default, disabled. 
I do agree there are circumstances where this would not be an optimal solution for embedding this content and can assure you we are discussing better ways to support this in the near future with more control over UI element visibility.

Related https://github.com/vimeo/player.js/issues/197
