### ISSUE TITLE
can't catch "ended" event 

### ISSUE THREAD

**Issue by stevermeister** [vimeo/player.js#29]
"play" event works fine for me:

    player.on('play', function() {
        console.log('played the video!');
    });

but can't catch "ended" one: 
          
    player.on('ended', function(event, playerId) {
        debugger
         console.log('ended the video!');
    });

**Comment by bdougherty** [comment]
Do you have an example page where this is happening?

**Comment by stevermeister** [comment]
ok, I found it. 
I had to remove from URL `api=1`
now it works, thank you for quick response! 


just put here a link if somebody needs sandbox to play with new API -https://plnkr.co/edit/edDlaLRJhZKO71CR3rSZ?p=preview

**Comment by mashuble** [comment]
You need to listen to the finish event. It works better ;)
