### ISSUE TITLE
Missing a way to determine what caused a pause to occur (playback button small screens)

### ISSUE THREAD

**Issue by jonasgroendahl** [vimeo/player.js#295]
### Expected Behavior
When you click the playback button on a mobile device, the video pauses, you expect that you can detect what caused the pause in the pause event handler. Also the playbackratechange event handler doesnt seem to be firing.

### Actual Behavior
It triggers a pause event twice(noticed by checking console.logs) and it's a bit problematic to show your own overlay since you dont wan't to be showing it when a pause is trigged by a click on the playbackrate button.

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/23399953/43317693-23ea1478-919e-11e8-879b-cf85c235369c.png)

**Comment by luwes** [comment]
@jonasgroendahl which mobile device is this? you can't playback at all?
