### ISSUE TITLE
On vimeo player full screen mode on iPad (iOS 11.3) tapping on play button turns it to pause button and it turns back to play button and nothing happens.

### ISSUE THREAD

**Issue by shinejsf** [vimeo/player.js#296]
### Expected Behavior

Platform : iOS 11.3 (iPad Pro 9.7 2016 model), iPhone 6s
Browser : Chrome, Safari
On full screen mode tapping on play button should start the video.
Issue only happens on full screen view.

### Actual Behavior

On iPad vimeo full screen mode tapping on play button turns it to pause button and it turns back to play button and nothing happens.

### Steps to Reproduce

Use this link to go to vimeo:  https://vimeo.com/239882943
1. tap on full screen button on vimeo player.
2. When it is in full screen tap on play button on bottom.
3. observe the behavior of play button.

**Comment by shinejsf** [comment]
I think it has something to do with slow WiFi.

**Comment by antonioreyna** [comment]
i have the same issue on android simulator

**Comment by luwes** [comment]
I couldn't reproduce this issue on my end. Could you please let us know if it would happen again. We've had several fixes in the play request flow that could have resolved this issue. Thanks for your patience.
