### ISSUE TITLE
getTextTracks() and VTT

### ISSUE THREAD

**Issue by roryhering** [vimeo/player.js#297]
More of an edge case than anything: I know I can use the getTextTracks promise to get the list of text tracks with a video:

``` javascript
player.getTextTracks().then((tracks) => {
  console.log('tracks', tracks)
})
```

Is there any way I can access the captions/subtitles data that's associated with each of the returned objects, for example: so I can convert the captions into a transcript? For example:

``` json
{
  "kind": "captions",
​  "label": "English",
​​  "language": "en",
​​  "mode": "disabled",
  "data": "WEBVTT\n\n00:00:00.910 --> 00:00:02.861\n<i>We are Vimeo,</i>..."
}
```

**Comment by tenacex** [comment]
We do not expose this features, however you might be able to play around with the requests coming from the player. We request .vtt using an expiration token, so you could look into that. Going to close this though, I will bring it up with the team if we want to enable something like this as it could definitely be useful.
