### ISSUE TITLE
How to I trigger whenever at the end of the video?

### ISSUE THREAD

**Issue by sohat** [vimeo/player.js#300]
![image](https://user-images.githubusercontent.com/19400518/44072802-bb2e746a-9fcb-11e8-88ea-ca07a07c5af9.png)

We have used a iframe tag for setting a autoplay function, but we have a problem.

we needed to know when the video ended,so we used 'ended' of event.

this event triggered just once when loaded first video, no longer trigger after another load Video. ( we changed iframe src(url) and change another video )

How can we make it triggered whenever the end of the video?

**Comment by fisherinnovation** [comment]
Video ended events will fire every time the video completes playback. For an example see https://jsfiddle.net/j8etkanc/. 

To ensure you are using autoplay control properly see https://help.vimeo.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos.

Please reopen this issue if you are still encountering issues.
