### ISSUE TITLE
Vimeo Foogaloop Api Could not be loaded !

### ISSUE THREAD

**Issue by maymktg** [vimeo/player.js#301]
I have multiple Wordpress sites getting the error message in this post title. The common denominator is both are Vimeo videos playing through the Revolution Slider plugin. 

The URLs are:

- http://mypastacaffe.com/
- http://larainpros.com/

Screenshot of the error... https://snag.gy/wRmBZl.jpg

**Comment by fisherinnovation** [comment]
I am not able to see the same issue on my end at the moment. Can you retest and verify you are still encountering issues loading the Froogaloop JS file (https://f.vimeocdn.com/js/froogaloop2.min.js)?

<img width="1420" alt="screen shot 2018-08-14 at 11 41 59 am" src="https://user-images.githubusercontent.com/306818/44102171-1af259b2-9fb7-11e8-83c8-986697edb9a3.png">
<img width="1410" alt="screen shot 2018-08-14 at 11 41 51 am" src="https://user-images.githubusercontent.com/306818/44102172-1b14a4b8-9fb7-11e8-868c-32a4d1729a8a.png">

I will also mention you should consider moving away from using Froogaloop as it is our old API and will eventually be removed in the future. To avoid conflicts  down the road, follow the steps in this document to update your usage to our latest API (https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md). 

Please reopen this issue pending you are still encountering loading issues.
