### ISSUE TITLE
Pass App Id to the player, enable/disable controls & buggy embed options

### ISSUE THREAD

**Issue by kaddyadriano** [vimeo/player.js#302]
### Expected Behavior

- Being able to create a player by id for private videos by passing App Id to the player
- Enable/disable player controls
- Enable/disable autoplay and loop

### Actual Behavior

Private videos don't play without passing App Id. Is there a way to pass it to the player embed options other than initializing the player with a url containing app_id param?

Is there a way to enable / disable video controls not through admin?

Also some embed options like autoplay and loop seem to not care about what the value is. Any browser support for this?

**Comment by fisherinnovation** [comment]
> Private videos don't play without passing App Id. Is there a way to pass it to the player embed options other than initializing the player with a url containing app_id param?

At the moment this is the only method of supplying this value to the player. We will review alternative methods to provide a channel to supply this information without using a URL param.

> Is there a way to enable / disable video controls not through admin?

Not at the moment. The closest solution is using background videos (https://help.vimeo.com/hc/en-us/articles/115011183028-Embedding-background-videos). This is another topic we have been discussing internally and hope to have a sound solution available soon.

> Also some embed options like autoplay and loop seem to not care about what the value is. Any browser support for this?

Can you elaborate so I understand what you are experiencing. A demo of your issue would also be very helpful. This help article may be of assistance as well (https://help.vimeo.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos)

**Comment by kaddyadriano** [comment]
For the last part, I figured when in background mode video always autoplays and loops. 
Thank you!
