### ISSUE TITLE
Uncaught TypeError: Player is not a constructor

### ISSUE THREAD

**Issue by gingerlime** [vimeo/player.js#307]
### Expected Behavior
```coffee
Player = require("@vimeo/player")
player = new Player(iframe)
```

### Actual Behavior
Throws `Uncaught TypeError: Player is not a constructor`

### Steps to Reproduce

We use webpack + coffeescript.

This started happening after upgrading from 2.2.1 to 2.6.3. We didn't change any of our code besides upgrading the player.

If we use `player = new Player.default(iframe)` then this doesn't throw an error...

**Comment by luwes** [comment]
Related to https://github.com/vimeo/player.js/issues/229

This can be fixed by configuring webpack not to use the "module" entry point in package.json but the "main" field. 

> I think this isn't bug after all, the main property in package.json still points to a UMD module which supports common js require. This must be something with your webpack configuration.

> I don't doubt that the es module change broke something but it's still possible to make it work correctly I think. Maybe it's possible to force webpack to use the main property as entry.
