### ISSUE TITLE
Instantiate and call player.play() on touch devices

### ISSUE THREAD

**Issue by dmnsgn** [vimeo/player.js#31]
### Expected Behavior
Instantiate a `Vimeo.Player` and call `.play()` inside a `touchstart` handler (user gesture) should play the video on touch devices:
```javascript
var options = {
  id: 59777392
};

var showVideo = function() {
	var player = new Vimeo.Player('player', options);
  
  player.on('play', function() {
    console.log('played the video!');
  });
  
  player.play();
};

document.querySelector('#play').addEventListener('touchstart', showVideo);
```

### Actual Behavior
Video does not play (hides the poster/title and show loading indicator though) and console output these warnings/errors:
```
player.js:8 Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.
player.js:14 'HTMLVideoElement.webkitSupportsFullscreen' is deprecated. Please use 'Document.fullscreenEnabled' instead.
player.js:8 Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.
player.js:13 'HTMLVideoElement.webkitEnterFullscreen()' is deprecated. Please use 'Element.requestFullscreen()' instead.
```
which suggest that you try to play a video without any user interaction.

### Steps to Reproduce
Tested on a Nexus 5 Android 6.0.1 on Chrome 51:
- Open https://jsfiddle.net/dmnsgn/yuqndu4f/1/ on a touch device
- Touch 'Play the video' button
- See poster/title fade to the black frame of the video not playing

This [stackoverflow answer](http://stackoverflow.com/a/32571967/1527470] related to a similar issue with audio) suggest that "even after a user gesture (such as click) it waits for 1000ms and if no sound was played it throws the exception above."
Perhaps a Promise is taking too long to resolve?

**Comment by bdougherty** [comment]
We've had this issue with iOS as well. I don't think the user gesture is carried through the `postMessage`, but besides that, the time it takes the player to load is usually long enough to trigger whatever timeout there is on the user gesture. Can you see if it works if the player is already loaded when you tap on the button?

**Comment by dmnsgn** [comment]
It doesn't work when:
- touch the #play link = loads the player but does not play
- touch the #play link again = does nothing

**Comment by bdougherty** [comment]
I meant if the video is loaded before you tap the button for the first time.

**Comment by dmnsgn** [comment]
You mean use the _Pre-existing player option_ (adding the video as an iframe in the HTML) instead of the _Create with a video id or url_ (the library adds the iframe)?
If so, yes it works: https://jsfiddle.net/dmnsgn/yuqndu4f/6/ the video plays on #play link touch.

**Comment by bdougherty** [comment]
I think that's the only way it's going to work. If you create a player as you did in the first fiddle, the library makes a request to oEmbed to get the embed code and no matter how long that takes, I think the callback from that will happen outside of the user gesture.

We'll update the player to handle the error state a little better, but I don't know if there's anything we can do to make your initial example work.

**Comment by andypillip** [comment]
I'm having an iframe player and I'm trying the following stack:

    $el.on('click', function() {
      console.log('play…');
      
      player.play()
        .then(function() {
          $el.off('click');
        })
        .catch(function(e) {
          console.log(e.name);
        });
    });

I still get the same errors if I'm trying to click my $el before the whole document loaded.
