### ISSUE TITLE
removeCuePoint not working. Promise pending forever.

### ISSUE THREAD

**Issue by bruchmanng** [vimeo/player.js#310]
### Expected Behavior
When player.removeCuePoint is called, it should either remove the CuePoint successfully or throw an error.

### Actual Behavior
Nothing happens and the promise stays pending forever. The CuePoint is not removed.

### Steps to Reproduce
I made a JSFiddle that reproduces this issue. It has corresponding comments.
https://jsfiddle.net/bruchmanng/4wy5fgkz/33/

### PD
This method was working well for me a couple of months ago.

**Comment by kommaJules** [comment]
Same for me.

**Comment by reckoner165** [comment]
This should be resolved now.

**Comment by kommaJules** [comment]
It is not resolved. Still having the same problem.
