### ISSUE TITLE
Autopause not currently working in Chrome, IE11, Safari

### ISSUE THREAD

**Issue by rbmstudio** [vimeo/player.js#311]
Using Chrome 68 / Safari 11.1.2 / IE11 videos on a page no longer autopause when another video is started.

Autopause still working in Firefox 61.0.2 and Opera.

**Comment by danaburger** [comment]
The players on your page https://redboxmedia.com/testzone/ou812/ do seem to automatically pause.

The other pages you provided seem to be using a skinned Vimeo player (using https://plyr.io which is not recommended), but the autopause functionality does seem to be working on in both Safari and Chrome none the less. Perhaps, do you have any browser extensions active, or is this issue occuring for any specific videos of yours?

**Comment by fisherinnovation** [comment]
@rbmstudio I have tested all of your examples in all of the browsers you have listed and have been unable to replicate your issue. The autopause functionality seems to be working as expected. If you can provide more insight into your browsers configurations and/or other steps to help us replicate this we will continue to debug. Closing this for now, feel free to reopen pending you can make more info available.
