### ISSUE TITLE
Events are not getting triggered for videos added dynamically on web page

### ISSUE THREAD

**Issue by danaburger** [vimeo/player.js#312]
### Expected Behavior
Events are triggered for dynamically added videos

### Actual Behavior
Events are not being triggered

### Steps to Reproduce

Below is the link for the demonstration of events not triggered on dynamically added videos.

Link : https://www.eduonix.com/home/vimeo_demo

In the above example when page get loads the events get triggered but as soon as you change the video on click of a button the events wont trigger for the new video added to the page.

cc// @fisherinnovation

**Comment by Alessiosdm** [comment]
Hi,
I suggest you use loadVideo instead of changing the iframe src
https://github.com/vimeo/player.js#loadvideoid-number-promisenumber-typeerrorpassworderrorerror
Ciao

**Comment by luwes** [comment]
@danaburger, @Alessiosdm is right `loadVideo` should be used if possible.
Also `?api=1` shouldn't be used in the url. The current one is api=3 but best to leave it off.
