### ISSUE TITLE
On iPhone 7 iOS 10 clickToPlay: true malfunctions with vimeo

### ISSUE THREAD

**Issue by stormrockwell** [vimeo/player.js#313]
### Expected Behavior
Clicking on the container should play/pause the video

### Actual Behavior
After clicking play, clicking the container multiple times results in a flickering effect

### Steps to Reproduce
I believe it is Safari and Chrome. Confirmed Safari
1. Use an iPhone 7 or emulator like Browserstack (Tested with browserstack and iPhone 7 Plus)
2. go to https://plyr.io/#vimeo
3. Click the play Icon
4. Click the container (not on the icon) and you will notice u will no longer be able to pause the video and will flicker on click.

Turning off clickToPlay is my temporary solution.

**Comment by rsichel107** [comment]
@stormrockwell I haven't fully tested this yet but if you go to https://plyr.io/#vimeo on desktop, that video is currently blocked. Could this have an effect on your bug?

**Comment by luwes** [comment]
This seems to be an issue with the plyr code, player.js doesn't have a `clickToPlay` option.
