### ISSUE TITLE
Can't resolve 'jquery'' in ...

### ISSUE THREAD

**Issue by urukai** [vimeo/player.js#314]
### Expected Behavior
I want to control a vimeo video inside of a vue component. So I added this player via `npm install @vimeo/player`. Compiling with webpack should not throw errors about missing jquery packages.

When using with the linked script, it works: https://jsfiddle.net/urukai/eywraw8t/339576/

Installing jQuery with `npm install jquery` does not change anything.

### Actual Behavior
Whenever compiling, the console throws something like this:

```
ERROR in ./node_modules/@vimeo/player/dist/player.es.js
Module not found: Error: Can't resolve 'jquery'' in '/[...]/node_modules/@vimeo/player/dist'
 @ ./node_modules/@vimeo/player/dist/player.es.js 1:0-18
 @ ./res/src/main.js

```

### Steps to Reproduce
This is the reduced version of the vue component:

```
<template>
    <div id="vimeo-video-container"></div>
</template>
<script>
    import Player from '@vimeo/player';

    export default {
        data() {
            return {
                vimeoId: 286871702
            };
        },
        mounted() {
            const player = new Player( 'vimeo-video-container', {
                id: this.vimeoId
            } );
        }
    }
</script>
```

I tried also this library https://www.npmjs.com/package/vue-vimeo-player, but to no avail: the same error occurred.

Just a note: the double inverted comma `''` in the error message seems strange to me.

**Comment by luwes** [comment]
@urukai I'm pretty sure this is not an issue with the player.js library.
we do have a reference to `window.jQuery` in player.es.js but that's it.
could you send over your webpack config or plugins you use?
closing for now but please comment below...

**Comment by tomkirsch** [comment]
Had this problem today after installing the vimeo package - if you look closely at the error, you can see there's an extra apostrophe character after jquery. I don't know where the issue lies in the source code. I resolved this in webpack by adding an alias as follows:
`
resolve:{
		alias:{
			'jquery\'': 'jquery',
		}
	}
`
Hope this helps someone.
