### ISSUE TITLE
Change video preview issue

### ISSUE THREAD

**Issue by demon1512** [vimeo/player.js#317]
Hello, i try to change video image via API, but i can do this only from ip which this video was uploaded. How to fix this problem? I need to change images from any ip.

**Comment by tommypenner** [comment]
@demon1512 It sounds like your server's IP address may be banned. Please contact vimeo at https://vimeo.com/help/contact and provide the exact error message you receive, your server's IP address, and/or the `x-banned-ip` header returned from Vimeo.

**Comment by rsichel107** [comment]
Hi @demon1512 , If you are using this https://developer.vimeo.com/api/reference/videos#edit_video_thumbnail, we don't control this feature in our repo. Following Tommy's solution is your best bet. Closing this.
