### ISSUE TITLE
When loading videos from onEnd event the previous video thumbnail is displayed.

### ISSUE THREAD

**Issue by chris-wayout** [vimeo/player.js#320]
### Expected Behavior
load video without displaying anything from previous one

### Actual Behavior
A frame which appears to be the Vimeo thumbnail of the video is displayed before new video is loaded.

### Steps to Reproduce

    player.on('ended', function(data) {
           player.unload();   // has no effect
           console.log ("video ended");
           player.loadVideo(nextVid).then(function(id) { ...

**Comment by luwes** [comment]
This is resolved and the player now removes the old thumbnail when loading in a new video. Thanks for reporting. Cheers
