### ISSUE TITLE
hangs when trying to play sequential videos in background tab

### ISSUE THREAD

**Issue by FuzzyWobble** [vimeo/player.js#321]
### Expected Behavior
when video is ended, and browser tab is not focused, it will still continue to the next video and play it. (for example, you can run a youtube playlist on a tab that is not focused and it will continue to play).

### Actual Behavior
goes to the next video, hangs, and is stuck in perpetual loading...

### Steps to Reproduce
http://musictele.vision/
^ happens here for me on Chrome OSX ^

**Comment by rsichel107** [comment]
I was able to get it to hang on the 8th video. Is there a way you could show us in a JSfiddle how you are using our API and we can try to dig deeper?

**Comment by ahmadawais** [comment]
I have the same problem of autoplaying the videos. :(

**Comment by playvici** [comment]
> I have the same problem of autoplaying the videos. :(

Same

**Comment by luwes** [comment]
Some more info that could be helpful

<img width="1214" alt="screen shot 2018-12-11 at 16 51 52" src="https://user-images.githubusercontent.com/360826/49832600-20e1e700-fd65-11e8-8337-1df5ff807d1e.png">

https://www.chromestatus.com/feature/5527160148197376

**Comment by luwes** [comment]
Closing this as I cannot reproduce the playlist stopping with corrected code.
