### ISSUE TITLE
cuepoint event listeners do not fire on iOS 12.0 (16A366)

### ISSUE THREAD

**Issue by schappim** [vimeo/player.js#325]
### Expected Behavior
`cuepoint` events should fire

### Actual Behavior
they do not :)

### Steps to Reproduce
1. Go to: https://player.vimeo.com/api/demo
2. Add `cuepoints`
3. Look at log (no cuepoints are firing)

Other Information: 
- OS: iOS 12.0 (16A366)
- User Agent: Mozilla/5.0 (iPad; CPU OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

**Comment by luwes** [comment]
This is resolved! Thanks for reporting.
