### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'o.data.method')

### ISSUE THREAD

**Issue by micahsp** [vimeo/player.js#326]
### Actual Behavior
Have been seeing this below error since roughly August 7th.  Affects mostly iOS devices and Safari browsers.
```javascript
TypeError: undefined is not an object (evaluating 'o.data.method')
File https://player.vimeo.com/api/player.js line 2 col 8633 in b
File https://player.vimeo.com/api/player.js line 2 col 10186 in e
```

Looks like it is coming from 
```javascript
function(e) {
    if (c(e.origin) && a.element.contentWindow === e.source) {
        "*" === a.origin && (a.origin = e.origin);
        var t = w(e.data),
            n = "event" in t && "ready" === t.event,
            o = "method" in t && "ping" === t.method;
        if (n || o) return a.element.setAttribute("data-ready", "true"), void r();
        b(a, t)
    }
}
```

Was not fixed by @luwes similar bug fix -  TypeError: undefined is not an object (evaluating 't.data.method') #308

I have been unsuccessful reproducing locally.

**Comment by reckoner165** [comment]
@micahsp Thanks for notifying!
Can you tell us what specific API method is called before this error thrown? 
If you're unable to pinpoint that, can you share a list of API methods that you are calling in your script?

**Comment by reckoner165** [comment]
This and #308 should be resolved now.

**Comment by micahsp** [comment]
I can confirm issue is resolved! Thanks @reckoner165
