### ISSUE TITLE
get blurred image instead of player. Console gives 404 on player.fr-FR.js

### ISSUE THREAD

**Issue by woluweb** [vimeo/player.js#335]
### Expected Behavior
Embedded video works
### Actual Behavior
get blurred image instead of player
Failed to load resource: the server responded with a status of 404 ()
https://f.vimeocdn.com/p/3.5.13/js/player.fr-FR.js
### Steps to Reproduce
The issue seems to occur randomly these last days : sometimes everything goes fine, sometimes I get that error.
Maybe an issue with the CDN ?
Example on https://www.moisdudoc.be/ (video bottom of homepage, but also any video on the website)

**Comment by ViLourenco** [comment]
The same here, pt-BR.js too!

**Comment by fisherinnovation** [comment]
This issue should be resolved now. Please reopen if you are still encountering errors. Thanks for your patience.
