### ISSUE TITLE
SetCurrentTime doesn't work until the user clicks the video

### ISSUE THREAD

**Issue by blackmambahk** [vimeo/player.js#338]
Looking to be able to setCurrentTime programmatically after a video is loaded before any user interaction.

I load a video with 

  player.loadVideo(mediaInfo.videoID)

The video loads without a problem, but if programmatically I call setCurrentTime then nothing happens.

I can see a bunch of xhr errors failed to get segment.

If i click play and pause then setCurrentTime works.

It seems clear that the issue is that without a user click the download doesn't happen except for the metadata. I can see as soon as I click the UI seekbar fills up light grey as it gets the file.

I know some browsers block video from playing until a user click action, is this the reason?

I also note calling player,play doesn't work either until after the user clicks. 
It not related to time, I have tried waiting, I also have tried the promise.then but nothing works until there is a user interaction.

**Comment by luwes** [comment]
@blackmambahk this is probably the reason yes. Which browser is this?

We're working to provide some better feedback in our play promises, should be added very soon.

**Comment by blackmambahk** [comment]
Chrome.Windows10.
I think I figured out the problem. I needed to add the **allow** **autoplay** property on the frame then setCurrentTime seems to work. I assume this is because to seek you need to download and in this case its is effectively an autoplay

**Comment by luwes** [comment]
thanks for letting use know @blackmambahk.

this allow=autoplay attribute is since today automatically added via the JS constructor (oEmbed). With the iframe you'll indeed need to add it manually.

**Comment by firewaller** [comment]
Having **allow autoplay** does not seem to fix this for me. Is this due to the fact that my videos have audio and browsers are now restricting autoplay with audio? https://help.vimeo.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos
