### ISSUE TITLE
Embed issue - two different errors

### ISSUE THREAD

**Issue by clickandcreate** [vimeo/player.js#339]
### Expected Behavior
I have a Wordpress site, where we have posts that pull a Vimeo video ID from the post meta and insert it into the Vimeo embed code.  This is supposed to display the video on the page.  And sometimes it does.

### Actual Behavior
At other times, no video diplays, and I get the following error in Chrome:
Uncaught Error: The player element passed isn’t a Vimeo embed.
    at new Player (player.js?ver=4.9.4:2)
    at HTMLDocument.<anonymous> (trapi-vimeo-player.js?ver=0.0.1:18)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

Even when the video does display, I get an error:
Uncaught TypeError: You must pass either a valid element or a valid id.
    at new Player (player.js?ver=4.9.4:2)
    at HTMLDocument.<anonymous> (learndash_template_script.js?ver=2.5.7:130)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

This is what it looks like on the page:

`<div class="embedcontainer" style="padding: 0px; position: relative; height: 439.04px;"><iframe src="https://player.vimeo.com/video/274759197" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" data-ready="true"></iframe></div>`

And this is what the PHP looks like:
`$videoid = get_post_meta($post->ID,'vimeo_video_id',true);
$framesrc = 'https://player.vimeo.com/video/'.$videoid;

echo '<div class="embedcontainer" style="padding:0;position:relative; height:0px;"><iframe src="'.$framesrc.'" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>'; `

The height on the embedcontainer div is generated by javascript.  I don't know if that would have anything to do with the issue I'm having.

### Steps to Reproduce
You can look at this page as an example: http://www.tennisresources.com/modules/module-37/

It's weird because sometimes it will work just fine without throwing any errors, and then it will throw one of the errors I mention above.

**Comment by luwes** [comment]
Seems you got it working! 👍

**Comment by LauraRi** [comment]
@clickandcreate Did you manage to resolve your issue? It has something to do with the loading time of the vimeo player, doesn't it?

**Comment by clickandcreate** [comment]
We did figure out the issue. It turned out that another script on our site
was causing a conflict. The problem was not actually with the player. The
problem resolved when we fixed the conflict in the other script.
