### ISSUE TITLE
enableTextTrack & getTextTracks after loadVideo not updated 

### ISSUE THREAD

**Issue by badoubadou** [vimeo/player.js#341]
### Expected Behavior
Set text track to wanted text track on the new video after loadVideo load a new video. 
getTextTracks get the tracks off the new video.
### Actual Behavior
Settexttrack : Not setting text track. 
getTextTracks :  get the first video tracks, not the new video one.
### Steps to Reproduce

https://codepen.io/romainmalauzat/pen/xyvyVW?editors=0010

**Comment by luwes** [comment]
This seems to be fixed. Please let us know if it's not the case.
