### ISSUE TITLE
Getting InvalidStateError in Firefox

### ISSUE THREAD

**Issue by alacayo** [vimeo/player.js#344]
I'm all the sudden getting the following error in Firefox only: InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

The video still plays and the error does not appear to break anything. 

Any idea how to fix this?

Here is my code: 

		<div id="vimeo-player" class="embed-responsive embed-responsive-16by9"></div>

		var options = {
		    id: '299316195'
		};

		new Vimeo('vimeo-player', options);

**Comment by bartclaeys** [comment]
Also having this problem....

**Comment by irahsu** [comment]
We are also. Same problem, same symptoms.

**Comment by natedunn** [comment]
Yep. Just getting this.

**Comment by wpchannel** [comment]
Same here

**Comment by KodernPl** [comment]
Also having this problem...

**Comment by reckoner165** [comment]
@alacayo I tried your code snippet [here](https://jsfiddle.net/khs5f0o7/2/) and was unable to reproduce the error on Firefox 62 and 63. 
Can you please provide an example instance (either a webpage or jsfiddle) where you encounter this error?

**Comment by laurens94** [comment]
Same problem with FF 63.0.3 (64-bit)

**Comment by laurens94** [comment]
> @alacayo I tried your code snippet [here](https://jsfiddle.net/khs5f0o7/2/) and was unable to reproduce the error on Firefox 62 and 63.
> Can you please provide an example instance (either a webpage or jsfiddle) where you encounter this error?

When browsing to the code snippet you provided, I also got the same error in the console..

**Comment by reckoner165** [comment]
Thanks!
This is seems like Firefox not properly handling function calls to the video element when readyState is 0.

We pushed a patch to prevent this from happening in the latest build. You should not see the error anymore.

**Comment by digitalheir** [comment]
Still happening for me
