### ISSUE TITLE
Seek bar does not reflect playback time

### ISSUE THREAD

**Issue by mitchtabian** [vimeo/player.js#348]
### Expected Behavior
When I visit a page and use the "setCurrentTime" method on the player, the seek bar should reflect that position on the player. 

Example:
1) page loads, I set the seek time.
2) If you look at the player, it does not "look" to be seeked
3) But if I press play, it starts playing from the seek position.

### Actual Behavior
When I set the seek time with the "setCurrentTime" method, the seek bar does not reflect that position on the player.

### Steps to Reproduce
Use the "setCurrentTime" method and look at the player.

**Comment by mitchtabian** [comment]
This is what I'm using as a work-around:

1. allow=autoplay on the iframe
2. pause the video as soon as the time is set using the setCurrentTime method

example:
https://gist.github.com/mitchtabian/1804e52865d4c2a31273beb6d83e81b6

**Comment by fisherinnovation** [comment]
Thanks for the report. We are reviewing this and will work to resolve this issue as soon as possible.

**Comment by rsichel107** [comment]
Hi @mitchtabian, this has been fixed. Thanks for logging.
