### ISSUE TITLE
Include non-minified dist version

### ISSUE THREAD

**Issue by adambiggs** [vimeo/player.js#35]
During development it's much easier to work with non-minified assets, since minified code is a complete PITA to debug.

Also, installing this library via Bower results in the following warning:

```
bower invalid-meta  The "main" field cannot contain minified files
```
### Expected Behavior

I should be able to use `/dist/player.js` for easier debugging during development.
### Actual Behavior

`/dist/player.js` doesn't exist.
### Steps to Reproduce

`$ bower install vimeo-player-js`

**Comment by bdougherty** [comment]
Would it help if we generated a source map for the dist file?

**Comment by adambiggs** [comment]
@bdougherty for users like us who use a module loader (e.g. RequreJS) to concatenate/minify all their dependencies into a single file for production, an un-minified file would be preferable.

I'm sure including a source map file would be helpful for others, but debugging with sourcemaps is still not as reliable as debugging the raw unminified code. Also, module loaders sometimes have trouble generating accurate sourcemaps of their own when dealing with nested dependency sourcemaps.

**Comment by stefan-hausmann** [comment]
+1 for including unminified dist file (source maps are generated by our build tools anyway)

**Comment by adambiggs** [comment]
Thanks! 🍻
