### ISSUE TITLE
Raises error when loading a new video with and invalid vimeo id

### ISSUE THREAD

**Issue by joker-777** [vimeo/player.js#350]
### Expected Behavior

player.loadVideo("<vimeo_id>").catch(function(error) {})

Would catch the error case when the vimeo_id is invalid.

### Actual Behavior

But instead, it throws this error `TypeError: Cannot read property 'log_plays' of undefined`

### Steps to Reproduce

1. create a video iframe and init it with `player = new Player.default($iframe)`
2. call `player.loadVideo("<invalid_vimeo_id>").catch(function(error) {})` with and invalid vimeo id to play another video

**Comment by luwes** [comment]
Pretty sure this was fixed. At least I can't reproduce the error on our api demo page. https://player.vimeo.com/api/demo
