### ISSUE TITLE
suddenly seeing colorful bar placeholder image in every video

### ISSUE THREAD

**Issue by dontsave** [vimeo/player.js#353]
### Expected Behavior
no colorful bars in the vimeo player

### Actual Behavior
colorful bar placeholder image served by vimeo shows up on devices with slow to load connections, and when the player moves from off to on screen on scroll. network inspector shows vimeo loading this placeholder image into the player for some reason. it would be cool to be able to remove these

### Steps to Reproduce
embed vimeo iframe player

**Comment by luwes** [comment]
Thanks for reporting @dontsave 
Do you have a test url where this is happening?

**Comment by luwes** [comment]
This is resolved in the latest release. Thanks again.
