### ISSUE TITLE
video element is missing `playsinline` attribute

### ISSUE THREAD

**Issue by mkhazov** [vimeo/player.js#355]
### Expected Behavior
`video` element should have `playsinline` attribute if `playsinline` embed option is set to true.
Video should play inline inside WKWebview in iOS apps.

### Actual Behavior
`video` element is missing `playsinline` attribute.
Video automatically goes fullscreen on playback inside WKWebview in iOS apps.

### Steps to Reproduce
Embed video and play it inside `WKWebview` on iPhone (iOS 11, iOS 12)

> On iPhone, `<video playsinline>` elements will now be allowed to play inline, and will not automatically enter fullscreen mode when playback begins.
> `<video>` elements without `playsinline` attributes will continue to require fullscreen mode for playback on iPhone.

https://webkit.org/blog/6784/new-video-policies-for-ios/

**Comment by luwes** [comment]
Please let us know if this is still an issue. Closing for now.

**Comment by mattcoz** [comment]
I'm experiencing the same issue and I have verified that configuration setting is set to true.

**Comment by mattcoz** [comment]
I figured out that it was a user agent issue. I was setting the user agent to my app name and version and you were therefore not detecting it as iOS. Maybe there is a way for this to work without relying on the user agent.
