### ISSUE TITLE
Quality parameter missing for initializing Vimeo.Player

### ISSUE THREAD

**Issue by leolux** [vimeo/player.js#358]
Regarding the documentation https://developer.vimeo.com/player/sdk/embed there is no parameter for setting the quality of the player. 

I load new videos with videoPlayer.loadVideo(id).then(...) but the quality of the video is bad.

**Comment by luwes** [comment]
You should pass them in the constructor like so

```js
    var player = new Vimeo.Player('player', {
    	id: 76979871,
      quality: '720p'
    });
```

**Comment by leolux** [comment]
It works, thank you!

However, the documentation is still missing this parameter.

**Comment by luwes** [comment]
Best to refer to these https://github.com/vimeo/player.js#embed-options
