### ISSUE TITLE
autoplay ignored in loadVideo()

### ISSUE THREAD

**Issue by leolux** [vimeo/player.js#359]
The video seems to start playing automatically after invoking `player.loadVideo(id).then(...)` altough the player has been initialized with `{autoplay: false}`

Why does the event "timeupdate" gets fired after loading the video in a player that should not autoplay?

**Comment by luwes** [comment]
Could you provide a jsfiddle or something similar?

A `loadVideo` call in itself should not automatically playback the video,
only when it was playing before I believe.

See https://player.vimeo.com/api/demo and load a random clip e.g. `24`

**Comment by luwes** [comment]
Duplicate of #42
