### ISSUE TITLE
Sub-resource Integrity

### ISSUE THREAD

**Issue by keithws** [vimeo/player.js#364]
### Expected Behavior
The ability to embed the Vimeo player.js script with [sub-resource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).

### Actual Behavior
URLs for player.js are unversioned and therefore cannot use sub-resource integrity.

### Steps to Reproduce
Add player.js script to page.
[Add sub-resource integrity property](https://www.srihash.org).
Wait for new version of player.js to be released.
Then, be sad that player.js fails integrity check and the browser blocks it from loading.

Ultimately we need versioned URLs for SRI to work. I believe the easiest way for you to get versioned URLs would be to [add it to the cdnjs.com repo](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson).

**Comment by luwes** [comment]
There's always unpkg:

https://unpkg.com/@vimeo/player
https://unpkg.com/@vimeo/player@2.6.7/dist/player.min.js
