### ISSUE TITLE
New dimensions in loadVideo not respected in resulting iFrame

### ISSUE THREAD

**Issue by lerran80** [vimeo/player.js#365]
### Expected Behavior
Passing both width and height into the options object when loading a new video with loadVideo should change the inner iFrame width and height attributes.

### Actual Behavior
New iFrame does not respect the new properties.

### Steps to Reproduce
https://jsfiddle.net/47vazxum/2/
Click Load Video in the test case above and inspect the iFrame height and width properties

**Comment by luwes** [comment]
@lerran80 I understand the problem but the existing iframe is re-used when calling the `loadVideo` method.

`loadVideo` is directly forwarded to the Vimeo player in the iframe and it's not possible to change the dimensions from within the iframe. 

I know the player.js API could potentially do this but for now we don't have any plans to add that custom behavior.

I recommend setting the dimensions yourself when the `loadVideo` promise resolves.

Hope this helps.
