### ISSUE TITLE
Dont play private videos

### ISSUE THREAD

**Issue by PabloPerezAguilo** [vimeo/player.js#367]
### Expected Behavior

Play a private video

### Actual Behavior

403 http code

### Steps to Reproduce

Just copy and paste the example of private video. I used the full url (https://vimeo.com/293438045/463ebf7bcf) 

https://codepen.io/anon/pen/KJKQMb

Chrome  71.0.3578.98

![image](https://user-images.githubusercontent.com/9373112/51531297-52a69d00-1e3d-11e9-96f3-2d1565b93262.png)

**Comment by luwes** [comment]
Codepen is not whitelisted so it's not allowed. It's no bug I think.

<img width="407" alt="screen shot 2019-01-29 at 12 10 52 pm" src="https://user-images.githubusercontent.com/360826/51926279-f0aae200-23be-11e9-926d-f33db454d6ea.png">

Please let me know if you have any questions.

**Comment by PabloPerezAguilo** [comment]
You are right, thx!
