### ISSUE TITLE
d.telecine is either null or undefined (ie11)

### ISSUE THREAD

**Issue by ilyen85** [vimeo/player.js#368]
### Expected Behavior
When clicking on a video it should start
### Actual Behavior
Video is paused, controls disappear
### Steps to Reproduce
I'm working on a site's ie11 compatibility, had issues with playing an embedded vimeo video. So I tried the vimeo.com page to find out if its working there or not.
0. Open up ie11 (I have version 11.0.9600.19236)
1. Opened a random video (in this case this was the first video: https://vimeo.com/313677812)
2. Clicked on the play button
3. Error occurs: 
player.js at line 11313:
`d.events.fire(d.telecine.paused ? Na.playButtonPressed : Na.pauseButtonPressed);`

d.telecine is null causing an issue when trying to get the paused attribute's value.

Created a screen shot also.
https://www.dropbox.com/s/ybs751v7d9ryum7/Screenshot%202019-01-29%2012.06.00.png?dl=0

Thanks for the help

**Comment by rebecca-sich** [comment]
Our QA team has been unable to reproduce this in multiple tests, we used versions 11.0.9600.18953, 11.407.17134.0 and 11.540.15063.0.

**Comment by ilyen85** [comment]
Hi, thanks for the feedback.

Does it matter if I'm using a virtual machine? I'm using Virtualbox, the system is: Windows 7 N x86.

**Comment by luwes** [comment]
it could, it's a long shot but have you tried toggling compatibility mode?

https://support.microsoft.com/en-us/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-v

**Comment by ilyen85** [comment]
No haven't tried compatibility mode. I wouldn't like to mess with anything like this, because our average user wouldn't know how to toggle it.

But I will try if it fixes it.
Also will try to test it on a real machine with ie11 on it.

Please feel free to close this one, if you guys can't reproduce this. Hopefully everything is working fine anyway.

Thanks for the fast feedback!
