### ISSUE TITLE
Cannot read property 'video' of null

### ISSUE THREAD

**Issue by luizguilhermefr** [vimeo/player.js#369]
### Expected Behavior

The player runs the video without problems.

### Actual Behavior

The player doesn't play the video (that keeps an eternal load) and an error is thrown.

![image](https://user-images.githubusercontent.com/6135939/52001692-2c20db80-24a7-11e9-874c-7401b5273ab8.png)

Stacktrace:

```
Uncaught TypeError: Cannot read property 'video' of null
    at i.value (player.js:2)
    at t.c.fire (player.js:2)
    at t._resolveSwitchComplete (player.js:2)
    at t.value (player.js:2)
    at t.value (player.js:2)
```

### Steps to Reproduce

`@vimeo/player@^2.7.0`

```html
<div
    id="vimeo-player"
    ref="vimeoPlayer"
    class="player"
  />
```

```js
const options = {
  id: this.id,
  autoplay: 1
}

this.player = new Player('vimeo-player', options);
this.player.loadVideo(this.id);
```

:arrow_right: Pro user
:arrow_right: Video is private but allowed to play at the `localhost` origin

**Comment by luwes** [comment]
thanks for reporting @luizguilhermefr. could you provide a codepen or jsfiddle?

is it only with autoplay enabled or click to play as well?

**Comment by arson2000** [comment]
What was the solution to this issue? I am having the same issue.

**Comment by johannesmols** [comment]
I am also having the same issue. It seems completely random if it happens or works fine.
