### ISSUE TITLE
Player should ignore unrecognized postMessage formats

### ISSUE THREAD

**Issue by bddean** [vimeo/player.js#370]
### Expected Behavior
Since postMessage messages can come from sources other than the Vimeo player api, the video player should ignore message events in an unknown format.

### Actual Behavior

Unrecognized messages cause the player to stop emitting `progress` and `timeupdate` events. This means that other scripts using the postMessage API might interfere with player.js.

More concretely, I work on a third party [analytics/session replay script](https://fullstory.com) that needs to send a postMessage message to each iframe on the page to try to communicate with it. This issue came up for us in a customer ticket.

I haven't checked for sure, but I *think* the culprit is the lack of validation in this `"message"` handler: https://github.com/vimeo/player.js/blob/4ebc8a52fba9757d531c65bab84c64268a8cc661/src/player.js#L68

In contrast the message handler in embed.js *does* validate the message format:
https://github.com/vimeo/player.js/blob/1b8d544804451425003eb9923ab322dfa1d1ce2c/src/lib/embed.js#L189

### Steps to Reproduce

Run this code on the [player.js demo page](https://player.vimeo.com/api/demo):

```
document.querySelector('iframe[src*="player.vimeo.com"]')
  .contentWindow
  .postMessage('{"foo": "bar"}', '*');
```

This JSFiddle also illustrates the error:
https://jsfiddle.net/4rc1vyfs/

Thanks!

**Comment by luwes** [comment]
Thanks for reporting @bddean. We have made some changes that should resolve this issue. As long as the post messages are not stringified json or query params the API should keep working like expected.

The problem was that we have multiple API versions we support and when receiving a postmessage with a simple string it would downgrade the API version.
