### ISSUE TITLE
Blocked a frame with origin

### ISSUE THREAD

**Issue by petrogad** [vimeo/player.js#376]
### Expected Behavior
Full Screen post messaging working correctly

### Actual Behavior
Full screen postmessaging not working

### Steps to Reproduce
Using Safari, placing a video in fullscreen, completing the video creates an error of:
```
Blocked a frame with origin "xxx" from accessing a frame with origin "https://player.vimeo.com". Protocols, domains, and ports must match.
```

when attempting to get a message on the parent frame when the video is complete.

After checking the privacy page on the video video, all domains match, currently using https on the domain embedding the url, however seeing that error.

Appreciate any help identifying the cause of this!

**Comment by luwes** [comment]
@petrogad do you have a test page perhaps?

**Comment by luwes** [comment]
Closing as this sounds like an issue where the protocols of the site and the iframe embed not match. It's recommended to enable the secure https protocol for your website.

**Comment by MaxWeisen** [comment]
@petrogad I am also having this issue with embedded Vimeo videos. Only on Safari.

**Comment by kangchals** [comment]
I am same situation like MaxWeisen said. it happens only on Safari.

**Comment by sharmarch** [comment]
same issue here and only recently - Safari only
