### ISSUE TITLE
Autopause not working in Firefox (even private browsing)

### ISSUE THREAD

**Issue by gilbert-hop** [vimeo/player.js#377]
### Expected Behavior
With multiple embeds, when a video is clicked to play all other videos should pause.
### Actual Behavior
On Firefox, you can play multiple videos at once. Tested in version 64, 65.
### Steps to Reproduce
Embed multiple Vimeo videos, try to play 2 of them at once (on Chrome the previous video gets paused, on Firefox both videos play)

**Comment by fisherinnovation** [comment]
@gilbert-hop I am testing https://jsfiddle.net/pLsuoa9q/ on Firefox 65 on OSX and I am unable to replicate your issue. Can you provide a link or example of a configuration where you are encountering this issue?

**Comment by gilbert-hop** [comment]
https://www.wendymogel.com/media

Actually a client reported this. I will send your jsfiddle to see if they
can replicate the issue with their machine.

Thanks for looking into this.

**Comment by luwes** [comment]
@gilbert-hop we can replicate this when disabling cookies (also disables localStorage). In turn this breaks the `autopause` functionality, it relies on localStorage to send data between the separate players that each run in an iframe which are basically separate webpages.

Do you happen to know if the user did disable cookies?
Private browsing could have an affect, depends on the browser I believe.

**Comment by luwes** [comment]
Closing for now as this seems out of our control. Please let us know if you have additional information that could be of help. Thanks
