### ISSUE TITLE
Vimeo video in modal not obeying events

### ISSUE THREAD

**Issue by mhulse** [vimeo/player.js#378]
### Expected Behavior

Events applied to video iframe's in modals handle applied events.

### Actual Behavior

Events attached do not fire; if they do, it appears to be random as sometimes I get events to fire.

### Steps to Reproduce

**Demo:** <https://jsbin.com/kudilet/14/edit?html,js,console,output> (snapshot), <https://jsbin.com/kudilet/edit?html,js,console,output> (latest)

I was not sure how to version the player.js via the cdn ... So it's latest.

I'm using <https://github.com/kylefox/jquery-modal>

Am I doing something wrong with the code? If it's my syntax and/or logic error, I apologize in advance for wasting anyone's time.

With that said, any suggestion of a modal that works with vimeo videos and events like `play`, `pause`, `ended`?

Related to #130.

**Comment by mhulse** [comment]
Here's my first attempt at fancybox (I can post a full example tomorrow):

```js
$(function() {

  	$('.ap_fancy').fancybox({
        type: 'inline',
        openEffect : 'none',
        closeEffect : 'none',
        padding : 0,
        margin : 0,
        width : '75%',
        height : 'auto',
        autoSize : false,
        afterShow: function(instance, current) {
            var iframe = instance.current.$content.find('iframe');
            var player = new Vimeo.Player(iframe[0]);
            console.log('afterShow', player);
            player.on('play', function() {
                console.log('playing');
            });
        },
        beforeClose: function (instance, current) {
            var iframe = instance.current.$content.find('iframe');
            var player = new Vimeo.Player(iframe[0]);
            console.log('beforeClose', player);
            player.off('play');
        }
	});

});
```

The `on('play' ...` just doesn't seem to fire.

I'm probably just doing it wrong. Any tips would be spectacular... Or, is this a bug of some kind?

**Comment by mhulse** [comment]
Just curious if anyone can tell me if my thinking is correct for how to handle vimeo events inside of modal window callbacks?

I'm working on a project where the client is paying for Vimeo pro, and they have requested functionality that requires vimeo videos embedded with modal windows and these modal windows depend on vimeo events (for tracking and altering UI).

Thanks in advance for any help you can provide!

**Comment by mhulse** [comment]
I'm gonna give this another look this week. Still curious if anyone has any tips for using the Vimeo API in conjunction with modal windows? Has anyone else had similar issues? If not, can tell me the name of the modal plugin you're using?

With that said, maybe I can roll my own ... I'm guess it has to do with modal windows copying code vs. using existing code. Perhaps I can find a modal that doesn't do this, or just roll my own modal and have it position off-screen vs. do a `display:none` ... I am crunched on time here, so this sounds like the quickest path to getting this to work.

I'm just surprised that I can't apply a new Vimeo instance on a vimeo iframe in a modal popup (and then `off` it when the modal closes).

Hrmm, maybe I should try a different approach, like programmatically generate the PDF using the Player.js API (vs. use already-embedded iframe).

I'll post back my results if/when I find a solution. I'm sure it will help future readers.

Thanks for reading!

**Comment by mhulse** [comment]
It's looking like a combination of programaticly creating the vimeo embed, and then `destroy()` when the modal closes (vs. `off('play')`) is going to work.

I'm still testing, but I've had a successful test where the above appears to work.

I'll post example code once I have a clean-ish demo. Maybe it will help other's in future whom are also using jQuery-based modals.

**Comment by mhulse** [comment]
I think this does the trick:

- Latest: https://jsbin.com/paxeneb/edit?console,output
- Snapshot at time of this comment: https://jsbin.com/paxeneb/2/edit?console,output

Seems solid enough for me to close this issue and stop bugging the rest of you. 👍

**Comment by luwes** [comment]
hey @mhulse, sorry we didn't get back to you yet! 

we've had some similar issues with modals,
https://github.com/vimeo/player.js/issues/130

Glad you got it solved!
