### ISSUE TITLE
Custom Unmute Button Not Working in Chrome

### ISSUE THREAD

**Issue by danaburger** [vimeo/player.js#382]
### Expected Behavior
Unmute button works

### Actual Behavior
When clicking on the button to unmute in Chrome, the video stops playing.

### Steps to Reproduce
1. Visit https://formats.eyeonx.ch/liquid-ad?preview=https%3A%2F%2Fcreatives.eyeonx.ch%2Fcampaigns%2Fcembra%2F2019%2Fjahreskampagne%2Fliquid-ad%2Findex.html

2. Click on Unmute button in the player

![image](https://user-images.githubusercontent.com/33134472/52880724-bcf6e880-3130-11e9-8040-4b0f4198be87.png)

See error from Chrome's autoplay policy
![image](https://user-images.githubusercontent.com/33134472/52880728-c2543300-3130-11e9-8cac-cb5d48d6d1fa.png)

Code:
```
<script src="https://player.vimeo.com/api/player.js"></script> 
<script> 
var options = { 
url: "https://vimeo.com/316975327", 
background: true, 
loop: false, 
autoplay: true, 
muted: true 
};

var videoPlayer = new Vimeo.Player('video', options);
```
cc// @fisherinnovation @luwes

**Comment by jacobsjensen** [comment]
+1 

I have the exact same behaviour here! Same goes for Chrome on Android (newest OS and Chrome versions)

**Comment by danaburger** [comment]
Per [Google's autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes), the solution here is to add `allow=autoplay` to the Vimeo iframe as well as any additional iframes the player is contained within. Problem Solved!

**Comment by jacobsjensen** [comment]
Hmmm... but you are not using the vimeo iframe... you are using a video element directly... so where did you place the allow=autoplay ?

**Comment by danaburger** [comment]
@jacobsjensen` allow=autoplay` only needs to be added to cross-origin iframes. This example had parent iframes (other than the Vimeo player). Your example may differ. 

Please open a separate ticket if your issue was not solved by this solution.
