### ISSUE TITLE
How to change language display element in frame (ex.. title when hover play button..)

### ISSUE THREAD

**Issue by trangianhuan** [vimeo/player.js#386]
### Expected Behavior
i want ..when hover into play video button..v.v.. show language same config
ex.
for button play
```
ja => '遊びます',
en => 'play',
fr => 'jouer'
```

### Actual Behavior
I try, but not working
```
<iframe
                class="iframe-vimeo"
                src="https://player.vimeo.com/video/.."
                language="fr"
                width="{{ $lesson->videos->first()->width }}" height="{{$lesson->videos->first()->height}}">
              </iframe>
```
or
```
var options = {
        id: 59777392,
        width: 640,
        loop: true,
        language: 'fr',
    };

    var player = new Vimeo.Player('made-in-ny', options);
```

**Comment by luwes** [comment]
@trangianhuan this is not possible via the API, the language is chosen based on the installed browser languages/locals. So if you set the primary language to French in your browser the player will have French copy.

Hope this helps. Please let me know if you have any more questions.
