### ISSUE TITLE
Couldn't find preset "@babel/preset-env" relative to directory

### ISSUE THREAD

**Issue by ashussen** [vimeo/player.js#388]
### Expected Behavior
Installed using NPM @vimeo/player, compiled all my JS using Gulp

### Actual Behavior
Showing an error 
```
Couldn't find preset "@babel/preset-env" relative to directory "[directory-to-path]/node_modules/@vimeo/player"
```
### Steps to Reproduce
Mac OSX
NPM 6.8.0
Node v10.6.0

**Comment by luwes** [comment]
@ashussen did you manage to find the solution?

I don't think it's an issue on the player api side, the api only has 2 dependencies listed here: https://github.com/vimeo/player.js/blob/master/package.json#L45

**Comment by ashussen** [comment]
Hi @luwes,

Sorry I didn't get the notification for your response. 
No, I have put this project on hold, still couldn't figure out why is it like that. 

I will have another look at the other library related to this. 
Thanks

**Comment by javafun** [comment]
I'm currently encountering the same issue. 

Can someone help with this pls? 

OS: Windows 10
Node: 10.16.0
NPM: 6.9.0
