### ISSUE TITLE
NotAllowedError: play() failed because the user didn't interact with the document first

### ISSUE THREAD

**Issue by danrossi** [vimeo/player.js#389]
There seems to be an odd issue with triggering the play api by user clicks. It's acting like an autoplay issue but playback is after user clicks. The play element is on top of the iframe so not clicking the embedded player.

The error received is.

NotAllowedError: play() failed because the user didn't interact with the document first

Any ideas ? 

https://jsfiddle.net/danrossi303/kohdg29c/2/

**Comment by luwes** [comment]
@danrossi this is an issue specific to jsfiddle and codepen like services.
On those test pages they wrap the user defined test content in an iframe which doesn't have the `allow="autoplay"` which prevents the `play()` action from happening.

<img width="959" alt="screen shot 2019-02-21 at 9 20 05 am" src="https://user-images.githubusercontent.com/360826/53175462-fe1c4c00-35b9-11e9-9361-42c0571e3180.png">

Also the Vimeo player iframe has to have the `allow="autoplay"` attribute.
You can see on the api demo page this doesn't have this problem if you press the custom play button on the top right. https://player.vimeo.com/api/demo


Hope this helps.

**Comment by danrossi** [comment]
Please don't just automatically close. It was just a basic example I had to setup. I don't configure like this. The api generates that attribute it is not autoplay because its user click triggering play ? Autoplay is in fact working when muted not playing with user clicks. I added that attribute and its still happening. 

Yours is likely working because of same domain. 

This is not happening with youtube. 

https://jsfiddle.net/danrossi303/kohdg29c/3/

**Comment by danrossi** [comment]
Same config but autoplay.  This is working. https://jsfiddle.net/danrossi303/kohdg29c/5/

**Comment by danrossi** [comment]
```
player.js:2 Uncaught (in promise) NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
    at https://player.vimeo.com/api/player.js:2:8670
    at Array.forEach (<anonymous>)
    at b (https://player.vimeo.com/api/player.js:2:8644)
    at e (https://player.vimeo.com/api/player.js:2:10391)
```

**Comment by danrossi** [comment]
Same thing on another fiddle platform. 

https://codepen.io/danrossi/pen/aXgERK
![capture](https://user-images.githubusercontent.com/710277/53242968-7be77100-36fa-11e9-8894-2dd2ec7c633b.PNG)

**Comment by danrossi** [comment]
With muted enabled it will work with user clicks only. This is a recent problem someone alerted me to. 

https://codepen.io/danrossi/pen/omrEvO

**Comment by luwes** [comment]
> Same thing on another fiddle platform.
This is still codepen.

Do you have a test page with a Youtube example?

**Comment by luwes** [comment]
I know it doesn't really make sense, `autoplay` is not the same as a user clicking to play but the wrapper iframes of those services do make a difference in the behavior with the Vimeo player as you can see in this recordit http://recordit.co/lWZNUZAYsy

Note that the wrapper iframe is not the Vimeo player iframe, it's another iframe they use to automatically reload the test code when you "save" or "run" the codepen or fiddle.

**Comment by danrossi** [comment]
I'm making some external examples now. Is that the same on codepen ?

**Comment by danrossi** [comment]
Sorry mate I don't know what is going on but my implementation similar isn't working and I have the autoplay property configured. These barebones demos outside of jsfiddle is. 

http://207.148.87.89/player/vimeo.html
http://207.148.87.89/player/youtube.html

These changes in Chrome are getting counter productive. I narrowed it down to a badly configured Iframe. I dynamically create the iframe as using the generated one using a div tag causes problems. But I was using a protocoless url. See this

http://207.148.87.89/player/vimeo2.html

Sorry about that. The iframe must be https regardless if loaded on http.

**Comment by danrossi** [comment]
Basically needs to be this

player.src = "https://player.vimeo.com/video/309741585";

not this

player.src = "//player.vimeo.com/video/309741585";

**Comment by danrossi** [comment]
According to Youtube looks like extra params are needed for futureproofing other restrictions ?

Adding this for good measure

```
el.setAttribute("allow", "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture");
```

**Comment by joshiefishbein** [comment]
I have this issue as well.

This seems to be occurring on Chrome (v72.0.3626.109) only for two different websites of mine.

It looks like their autoplay policy was updated on February 12th, 2019. A change in their policy may be affecting `play()` being trigger-able.

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by danrossi** [comment]
My problem is I needed to load the player in the iframe via https. Even under http. Don't ask why.

**Comment by downtroden** [comment]
Is there a hook to get to the iframe to use setAttribute? I have the same problem NOT in a online editor.

[https://careers.daugherty.com/culture/
](url)

What's really weird is videos that I append to the page play just fine, the video that is on the page onload is the one that's being penalized. Is there a js hook I should be aware of or should I make an edit to a function? wp_video_shortcode is putting the video on the page.

**Comment by mhiwy** [comment]
> @danrossi this is an issue specific to jsfiddle and codepen like services.
> On those test pages they wrap the user defined test content in an iframe which doesn't have the `allow="autoplay"` which prevents the `play()` action from happening.
> 
> <img alt="screen shot 2019-02-21 at 9 20 05 am" width="959" src="https://user-images.githubusercontent.com/360826/53175462-fe1c4c00-35b9-11e9-9361-42c0571e3180.png">
> 
> Also the Vimeo player iframe has to have the `allow="autoplay"` attribute.
> You can see on the api demo page this doesn't have this problem if you press the custom play button on the top right. https://player.vimeo.com/api/demo
> 
> Hope this helps.

thanks

**Comment by gingerlime** [comment]
@luwes 

> I know it doesn't really make sense, autoplay is not the same as a user clicking to play but the wrapper iframes of those services do make a difference in the behavior with the Vimeo player

Seems a bit strange to me, I have to say. I just hope that the player doesn't change something later on, and starts auto-playing those iframes with `autoplay` turned on, when the only reason to set this flag is to allow programatic play...

**Comment by joker-777** [comment]
Guys, using `allow="autoplay"` seems to be more a workaround rather a real solution. It also makes some browser block this iframe which isn't desirable at all. Are you guys actively working on fixing this?

**Comment by sheriffderek** [comment]
My project uses
```
<video-background>
  <iframe id='video-outlet' src='https://player.vimeo.com/video/400744064?controls=false&loop=true' width='640' height='480' frameborder='0' webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</video-background>
```

![Screen Shot 2020-03-26 at 3 16 00 PM](https://user-images.githubusercontent.com/2066617/77704282-f88df400-6f79-11ea-85d4-be1aa914431b.png)

and has a little loading/title screen on top of the iframe. The text in the middle triggers playson click. This is a user interaction.

```
var $videoOutlet = document.querySelector('#video-outlet');
var backgroundPlayer = new Vimeo.Player($videoOutlet);

document.addEventListener('click', function(event) {

  // site enter button
  if ( event.target.matches('.click-suggestion') ) {
    document.querySelector('.branding').classList.add('fly-away');
    backgroundPlayer.play();
  }

});
```

Some (seems like most) of the time - it works as expected - but in other cases / it just stalls - and when I check the console: 

![Screen Shot 2020-03-26 at 3 16 42 PM](https://user-images.githubusercontent.com/2066617/77704320-093e6a00-6f7a-11ea-9501-911ef68b70b7.png)

I'll have the real site up soon - and so, I can check if it's an HTTP/HTTPS thing as suggested in this thread, but I'm curious what is causing this intermittently.

**Comment by sheriffderek** [comment]
Here's a live site of the one pointed out just above. https://latakedown.com I haven't got an error since it was live / so, that's great - but I'd love to have some clarity on what makes it tell me that locally. Here's the error - in case someone knows. : )

![Screen Shot 2020-03-28 at 6 33 52 PM](https://user-images.githubusercontent.com/2066617/77837872-134f9c80-7123-11ea-8459-43d450fb7e15.png)

**Comment by sheriffderek** [comment]
Now I am receiving reports that the live site is erroring. ^

**Comment by sheriffderek** [comment]
For some reason / I skimmed over the "autoplay" setting discussion because / it can't _really_ autoplay - so, I just expected that to no longer have any effect and was on its way to being depricated. After getting this error on the live site / and counting out _the http vs https issue_ - I tried the autoplay setting - and it appears to avoid the error.

I made a minimum example here - and it seems to be consistent: 
https://github.com/sheriffderek/vimeo-autoplay-example

: )

**Comment by struthy** [comment]
adding the autoplay worked for me

**Comment by tuantiensiu** [comment]
How to using in tagname video? I want to fix autoplay and unmuted video

**Comment by DATEx2** [comment]
This is still an issue in Noember 2024 when you add your own `"Unmute"` button, of course outside of the iframe
First the user needs to click on the dumb iframe and just then anything outside of the iframe would work
This is a limitation because the vimeo renders in an iframe and the `document` refers to the iframe and not the main document, unfotunately.

I don't think there is an workaround and Chrome as other browsers seem to consider the same bad behavior towards the end user

You closed the issue, but it is NOT fixed or a feasible work around in any way, so please reopen it
