### ISSUE TITLE
No load event on new loaded video

### ISSUE THREAD

**Issue by danrossi** [vimeo/player.js#391]
I've noticed this recent issue. loaded event is used to obtain duration from the video. But newly loaded videos in a playlist never receive this event. 

Here is a fiddle

https://jsfiddle.net/danrossi303/bympk2rg/11/

**Comment by luwes** [comment]
Good find, I can confirm this is a bug.

**Comment by luwes** [comment]
Thanks for reporting @danrossi! This is resolved in the latest player release.
