### ISSUE TITLE
When 'playsinline : false' captions not display.

### ISSUE THREAD

**Issue by ct7ct7ct7** [vimeo/player.js#393]
when I set 'playsinline : false' at android WebView js options, Yes , the controls is not display ,but I think the captions must be showed.

**Comment by luwes** [comment]
@ct7ct7ct7 can you provide a screen shot or video?

How do you mean the controls are not displayed?
Did you set the captions first with the API then if there were no controls for the user to interact with?

https://github.com/vimeo/player.js#enabletexttracklanguage-string-kind-string-promiseobject-invalidtracklanguageerrorinvalidtrackerrorerror

**Comment by luwes** [comment]
@ct7ct7ct7 did you manage to get it to work?
