### ISSUE TITLE
Error when embedding video protected by private link via player.js

### ISSUE THREAD

**Issue by cdiem** [vimeo/player.js#396]
It seems that embedding videos protected by private link (without domain protection) with player.js don't work when you specify the video ID. Player.js gets 404 error from oEmbed API.
Issue #334 says that is should have been fixed, but apparently it's not.

Video settings:
<img alt="screenshot 2019-02-27 at 19 25 07" width="375" src="https://user-images.githubusercontent.com/4948518/53505700-735db480-3ac5-11e9-82ed-4c5581e241c8.png">

### Expected Behavior
The video is embedded correctly.

### Actual Behavior
Error "https://vimeo.com/320269670” was not found."

<img alt="screenshot 2019-02-27 at 19 10 22" width="695" src="https://user-images.githubusercontent.com/4948518/53504653-62ac3f00-3ac3-11e9-8b25-133aa0df0234.png">

### Steps to Reproduce

Codepen: https://codepen.io/cdiem/pen/ZPGvjZ
Link to the video: https://vimeo.com/320269670/eced817cc0

**Comment by luwes** [comment]
@cdiem this is a known limitation of the oEmbed api. There are 2 workarounds:

1. Use the direct iframe embed (recommended)
There is no need here to publish the private hash in your source code.
https://github.com/vimeo/player.js#pre-existing-player

2. Use the private link as the url parameter

```js
    var options = {
        url: 'https://vimeo.com/320269670/eced817cc0',
        width: 640,
        loop: true
    };

    var player = new Vimeo.Player('made-in-ny', options);
```
