### ISSUE TITLE
I need the fast forward function to be inactive while pause and rewind to be active.

### ISSUE THREAD

**Issue by shahjehanali1** [vimeo/player.js#40]
We need the fast forward function to be inactive while pause and rewind to be active.

[Here is link on which i'm working](http://jsfiddle.net/HfwWY/4322/l)

**Comment by bdougherty** [comment]
That example is using our old library, which is unsupported.

If I understand correctly, you're asking to be able to block seeking forward in the player? You should be able to implement that via the api by using the `timeupdate` event to track and calling `setCurrentTime()` to move back if they seek forward.

If you think it's something we should implement in the player itself, I encourage you to submit the feature requests in our forums: https://vimeo.com/forums/feature_requests.
