### ISSUE TITLE
Still not working on iOS 12+/Cordova/Phonegap

### ISSUE THREAD

**Issue by GeoTimber** [vimeo/player.js#401]
### Expected Behavior
See the player, and have the IFrame loaded
### Actual Behavior
Nothing loads
### Steps to Reproduce
Include the iframe and playe. js in a cordova/phonegap app

I was hoping this would fix it, but I still have the problem
https://github.com/vimeo/player.js/issues/162

It works fine on Android....

**Comment by luwes** [comment]
@GeoTimber do you have any more info? does it throw any errors?

**Comment by GeoTimber** [comment]
Hi there were no errors, but I think the problem lies somewhere in a Content Policy/iOS Safety Feature Quirck not picked up by the Phone Gap Build process.

As when I build the IPA instead of with PhoneGap but directly XCode 10 the IFrame loads well and the video plays, if I find a solution for Phonegap I will add it here but I dont think it is related to the Vimeo Player so you can probably close it, thanks for getting back.

**Comment by alextkd** [comment]
Hey, try this. Just got deeper into it and I succeeded to fix it. Add at the end of your `config.xml` before closing </widget> tag:

```
<feature name="IntentAndNavigationFilter">
        <param name="ios-package" value="CDVIntentAndNavigationFilter"/>
        <param name="onload" value="true"/>
    </feature>
<allow-navigation href="*" />
```

Then go to your index and make sure to have https://*.vimeo.com and https://*.viemeocdn.com in both default-src and script-src

Let me know if this fixes it for you, for me it worked

**Comment by luwes** [comment]
Thanks for your help @alextkd! Looks like a configuration issue then, closing here.

**Comment by thesayyn** [comment]
@luwes This is not a configuration problem. Vimeo player has serious problems on ios 12 with Cordova/Ionic. You should give it a try low battery mode on a Cordova app.

**Comment by prabhashibuddhima** [comment]
I have solved my issue by adding 

```
<meta http-equiv="Content-Security-Policy"
      content="default-src * 'self' data: gap: 'unsafe-inline' 'unsafe-eval';
      style-src * 'self' 'unsafe-inline' 'unsafe-eval' gap:;
      script-src * 'self' 'unsafe-inline' 'unsafe-eval' gap:; frame-src *;">
```

to my index.html
