### ISSUE TITLE
403/500 error in console when using loadVideo on existing iframe

### ISSUE THREAD

**Issue by joker-777** [vimeo/player.js#407]
We have a Vimeo iframe in the document when the page is loaded and we give the user the possibility to start/load a different video in this iframe by providing different links which eventually use `loadVideo` to load a new video in this iframe. This works like expected, but somehow the console shows a 403 privacy error (on my dev server it is a 500). As I said, it doesn't have an influence on the behavior of the player, the new video still loads but it is strange nevertheless. Our videos are restricted to be used only with our domain.

### Steps to Reproduce

https://codepen.io/kenhub/pen/KEgaXJ

**Comment by luwes** [comment]
Thanks for reporting, this is a strange one. I think it's related to our use of history.pushState when a new video is loaded. Although the player doesn't really go to that new path, the browser does make a request which responds with a 403 on my end.

<img width="1348" alt="Screen Shot 2019-04-04 at 3 40 32 PM" src="https://user-images.githubusercontent.com/360826/55583564-28504600-56f0-11e9-9723-b7e687209e73.png">

Was it a 500 on your end?

**Comment by joker-777** [comment]
I think on production it is a 403 and on my dev server, it is a 500.

**Comment by glomotion** [comment]
Hello there! 

We're also having privacy errors like the above, when unloading a player and then calling .loadVideo with another private video. 
Im pretty sure this functionality worked just days ago. 

Has something changed lately in the API with regard to privacy? 

This is a huge issue for us, as it completely breaks our application - which heavily utilises the Vimeo Player. :(

Both videos in the example codepen have been set to be allowed to be embedded on codepen.io:
![Screen Shot 2020-05-27 at 9 52 31 am](https://user-images.githubusercontent.com/1452237/82961138-cc393700-9fff-11ea-9e2a-143f37aa14f8.png)

Codepen demo:
https://codepen.io/glomotion/pen/GRparyv

**Comment by glomotion** [comment]
actually, Looks like it's something to do with the "where can this be embedded" privacy settings. I don't think the player is correctly respecting the whitelist. For now, We've had to just allow all videos to be "embedded anywhere".

**Comment by bortraws** [comment]
We also get the exact same 403 error when loading a new video into an embed using player.loadVideo().

Our videos also have privacy settings where we don't show them on Vimeo and only allow embed on our own domain.

**Comment by houmark** [comment]
We are seeing the same issue, any update here from the Vimeo team?

**Comment by vurhd** [comment]
Bump. We're facing the same issues. Did anyone figure out an update to this?

**Comment by joker-777** [comment]
No, unfortunately not :(

**Comment by vidiot1969** [comment]
Same experience here as @bortraws.  We experienced the issue mostly in iPad Safari.  Our solution _appears_ to be to add a player.play() inside the loadVideo promise... but it does seem to affect the speed with which the video starts playing.

**Comment by nearlyheadless** [comment]
Any news on this issue?

**Comment by bdougherty** [comment]
I can't reproduce any of the examples provided. If you are still having this issue, please reply back with a demo of some sort for us to try to reproduce.

**Comment by birdofpreyru** [comment]
Same here &mdash; create a player with one video URL, then use `.loadVideo()` with a different URL (both URLs work fine if they are used when creating a new player instance) &mdash; 403 (Forbidden) error in console, the `.loadVideo()` promise stays unsettled indefinitely. It is very unsettling that Vimeo being a big commercial project, nobody can reproduce and solve this issue for years, when I bumped into it just after a few days of using the library.

**Comment by birdofpreyru** [comment]
@rkrishnan8594 not exactly that 403 error, but also `.loadVideo()` issue (in my current experience, if `.loadVideo()` is called on existing player instance, that player instance just can't be relied to work correctly at all) &mdash;
- Save locally and serve, say with `npx serve`.
- Visit the page, click "Play" button.
- Then click "Next" button &mdash; you'll see it loads another video, but it does not start playing; however, if I just remove the `.loadVideo()` call from that button's handler, turning
  ```js
      nextButton.onclick = async function () {
        await player.pause();
        await player.loadVideo(videos[++pos % 2]);
        await player.play();
      };
  ```
  into 
  ```js
      nextButton.onclick = async function () {
        await player.pause();
        // await player.loadVideo(videos[++pos % 2]);
        await player.play();
      };
  ```
 then no problem &mdash; the current video pauses and continues to play just fine.

adding `await player.unload()` before `.loadVideo()` call does not help either.

It all looks like attempt to reload a video does not correctly clean-up after the previous video and related state, and then depending on your luck, and what event listeners were connected to the player before, it either fails to start playback of the new video, or fails to load it with that 403 error.

```html
<html>
  <body>
    <div id="container"></div>
    <button id="play">Play</button>
    <button id="next">Next</button>
    <script src="https://player.vimeo.com/api/player.js"></script>
    <script>
      let pos = 0;
      const videos = [
        'https://player.vimeo.com/video/76979871?h=8272103f6e',
        'https://player.vimeo.com/video/1091012065',
      ];
      const container = document.querySelector('#container');
      const playButton = document.querySelector('#play');
      const nextButton = document.querySelector('#next');
      const player = new Vimeo.Player(container, {
        controls: false,
        keyboard: false,
        url: videos[0],
      });
      player.on('playing', () => {
        console.log('PLAYING');
      });
      player.on('timeupdate', () => {
        console.log('TIME UPDATE');
      });
      playButton.onclick = async function () {
        await player.play();
      };
      nextButton.onclick = async function () {
        await player.pause();
        await player.loadVideo(videos[++pos % 2]);
        await player.play();
      };
    </script>
  </body>
</html>
```

**Comment by rkrishnan8594** [comment]
Thanks for reporting this issue, @birdofpreyru - it should now be fixed. Let me know if you're still able to reproduce it.
