### ISSUE TITLE
Typo in docs code example

### ISSUE THREAD

**Issue by bderblatter** [vimeo/player.js#410]
### Expected Behavior

All examples should be syntactically correct

### Actual Behavior

The last example on [this page](https://developer.vimeo.com/player/sdk/basics) has a missing `"`

Currently:

```
<div data-vimeo-url="{video02_url} data-vimeo-width="{video02_width}" id="{video02_name}"></div>
```

Should be:
```
<div data-vimeo-url="{video02_url}" data-vimeo-width="{video02_width}" id="{video02_name}"></div>
```

### Steps to Reproduce

1. Go to [this page](https://developer.vimeo.com/player/sdk/basics)
2. Scroll down

Submitting here because that's where the "Contact Us" link points

**Comment by fisherinnovation** [comment]
Thanks for reporting! We will work to correct this ASAP.

**Comment by danaburger** [comment]
This should now be resolved- https://developer.vimeo.com/player/sdk/basics 

Thanks again for bringing this to our attention!
