### ISSUE TITLE
Help with API

### ISSUE THREAD

**Issue by christianrockbryan** [vimeo/player.js#413]
Hello.  I am working for a client who has a pro membership.  

I cannot get the videos I am playing using the API to not loop and play the next one.

This section of code is suppose to loop through a set of videos.  When the "ended" event is launched, then the next video is suppose to play.  The "ended" event is not being called.

You can see this in action here:

   http://boomboom.cart32.com/cards.php?catid=109&catname=New&action=playall

Please let me know what I am doing wrong on this.

Thanks!
Bryan

<script language="javascript">

iCurrentVideo=0;
//create array of videos to play
ArrPlayAll=[];
ArrPlayAll.push('310882602');
ArrPlayAll.push('321862570');
ArrPlayAll.push('325780311');
ArrPlayAll.push('300395198');
ArrPlayAll.push('300534096');
ArrPlayAll.push('300363905');

//set up initial options
var options = {
   id: '310882602',
   byline: false,
   title: false,
   autoplay: true,
   loop: false
}

//open model and play initial video
HTML='<div id="divplayall" class="embed-responsive embed-responsive-16by9"></div>';
jQuery('#ModalVideoBody').html(sHTML);
player = new Vimeo.Player('divplayall', options);
jQuery('#ModalVideo').modal({});

//setup action to do when video play is ended
player.on('ended', function(e) {
   alert('in ended.  Getting ready to pay next video');
   PlayNextVideo();
});

function PlayNextVideo() {
   iCurrentVideo++;
   if (ArrPlayAll.length==iCurrentVideo) iCurrentVideo=0;  
      alert('in PlayNextVideo.  iCurrentVideo='+iCurrentVideo);
      player.loadVideo(ArrPlayAll[iCurrentVideo]).then(function(id) {
      player.play();  //play from beginning
   });
}

</script>

**Comment by luwes** [comment]
This was resolved internally, thanks for reporting!
