### ISSUE TITLE
Getting download link from API call

### ISSUE THREAD

**Issue by christianrockbryan** [vimeo/player.js#414]
I am trying to use the Vimeo API to get the download link for a video as well as maybe use an HTML5 player to play the video instead of the iframe.

I am calling this URL:
 
   https://api.vimeo.com/me/videos/310882602

I have authenticated and I get the attached returned JSON message.

Do I need to password different parameters or something different to get the download link or video link to use in a HTML5 video player?
[vimeo-json-return.txt](https://github.com/vimeo/player.js/files/3095448/vimeo-json-return.txt)

**Comment by luwes** [comment]
@christianrockbryan could you ask this question in one of the API repo's?
https://github.com/vimeo

The devs on there will better be able to help you out.

Or

https://stackoverflow.com/questions/tagged/vimeo

Thanks

**Comment by fercunha** [comment]
Hey @christianrockbryan, any luck with that?

I have the issue and the documentation is not clear about direct links.
