### ISSUE TITLE
on pause function

### ISSUE THREAD

**Issue by woodhall2k** [vimeo/player.js#417]
### Expected Behavior

I have been using the following script to create an event when the pause button is clicked.
I am using it specifically to add a class to the div that contains the player when the pause button is clicked.

I have made a stripped down version that should show a message in the console saying 'paused the video' but this does not give the expected/ previously working behavior 

    var iframe = document.querySelector('iframe');
    var player = new Vimeo.Player(iframe);

    player.on('pause', function() {
        console.log('paused the video!');
    });

This was working perfectly until 23/04/2019

### Actual Behavior
The function does not run and as a result the console does not show 'paused the video!' when the pause button is clicked.

### Steps to Reproduce

I have made a Codepen that demonstrates this,
I have also included the play event which works fine and the pause event that doesn't work at all

https://codepen.io/meshviz/pen/vMQvjX

**Comment by pratikt4f** [comment]
I also notice that issue from last 2 days.

**Comment by SemanticMikeG** [comment]
Same issue for me, on across several sites we develop.

**Comment by luwes** [comment]
We're actively working on resolving this asap. 
We'll keep you updated, this should be resolved before noon.

**Comment by luwes** [comment]
This should be resolved! Please let us know if the issue persists on your end. 
Thank you
