### ISSUE TITLE
how to have vimeo video pick up from where a viewer leaves off when the page is reloaded

### ISSUE THREAD

**Issue by milbo13** [vimeo/player.js#418]
Is it possible to edit the embed code or something else so that when a viewer of an embedded video on our site leaves the page and then returns at a later time they can pickup viewing where they left off (v. starting over)?  Thanks,

**Comment by luwes** [comment]
yes, you can use the `#t` hash parameter to seek to a time before playback.
for example `https://player.vimeo.com/video/76979871#t=20`

note that if you want `autoplay` the query parameter always comes before the hash parameter.

`https://player.vimeo.com/video/76979871?autoplay=1&muted=1#t=20`

Hope this helps.

**Comment by milbo13** [comment]
Not sure why closed when I have a q - are you saying if I watch a video, close my browser and come back a few days later I will be able to pick up where I left off?  Or are you saying it will seek, in this case, 20 mins in, with that code so it sets to pick up at a specific time v. starting where I left off?  Thanks,

**Comment by luwes** [comment]
@milbo13 sorry, I imagined you would have sufficient info to develop this behavior.

at the moment there is no resume functionality build in the Vimeo player embeds.

this would require some work on your end, storing the last viewed time in localStorage for example by listening to the timeupdate event and with this API automatically seek to that time when the user returns.

**Comment by MiBiT-Discuss** [comment]
@luwes You mean there's no resume in any Vimeo player, right?

**Comment by mightyx** [comment]
I am also looking for this feature. I think it is very basic and should be included.

There is a possibility if you use wordpress, you can use the FV Player plugin, but for vimeo it is a premium feature.l

**Comment by fisherinnovation** [comment]
@MiBiT-Discuss Correct, at the moment there is no resume logic for Vimeo Player embeds.

**Comment by MiBiT-Discuss** [comment]
> @MiBiT-Discuss Correct, at the moment there is no resume logic for Vimeo Player embeds.

My point was there doesn't seem to be any resume logic period in Vimeo. Unless you manually build something with URLs, but I haven't seen any such solutions.

**Comment by bjmgeek** [comment]
I also would like to request the feature of picking up where I left off.  If my browser crashes, or I reboot my computer, it should just seek to the spot in the video where I was.  I'm accessing a password-protected video, and when I go to the page after a browser crash or computer reboot, it doesn't ask me for the password.  So, it must remember at least some data about me in relationship to the video I'm watching.
