### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by oguilleux** [vimeo/player.js#420]
I'm initialising a player like so :

```
// HTML
<iframe
  class="home__hero__video"
  src="https://player.vimeo.com/video/MYVIDEOIDHERE?background=1&autoplay=0&loop=1&byline=0&title=0"
  frameborder="0"
  webkitallowfullscreen
  mozallowfullscreen
  allowfullscreen>
</iframe>

// JS - webpack + babel
import Player from '@vimeo/player';
class HomeFn {
  constructor() {
    this.initVideo();
  }

  initVideo() {
    const player = new Player(document.querySelector('.home__hero__video'));
    player.on('loaded', () => {
      player.play();
    });
  }
}
export default HomeFn;
```

And I get this warning in my console :
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://fresnel.vimeocdn.com/add/player-stats?session-id=6382900865a72ab0f6813cecc33d0ebc654a744d1556634198 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

How can I solve this console warning ? Thanks for your help.

**Comment by luwes** [comment]
hi @oguilleux, thanks for reporting. 

we're currently working to hide this warning however it shouldn't affect website behavior, it can safely be ignored for the time being.

For more info see https://www.chromium.org/Home/chromium-security/corb-for-developers.

**Comment by oguilleux** [comment]
Ok, thanks for your quick feedback.

**Comment by munyah** [comment]
Hi @oguilleux, 

This is actually breaking website behaviour on  my sites; is there a patch or something that one could use in the meantime?

**Comment by mmjjb** [comment]
Seems to cause vimeo player to stop playing on some of my sites

**Comment by jstortz** [comment]
> Hi guys,
> 
> This is actually breaking website behaviour on my sites; is there a patch or something that one could use in the meantime?

how is it breaking the site? Asking as I'm curious. I get the warning, but it doesn't seem to be breaking anything...but your comment makes me wonder if I'm missing something.

**Comment by munyah** [comment]
@jstortz My site makes use of a carousel that contains multiple vimeo videos. For every instance that is blocked CORB; the body response is empty & as such will not load the videos altogether. 

The CORB documentation quoted above by @luwes does state that CORB may replace the body with an empty response in some scenarios.

**Comment by anchietajunior** [comment]
Hello guys, 

In my app (staging and production) the videos just stoped playing when i get this warning, localhost is working fine, any ideas?

**Comment by mozzi** [comment]
Same here. On one of the company computers video just stopped working. chrome version 74.0.3729.157. Tried on multiple other computers with same chrome version - wasn't able to reproduce.

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/906026/58029424-cff8ca80-7b1c-11e9-981d-24f1ba9cf77e.png)
</details>

**Comment by luwes** [comment]
Could you please send the OS/browser and the link of affected videos?

It really shouldn't affect playback at all because it's only blocking a request the analytics.

**Comment by luwes** [comment]
Oh I see it's in the screenshot :) for you @mozzi. Will check it out.

**Comment by mozzi** [comment]
sorry, my mistake. on this website we use default vimeo player, not player.js. i've updated comment.

**Comment by nikolovag** [comment]
I also get this warning in the console and it actually breaks my website. Can't load facebook videos and not supported MIME type is text/html

**Comment by AbeSchor916** [comment]
why is this closed, it simply doesn't work?

**Comment by iit07ajay** [comment]
I am able to read document object of main frame content but not able read child frame content through Chrome extension, Can anyone help me?
<img width="938" alt="Cros" src="https://user-images.githubusercontent.com/103763215/163771312-97ebc0ab-0de2-4b7a-af56-9ae3631af56e.PNG">

**Comment by rkrishnan8594** [comment]
@iit07ajay Can you file a separate issue for this if it's related to the player.js library?
