### ISSUE TITLE
Disable buffering when loading new video into player...

### ISSUE THREAD

**Issue by seimic** [vimeo/player.js#427]
Not an issue but a question how to disable the immediate buffering of videos when new video-id is set into player. Any chance to achive this?

### Expected Behavior

Buffering/Loading of video chunks after the user hit the play button or programmatically via call to an api. 
Preview picture with controls only at beginning. Minimize traffic before play button is pressed.

### Actual Behavior

Immediately after a new video is set the player starts buffering and causes unnecessary traffic (especially on mobile devices).

### Steps to Reproduce

Call of the player.loadVideo(newId) function on an embedded player.

Best regards,
Michael

**Comment by luwes** [comment]
this is not an issue anymore I believe. let me know if otherwise. thanks.
