### ISSUE TITLE
how to maintain the with of my video (iframe) auto to be always fitting my box (project.x4).

### ISSUE THREAD

**Issue by TasioC** [vimeo/player.js#428]
how to maintain the with of my video (iframe) auto to be always fitting my box (project.x4).

https://codepen.io/ta_io/pen/KEbQxo

thnaks :)

**Comment by fisherinnovation** [comment]
I recommend reviewing the 'Responsive Embed Code' option which you can learn more about at https://help.vimeo.com/hc/en-us/articles/360000710167-Adjusting-the-size-of-the-embedded-player
