### ISSUE TITLE
Possible to ignore isVimeoUrl check?

### ISSUE THREAD

**Issue by MartinMystikJonas** [vimeo/player.js#429]
For some security and technical reasons we do not embed our private vimoe videos with direct link to video but we user url to our service which redirects to vimeo url. But we are unable to use this plugin to control video plaing.

### Expected Behavior

Way to ignore or redefine isVimeOUrl check of embed src.

### Actual Behavior

If URL not directly linkinf to Vimou is used then player throwws error "The player element passed isn’t a Vimeo embed."

**Comment by SebastianAwatramani** [comment]
We also ran into a problem with this as one of the domains that uses a client's service is a proxy that rewrites all URLs.  The ability to bypass this check would be appreciated.

**Comment by luwes** [comment]
thanks for the feedback. this can be solved by forking this repo and making the change in the source code, re-build and host the custom resulting bundle on your own CDN or website. in this repo the `isVimeoUrl` check will be kept as is for security. hope you understand.

**Comment by MartinMystikJonas** [comment]
Could you explain how it could cause security concerns if this check would be optionaly disabled or if it would be possible to change base url?

Forking is possible but then we would have to keep our fork up to date and it would be time consuming.
