### ISSUE TITLE
Real Weird Volume Event Listener

### ISSUE THREAD

**Issue by pxwee5** [vimeo/player.js#430]
![image](https://user-images.githubusercontent.com/14123790/57741675-0e078000-7712-11e9-9ede-4e03c7807493.png)

I put my player on `window.testPlayer` and started playing with volumes with only 1 volume listener. This is what I got. 

Can someone else replicate this issue?

This is on iOS. And this is the code that fixes it.

```
      this.player.play().catch(() => {
        // Restart with zero volume
        this.player.getPaused().then(paused => {
          if (paused) {
            this.player.setVolume(0).then(() => {
              this.player.play();
              this.player.setVolume(0); // Fixes iOS Safari quirks where volume was automatically set to 1 after the first setVolume() above.
            });
          }
        });
      });
```

**Comment by luwes** [comment]
@pxwee5 iOS is a special case in regard to volume, only `0` and `1` is possible.
Basically muting and unmuting because of the hardware volume controls on iOS.

What exactly is the problem?

**Comment by pxwee5** [comment]
If you refer to the screenshot, I set the volume to 0, but it automatically resets to 1. Bear in mind that the player has been muted, but the value returned is 1.

**Comment by luwes** [comment]
this issue has been resolved in the mean time. use `setMuted()` for mobile devices
