### ISSUE TITLE
Help with modifying controls css

### ISSUE THREAD

**Issue by daniellehoo** [vimeo/player.js#436]
### Expected Behavior
I am attempting to display a video that occupies the entire 50% of the left-most screen space (with 100% height). I have replicated the dimensions from [this CodePen](https://codepen.io/abennington/pen/ZONqqv).

I would like to fix the controls so that they appear on the visible portion of the video, but I cannot seem to place them or manipulate the css accordingly.

also, would only like video to play if in fullscreen mode.

### Actual Behavior

The controls are currently off the screen and cannot be toggled from within the view space.

### Steps to Reproduce
CodePen here:
https://codepen.io/daniellehoo/pen/VOQOVG

**Comment by luwes** [comment]
@daniellehoo thanks for your feedback. sorry to say this is not possible with the iframe Vimeo player. you can't change the CSS in an iframe from the parent.

the best you can do is toggle `controls` off and create your own custom controls which would be easily styled and laid on top of the Vimeo player.

hope this helps a bit.
