### ISSUE TITLE
loadVideo issue on IE11 for hidden videos

### ISSUE THREAD

**Issue by rnowak8** [vimeo/player.js#439]
On IE11 loadVideo is properly loading the new video, but call reject callback instead of success.
Only when currently loaded video is hidden from vimeo.com and autoplay is enabled. Sometimes I see 'Unhandled video privacy' overlay, so probably this is a problem, I think.

### Expected Behavior
Method loadVideo should call the success callback after successful load new video.

### Actual Behavior
The method is calling failure callback, but the video is successful loaded.

### Steps to Reproduce
Failed on IE11 in Windows 10, works well on Chrome.
http://jsfiddle.net/rnowak8/7cka3g4L/13/

**Comment by bdougherty** [comment]
We no longer officially support Internet Explorer.
