### ISSUE TITLE
Setting the current time too close to the end of the video will cause the player to become unresponsive.

### ISSUE THREAD

**Issue by brainkim** [vimeo/player.js#44]
### Expected Behavior
When you set the current time using `player.setCurrentTime` to the end or close to the end, it should set the video status to ended and fire timeupdate and ended events.

### Actual Behavior
The player seems to stall without firing any meaningful events, and further setCurrentTime calls don't do anything, until the user interacts with the player again.

### Steps to Reproduce
Go to https://player.vimeo.com/api/demo. Set the current time to 61.86 (or whatever the video's actual duration is). The video will stall without firing any meaningful events.

**Comment by adnanrahic** [comment]
I had the same issue today. Leaving a comment in hopes it'll be fixed.

**Comment by brainkim** [comment]
@adnanrahic I've just been setting the current time to `Math.min(video.duration - 1, targetTime)` instead. Haven't really noticed a difference cuz the video immediately ends anyways.

**Comment by adnanrahic** [comment]
@brainkim Very ingenuitive solution indeed. I'll surely use that for my own purposes. But I can relate to the hacks, it has been a struggle implementing this into an angular app. :D

**Comment by LetterAfterZ** [comment]
Seems like it might be similar to this issue: https://github.com/vimeo/player.js/issues/34

**Comment by bdougherty** [comment]
Yeah, I believe this has the same root issue as #34, so closing in favor of that one.
