### ISSUE TITLE
IE11 'object doesn't support property or method 'isNaN''

### ISSUE THREAD

**Issue by mitrovicsinisaa** [vimeo/player.js#441]
### Actual Behavior
There is the error in console for IE 11:

Doesn't work in IE11  - Object doesn't support property or method 'isNan'.

### Steps to Reproduce
Just run video in IE11 (Document mode 11 (Default))

### Analysis
This happens on IE11 with  Document mode 11 (Default), but not on IE11 with Document mode Edge. Problem is not in this player.js, but in included one `https://f.vimeocdn.com/p/3.11.27/js/player.js` 
Issue is caused by condition 
`(t=parseInt(t,10),Number.isNaN(t))` which is not IE11 friendly. This is only place where Number.isNaN is used. 
There are 31 occurrences of `isNan`, so maybe this can be converted?

**Comment by marko-neopix** [comment]
I can confirm that the current player.js isn't IE 11 compatible.

Here is a reproducible case:

**Comment by ilicmarko** [comment]
I can confirm that the current player.js isn't IE 11 compatible.

Here is a reproducible case:
https://codepen.io/rema/pen/xoboOm

Play the video, then stop it and try to play it again... I won't work. Other browsers work without a problem.

**Note: You can't open Codepen on IE11, here is a debug mode link:**
https://s.codepen.io/rema/debug/xoboOm/YvkgOnEdNQpk

**Comment by kevinramharak** [comment]
Is this the correct place to report this error and check its status? The [Help center](https://vimeo.zendesk.com/hc/en-us/articles/224979828-I-ve-encountered-an-error-or-unexpected-behavior-What-should-I-do-) is not very helpfull where to report this as it just sends me to the contact page (https://vimeo.com/help/contact). There is no option to ask/report developer/API related questions/issues.

**Comment by rebecca-sich** [comment]
Thank you all for bringing this to our attention. We are working to fix it immediately.

**Comment by luwes** [comment]
This should be resolved! Thanks for reporting.

**Comment by kevinramharak** [comment]
@luwes @rebecca-sich Thank you for the quick response. Just to verify: the correct approach in reporting these kind of errors (not in this repo, but in the embed API of Vimeo that uses this repository) is this repository?

**Comment by honeyamin** [comment]
my you use Number.isNAN
prefer to be isNaN
