### ISSUE TITLE
Does the Player SDK work fully in nested iframes?

### ISSUE THREAD

**Issue by mdonadio** [vimeo/player.js#443]
The short question is whether the Player SDK works fully in nested iframes?

The situation I have is that I have a iframe on my site

`<iframe src="/oembed/1234"></iframe>`

"/oembed/1234" will do the OEmbed JSON request to Vimeo and then use the HTML from response to build the contents of that `<iframe>`.  So, the HTML on the page ends up like

`<iframe src="/oembed/1234"><iframe src="https://player.vimeo.com/video/1234?app_id=5678"></iframe></iframe>`

This all works great for playing the video.  Yay.

I can locate the inner `<iframe>` in the DOM, and attach a `Vimeo.Player()` to it,  eg

```
var video = $('iframe.oembed').contents().find('iframe').get(0);
var player = new Vimeo.Player(video);
```
I can attach the `.ready()` to it, too

```
player.ready().then(function() {
  console.log('### ready');
 }).catch(function(error) {
  console.error('### ready', error);
});
```

and the promise is fulfilled, and I get my console log.  However, if I attach any other function to it, eg

```
player.getVideoId().then(function(id) {
  console.log('### player.getVideoId()', id);
}).catch(function(error) {
  console.error('### player.getVideoId()', error);
});
```

the promise is never fulfilled, and I don't get an error, either.  I can tell things are running properly and not silent erroring, with code like:

```
console.log('### BEFORE');

player.ready().then(function() {
  console.log('### player.ready()');
 }).catch(function(error) {
  console.error('### player.ready()', error);
});

player.getVideoId().then(function(id) {
  console.log('###  player.getVideoId()', id);
}).catch(function(error) {
  console.error('###  player.getVideoId()', error);
});

console.log('### AFTER');
```

The output looks like

```
### BEFORE
### AFTER
### player.ready()
```

IOW, the code is running, and the the promise from the `.ready()` fires after the main code, but nothing from the `player.getVideoId()` call.

If I debug things, and lift the player out to an iframe directly in the main body, then I can find the iframe and the player.js API works as usual.

So, I am at a loss as to what can cause a problem, other than nested iframes here.  There are no errors in the Chrome console, but tracing out the API calls in the network log hasn't been fruitful.

I'll post a minimal example if I can.

**Comment by mdonadio** [comment]
OK, this works (look at the console output), https://jsfiddle.net/mdonadio/xu2trd6m/

This simulates what the oembed will do, and then look at the console, https://jsfiddle.net/mdonadio/7mL14tc6/

**Comment by luwes** [comment]
@mdonadio are you sure it doesn't work?

adding the example to any service like jsfiddle, codepen, etc. makes it already be in a nested iframe.

**Comment by mdonadio** [comment]
@luwes The fiddles in the comment above yours are still active.  In the first one, the `console.log()` shows the activity.  The second one shows the `ready()` firing so the code is finding the player, but the `getVideoId()` not fire.

**Comment by amjad1233** [comment]
I am having the same issue. So Subscribing.

**Comment by amjad1233** [comment]
@luwes This sounds like a bug.

**Comment by luwes** [comment]
<img width="948" alt="Screen Shot 2020-08-05 at 8 14 21 AM" src="https://user-images.githubusercontent.com/360826/89411612-b462eb00-d6f3-11ea-9cd4-be9c29971f2c.png">

it's not a bug I believe, the window in which you embed the player (iframe) will receive the post messages, in the screenshot above it's the `.oembed` iframe. But that window does not have any API script, in turn doesn't have a `window.addEventListener('message', ...` handler.

The solution is to add the player API script tag in the `.oembed` iframe.
Then there is a communication pipeline from player.vimeo.com <-> `.oembed` window.

It's up to the developer to create a pipeline from the parent window <-> `.oembed` window.
In this case the parent window is https://fiddle.jshell.net/mdonadio/7mL14tc6/show/?editor_console=

If the 2 upper windows are cross-origin you'll have to resort to using `postMessage`,
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

If they're on the same domain it should be pretty easy and you can call a function or access a global player variable like `document.getElementById('targetFrame').contentWindow.targetFunction();`

**Comment by amjad1233** [comment]
Hi @luwes,

I really appreciate your prompt response. 

I tried the approach above but still seems to give me "Promise<Pending>" in return when I try to run any function.

For example player.play() -> Returns Pending Promise. And With the similar logic YouTube is working fine. 

Here is the structure if that helps 

<img width="1311" alt="Screenshot 2020-08-06 at 12 38 15@2x" src="https://user-images.githubusercontent.com/661146/89484539-14d05600-d7e2-11ea-942d-751c8851a78e.png">

`const player = new Player(childFrame);
    player.on('play', function() => {
      console.log('I am playing');
    });`

Where the childFrame is the embedded player.(Vimeo iFrame)

Output of console.log(childFrame.play())

<img width="791" alt="Screenshot 2020-08-06 at 12 43 35@2x" src="https://user-images.githubusercontent.com/661146/89484749-7c86a100-d7e2-11ea-9962-853dc5b76ede.png">

FYI Could not access the link you sent in previous comment.

**Comment by luwes** [comment]
in which `window` is that script called?

`const player = new Player(childFrame); player.on('play', function() => { console.log('I am playing'); });`

**Comment by luwes** [comment]
it should be in the same window as where the player.js script is loaded.

it's possible Youtube is broadcasting the messages through the parents, like passing them through. that's not something we have implemented.
