### ISSUE TITLE
Embedded Player // Videos with captions load forever on iPhone/iPad

### ISSUE THREAD

**Issue by MBWebTechMariusz** [vimeo/player.js#445]
### Expected Behavior
Displaying a video with captions should load properly on iPhone/iPad.

### Actual Behavior
When visiting a video which has subtitles/captions, the whole site blocks and is sometimes unresponsive. The video doesn't load at all.
The "captions"-Button in the controls is not visible.
After a while (1-2m), the caption-Button is visible and the video loads/plays correctly.

### Steps to Reproduce
- Use Chrome/Firefox in emulated iPhone X Mode
- GoTo https://vimeo.com/76979871
![image](https://user-images.githubusercontent.com/37508162/59796573-1b4df680-92de-11e9-8c45-76f541a25ad8.png)

### Further Analysis
I've already tried to debug this. Here are some further remarks:
- Only videos with captions are affected
- It's only an issue on iPhone/iPad
- It popped up recently. I am sure that this worked fine a while ago, but I'm not quite sure when this broke
- When I debug this with firefox, and stop the execution, it always pinpoints me to some point where I see something with iPhone/iPad, but I can't dig any further what's happening

**Comment by luwes** [comment]
Great find @MBWebTechMariusz! This regex bug should be resolved.
