### ISSUE TITLE
Issues with 'Ended' event

### ISSUE THREAD

**Issue by phil-the-dev** [vimeo/player.js#446]
### Expected Behavior

When a video gets to the end, the 'end' event fires.

### Actual Behavior

Video doesn't fire end, loops to the back to the beginning to the video

### Description

Hello,

I have an app that's been running for a few months without a hitch, I have a list of vimeo ids that I play sequentially. On the 'ended' event, I set the video id to the next one, and move on. Working perfectly until today where it seems to be stuck on a single video and looping even though I've explicitly made the loop option false for the vimeo player.

The only other thing that I would say isn't "typical" is that I'm using the video as a background video because I didn't want the seek bar on the screen, but I don't think it would have changed how it worked.

I've bound the function that moves to next video it would normally trigger to a keypress, which works, so the 'ended' event seems to be the issue in question.

Were there any changes that would cause a previously non-looping video to be looping as of today?

Thanks,
-Phil

**Comment by JohnnyWalkerDesign** [comment]
Looks like #200 has reverted

**Comment by casevanarkel** [comment]
Seeing this also. Broke our site.

**Comment by fisherinnovation** [comment]
See https://github.com/vimeo/player.js/issues/447#issuecomment-504588572

By the sounds of you issue, switching `background=1` to `controls=0` will correct this issue.

Apologises for the inconvience with this change! We had never intended to allow background videos to be overridden but that wasn't conditioned properly on our end. With the advent of the `controls` embed param we made that correction.

**Comment by phil-the-dev** [comment]
So I have some questions about this, and being new to open source stuff, apologies if I'm clueless to this or if this is not the correct place to ask.

Why does the repo's latest release/commit say May, yet the player code was changed or was it something that wasn't the player's code base that changed? I wish there was a way to version calls to endpoints/urls or notices for these kinds of changes, is there something I should be subscribed to for these types of changes? I feel a little burned by this change and I'm trying to find a way to prevent such a change to impact my app.
