### ISSUE TITLE
Loop: false not respected when background: true

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [vimeo/player.js#447]
### Expected Behavior
Setting loop: false have an effect regardless of background: true

### Actual Behavior
It loops.

### Steps to Reproduce
https://jsfiddle.net/p7daL424/

(In other words #200 has reverted.)

**Comment by phil-the-dev** [comment]
oh hey, that's the same issue I'm having! My ticket is #446

**Comment by danaburger** [comment]
@JohnnyWalkerDesign @phil-the-dev The background parameter will always set your video to loop by default. 

We did previously allow loop to work for background videos, however now this behavior has been reverted in favor of the `controls=0` embed parameter. The controls parameter will hide all player controls while offering separate control over looping and muting.

**Comment by JohnnyWalkerDesign** [comment]
Well it would be great if the SDK documentation noted this sudden change in behaviour, and indeed that a `controls` option existed at all: https://developer.vimeo.com/player/sdk/embed

**Comment by danaburger** [comment]
Thank you! The controls parameter is in the progress of being added to our main SDK docs, but for now, this information can be referenced in our help center here- https://vimeo.zendesk.com/hc/en-us/articles/360001494447-Using-Player-Parameters.
