### ISSUE TITLE
How can I add Custom Button to Player

### ISSUE THREAD

**Issue by azadhussain16** [vimeo/player.js#452]
### Expected Behavior
I want to add an additional custom button to the player on click of that button I will perform some task from js. 
Basically, I want to provide bookmarking power to users like if a user wants to bookmark at 3:15 he can bookmark by clicking the custom button which will lead to server API call for saving 3.15 to DB server 

### Actual Behavior
How can I achive it 

### Steps to Reproduce
Something like  given image 

![Screenshot from 2019-07-02 07-32-48](https://user-images.githubusercontent.com/47494673/60499928-0195b180-9cd7-11e9-821a-f7116de26933.png)

**Comment by luwes** [comment]
Thanks for your question @azadhussain16. 

The `player.setCurrentTime()` is needed for that one. 
https://github.com/vimeo/player.js#setcurrenttimeseconds-number-promisenumber-rangeerrorerror

We can't help you with developing your application however. Try the forums on StackOverflow, you might have more help there. This repo is only for reporting bugs and issues.
