### ISSUE TITLE
SetTextTrack

### ISSUE THREAD

**Issue by svinkle** [vimeo/player.js#46]
Hi,

I see the method to `getTextTracks()`, but there is no `setTextTrack()`. How do you set a track after you make a selection? I'm just building out a custom form with player controls, and tracks will be radio controls.

Thanks.

**Comment by bdougherty** [comment]
Hi, Scott. You're looking for [`enableTextTrack()`](https://github.com/vimeo/player.js#enabletexttracklanguage-string-kind-string-promiseobject-invalidtracklanguageerrorinvalidtrackerrorerror). We did it that way to potentially allow for multiple tracks to be enabled at the same time in the future.

**Comment by svinkle** [comment]
Oh wow, didn't see that. Thanks, @bdougherty.
