### ISSUE TITLE
feature request: show controls on hover, optional logo

### ISSUE THREAD

**Issue by cheryly279** [vimeo/player.js#460]
Hi I'm looking for a way to play my video, but only show the controls when the user hovers over the video (and subsequently re-hides when the user moves the mouse out of the area). This doesn't seem to be possible without building our own controls, which is possible but of course time consuming. Is there some current solution in the API that I am missing?

Also, we have our account set up to show a logo on upload videos but is it possible to have that be something we can remove from the controls when we play videos via the API? I also could not find an option for this.

**Comment by fisherinnovation** [comment]
The controls visiblity feature you are requesting should be what occurs in all cases. Can you provide a link to an example where you are not seeing this?

Can you also provide a link to where your embedded player is not showing your custom logo?

**Comment by cheryly279** [comment]
I see the controls feature, but there is no setControls where I can set it to false on mouse out and true on mouse over.

We are still working on the embedded player but it _is_ showing the custom logo, we have some cases where we don't want the custom logo.

**Comment by cheryly279** [comment]
Oh, I see the controls do fade out, but it takes a few seconds. I'm so impatient I must have kept moving the mouse over again before I could see the controls fade out.

**Comment by fisherinnovation** [comment]
Ah apologies, I misread you question - custom logos are set across all embeds of your video and can not be modified for a specific embed. I do see good reason why that would be helpful though. I will take it back to our product team and discuss that ideas more.

Thanks,

**Comment by Keerthinir3** [comment]
@cheryly279  @fisherinnovation  
Player control shows only on hover is there any possible way to show controls all the time
