### ISSUE TITLE
Show white screen while playing video.

### ISSUE THREAD

**Issue by tarun57** [vimeo/player.js#463]
I am using ionic 4 and vimeo player.
In which video playing properly on some devices but on  android emulator with version 6 video is playing but  not show anything only display white screen and hear audio.

**Comment by fisherinnovation** [comment]
Do you notice the issue when using Andord v6 on a non-emulated setup?

**Comment by tarun57** [comment]
yes 
Issue on huawei p8 android device.

**Comment by luwes** [comment]
@tarun57 could you provide a test page? 
is this also the case on https://player.vimeo.com/api/demo ?

**Comment by DmitriiMelnikOnix** [comment]
I am using React Native and show Vimeo with WebView
Users with Samsung S10+ report the same bug

**Comment by DmitriiMelnikOnix** [comment]
I found a device (Samsung S8) on which I was able to reproduce the bug, it looks like a bug in chrome
Error logs matched
I'm waiting for the update of the chrome version to 85
If using Chrome Canary for WebView, the error cannot be reproduced
[https://bugs.chromium.org/p/chromium/issues/detail?id=1109016&q=ERROR%3Ashared_image_stub.cc%28169%29&can=2]link to chrome issues)

**Comment by luwes** [comment]
thanks for providing the link to the Chrome issue @DmitriiMelnikOnix. very helpful.

will close the issue here as it's a browser issue.
