### ISSUE TITLE
Support for IE11

### ISSUE THREAD

**Issue by alokjain-lucky** [vimeo/player.js#468]
Video is not working in IE11.

The demo page is also not working for me (screenshot attached)
![picturemessage_z5fij0sa 00e](https://user-images.githubusercontent.com/5526402/62613278-c5cdb780-b926-11e9-845a-aeda9e3589ac.png)

Website URL (https://www2.nufarm.com/de/) where I am facing the issue. Video is working in all browsers except IE11. (Video is added as a background of the page header, at the top of the page.)

**Comment by captiva-megan** [comment]
Bump. I am also seeing this issue. I attempted to get around it by faking the look of the background video using other embed parameters. Autoplay appears to be the hangup. Any embed with autoplay on it never plays in IE11.

**Comment by alokjain-lucky** [comment]
I was able to fix this by using `play` method in JavaScript. 

```javascript
var $iframe = $homeVideo.find('iframe');
if($iframe.length) {
      var player = new Vimeo.Player($iframe[0]);
      player.play();
}
```
