### ISSUE TITLE
Multiple events with the on() method

### ISSUE THREAD

**Issue by migueldemoura** [vimeo/player.js#47]
### Expected Behavior

Being able to send multiple events to the on() function to reduce copy pasted code.
### Actual Behavior

Unable to do it as the function apparently only supports one event as argument.
### Steps to Reproduce

Asuming jQuery & player.js:

``` javascript
var player = new Vimeo.Player($('#video'));

// Works
player.on('play', function() {
    // doSomething
});
player.on('pause', function() {
    // doSomething
});

// What I'd like to have
// like jQuery
player.on('play pause', function() {
    // doSomething
});
// as an array
player.on(['play', 'pause'], function() {
    // doSomething
});
```

My naive approach to adding this functionality (with an array) would be to modify the method as follows:

``` javascript
    /**
     * Add an event listener for the specified event(s). Will call the
     * callback with a single parameter, `data`, that contains the data for
     * that/those event(s).
     *
     * @author Brad Dougherty <brad@vimeo.com>
     * @param {array} eventsName An array containing the name of the event(s).
     * @param {function(*)} callback The function to call when the event(s) fire(s).
     * @return {void}
     */
    on(eventsName, callback) {
        if (!eventsName) {
            throw new TypeError('You must pass an event name.');
        }

        if (!callback) {
            throw new TypeError('You must pass a callback function.');
        }

        if (typeof callback !== 'function') {
            throw new TypeError('The callback must be a function.');
        }

        for (var i; i < eventsName.length; i++) {
            const callbacks = getCallbacks(this, `event:${eventsName[i]}`);
            if (callbacks.length === 0) {
                this.callMethod('addEventListener', eventsName[i]).catch(() => {
                    // Ignore the error. There will be an error event fired that
                    // will trigger the error callback if they are listening.
                });
            }
            storeCallback(this, `event:${eventsName[i]}`, callback);
        }
    }
```

Disclaimer: I didn't test this nor check how the other functions called by this one work.

**Comment by bdougherty** [comment]
Are there any other events besides play/pause that you'd want to have a common listener for? I'm open to a PR that adds the array syntax, but I'm not sure how useful it is overall when you could do something like:

```js

function eventHandler(data) {
    doSomething();
}

player.on('play', eventHandler);
player.on('pause', eventHandler);
```

without too much trouble.

**Comment by bdougherty** [comment]
I suppose we could return `this` so you could chain as well: `player.on('play', eventHandler).on('pause', eventHandler);`. Not sure why it doesn't do that now actually.

**Comment by migueldemoura** [comment]
I'm currently only using `play`, `pause` and `ended`.
I agree that this shouldn't be marked as high priority, but I still believe it is a useful enhancement. I can submit a pull request for the `return this` if you want, but I'd need guidance to do the same for the array syntax to make sure I'm not breaking consistency across the codebase.

**Comment by mirague** [comment]
One does not commonly see this behaviour in EventEmitter-like projects. I believe jQuery could be the exception.

**Comment by luwes** [comment]
This is something that will not get added for now.
One simple solution would be to extend the VimeoPlayer class and override the `on` or `off` methods if you really need this behaviour.
