### ISSUE TITLE
How to set scrub time

### ISSUE THREAD

**Issue by ocipap** [vimeo/player.js#472]
I found that using left and right arrow keys can scrubbing video by 1 sec. But in some video this function working as scrubbing video by 5 or even 10 secs. I'd like to set this scrubbing interval to 5 secs programmatically in my web service. Which part of code should I look into?

**Comment by lessthanweb** [comment]
Just about to ask the same thing. It works via external buttons or keyboard presses as long as the video is not in focus which is quite useless. Checked the docs and cannot find anything regarding this.

**Comment by reckoner165** [comment]
Hi! All keyboard scrub attempts should now default to 1s hops. 
A viewer can manually change this to 5 or 10s intervals using [this page](https://player.vimeo.com/flags?p=general)

Presently, the interval can only be changed by the end user via the above linked flags page, and not set via the API.

**Comment by wbqd** [comment]
> Hi! All keyboard scrub attempts should now default to 1s hops.
> A viewer can manually change this to 5 or 10s intervals using [this page](https://player.vimeo.com/flags?p=general)
> 
> Presently, the interval can only be changed by the end user via the above linked flags page, and not set via the API.

Hi, reckoner165. I looked up the page you said, but it seems not working. Any solution on this?

**Comment by steve52** [comment]
Hi @wbqd , the page seems to be loading fine for me. What are the errors you're seeing?

**Comment by wbqd** [comment]
> Hi @wbqd , the page seems to be loading fine for me. What are the errors you're seeing?

Hi @steve52 , tha page is showing fine, but Vimeo keyboard seeking interval are not changed even after I set Keyboard Seeking to 10s. It's still seek by 1 sec on player.

Both clearing cookie and chrome secret tab didn't resolve this.

**Comment by steve52** [comment]
You're right! 😱

We'll try to get a fix out soon! Thanks for calling attention to this!

**Comment by wbqd** [comment]
> You're right! 😱
> 
> We'll try to get a fix out soon! Thanks for calling attention to this!

Hi @steve52 ,
today I found that Vimeo keyboard seeking interval has been removed on [https://player.vimeo.com/flags?p=general](https://player.vimeo.com/flags?p=general). Now where we can find and change this setting?

**Comment by fisherinnovation** [comment]
Thanks for reaching out. This setting was removed as we are in the final stages of moving this interval to 5 seconds. This update should be live in the coming days.

**Comment by wbqd** [comment]
> Thanks for reaching out. This setting was removed as we are in the final stages of moving this interval to 5 seconds. This update should be live in the coming days.

Hi, @fisherinnovation, thanks for reply.
Do you mean all interval will be set and fixed to 5 secs and no other options?

**Comment by davidhan527** [comment]
It would be great if we can set the scrub rate using the API. I'm actually hoping to set it to something like 0.3 seconds if this was an available option.
I believe other video api's like Cloudinary provide this feature and I found it useful in the past.
