### ISSUE TITLE
Feature Request: Ready Callback function that fires then the script is loaded.

### ISSUE THREAD

**Issue by nextgenthemes** [vimeo/player.js#473]
### Expected Behavior
The YouTube iframe API has this offical way of initializing that calls a `onReady` function when the script is loaded. In case I did not miss anything this does not have something like this.

### Actual Behavior
I like to load the JS only when the user clicks on a thumbnail and then start the video when the script is ready, very much like the [YouTube API example.](https://developers.google.com/youtube/iframe_api_reference?hl=de)

I have seen various script loader function on StackOverflow but I would feel more comfortable with something build in that I can rely on rather than copying some code from somewhere.

**Comment by gardelin** [comment]
I was looking for same think few days ago. Would be nice if there is event telling 'Hey script just loaded'

**Comment by igoradamenko** [comment]
@luwes, hi!

Are there any plans of implementing this feature? May I help here somehow? 

In my project I load Vimeo SDK dynamically (depending on a video existence on the current page) and want to be sure that I won't trigger `Vimeo` object too soon. Not sure that there's legit way to add “onready” callback right now. And if there's a way to help Vimeo team with this feature I'm ready :-)

**Comment by luwes** [comment]
I know this could be convenient but a small utility function can easily provide this functionality.
also this API supports being imported as a module which has no use for such a callback function.
for these reasons this won't be implemented, hope you understand.

for example creating a new bundle with some logic like below would do the same.

```js
import Player from '@vimeo/player';
onVimeoReadyCallback(Player);
```

OR

```html
<script>
var script = document.createElement('script');
script.src = 'https://player.vimeo.com/api/player.js';
script.onload = onVimeoReadyCallback;
document.head.append(script);
</script>
```

**Comment by marekmaurizio** [comment]
Lol closed.
