### ISSUE TITLE
Embeded Videos with Hide from Vimeo status lockup 

### ISSUE THREAD

**Issue by futureandahope7** [vimeo/player.js#474]
I have a collection of videos which have the Hide from Vimeo status (set via the API). These are embeded on our website, with forward and back feature added via jQuery. The videos play correctly. But when loaded quickly, by clicking through videos at speed. The following error occurs and the videos crash. Once crashed the video can no longer play.

https://player.vimeo.com/video/357697658/config?loop=0&title=0&byline=0&portrait=0&autoplay=true

{"message": "Because of its privacy settings, this video cannot be played here.", "title": "Sorry", "button": {"text": "Watch on Vimeo", "link": "https://vimeo.com/357697658"}, "view": 7}

I use the loadVideo feature with the full url, not the id, to move between videos on jQuery click event.

Note that the embed status is set to Play Anywhere.

Because this is a private project we can not link to it.

**Comment by futureandahope7** [comment]
Just to add to this request. It seems to be that the player still runs in the background, but the following css class shows the "play other videos place holder, over the top of it"

.player .vp-outro-wrapper.in .vp-outro-shade {
    opacity: 1;
}

**Comment by futureandahope7** [comment]
After messing around for a while ... I am thinking this issue .... of the player crashing when moving between videos may be related to the way I am using the player and not the error message. Can you offer any insight into the best way to move between videos. I was trying some thing along the lines of the code below:

//unload the last video
thisPopupVideoPlayer.Player.unload().then(function(){
     //load in the new video
     thisPopupVideoPlayer.Player.loadVideo(VPAVideoReview.vimeo_url).then(function(){ 
            //play the video
             thisPopupVideoPlayer.Player.Play();
});;

However the feature that I really need, and it may already exists, is a way to tell if the player is in a transition state, or has moved to a state where it can be acted on. I.e. while it is waiting for "then" to complete, there is a state of "busy". When idle or playing it is set to "inactive". I tried to use variables to keep tract of it, but often the player does not complete its "then" cycle so a variable method may get locked.

**Comment by futureandahope7** [comment]
With the time I have had to spend on this we have uncovered that the issue seems to be related to the full screen mode. If a video ends playing, the preview at the outro starts to play automatically (i.e. the first video in the outro). For some reason the player in small screen mode can play the video we want, but the full screen mode is locked into the first outr video. Which incidentally locks up on some devices.

**Comment by luwes** [comment]
@futureandahope7 did you figure out the issue? 
calling `unload()` before is not necessary.

**Comment by futureandahope7** [comment]
We did not figure out the issue. But we did isolate it farther. It appears to only be in IOS mobile devices, like the iphone. Full screen mode has worked for us in all devices we have used, i.e. android etc, but it fails to work properly in IOS, iphone.

**Comment by luwes** [comment]
closing this issue as it's outdated
