### ISSUE TITLE
getPlayed returns array<undefined> in IE11 in callbacks

### ISSUE THREAD

**Issue by Moghul** [vimeo/player.js#476]
### Expected Behavior
getPlayed should return what it always does, an array of played sections
### Actual Behavior
Returns array<undefined> with a length equal to the number of segments played
### Steps to Reproduce
Put getPlayed and log its results in the on('pause') event.
Play and pause repeatedly.

**Comment by luwes** [comment]
This is resolved in the latest release of the player! Thanks for your patience.
