### ISSUE TITLE
loadVideo() can not change playsinline param value to iFrame

### ISSUE THREAD

**Issue by lortschi** [vimeo/player.js#478]
### Expected Behavior
Instantiate same player with playsinline property this way:
`player.loadVideo({
   id: 'current Id of the player object',
   playsinline: 0
});`
### Actual Behavior
After reloading the same video and it's ready to play, the iFrame has no playsinline parameter in the url:
`<iframe src="https://player.vimeo.com/video/139953280?muted=1&amp;autoplay=1&amp;loop=1&amp;transparent=0&amp;background=1&amp;app_id=122963" width="640" height="360" framebo...`

**Comment by luwes** [comment]
@lortschi not sure this is unexpected, does the property take affect?

I think we don't serialize the passed properties back in the iframe src url.
it's handled internally.

**Comment by ixon666** [comment]
I have the same problem, 'playsinline' passed via loadVideo does not work.
@lortschi shouldnt the 'id' to be vimeo_id instead of player ID ?

**Comment by bdougherty** [comment]
`loadVideo` and other method calls do not modify the DOM on the parent page and only send a message to the existing iframe. If you need to change something that does not have an API method, you will need to do it yourself. This can be done with this library if you remove the existing iframe from the DOM and call the `Vimeo.Player` constructor.
