### ISSUE TITLE
Not able to load private video in allowed domain

### ISSUE THREAD

**Issue by salatielq** [vimeo/player.js#479]
### Expected Behavior
Expected to load the new video successfully. 

### Actual Behavior
When try to open I get an error:
```
player.js:2 Uncaught (in promise) Error: “https://vimeo.com/330754566” is not embeddable.
at XMLHttpRequest.o.onload (player.js:2)
```
Videos privacy setting:
<img width="362" alt="Screen Shot 2019-09-29 at 19 40 08" src="https://user-images.githubusercontent.com/6747627/65840561-04fa0280-e2f1-11e9-838b-964e37cc9d2d.png">

### Steps to Reproduce
1. Open [this page](https://ensino.academiadepregadores.org/vimeo-error)
2. Click in open class 02 or 03
3. Open the browser console

After a lot of research I couldn't find a solution, we get in contact with the Vimeo support and they told us to open an issue. I don't know but seems related to #334 and #270

**UPDATE**
I'm **not** getting the `is not embeddable` anymore but when I try to open a video it throws this error:
```
GET https://player.vimeo.com/video/330754566?byline=0&color=ffb825&app_id=122963 403 (Forbidden)
```

**Safari 13.0.1:**
<img width="875" alt="Screen Shot 2019-09-30 at 12 20 32" src="https://user-images.githubusercontent.com/6747627/65892518-d32e7d80-e37c-11e9-9091-b0fcaeee912d.png">

**Chrome 77.0.3865.90:**
<img width="530" alt="Screen Shot 2019-09-30 at 12 20 40" src="https://user-images.githubusercontent.com/6747627/65892535-d9245e80-e37c-11e9-86f1-da69e458ea19.png">

**Firefox 69:** Seems fine, no error at all.

Either way that a problem for me because when the player.js throw an error my JS code stop working.

**Comment by fisherinnovation** [comment]
Thanks for reporting @salatielq 

At the moment I am unable to replicate the output you are seeing when testing your demo. Can you confirm this is still an issue on your end?

**Comment by salatielq** [comment]
@fisherinnovation Weird but I'm not seeing the error either. But now I still get an error. I just updated the issue.

**Comment by luwes** [comment]
@salatielq is this still an issue?

**Comment by salatielq** [comment]
@luwes No, isn't an issue anymore. I solved at the time destroying and constructing the player instance again but now we are using another player provider.

**Comment by TodorMarkov88** [comment]
Just add in html meta tags ->

**<meta name="referrer" content="origin">**
