### ISSUE TITLE
Ended Video Event

### ISSUE THREAD

**Issue by PragnaBrahmbhatt** [vimeo/player.js#480]
When the video ends that time first ended event call and then pause event call that is the ISSUE.

I put the iframe in my code, and I display the replay icon when the video ends. Here what happen is when video end then it override the code of ended event with pause event. Check below 3 points.

1) When video ends that time **PAUSE** event call.
2) then **ENDED** event call.
3) then _AGAIN_ **PAUSE** event call.

So the replay icon not show and the play icon display as I had display the play icon on pause event.

Please give some solution. 

Thanks in advance. :)

**Comment by fisherinnovation** [comment]
@PragnaBrahmbhatt Would you be able to provide an example of your issue in JSFiddle or some other online editor?

**Comment by carlos-cne** [comment]
I'm with the same issue, but in my case, ended event does not fire. In my case, I use stream live videos.

**Comment by luwes** [comment]
@PragnaBrahmbhatt did you figure out a solution?


on the api demo page I couldn't reproduce

https://player.vimeo.com/api/demo

<img width="1120" alt="Screen Shot 2020-02-06 at 12 30 18 PM" src="https://user-images.githubusercontent.com/360826/73962495-8e8f9180-48dc-11ea-8cde-47e676dc08a6.png">
