### ISSUE TITLE
Flutter player

### ISSUE THREAD

**Issue by MrMoronIV** [vimeo/player.js#481]
I'm don't think there's a correct place to put this ticket so I think the player repo is the closest.

Can Vimeo please work towarda supporting Flutter for mobile apps with a flutter package that provides a player and exposes an API to interact with?

It would be great to have a solution to show private (or domain bound) videos inside flutter apps.

As of today a workaround is needed by using a webview but this is generally messy and a native player would probably perform much better.

Ao kindly please support Flutter as it only growing bigger and bigger as a platform!

**Comment by fisherinnovation** [comment]
Thanks for the feedback - I will ensure this feedback is brought to the correct teams internally. Given this isn't an actionable item for this specific project I will close this issue.

Thanks again!
