### ISSUE TITLE
Catch function after load() or ready() getting call infinitely if error catched

### ISSUE THREAD

**Issue by jimkeecn** [vimeo/player.js#483]
### Expected Behavior
Catch error will only run whatever function inside once.
### Actual Behavior
function inside catch() getting call repeatly.
### Steps to Reproduce
I am using angular 8.

     import Player from "@vimeo/player";

     private player: Player;

      ngAfterViewInit() {
          this.player = new Player(this.dashboardPlayer.nativeElement, {
          url: "https://player.vimeo.com/video/private-id",
          width: 640
       });
           this.player.ready().catch(err=>{
                console.log(err)
           })
       }

**Comment by luwes** [comment]
@jimkeecn do you have a test page online? thanks
