### ISSUE TITLE
Loading new video into player requires player.vimeo.com to be set up as an embedded site

### ISSUE THREAD

**Issue by marshals** [vimeo/player.js#49]
### Expected Behavior
It should continue to think that it's embedded in my domain.

### Actual Behavior
Thinks it's embedded in player.vimeo.com

### Steps to Reproduce
I have privacy set up to only allow videos to be embedded in certain domains. 
When I load the player initially using the following code I don't see an issue.
```
  this.player = new Vimeo.Player('videoContainer', {
    id: videoId,
    width: 800,
    height: 450,
    autoplay: true
  });
```

However, when I load a new video into the existing player I am told that I have to change the privacy settings so it can be embedded on player.vimeo.com
```
this.player.loadVideo(videoId).then((function(_this) {
  return function() {
    return _this.player.play();
  };
})(this));
```

**Comment by ccampbell** [comment]
Thanks @marshals. I just made a comment about this in https://github.com/vimeo/player.js/issues/41#issuecomment-243812956

**Comment by ccampbell** [comment]
I just deployed a fix for this, and I believe it should be working now. Let me know if not!

**Comment by marshals** [comment]
@ccampbell Looks like it's working now.  Thanks!
