### ISSUE TITLE
Question on Folder Organization

### ISSUE THREAD

**Issue by villaverder** [vimeo/player.js#491]
We currently have Business Account for Vimeo.
 
This account is managed by multiple business users.   Is there any way to organize/structure the videos/contents (e.g. functional areas) considering no business group should access to other group’s videos?

**Comment by luwes** [comment]
@villaverder thanks for your request.

this is something we can't assist you with here, this repo is only about the player API. 

reach out at 
https://vimeo.com/help/contact

or check the help center at
https://vimeo.zendesk.com/hc/en-us
