### ISSUE TITLE
Player API doesn't work w/ recurring Live embeds

### ISSUE THREAD

**Issue by Zaniyar** [vimeo/player.js#493]
### Expected Behavior
To play the embedded live-stream video.
### Actual Behavior
No errors, but also nothing happens.
### Steps to Reproduce
```
<iframe src="https://vimeo.com/event/XYZ/embed"
              frameborder="0"
              allow="autoplay; fullscreen"
              allowfullscreen
              id="livestream">
</iframe>
<script src="https://player.vimeo.com/api/player.js"></script>
<script>
var stream = document.querySelector('#livestream');
var player = new Vimeo.Player(stream);
player.play(); //nothing happens.
</script>
```

**Comment by spingary** [comment]
+1

**Comment by rotvr** [comment]
+1

**Comment by dbonomo** [comment]
This would be huge for us. Would love to be able to get player state, position, Video ID/Title, etc...

**Comment by luwes** [comment]
thanks for the feedback, we've enabled the player API for recurring live events today.
please let us know if you see any issues.

**Comment by richardhasseneeg** [comment]
I don't understand why this is closed. The issue is that these aren't fired on recurring events and that they need to.

**Comment by SamuelNitsche** [comment]
The api was not working with recurring live events until now. The issue should be fixed.

**Comment by spingary** [comment]
I just tested it - seems to work well. THANK YOU!  This saves me so much trouble y'all have no idea... !

**Comment by richardhasseneeg** [comment]
Awesome! Thank you so much

**Comment by dbonomo** [comment]
You just seriously saved our bacon. Thank you so much for getting this done!
