### ISSUE TITLE
Sequential clip autoplay?

### ISSUE THREAD

**Issue by jeffburger** [vimeo/player.js#498]
Apologies if this is not the right place to post a basic functionality question. 

I want to create a viewing experience where we can programmatically interrupt/override a video the user is watching with a different video (presumably based on replacing the embed code at a given time of day and retriggering). I know that some browsers/devices like iOS don't allow autoplay. Assuming the user has hit the Play button at the beginning of their viewing experience, would the replacement video start playing automatically at the interrupt time... or would it require the user to click Play again?

Thanks so much!
Jeff

**Comment by fisherinnovation** [comment]
Pending the initial play request was sourced from a user gesture, new videos initialized via `loadVideo` (https://github.com/vimeo/player.js#loadvideooptions-numberobject-promisenumberobject-typeerrorpassworderrorerror) calls should play without issue. Here is a simple example to help you get started https://jsfiddle.net/mh4pnbxt/
