### ISSUE TITLE
Method For Parsing Video ID From URL?

### ISSUE THREAD

**Issue by kgrote** [vimeo/player.js#50]
Does the API have a method I can use to extract the ID from any Vimeo URL? I ask because I want to use the `loadVideo` method to update an existing player, but it only accepts an ID. However I only have a video URL to work with rather than a pure ID. Alternately, if the `loadVideo` method could be updated to accept a URL or an ID, that would work too. However a separate method would be most useful since it can be used in other places.

**Comment by Dashron** [comment]
The API relies on your video's URI as the unique identifier. @bdougherty does this library accept API URIs?

**Comment by ccampbell** [comment]
The `loadVideo` method currently only supports a video id. If you have a vimeo url to start with like `https://vimeo.com/47943362` then you can call this to load it:

```javascript
player.loadVideo(47943362);
```

So for now I would recommend parsing out the video id yourself.

**Comment by kgrote** [comment]
OK, feature request then. It looks like you've already got the ID parsing logic in the library since you can use either a URL or an ID when initializing a new player object. So it would be nice to get access to that existing logic rather than having to write my own.
