### ISSUE TITLE
Memory leak when using player.ready() promise.

### ISSUE THREAD

**Issue by KayoMaciek** [vimeo/player.js#500]
I've experienced memory leak after attaching handlers to player.ready() promise. Digging deeper with Chrome's Memory tools (taking Heap snapshot) I got retainers chain like this:

<img width="375" alt="Screen Shot 2019-11-15 at 16 49 45" src="https://user-images.githubusercontent.com/23442299/68926238-648c6e80-07c8-11ea-8d43-a1234b0a9657.png">

which pointed me to this place in player.js's code:

![Screen Shot 2019-11-15 at 16 50 47](https://user-images.githubusercontent.com/23442299/68926329-9ef60b80-07c8-11ea-9ef1-488f84ba39eb.png)

onMessage is constructed as an arrow function which makes it hold its parents contexts' references (including readyPromise) and it's attached to window object but never detached (as far as I can see searching for ".removeEventListener('message'" in that file).

Promise handlers are referenced by that promise under the hood so anything I reference from those handlers is never garbage collected.

To resolve this issue one could remove 'message' event listener at one point or another (I haven't analyzed the source, but destroy() comes to mind).

### Expected Behavior

Attaching handlers to player.ready() should not cause memory leaks.

### Actual Behavior

It does.

### Steps to Reproduce

Attach handlers to player.ready() and observe that the variables they reference never get garbage collected (including their parents contexts if defined using an arrow function).

**Comment by luwes** [comment]
good catch! if this is called for every player creation then it makes sense the event would be removed in destroy(). will look into this soon.
