### ISSUE TITLE
Videos don't play in Safari 13.0.3 (15608.3.10.1.4) Catalina

### ISSUE THREAD

**Issue by casevanarkel** [vimeo/player.js#502]
### Expected Behavior

This video should play in Safari 13.0.3 (15608.3.10.1.4): https://vimeo.com/335525440

As it plays in Chrome: https://vimeo.com/335525440

### Actual Behavior

This video does not play in Safari 13.0.3 (15608.3.10.1.4): https://vimeo.com/335525440

But it does play in Chrome: https://vimeo.com/335525440

### Steps to Reproduce

Hit each of the links in Safari and Chrome and see that it doesn't work in Safari and works in Chrome.

**Comment by lg-elit** [comment]
Can confirm this in Safari Version 13.0.3 (15608.3.10.1.4) on Catalina.

With Safari Version 13.0.3 (13608.3.10.10.1) on High Sierra it seems to work though.

**Comment by fisherinnovation** [comment]
Thanks for reporting! We will review this and work to resolve this issue as quickly as possible.

**Comment by casevanarkel** [comment]
@fisherinnovation 

Thanks for your help with this. Any update?

**Comment by fisherinnovation** [comment]
We have managed to identify the source of the issue and have a patch in the final stages of review - aiming to have that deployed this week. I will ensure this thread is updated once that change is available. Thanks for your patience!

**Comment by casevanarkel** [comment]
Great, thanks for the update!

**Comment by sulkowski** [comment]
@fisherinnovation Is there any chance the patch will go out this week? 🙇🏼‍♂️

Alternatively, do you have any workaround that could be applied for Safari?

**Comment by fisherinnovation** [comment]
The initial stage of this fix was rolled out yesterday. Please advise if you are still seeing this issue when attempting to view your content. Thanks again for you patience!

**Comment by sulkowski** [comment]
It worked!

**Comment by casevanarkel** [comment]
Thanks for the update @fisherinnovation and for addressing the issue!
