### ISSUE TITLE
Responsive prop doesn't work for landscape formats

### ISSUE THREAD

**Issue by haach** [vimeo/player.js#504]
### Expected Behavior
When creating a new Player with the responsive prop set to true, I expect that the video fits its container, no matter the videos dimension.

### Actual Behavior
Only the width of the Player is responsive, which causes a landscape to overflow it's parent container.

### Steps to Reproduce
create a Player with the following options:

```
this.player = new Player(
      domRef,
      {
        id: YOUR_VIDEO_ID,
        loop: true,
        muted: true,
        controls: true,
        autoplay: true,
        autopause: false,
        responsive: true,
      }
)
```

And use a video with portrait format.
I am using @vimeo/player at v2.10.0

**Comment by luwes** [comment]
@haach did you figure it out? I'm pretty sure this is related to the wrapping element and the CSS applied to it. if you could supply a jsfiddle or similar?
closing for now
