### ISSUE TITLE
Cannot control title / byline for some videos

### ISSUE THREAD

**Issue by fattomhk** [vimeo/player.js#505]
### Expected Behavior
Hide title and byline

### Actual Behavior
Cannot hide them

### Steps to Reproduce
Follow the example of https://github.com/vimeo/player.js#create-with-a-video-id-or-url, change the id to `76979871`

add 
```
title: false,
byline: false
```
in options

Example:
https://codesandbox.io/s/quizzical-dubinsky-6l6wl

**Comment by fisherinnovation** [comment]
Thanks for the report. Forgive me for not having too much experience using codesandbox.io, but when I go to update that example you shared, I am not seeing my edits displayed. Here JSFiddle example Vimeo Player embed to show how to use these embed options. At first glance it looked like you were implementing the options correctly, I believe the tool my be what was holding you back at the moment.

https://jsfiddle.net/kge4vop5/

Let me know if you still encounter issues. Thanks!

**Comment by luwes** [comment]
This might have been caused by that specific video having overriding options.
The creator can override and choose whether color, title, byline, etc. have to show even when the embedder changes those

**Comment by fattomhk** [comment]
Thanks @luwes @fisherinnovation , the video (76979871) in readme.md took me two hours for debugging. I thought developer can override those settings.
