### ISSUE TITLE
Get URL to currently active live stream

### ISSUE THREAD

**Issue by Stanzilla** [vimeo/player.js#507]
### Expected Behavior
An API that returns the url of the currently active livestream

### Actual Behavior
Can only check files API for files with the type `hls` and then filter

### Steps to Reproduce

N/A

In general, I would love to be able to embed a Vimeo livestream into a static content website without having to update the video ID on every new stream.

**Comment by fisherinnovation** [comment]
To help you avoid updating the video ID for every live stream you want to embed check out Recurring Events (https://vimeo.zendesk.com/hc/en-us/articles/360002114347-Recurring-events).

I will also bring your request internally to review as we continue to find better ways to enable you to gain more control over your embeds. 

Thanks for the feedback!

**Comment by Stanzilla** [comment]
Awesome, thank you!

**Comment by SamuelNitsche** [comment]
@fisherinnovation May I ask how I can embed a live event into the player?

**Comment by fisherinnovation** [comment]
Live events can be loaded in the Player and embeded anywhere (given your privacy configuration) when setting up and managing your live stream. Look for the 'Event Embed Code' button on the live event configuration page and copy and paste the embed code in the same way you would copy and paste the embed code for a non-live VOD.

The (responsive) embed code should look something like the following (subsitute the proper video ID in the URL)

```html
<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/[LIVE VIDEO ID]" frameborder="0" allow="autoplay; fullscreen" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div>
```

The player also supports reoccuring live events, more information on that configuration option can be viewed here https://vimeo.zendesk.com/hc/en-us/articles/360002114347-Recurring-events.

**Comment by SamuelNitsche** [comment]
Unfortunately, this doesn't work since the video id changes every time the stream gets started.

The event embed code looks like this (https://vimeo.com/event/{id}) and cannot be embedded into player.js

**Comment by GlaucoNeves** [comment]
Is it any solution for this?

**Comment by joelbriggs** [comment]
I found a workaround that will get the URL for the live video for a live event

I'm using PHP to get some JSON from vimeo

`$json = json_decode(file_get_contents("https://vimeo.com/live_event/{LIVE_EVENT_ID}/status"));`

This returns a JSON object that looks something like this

`next_live_clip: {
config: "https://player.vimeo.com/video/{VIDEO_ID}/config?autoplay=1&badge=0&byline=0&bypass_privacy=1&collections=0&color=00adef&context=embed_playlist.&default_to_hd=0&external_embed=0&force_embed=1&fullscreen=1&like=0&logo=0&playbar=1&portrait=0&privacy_banner=0&responsive=1&responsive_width=1&share=0&title=0&transparent=0&volume=1&watch_later=0"
config_no_autoplay: "https://player.vimeo.com/video/{VIDEO_ID}/config?autoplay=0&badge=0&byline=0&bypass_privacy=1&collections=0&color=00adef&context=embed_playlist.&default_to_hd=0&external_embed=0&force_embed=1&fullscreen=1&like=0&logo=0&playbar=1&portrait=0&privacy_banner=0&responsive=1&responsive_width=1&share=0&title=0&transparent=0&volume=1&watch_later=0"
duration: "00:00"
id: VIDEO_ID
is_live: true
is_pending: false
owner: "{OWNER_NAME}"
plays: 14687
thumbnail: "https://i.vimeocdn.com/video/a.webp"
title: "VIDEO_TITLE"}`

With that you can grab the video URL from

`$json->next_live_clip->config`
