### ISSUE TITLE
Feature Request: Allow use of methods like getDuration without embedding a video

### ISSUE THREAD

**Issue by TheFunkyMonk** [vimeo/player.js#508]
I have a situation where I'm pulling in video duration lengths on post preview cards that don't actually include the video (until you click through to the post).

It would be nice if I could pass `false` or omit the element reference when initializing a new player, like `const player = new Player(false, options);` so I can use `player.getDuration()` without having to embed a video on the page.

Maybe there's a better way to do this?

**Comment by fisherinnovation** [comment]
I would reccomend using the Vimeo API to allocate this information (https://developer.vimeo.com/api/reference/videos#get_video) pending you have no use for the Player.
