### ISSUE TITLE
Vimeo iframe sometime simply doesn't load

### ISSUE THREAD

**Issue by thomasjulienalain** [vimeo/player.js#512]
Hello !

I have a restricted video by domain name that I want to embed on a website with an iframe as a background. And I want to wait and check when it's ready. 
`<iframe src="https://player.vimeo.com/video/377417192?background=1&dnt=1&quality=720p" allow="autoplay; encrypted-media" frameborder="0" ></iframe>`

I'm trying to use either `autoplay=1` or` background=1` as parameters but the video loads randomly.
When the video simply don't load I have some error in the console :

![image](https://user-images.githubusercontent.com/12446126/71936158-a73e4780-3176-11ea-8f5b-2aca25caa9ba.png)
`GET https://193vod-adaptive.akamaized.net/exp=[...] 400 (Bad Request)
Access to XMLHttpRequest at 'https://193vod-adaptive.akamaized.net/exp=[...] 'https://player.vimeo.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I embedded the same video in a simple iframe with autoplay and have the same issue here :
http://bit.ly/37LNdsl

It's not directly related to the player but maybe someone have an idea.

**Comment by fisherinnovation** [comment]
Thanks for the report. We have replicated this issue and are working to resolve this issue in our CDN configuration. I will ensure this thread is updated when this is resolved.

**Comment by fisherinnovation** [comment]
Thanks again for reporting this. We have resolved the issue and you should no longer encounter this blocker. Please reopen this issue if you are still having issues.

**Comment by anil-gohil** [comment]
Hello,

Is there a way to remove the link **https://148vod-adaptive.akamaized.net/** from the Vimeo iframe? My site is taking up a lot of space because of it.

Thanks

**Comment by peterjdickinson** [comment]
Did you ever fix this? As I have the same problem.

**Comment by mrimran** [comment]
> Hello,
> 
> Is there a way to remove the link **https://148vod-adaptive.akamaized.net/** from the Vimeo iframe? My site is taking up a lot of space because of it.
> 
> Below is the screenshot.
> 
> ![image](https://user-images.githubusercontent.com/86834011/193747765-57a2038c-e1af-4ef3-b3b5-7ac42f021c91.png)
> 
> Thanks

Same problem on our side, it orinates too many requests and due to that the page size becomes 250MB, which is huge.
<img width="1216" alt="image" src="https://github.com/vimeo/player.js/assets/6545893/268f579d-4285-47ca-8b82-ebf94358a5ee">

**Comment by rkrishnan8594** [comment]
These are the requests for the video segments themselves, so they are required for playback and cannot be blocked or filtered out.
