### ISSUE TITLE
player.js Oops! Backend error 503

### ISSUE THREAD

**Issue by Cookiezzz** [vimeo/player.js#523]
### Expected Behavior
Vimeo player should just play a video
### Actual Behavior
Receive an error 503.
### Steps to Reproduce
Can't really reproduce this as I believe this is due to an error on Vimeo servers once every while?

![image](https://user-images.githubusercontent.com/2996654/74176592-481d9800-4c38-11ea-8483-f8bcb68fb57a.png)

I just want to know if anyone has a good way to catch this error.

**Comment by luwes** [comment]
@Cookiezzz thanks for the feedback, there was indeed an outage for some time recently. This probably caused this issue and has since been resolved. As it's an internal backend related issue I'm going to close it here.

**Comment by Cookiezzz** [comment]
Hi Luwes,

I understand that it is an internal outage. I'd however like to know if I can prevent this from happening. (Not the fact that it's an outage, but my website freezing).
Somehow try/catch it in my code. Any advise on how to do that best?

**Comment by bratmen** [comment]
Hi @luwes this issue still actual. How we can fix it?

**Comment by bratmen** [comment]
> Hi @luwes this issue still actual. How I can fix it?

Do you have a solution for it?

**Comment by fisherinnovation** [comment]
@bratmen Can you post links to where you are encountering these issues so we can take a look?

**Comment by bratmen** [comment]
@fisherinnovation keller-x.com, we use "vue-vimeo-player": "0.1.0" you can see 503 errors in the console for browser.

**Comment by fisherinnovation** [comment]
I am not able to see where you are seeing 503's on the provided URL. Are you sure the Vue plugin isn't causing this issue?

**Comment by bratmen** [comment]
@fisherinnovation sorry regarding to the URL, this - https://www.keller-x.com/story/nike-air/. The error appears after several minutes without any actions at this page.

**Comment by bcpurleigh** [comment]
Hey @fisherinnovation we've had some user reports of this issue this week. The URL that has been reported is https://thecoachingmasters.com/online-business-webclass-in-progress/ with people getting 50 minutes into the video and then it stopping. On testing this morning I had 2 instances of 503 errors (however the video didnt stop for me). Hope this helps!

**Comment by bratmen** [comment]
Hello @fisherinnovation, any news?

**Comment by Alex-Golovin** [comment]
this happened again

**Comment by fisherinnovation** [comment]
This is the result of some unexpected downtime in our system. Everything should be recovered now.

**Comment by Alex-Golovin** [comment]
@fisherinnovation I understand, but can you advise solution for this case... how to detect this error on front-end? I would replace video with static image in this case

**Comment by michaelck** [comment]
@fisherinnovation Like Alex-Golovin, I could also use some guidance on this.

**Comment by Cookiezzz** [comment]
Kinda also still looking for a solution to catch this. I don't need a fix from Vimeo just a catch so that if it happens I can either reload the page, display an image or something else.

**Comment by bastienbengler** [comment]
I currently have a Vimeo business plan and I'm not able to play videos for more than 2 days in a row without having a 503 backend read error. This is just ridiculous. Can someone from the Vimeo Development Team can, as someone said before, not fix the issue but at least allow us to catch the error ???

**Comment by fisherinnovation** [comment]
Thanks for the reports all. We are working on providing a better feedback system in the API for load monitoring. Will track the request at https://github.com/vimeo/player.js/issues/651
