### ISSUE TITLE
Odd behavior w/ multi-players on the same page

### ISSUE THREAD

**Issue by AlchemyUnited** [vimeo/player.js#524]
### Expected Behavior

Consistency 

### Actual Behavior

I have three players on a test page. Aside from the native controls, I have a play button floated over top of each player. The button is v and h centered (tho it doesn't matter, it might help your vision for seeing what's going on). 

If I scroll down and click the play button for the 2nd or 3rd player I get this msg in the console:

"Unhandled promise rejection NotAllowedError: play() failed because the user didn't interact with the document first"

I'm dev'ing Chrome and am aware of its Autoplay policies.  That being said, what's got me confused is the first player will play via the play button. No error. Why would that be?

I have three other related details to share:

1) This is for a Shopify site. In the admin page preview. everything works fine. 

2) If I set the first video - and only the first video - to autoplay occasionally one the other two will also autoplay. I've checked and the src's autoplay=0 for the others so this adds to the confusion.

3) Using F5 vs a return vs Dev Tools Network disable cache (on or off) also creates different results. There doesn't seem to be a pattern. Well, not unless you consider random a pattern :)

### Steps to Reproduce

Unfortunately, I don't have a URL I can share here.

**Comment by luwes** [comment]
@AlchemyUnited have you looked at https://github.com/vimeo/player.js/issues/389?

is there any delay between the click on the custom button and calling `player.play()`?
