### ISSUE TITLE
Best practice for using player.vimeo.com/api/player.js

### ISSUE THREAD

**Issue by AlchemyUnited** [vimeo/player.js#527]
Is there a way to specify the version? What's the best way to get notified of updates? 

It seems to me we should copy and host this local, but maybe not?

**Comment by luwes** [comment]
Duplicate of #364

Our CDN url will always return the latest version which is not always ideal.

I recommend using a versioned CDN like unpkg.com or indeed installing the package via NPM and bundling it with your app or hosting a specific version on your own server.

Hope this helps.

**Comment by AlchemyUnited** [comment]
@luwes - Yes. Helps. 

Sorry for the dupe. If this is in the README, I didn't see it.

**Comment by luwes** [comment]
@AlchemyUnited all good. it makes sense to lock your app to a fixed version.
since today we have enabled a versioned endpoint to the player releases.

e.g. https://player.vimeo.com/api/player-2.9.1.js
