### ISSUE TITLE
Playback Speed <0.5

### ISSUE THREAD

**Issue by austinhjones** [vimeo/player.js#528]
I have a tool that controls an embedded vimeo player, and I'd like the playback speed to be configurable to be less than 50%. I saw that playback speed can only be adjusted between 0.5-2. Why is this? Would you guys be able to allow for any custom speed option like on normal html video?

**Comment by ffmammadov** [comment]
Alternatively, I wanted to use 1.75x speed

**Comment by luwes** [comment]
thanks for the feedback, this will be released soon. any number between 0 -> 2 will be available to set the playback rate to. cheers

**Comment by luwes** [comment]
this was released today 🎉, 2 is still the max limit but anything below can be set.
