### ISSUE TITLE
Why getters are promises?

### ISSUE THREAD

**Issue by hogash** [vimeo/player.js#53]
### Expected Behavior
In my case, `player.getPaused()` i expected to return `true` or `false`, or `player.getVolume()` to return the volume value.

### Actual Behavior
Returns a promise that i can't seem to get the values from.

### Steps to Reproduce
`console.log(player.getPaused() )`
`console.log(player.getVolume() )`

I understand that "setters" are actionable, but "getters" should only get values i think. Is there a way to just get the value?

Thanks!

**Comment by bdougherty** [comment]
Getters and setters are promises because we need to asynchronously post a message to the player and listen for a response. Rather than try to do a bunch of "magic" stuff to turn them synchronous, we opted to keep them async.
