### ISSUE TITLE
Loop not working for background true in safari 13

### ISSUE THREAD

**Issue by b14sha** [vimeo/player.js#538]
### Expected Behavior
Expected background videos to loop when background = true. It works in all browsers (FF, Chrome, Edge) except Safari (13.0.5 - 15608.5.11) on MacOS Catalina (10.15.3)

### Actual Behavior
Player stops after one iteration.

It seems to happen on videos without sound - videos that have sound loop correctly. 

Extra info: The video is hosted on a Premium account, and under the video settings 'Interaction tools' - the end screen is set to 'loop'.

### Steps to Reproduce
https://codepen.io/hamder/pen/ExjoyEV

**Comment by luwes** [comment]
thanks for reporting! we'll look into this.
I believe this is a Safari bug we encountered before.

quick test link, scrub to end in Safari 13, loop does not work.
https://player.vimeo.com/video/341520309?loop=1&autoplay=1

**Comment by silllli** [comment]
I’ve encountered the same problem. Any news?

**Comment by luwes** [comment]
this should be fixed 🎉
please let us know if you see any issues.
