### ISSUE TITLE
[Feature request] Possible to show a text over video with cuepoints or other method

### ISSUE THREAD

**Issue by guilhermej** [vimeo/player.js#542]
I want to show a dynamic text (like cues), different for each of my users, over the video, even in fullscreen mode.

I know this can be accomplished by using CSS (https://github.com/vimeo/player.js/issues/299), but not in fullscreen mode.

**Comment by luwes** [comment]
Sorry we can't help you with that here, please ask on Stackoverflow or another question/answer platform.

I believe it would require to make a wrapping element to go fullscreen and not the player iframe. on this wrapping element you can add text etc driven by the cuepoint API.
