### ISSUE TITLE
IE11 - Object doesn't support property or method 'hasOwnProperty'

### ISSUE THREAD

**Issue by tashaxavier** [vimeo/player.js#545]
### Actual Behavior
IE11 showing the above console error for https://f.vimeocdn.com/p/3.18.4/js/player.js

**Comment by neuromancer9** [comment]
Having the same issue.

**Comment by joker-777** [comment]
I'm seeing the same error on ie11

**Comment by mum-never-proud** [comment]
@luwes can you review the PR? #555

**Comment by luwes** [comment]
thanks for adding the PR @mum-never-proud. 
are you still having the issue? because I cannot reproduce it in browserstack IE11

**Comment by joker-777** [comment]
At least for me, this doesn't happen anymore

**Comment by tashaxavier** [comment]
I'm still seeing this

**Comment by tashaxavier** [comment]
After clearing my cache this seems to have been resolved. Don't see the error anymore
