### ISSUE TITLE
Uploading video to vimeo directly using API by post form.

### ISSUE THREAD

**Issue by wsafi** [vimeo/player.js#547]
hello there i face a problem when uploading video to vimeo using API by post form.Every thing is work fine and i test it before.
In more details i use vimeo API to get uploaded link i put it in post form and send file input in this request.
Now error with message " Sorry this video will be available for viewing shortly" as in attachment.
![IMG_20200321_004704](https://user-images.githubusercontent.com/62106954/77460650-0de41080-6e0a-11ea-80bd-e7c5c1212a30.jpg)

I don't know what's happens. I tried this from different browsers like chrome and Firefox with latest version.

Thank you

**Comment by luwes** [comment]
@wsafi this repo is only regarding the player.js API.

maybe ask here
https://github.com/vimeo/vimeo.php
or here
https://github.com/vimeo/vimeo.py
