### ISSUE TITLE
Option to remove all player user interface (and use custom buttons)

### ISSUE THREAD

**Issue by sheriffderek** [vimeo/player.js#548]
### Expected Behavior
I expect to be able to remove all default player controls and to build out different controls with the player API. Our project calls for a background video to be triggered by the users - with custom UI.

_(we're attempting to rebuild this site with Vimeo - with the expectation that we'll be able to avoid the changing youtube branding and pause states that have changed over the years: http://latakedown.com/la-takedown_

### Actual Behavior
I can remove the controls at the bottom - and narrow it down to just the play/pause toggle button in the center of the player - but that's as bare as I can get it.
![Screen Shot 2020-03-25 at 3 36 45 PM](https://user-images.githubusercontent.com/2066617/77592197-e98e3f80-6eae-11ea-9ce2-d3ffad87530d.png)
The specs call for a full-screen streaming background video - and the default controls are not usable.

### Steps to Reproduce
1. Use the vimeo player
2. Try and remove the default/standard UI for play button
https://codepen.io/sheriffderek/pen/ebf5d629621fe78982295e62dc4800db?editors=1010

Is this currently possible somehow? Thanks.

Here is a minimal example: https://codepen.io/sheriffderek/pen/ebf5d629621fe78982295e62dc4800db?editors=1010

Here is a more specific example: https://codepen.io/sheriffderek/pen/poJWBde?editors=0011

**Comment by sheriffderek** [comment]
I figured I could skip some of the project requests - and use the default button for now - but here is another side-effect of using that:

In the case of a fullscreen video - (that needs to prefer an edge: think background-position) (in this case the people on the street are the focus - so, it can't be centered vertically) the default button is not centered.

![Screen Shot 2020-03-25 at 5 12 38 PM](https://user-images.githubusercontent.com/2066617/77597445-24e33b00-6ebc-11ea-91b4-c6e1aa770ac8.png)

![Screen Shot 2020-03-25 at 5 10 08 PM](https://user-images.githubusercontent.com/2066617/77597471-39273800-6ebc-11ea-8eaa-1e8c0fb88e63.png)

**Comment by luwes** [comment]
Have you tried the `controls` parameter?
https://github.com/vimeo/player.js#embed-options

(only for plus, pro, ...)

**Comment by sheriffderek** [comment]
No! I did not see those. I do have a 'pro' account. "Video must be hosted by a Plus account or higher." - but I see no 'plus' - so, maybe that's an old lingo.

I look forward to trying those out in the morning! Thanks @luwes

**Comment by sheriffderek** [comment]
My check on the constructor didn't pan out - but adding the parameters to the url did! https://codepen.io/sheriffderek/pen/a8a013f773249b792133f639e6e0a832?editors=1010

(note that for normal reason / background=true - puts it in auto play - which removes the audio.

This gives me the control I need! It appears that no click events stick around too - so that's great. : )

Of course - until the client asks for a scrubber. hehe... ; )

**Comment by sheriffderek** [comment]
That all worked out for me. Please close it up! Thanks.
