### ISSUE TITLE
Request::Check if player is in fullscreen, add isFullscreen method to player

### ISSUE THREAD

**Issue by andrelandgraf** [vimeo/player.js#549]
### Expected Behavior
Not all browsers support the isFullscreen method of the browser yet. E.g. Safari will not tell you if the browser has the vimeo player in fullscreen mode. Adding a state that toggles on entering and leaving fullscreen would be very helpful.

### Actual Behavior
Not implemented 

### Steps to Reproduce

I am having some problems to detect if the player is in fullscreen.

This is my current approach: https://stackoverflow.com/questions/60921169/vimeo-detect-fullscreen-to-block-fetching-of-new-player-dynamic-width-changes

Listening to webkitFullscreenChange is also not an option for me.

As the last comment in issue #72 states, not all browsers and cases are supported by the tools provided through the fullscreen api.

**Comment by luwes** [comment]
This was actually released today, can be tested on https://player.vimeo.com/api/demo with the fullscreen for 3s button in the top right corner.

**Comment by andrelandgraf** [comment]
Tested it today and it works like a charm! :100:
Thanks you for notifying me!

**Comment by akadebnath** [comment]
![image](https://user-images.githubusercontent.com/18642790/113296287-e2e2a580-9316-11eb-8f9b-c2f841f497bf.png)

Any idea why fullscreenchange is triggrered twice when I switched to fullscreen or close fullscreen?
Also, is it possible to identify whether the player went to fullscreen or back from fullscreen. Currently both the event triggers same "fullscreenchange" event.

**Comment by lectricas** [comment]
Any update on this? I also want to know how to differ between this two
