### ISSUE TITLE
"Buffering" event / property?

### ISSUE THREAD

**Issue by casdevs** [vimeo/player.js#55]
### Expected Behavior

I would like to be notified if the player starts buffering / stops buffering, to be able to display a custom loading indicator. So we need an event to notify that buffering has started (because of a user action or limited bandwidth) and ended. A matching property getter would be nice, too.
### Actual Behavior

It is not possible to get "buffering" state information at the moment. A "seeked" event is available, but it appears to be fired after buffering has ended. Using the player API example page, I'm not aware of any event or property that tells us the player is in buffering state, as opposed to playing or paused state.
### Steps to Reproduce

See current events documentation / use sample player.

**Comment by EugeneButusov** [comment]
Hi everyone, does anyone have info about when this feature (buffering event) may appear in Vimeo JS Player roadmap? Thanks in advance!

**Comment by luwes** [comment]
Closing for #211
