### ISSUE TITLE
Request: Get Chapters from Player

### ISSUE THREAD

**Issue by CalebKester** [vimeo/player.js#551]
There's support for TextTracks. Could we get support for getting Chapters from this? Or is this planned for the future? https://developer.vimeo.com/api/upload/texttracks

**Comment by danrossi** [comment]
The old way is you put them in the description and parse them for navigation. There is now a "getCuepoints" api. I assuming these are for chapters, is there an example video for that ?

**Comment by danrossi** [comment]
I have a video with chapter markers. That displays in non pro mode in the embedded player controlbar. But to obtain this data to include in a custom controlbar shows up as empty data. Is this the correct api method ?

```
this.vimeoPlayer.getCuePoints().then(function(cuePoints) {
                  console.log("cues", cuePoints);
                }).catch(function(error) {
                     console.log("cues", error);
                  switch (error.name) {

                      case 'UnsupportedError':
                          // Cue points aren't supported by the current player or browser
                          break;

                      default:
                          // Some other error occurred
                          break;
                  }
                });
```

**Comment by steve52** [comment]
@danrossi , the `getCuePoints()` method returns `cuePoints` added using out `addCuePoint()` method. https://developer.vimeo.com/player/sdk/reference#add-a-cue-point-to-a-video

As @fisherinnovation said, a `getChapters()` method is something we've been planning to add to our Player SDK. ever since we released Chapters. I'm working on it now and it should be available in a few days. I'll update this thread when it's in production!

**Comment by steve52** [comment]
@CalebKester @danrossi , `getChapters()`, `getCurrentChapter()`, and a `chapterchange` event have all been added to the player and this library! Feel free to use and leave any feedback for more improvements. :)

https://github.com/vimeo/player.js/blob/master/README.md#getchapters-promisearray-error
https://github.com/vimeo/player.js/blob/master/README.md#getcurrentchapter-promiseobject-error
https://github.com/vimeo/player.js/blob/master/README.md#chapterchange

**Comment by CalebKester** [comment]
Thanks @steve52 . I pulled it from github (npm isn't updated yet) and it's doing exactly what I would expect. I'll report back after I use it more if I have any issues. Thanks again for the quick turnaround.

**Comment by steve52** [comment]
FYI, npm should install the latest version now!

**Comment by danrossi** [comment]
This works. I get cues and the chapter event works. but the data api Ive been using to get stills for video posters has now been turned off, I now get a 404, it was working before only the other day. What can I do about that ? The oauth data requirement just to get the image url is bloaty and unnecessary. There is still no qualities api to do quality selection on a custom controlbar.
