### ISSUE TITLE
sourcemaps are not linked

### ISSUE THREAD

**Issue by mum-never-proud** [vimeo/player.js#556]
### Expected Behavior
minified js should include the source-map link
### Actual Behavior
source-map link is removed
### Steps to Reproduce
`npm run build`

in rollup config, I found that we are intentionally emptying the source-map URL, any reason?

**Comment by mum-never-proud** [comment]
closing got the answer!

**Comment by osro** [comment]
> closing got the answer!

Could you share the answer? 🤔
