### ISSUE TITLE
Request: set video quality for live events (or any other way to have a more consistent delay)

### ISSUE THREAD

**Issue by rotvr** [vimeo/player.js#559]
Hello 👋

Currently we cannot do something like https://player.vimeo.com/video/157588560?autoplay=1&quality=1080p for live events. We have several use cases with real-time viewer interaction that need to account for a somewhat consistent delay and forcing a lower quality for everyone could be an option. Please consider some way to address situations where a delay in the double-digits is worse than having a lower quality video.

**Comment by BjornGameDev** [comment]
+1

**Comment by cclobo2** [comment]
+1

**Comment by goranefbl** [comment]
+1

**Comment by spingary** [comment]
+1

**Comment by rotvr** [comment]
To provide a bit more context, the current circumstances dictate that a lot people are having their first contact with live streaming. These people will not click a ⚙and have no idea what 720p is. They simply look at alternatives from competing platforms and it looks better, only because it defaults to HD. Or it has lower latency for everyone because it defaults to 360p. As it lags behind with issues like these, live streaming is an opportunity that Vimeo is not taking full advantage of.

**Comment by fisherinnovation** [comment]
Thanks for your feedback everyone! The first iteration of this change is now live in the Player. Although support options for this request are not fully finished, you should now be able to set the default quality for your live stream embedded player via the `quality` property in the URL (eg. https://player.vimeo.com/video/LIVE_VIDEO_ID?quality=540p). Please note that the selected quality will be the only quaility used, however we have found an issue where the selected quality isn't always displayed as selected in the settings window. This is a known issue we are working to correct. You can always verify the quality being played back in the Debug Window (press 'D' key to open when using the player)

We will continue to develop and improve this support in the coming days. Thanks again for the feedback and patentice in a very busy time.

I will leave this issue thread open until support for this feature is fully finalized.

**Comment by luwes** [comment]
The next step of the dynamic quality feature is tracked in #601. Coming soon!
