### ISSUE TITLE
'Error' event not being fired if player initially loaded with domain protected video and missing referrer header

### ISSUE THREAD

**Issue by casdevs** [vimeo/player.js#56]
### Expected Behavior

If I create a new player object for a domain protected video, but the user's browser does not send the referrer header or an incorrect one, the player should fire an error event telling me that the video cannot be played due to an 403 error.
### Actual Behavior

we do a 

```
var player = new VimeoPlayer(elementVideoPlayer, {id: <ID OF DOMAIN PROTECTED VIDEO>}); 
player.on('error', function(data) {
     console.log('error', data);
});
```

The player displays correctly "Sorry Because of its privacy settings, this video cannot be played here.", but no error nor any other event is fired that allows me to detect and react to this problem.
### Steps to Reproduce

see above

**Comment by stefan-hausmann** [comment]
even
```
player
            .ready()
            .then(() => {
                console.log("READY");
            }, error => {
                console.log("ERROR 1");
            })
            .catch(error => {
                console.log("ERROR 2");
            });
```
does not print anything on the console if we've created player before with an id of a video giving an 403 error.

However, if we supplied an inexisting video id before (getting back a 404 error),  "ERROR 1" is printed out.

**Comment by bdougherty** [comment]
This is something on our todo list. Right now, server-side error pages (like the domain-level privacy error) don't support the API, but it's something we hope to enable soon.

**Comment by stefan-hausmann** [comment]
ok great, thanks!

**Comment by rijk** [comment]
> it's something we hope to enable soon

How soon is soon? 😜

**Comment by luwes** [comment]
The ready promise will be rejected with a proper error message in 2.6.6
