### ISSUE TITLE
Embedding with domain whitelist doesn't work in Chrome, works in other browsers

### ISSUE THREAD

**Issue by admiralobvious** [vimeo/player.js#561]
### Expected Behavior

Video should play in our website since it's in the whitelist. 
### Actual Behavior

Player instead displays: 

```
To play your video here, change its privacy settings so it can be embedded on: player.vimeo.com
```

Doesn't work on a mac on Chrome 80.0.3987.163, but works on Safari 13.0.5 and Firefox 72.0.1.

### Steps to Reproduce

We're creating a video for a live event with the following privacy settings:

```
Who can watch this event?
Hide this event from Vimeo.com

Where can this event be embedded?
Only on sites I choose
app.test.mydomain.com
```

We're not using the lib directly but we're using [react-vimeo](https://github.com/u-wave/react-vimeo) which [depends on it](https://github.com/u-wave/react-vimeo/blob/8dda6afd9a33d39759209bd23a956d542968803c/package.json#L37) and it generates the following iframe:

```
<iframe src="https://player.vimeo.com/video/<video_id>?autoplay=1&amp;app_id=<app_id>" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen="" title="Test Title"></iframe>
```

**Comment by steve52** [comment]
@admiralobvious would you be able to share a link to your website where you're seeing this behavior?

**Comment by admiralobvious** [comment]
@steve52 no sorry, it's on a website that requires authentication and I can't give access to outsiders. I will try to get a small website up and running that can reproduce the problem and report back here.

**Comment by admiralobvious** [comment]
@steve52 Here you go https://vimeotest.test.klik.co/
The domain whitelist is: `localhost` and `vimeotest.test.klik.co`.

Still have the same issue in Google Chrome while it works with other browsers on the website and locally with a web server on my computer.

**Comment by admiralobvious** [comment]
@steve52 disregard, I have found the issue. I have this [extension](https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf?hl=en) in my Chrome browser and although it was disabled for that page, it was not enough for it to work. I have to completely disable the extension from the Chrome settings.

Sorry about that, never experienced such an issue in years of using this extension.

**Comment by steve52** [comment]
@admiralobvious , glad you found the source of the issue!
