### ISSUE TITLE
hide the vimeo cdn url in video src tag

### ISSUE THREAD

**Issue by deekshithmasthmysore** [vimeo/player.js#563]
Hi i am using vimeo pro account to host videos and embedded to my laravel website using player.js and when we inspect the element and finds out video tag in src parameter it should show the blob url and it is working in other vimeo integrated websites (example check laracasts videos it is showing blob url as src and in network it is showing as chunks / segments instead of direct mp4 file) but when i checked my video src it is directly showing the cdn url where we can copy that url and can download. sometimes it shows blob url and some times it shows akamai cdn url. please help me out i want to display blob url everytime in video tag src

**Comment by luwes** [comment]
@deekshithmasthmysore in normal circumstances it will show the blob url in the video tag and use segmented video. only when that playback mechanism fails it would fallback to progressive mp4's. Do you have a test page online?

**Comment by juliovirginio** [comment]
I'm having the same issue. All my videos are private and I embeed then on my Website. I've set all rules, including domain restrictions. Somehow this plugin gets the cdn file url and all my privacy is blowed!

Vimeo request number: 5977901

https://chrome.google.com/webstore/detail/vimeo-video-downloader/cgpbghdbejagejmciefmekcklikpoeel

**Comment by deekshithmasthmysore** [comment]
and also i have seen many users using bitmovin and when ever they use plugins to download it is not showing full video to download but showing in segments to download which is very hard for users to download every piece of video but when comes to vimeo it is showing only one video to download which is full video this is poor.

**Comment by luwes** [comment]
we've discussed this internally and there is not much we can do to prevent this.
once a user can view a video he/she might as well record it with a screen recorder and use that.
that would even bypass DRM.

closing the issue.
