### ISSUE TITLE
Console errors when using player.loadVideo then player.play for videos with chapters

### ISSUE THREAD

**Issue by epsilon42** [vimeo/player.js#564]
### Expected Behavior
No console errors when using `player.loadVideo` and `player.play` in succession on videos that have chapters.

### Actual Behavior
When using `player.loadVideo` to change the current Vimeo video to one that has chapters, then try and play the video using `player.play` I receive errors in the console with the message: 
```
Uncaught TypeError: Cannot read property 'startTime' of undefined
```

Of the browsers I am able to test (Chrome, Safari, Firefox), only Chrome and Safari seems to have the error message.

One thing I am currently unable to investigate is how the videos have been setup in Vimeo itself (i.e. if there is any setting that could be causing this).

Everything still seems to function fine, but was wondering if I might be incorrectly trying to load then play videos, or if there is a way of suppressing the error message.

### Steps to Reproduce
1. Use Chrome or Safari and have the developer tools console open (the console built in to CodePen does not seem to display the error).
2. Visit: https://codepen.io/epsilon42/pen/YzyqaKR
3. Try clicking the `Load` buttons and observe the console when you load videos that contain chapters vs videos that don't.

**Comment by steve52** [comment]
@epsilon42 , thanks for catching this and including a codepen! 🙌Made it very easy to debug. I think I've tracked down the issue and we should be able to roll it into production within the next day or two!

**Comment by epsilon42** [comment]
@steve52 No problem. Thanks for looking into it so quickly. Will test it out once it's rolled out.

**Comment by steve52** [comment]
@epsilon42 thanks again for calling this out. Took a little while as other high priority stuff had to go out, but this fix is in production now! Let us know if you see these error messages pop up again!
