### ISSUE TITLE
Feature Request: A setting to prevent video outro from playing at the end of a video's playback

### ISSUE THREAD

**Issue by glomotion** [vimeo/player.js#565]
Please forgive me if this is the wrong place, but I have a feature request...

### Intended Behavior
Pass an option/setting through to the player on init that prevents it from playing the "outro" at the end of a video's playback. When this setting is enabled, a video plays right up until the last frame of the video, and then stops on that last frame.

To try and achieve this, I'm currently having to watch the progress percent of the video using the 'timeupdate' event... but it's proving very difficult to reliably detect the very last frame, due to the speed of updates that the 'timeupdate' event fires at. ATM the closest I can let the progress precent go seems to be 0.94, which almost certainly is not the very last frame (i'm dealing with a number of very short videos - ~5secs or so).

### Actual Behavior
All videos play the outro after they complete playing

### Steps to Reproduce
... as explained above.

**Comment by luwes** [comment]
thanks @glomotion, this can be configured in the video settings if you own the video. if you don't have ownership there is no option unfortunately.
