### ISSUE TITLE
Can I use this script to autopay vimeo on mobile?

### ISSUE THREAD

**Issue by sambuev** [vimeo/player.js#569]
Hello, I looking for the script to auto-play vimeo embedded videos on mobile phones, is it possible to do it with this script?

**Comment by fisherinnovation** [comment]
Due to autoplay policies, the optimal method to ensure your videos autoplay is to enable the `autoplay` and `muted` properties. Example - https://player.vimeo.com/video/76979871?autoplay=1&muted=1
