### ISSUE TITLE
How can I use Vimeo Player in my TV Apps? (Tizen and WebOS)

### ISSUE THREAD

**Issue by wilsonneto-dev** [vimeo/player.js#571]
Is the player compatible with TV apps?
How can use my videmo vídeos in my TV apps?

Thanks so much!

**Comment by luwes** [comment]
if they support HTML, JS and CSS the player should be able to work there. cheers!

**Comment by rafaelvinicius** [comment]
I can not use webOS on LG. Does not load the video.
Youtube, MP4 and HLS work.
