### ISSUE TITLE
Question: Features related to Live Chat?

### ISSUE THREAD

**Issue by anekola** [vimeo/player.js#572]
I'm looking to see if I can automatically log a user into the chat as a guest with their name, but I haven't seen any documentation related to Live Chat / Q&A. Does this exist somehow, or is it on the roadmap at all? Apologies if this isn't the correct forum to reach out.

**Comment by fisherinnovation** [comment]
Thanks for reaching out @anekola 

This issue tracker is specifically for the Vimeo Player API and thus isn't the optimal place for this question. I reccomend connecting with our support teams (https://vimeo.com/help/contact) to raise your concern/question around documentation of the Chat system.

Thanks,
