### ISSUE TITLE
Unable Play video in Ios UIWebview

### ISSUE THREAD

**Issue by SwarajMeetIOSDeveloper** [vimeo/player.js#576]
### Play in Ios Webview
 

I need i play video in ios uiWebView video doesn't autoplay and set current time not working

### Code
 <!DOCTYPE html>
        <html>
        <body>
        <style type="text/css">
        body, html {width: 100%; height: 100%; margin: 0; padding: 0;background:#1C00ff00}
        .main {position: absolute;top: 0; left: 0; right: 0; background-color: #1C00ff00;height:100%;}
        .main iframe {display: block; width: 100%; height: 108%; border: none;}
        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <script src="https://player.vimeo.com/api/player.js"></script>
        <div class="main">
        <iframe src=\(url)></iframe>
        </div>
        
        <script src="https://player.vimeo.com/api/player.js"></script>
        <script>
        var iframe = document.querySelector('iframe');
        var player = new Vimeo.Player(iframe);
        
        player.on('play', function() {
        window.webkit.messageHandlers.play.postMessage("play")
        });
        
        player.on('ended', function(data) {
        window.webkit.messageHandlers.ended.postMessage("ended")
        });
        

        Promise.all([player.getVideoWidth(), player.getVideoHeight()]).then(function(dimensions) {
        var width = dimensions[0];
        var height = dimensions[1];
        window.webkit.messageHandlers.dimensions.postMessage(dimensions)
        });
        
        player.setCurrentTime(\(500).then(function(seconds) {
        window.webkit.messageHandlers.seconds.postMessage(seconds);
        });
        
        function play() {
        player.play();
        }
        
        function pause() {
        player.pause();
        }

        
        
        </script>
        
        </body>
        </html>

**Comment by luwes** [comment]
Have you enabled autoplay to not require a user gesture in the web view?
https://stackoverflow.com/questions/34429042/autoplay-on-video-in-uiwebview-ios

You have to either enable this or it might work with the sound muted.
