### ISSUE TITLE
Fullscreen video scaling do not work properly on iOS browsers

### ISSUE THREAD

**Issue by mydudechris** [vimeo/player.js#577]
### Expected Behavior
- On tapping full screen button, the user should be able to go into fullscreen **and** use the scaling button in the top-left corner to scale video to 100% height (getting rid of black bars on top/bottom)

### Actual Behavior
- Upon entering fullscreen, users are unable to scale to 100% height
- Tapping the scale button causes the video to jump around
- See video here: https://www.dropbox.com/s/9xkzuuemkbwwr5e/RPReplay_Final1590092122.MP4?dl=0

### Steps to Reproduce
- Watching any video on vimeo.com or video from embed code provided by vimeo live on iOS tablet (affects various versions of iOS with Chrome and Safari)
- Enter full screen then try to scale the video to 100% height

**Comment by mydudechris** [comment]
Bueller?

**Comment by fisherinnovation** [comment]
Thanks for the report as well @mydudechris. We will also review this internally and provide status updates on this ticket.

**Comment by mydudechris** [comment]
thanks @fisherinnovation

**Comment by mydudechris** [comment]
@fisherinnovation any progress on this?

**Comment by mydudechris** [comment]
I noticed that the Vimeo Livestream player works as expected on tablets. I can use two fingers to zoom to full screen, then scale it to 100% height. Is there any way we can get this implemented on the Vimeo player? I do a lot of live streaming with my Vimeo Premium account and this feature is a real issue for me as many of my viewers view it properly on their tablets. This in combination with the chat minimizing problem create a real issue for my users—both on tablets and desktop as the experience is poor on both. Not being able to use fullscreen properly is forcing me to consider other platforms such as YouTube, Wowza and Dacast. I really don't want to switch (especially to youtube).

**Comment by mydudechris** [comment]
bump

**Comment by mydudechris** [comment]
Bump
