### ISSUE TITLE
Minimize chat not working properly

### ISSUE THREAD

**Issue by mydudechris** [vimeo/player.js#578]
### Expected Behavior
- I should be able to easily minimize chat from a fullscreen video 

### Actual Behavior
- I cannot select Minimize chat until I have either entered my name or logged in
- Once I've done one of those two, I can select the "..." button and minimize chat, which creates a really weird animation and is inconsistent on desktop vs. tablet browsers
- **The real issue** - If the user has chat open and a full screen video then they cannot access the "minimize" option presented by the "..." button because the "minimize" link appears behind the chat window and the video player.
- I have to exit full screen, then minimize chat, then re-enter full screen

### Steps to Reproduce
- Open any video page that has chat enabled
- Try to fullscreen the video and minimize the chat after video is full screen

**Comment by mydudechris** [comment]
Bump.

**Comment by fisherinnovation** [comment]
Thanks for the report. We will review this internally and provide status updates on this ticket.

**Comment by mydudechris** [comment]
Thanks @fisherinnovation

**Comment by mydudechris** [comment]
Any progress on this @fisherinnovation

**Comment by mydudechris** [comment]
Bump

**Comment by mydudechris** [comment]
Bump

**Comment by luwes** [comment]
thanks for following up @mydudechris. this is being investigated internally at the moment.

I'm closing the issue here because this repo is only intended to cover issues related to the player API. for more general vimeo.com site issues please see https://vimeo.zendesk.com/hc/en-us
