### ISSUE TITLE
getVideoTitle  loads old title 

### ISSUE THREAD

**Issue by capbussat** [vimeo/player.js#581]
### Expected Behavior
getVideoTitle should get title of video after loading a new video.

### Actual Behavior
Loads new video but sometimes **getVideoTitle** does not work. gets old title instead

### Steps to Reproduce

Try fast reload some times in this Codepen 

https://codepen.io/capbussat/pen/zYrvQzy

**Comment by capbussat** [comment]
Fix: one different player for each video. Hide videos and show/hide as required.
Same example rewrited
https://codepen.io/capbussat/pen/Yzwwmrj

**Comment by capbussat** [comment]
Another solution. Just change order of my code and added additional getVideoTitle before reading 'title' in my code. It seems it needs some time to get the video title or it maybe that reading a second time reads the new title correctly. 
(I am not an expert but it seems to me **getVideoTitle** should wait for the promise to fulfill a 'new' value not get previous video title instead. Some 'undefined' or 'initial' value would be preferred).

**Comment by luwes** [comment]
try this one, https://codepen.io/luwes/pen/YzwoqON

there is a race condition going on. 

IN the function you wait for the promises to resolve but when calling `view_video` this was done synchronously, probably making the last call to loadVideo take precedence...

**Comment by capbussat** [comment]
Thanks, you must be right.
