### ISSUE TITLE
Fullscreen request denied, not called from inside a short running user-generated event handler.

### ISSUE THREAD

**Issue by WolkeLandgraf** [vimeo/player.js#584]
Hi!

I've started creating a site using player.js, so far it works awesome but I'm getting stuck with the Method "requestFullscreen". It asks for a user interaction and i'm using it inside a Jquery click function:

#### Firefox
Request for fullscreen was denied because Element.requestFullscreen() was not called from inside a short running user-generated event handler.

TypeError: Fullscreen request denied

#### Chrome
Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.

### Steps to Reproduce
Here is a JsFiddle with the simplest aproximation:
https://jsfiddle.net/wgb1k0ma/

To load the library I'm using the cdn:
<script src="https://player.vimeo.com/api/player.js"></script>

Thanks, I'm most certainly doing something wrong so sorry in advance!

**Comment by luwes** [comment]
@WolkeLandgraf does it work on https://player.vimeo.com/api/demo on your end?

sometimes these websites like jsfiddle, codepen, etc. use nested iframes which don't always have the required `allow` attribute.

do you have a personal test page?

**Comment by pmediavictor** [comment]
@luwes I am having same issue. Your DEMO page is working just fine but it is not working like that in our pages. 

I am auto playing video and trying make it fullscreen when clicking on button starting video from beginning but i am getting user-initiated event. But it was setup only after clicking on button.

https://prnt.sc/t0bpxl

**Comment by luwes** [comment]
thanks for the feedback, I reproduced the same issue on my end.
it hadn't occurred to me that this was limited with cross-domain security. 

I'm doing more research on whether it's even possible to go fullscreen via iframe postMessage.
it doesn't look good so far. will keep you posted.

**Comment by pmediavictor** [comment]
Sure @luwes

**Comment by luwes** [comment]
little update here what the plan is with the fullscreen API. we tested the functionality with iOS which uses the internal video element to go fullscreen. our testing showed that this worked as expected, it does not throw the user-initiated gesture error.

in an upcoming update to this library a browser detection will be made and for most browsers the player will go fullscreen via the parent iframe and no post message will be sent fixing this issue, for iOS the post messages will be used to internally request and exit fullscreen on the video element. 

if you're eager to make this work have a look at 
https://stackoverflow.com/a/9039885/268820
https://github.com/sindresorhus/screenfull.js

**Comment by luwes** [comment]
this should be resolved, please let me know if there are any issues. cheers!

**Comment by pmediavictor** [comment]
Thanks @luwes . I will check.
