### ISSUE TITLE
Rejected promise on load player.js in Salesforce

### ISSUE THREAD

**Issue by pserquiz** [vimeo/player.js#585]
Hello!

right now I'm trying to use the player.js in a Lightning Web Component (Salesforce). I'm getting a REJECTED promise with an undefined error basically.

### Steps to Reproduce

_I downloaded the player.js from https://player.vimeo.com/api/player.js_

1 - Add the player.js as a new static resource in the salesforce platform
2 - Try to load in a Lightning Web Component using `loadScript(this, vimeoPath + '/player.js')`
3 - I get back a promise status = rejected and value = undefined
4 - not sure if this is relevant but I also get a warning `Cannot assign to read only property 'Promise' of object '[object Object]' [Cannot assign to read only property 'Promise' of object '[object Object]']`

Appreciate any help!

**Comment by fisherinnovation** [comment]
Looking at https://developer.salesforce.com/docs/component-library/documentation/en/lwc/js_third_party_library you may need to follow Step 2 `Upload the library to your Salesforce organization as a static resource, which is a Lightning Web Components content security policy requirement.` to get this to work properly.

Closing as this doesn't look to be an issue with this project,

**Comment by sunhao12** [comment]
I have already resolved it
