### ISSUE TITLE
on end event i want call api in angular 7 but it is not calling. please help

### ISSUE THREAD

**Issue by sanjeevuideveloper** [vimeo/player.js#588]
setVideoVideoContent1(video_link_url, id, video) {
    var vlink = video_link_url;
    var res = vlink.split("/", 5);
    let link = res[4].split(".", 1);
    console.log(link[0]);
    this.options = {
      url: "https://player.vimeo.com/video/" + link[0],
      width: 700,
      loop: false
    }

    setTimeout(() => {

      this.player = new Vimeo.Player(id.toString(), this.options);

      this.player.on('ended', function () {
        console.log('finished');
        this.lessonService.stcVideoEnded(video.reward_video_id, localStorage.getItem('token')).subscribe(res => {
          if (res.status == 1) {
            console.log(res)
    
            this.toastr.success(res.message, 'Success!', {
              timeOut: 3000,
              positionClass: 'toast-bottom-right'
            });
          }
          else {
            this.toastr.error(res.message, 'Please try again later', {
              timeOut: 3000,
              positionClass: 'toast-bottom-right'
            });
          }
        },
          err => {
            this.toastr.error('Something went wrong. Please try again later', '', {
              timeOut: 2000,
              positionClass: 'toast-bottom-right'
            });
          })

      });

    }, 1000)

  }

only out i am getting is->"finished" in console
![Screenshot (100)](https://user-images.githubusercontent.com/46085964/85701571-27437400-b6fb-11ea-93c4-5b3ec74064a4.png)

**Comment by fisherinnovation** [comment]
Not sure this is related to the player. If you're executing the code in the ended event handler, anything past that looks to be unrelated to the player and more specific to your application code.

Pending I am incorrect about this please update this ticket. A working example is also a better asset to review as its easier to see whats going on.
