### ISSUE TITLE
Player fullscreen button doesn't sync w/ fullscreen API

### ISSUE THREAD

**Issue by luwes** [vimeo/player.js#592]
Just noticed when using the fullscreen API the player's own fullscreen button does not reflect the iframe's fullscreen state. Pressing the button doesn't exit fullscreen, however using ESC key does do the job.

Can be seen in this example, https://jsfiddle.net/wgb1k0ma/

**Comment by pmediavictor** [comment]
Hi luwes,

Thanks for Fix but still issue there. We have to double click to close the fullscreen in Android. Please test in Android Phone.

**Comment by luwes** [comment]
thanks for the feedback @pmediavictor, will check this on monday.

**Comment by luwes** [comment]
sorry for the slow reply on this @pmediavictor. we did some testing on our end and it looks like the fullscreen button in the player on Android is a bit glitchy. we believe it's not related to this specific API change so I'll close this issue here but we are tracking this internally and will resolve this bug as soon as possible. cheers

**Comment by pmediavictor** [comment]
@luwes Any idea when you guys fix the issue OR should i create new bug issue here?

**Comment by luwes** [comment]
@pmediavictor thanks for following up. yes please create a new issue for that.
