### ISSUE TITLE
Password Protected Player - sentry.js was blocked due to nosniff header

### ISSUE THREAD

**Issue by abhi-markan** [vimeo/player.js#600]
### Expected Behavior
Password Protected Player - To start the live stream or video straight after the correct password has been entered.

### Actual Behavior
Upon entering the password the player loads with a black screen, error on console which does not load an important JS file thus not showing the stream. However upon a refresh stream can be viewed.

Error - The resource from “https://player.vimeo.com/video/module/sentry.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

### Steps to Reproduce
1. Create a password protected player
2. Embed - Anywhere
3. Open the direct link (not iframed) in an incognito window to avoid reading already cached JS files.
4. Once the correct password has been entered following error will come up on the console thus showing "black" video player, once refreshed stream is visible on the player.
![Screenshot 2020-07-22 at 17 22 56](https://user-images.githubusercontent.com/32125108/88201912-014cb900-cc40-11ea-9532-09bec7000459.png)

**Comment by luwes** [comment]
Thanks for the feedback, we are currently working on this. Cheers!

**Comment by abhi-markan** [comment]
> Thanks for the feedback, we are currently working on this. Cheers!

Many thanks

**Comment by luwes** [comment]
this is resolved
