### ISSUE TITLE
Add quality API methods 

### ISSUE THREAD

**Issue by daviddfm** [vimeo/player.js#601]
I embed the player and hide all controls in order to surface my own controls.  I can't have Vimeo controls surface for my application.  I have customers that require the ability to set quality playback to 1080p.  However, I can't have that be a hardcoded setting for all users who may have bandwidth restrictions.  

I need to be able to surface a Quality control that mimics what the Vimeo player shows... so I need an API to GET

- The current quality
- The available qualities

and SET
- the quality to use from now on in a currently playing video

**Comment by danrossi** [comment]
This would be the duplicate but ok. I've been asking to add it in for years. Hopefully something can happen.

**Comment by luwes** [comment]
sorry about that @danrossi, you're right.
original request by @danrossi at https://github.com/vimeo/player.js/issues/552

we're going to discuss this in the next team meeting.

**Comment by danrossi** [comment]
It's fine. Just needs something similar to YT api ? qualities list, and set quality.

**Comment by luwes** [comment]
@danrossi did you see the `getQualities()` method. this gets the list of available qualities

there is `getQuality()` and `setQuality()` with a `qualitychange` event.

the `resize` event is fired when the player actually changes the video resolution.
