### ISSUE TITLE
remove vimeo logo and sidedock

### ISSUE THREAD

**Issue by GlauberF** [vimeo/player.js#602]
It may not be the right place, but I tried and tried several ways already.

I need to remove the sidedock:
![sidedock](https://user-images.githubusercontent.com/11314585/88282695-6ba53e00-ccc0-11ea-9a19-5b2808222f92.png)

And remove the logo from vimeo:
![vimeo](https://user-images.githubusercontent.com/11314585/88282701-6ea02e80-ccc0-11ea-96b2-2fd54d0d0288.png)

Note: I'm not using the library, but setting it in the direct URL. But I believe they can help me, because they must have configured this inside the library (parameter)

My iframe
```html
<iframe [src]="'https://player.vimeo.com/video/440958739?byline=false&title=false&portrait=false&color=039be5&fun=false&sidedock=false' | safeURL" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen>
</iframe>
```

if you can help me I am very grateful :)

**Comment by fisherinnovation** [comment]
Thanks for reaching out. Both of these settings need to be made within the Video Settings for that specific video. Given they can only be controlled by the owner of the video, they are not controllable via the API.

**Comment by GlauberF** [comment]
maybe you can help me and would appreciate it if you can.

the video is my own, I deselected it, as shown in the image below
![Captura de Tela_selecionar área_20200723110335](https://user-images.githubusercontent.com/11314585/88295839-520df180-ccd4-11ea-8a4c-166a9a410d76.png)

when I click on embed url it stays the same without the options
![Captura de Tela_selecionar área_20200723110356](https://user-images.githubusercontent.com/11314585/88295899-65b95800-ccd4-11ea-841f-e5092e677471.png)

and on this first screen, you have no option to save the changes
![Captura de Tela_selecionar área_20200723110335](https://user-images.githubusercontent.com/11314585/88295956-7964be80-ccd4-11ea-93a3-0e4dcb0bdfa1.png)

**Comment by fisherinnovation** [comment]
The save/cancel buttons should show up once a change as been made to the configuration. It should be below the list.
![Untitled](https://user-images.githubusercontent.com/306818/88305507-9949b180-ccd7-11ea-942a-2da77b1a0e84.png)

**Comment by GlauberF** [comment]
For me it doesn't show up, I think because my plan is free.
![Captura de Tela_selecionar área_20200723125602](https://user-images.githubusercontent.com/11314585/88308852-ef245680-cce3-11ea-88e2-544a4d06f516.png)

**Comment by fisherinnovation** [comment]
Correct, you can get more information on features here https://vimeo.com/upgrade
