### ISSUE TITLE
Nothing is executed after Player instantiation and ready statement

### ISSUE THREAD

**Issue by peacepostman** [vimeo/player.js#603]
Hello,

I am facing an issue after the player instantiation, i can define any possible player api in the then promise but nothing is executed.

I am using react and react-frame-component, i've had no problem instantiating the player using a ref but nothing seems to work inside the ready statement. All my console.log are correctly output but it is like all the player function does nothing.

If anyone has ever face this type issue, i would be really grateful to have some help :)

Best regards,

**Comment by luwes** [comment]
@peacepostman do you happen to have a test page online? that would help us debug the issue more easily

**Comment by peacepostman** [comment]
Hello, yes of course : https://codesandbox.io/s/strange-bouman-erboz?fontsize=14&hidenavigation=1&theme=dark

I suggest you to use firefox, chrome has the autoplay policy error while using codesandbox.

Best regards,

**Comment by luwes** [comment]
not sure if this is the intention but you can't access a ref or element cross window.
see the 2 nested iframe's. for this to work there should only be 1, the player iframe.

if you really need 2 nested iframe's, it's possible but it's gonna get more complex. 
basically the JS to control the player should be in the first generic iframe and then from the parent you will need to send a postMessage to the window of the generic iframe which would in turn call the player API methods.

<img width="1037" alt="Screen Shot 2020-07-30 at 1 58 41 PM" src="https://user-images.githubusercontent.com/360826/88957904-a6354a80-d26d-11ea-8a75-2c9c9c7ca1a6.png">
