### ISSUE TITLE
player.play() stuck on pending promise

### ISSUE THREAD

**Issue by david-inertia** [vimeo/player.js#605]
### Expected Behavior
I need to play the video when it has loaded
### Actual Behavior
After I load the video, it sets event to play and gets stuck, if I click on pause, I get the following error
**Uncaught (in promise) PlayInterrupted: The play() request was interrupted by a call to pause()**
### Steps to Reproduce
The below function is loading the video, and also fetching the seconds to continue if the seconds are set, after the video is loaded I am calling the event to play the video, it works very inconsistently, also the function below is being called when the page loads first time. 

Any help will be greatly appreciated.

```
function LoadVideo(video_id, sess_id){
            player.loadVideo(video_id).then(function(data) {
                secs = $("#toggle_"+sess_id).data('seconds');
                  player.setCurrentTime(secs).then(function(seconds) {
                  // seconds = the actual time that the player seeked to
                  }).catch(function(error) {
                    console.log(error);
                      switch (error.name) {
                          case 'RangeError':
                              // the time was less than 0 or greater than the video’s duration
                              break;
        
                          default:
                              // some other error occurred
                              break;
                      }
                  });  
          player.play();

            }).catch(function(error) {
                console.log(error.name);
                switch (error.name) {
                    case 'TypeError':
                        // the id was not a number
                        break;
            
                    case 'PasswordError':
                        // the video is password-protected and the viewer needs to enter the
                        // password first
                        break;
            
                    case 'PrivacyError':
                        // the video is password-protected or private
                        break;
            
                    default:
                        // some other error occurred
                        break;
                }
            }); 
}
```

**Comment by luwes** [comment]
I don't think it's really a bug. have you tried waiting for the play promise to resolve and then set the current time or vice versa? 

```js
player.play().then(() => player.setCurrentTime(secs));
```

closing but please reply, I'll follow up.

**Comment by david-inertia** [comment]
Thanks for the reply, I will try this and test it for a bit, as my above function was working but very inconsistently

**Comment by david-inertia** [comment]
Hi, the same issue is still happening, it gives a pending promise, for a very long time. if I pause it I get the same issue **"Uncaught (in promise) PlayInterrupted: The play() request was interrupted by a call to pause()"**

**Comment by luwes** [comment]
do you have a test page online? is the video starting at all at some point?

it's normal if you play and then very quickly pause before the video starts playing that error is thrown. that's why one should wait for the play promise to resolve.

**Comment by david-inertia** [comment]
I will create a test page and send it to you as soon as I can, The video does play occasionally, but sometimes it just hangs and I need to call the function again or reload the page for it to play again.

I figured the Mozilla Firefox going back to pause due to autoplay policies, since it plays in Google Chrome

**Comment by leymannx** [comment]
I had the infinitely pending promise issue when the Vimeo iframe was nested in another iframe (for [security reasons](https://oembed.com/#section3)). Getting it out of the other iframe made it work.
