### ISSUE TITLE
Player.js requires many CSP exceptions (these are missing from documentation)

### ISSUE THREAD

**Issue by glomotion** [vimeo/player.js#611]
Feature / Documentation request:

The vimeo player seems to need a multitude of CSP exceptions in order to function properly. Sadly, there doesn't seem to be any solid documentation on this... and one has to resort to trial and error to try and open up CSP exceptions...

I wonder, does anyone in the Player.js team have a definitive list of all CSP exceptions required to use the software? If not, could we please get this added to the official docs?

I have found this gist in some guy's GitHub ... but some sort of official confirmation would be super amazing! 
```
default-src *.vimeo.com ;
script-src *.vimeo.com *.vimeocdn.com *.newrelic.com *.nr-data.net ;
style-src *.vimeocdn.com ;
child-src 'self' *.vimeo.com *.vimeocdn.com ;
connect-src *.vimeo.com ;
```

**Comment by luwes** [comment]
thanks for the feedback @glomotion. how are you embedding the Vimeo player?
I'm not aware of any CSP exceptions that need to be added if the player is embedded via an iframe.

**Comment by glomotion** [comment]
@luwes we are using both iframes and your player.js to embed videos - inside an electron web app (which is running with a CSP whitelist).
Not all cases can simply be an iframe, sadly as we need alot of control over the playback of some videos.

**Comment by luwes** [comment]
@glomotion sorry but this is not something that will be made public. the Vimeo player is not intended to be embedded without an iframe. pro plans and up can use a 3rd-party player with Vimeo hosting, see https://vimeo.zendesk.com/hc/en-us/articles/224823567-Direct-links-to-video-files

**Comment by glomotion** [comment]
@luwes Sorry, I think we had a mixup in communication. 

On occasion inside an electron app that I work on, I use the the (official) vimeo player.js API to dynamically create iframe video embeds (eg like you do in your docs https://github.com/vimeo/player.js#create-with-a-video-id-or-url). 

When doing this (and also trying to enforce CSP) you have to whitelist the various things that you know the iframe is going to reach for.  

Could you even PM me the CSP requirements for a player iframe?
