### ISSUE TITLE
Private videos throw a 403 error that prevents destroy() and new embeds from happening

### ISSUE THREAD

**Issue by neojp** [vimeo/player.js#618]
### Expected Behavior

1. `player.destroy()` should remove the iframe tag when embedding a video that has privacy settings.
2. It should be able to create new embed afterwards.

### Actual Behavior

1. `player.destroy()` doesn't remove the iframe tag.
2. It doesn't remove the attribute `data-vimeo-initialized="true"` from the container element. 
3. It won't let you create new embeds afterwards.

### Steps to Reproduce

When attempting to embed a video with privacy settings it returns this error in the JS console:

```
Error: “https://vimeo.com/event/000000” is not embeddable
```
https://github.com/vimeo/player.js/blob/cf794283d3169b913624b57de34ce74f870d9139/src/lib/embed.js#L107-L110

The player script creates an iframe with the embed, and it looks like this:

![image](https://user-images.githubusercontent.com/127994/91172797-ca3c4e00-e6aa-11ea-8d4b-371e13162348.png)

I believe that due to this error, the code exits early and while the player creates an iframe it doesn't get added as `_originalElement` and therefore it's not destroyed afterwards.

https://github.com/vimeo/player.js/blob/22ceb7af94cc7f68dc09c1cfbeb3a8ce07f62998/src/player.js#L473-L476

This creates a problem with how the `player.js` tracks if a player already exists and it won't let you embed new players afterwards.

### Demo

I have created a simple jsfiddle to demo this issue. Note how you can't embed anything after destroying the player: https://jsfiddle.net/neojp/ekb21hwz/5/

### Workaround

One way I was able to work around this issue was to delete the iframe and remove the data attribute myself on the destroy callback. This finally let me create new player embeds.

### Browser version
Microsoft Edge Version 85.0.564.36 (Official build) beta (64-bit)

**Comment by luwes** [comment]
thanks for the detailed report @neojp. we will take a look at this soon.
