### ISSUE TITLE
Vimeo player PLAY\PAUSE events not triggered

### ISSUE THREAD

**Issue by SheltonAlves** [vimeo/player.js#627]
Hi

I have embedded vimeo link in an iframe, I also have custom button below iframe onclick of which the iframe source(src) is changed to different vimeo URL.
I listen to vimeo player PLAY and PAUSE events.I cannot listen to player events (PLAY/PAUSE) when dynamically source of iframe is changed. 

**CASE 1:** When new video is loaded,I tried to unload old vimeo player instance using 'player.unload()' and again created player object, but PLAY/PAUSE events not getting triggered for newly rendered video.
**CASE 2:** When new iframe src is loaded, I created new vimeo player object, When i pause the player PAUSE event is triggered twice.
**CASE 3:** Added 'player.loadVideo(id)' event to load player with new vimeo link but media events(PLAY/PAUSE) not getting fired.

Created vimeo player object using 'player.vimeo(iframe)'.
I want to track PLAY/PAUSE events of both vimeo links when iframe src is loaded with new vimeo link.How do i listen to PLAY/PAUSE events when iframe src is changed with different vimeo URL dynamically?

Thanks
Shelton

**Comment by luwes** [comment]
@SheltonAlves it's not possible to change the iframe src url and keep the player API working as you found out. use the `player.loadVideo(id)` method to change the video and the player API will keep working.

try it out on https://player.vimeo.com/api/demo, play the video, there will be a `play` event, pause the video will trigger a `pause` event. now load in a new clip ID, enter `24` in the input, click Load video, again play and pause will trigger the needed events.
