### ISSUE TITLE
data-vimeo-defer

### ISSUE THREAD

**Issue by rootion** [vimeo/player.js#63]
From the documentation:

> Elements with a data-vimeo-id or data-vimeo-url attribute will have embeds created automatically when the player API library is loaded. You can use the data-vimeo-defer attribute to prevent that from happening and create the embed at a later time.

How can I create the embed at a later time using `data-vimeo-defer`?
And how would that be different from simply writing the following code, without using `data-vimeo-defer`?

```
<div id="59777392"></div> 
```
```
var options = { loop: true };
var player = new Vimeo.Player('59777392', options);
```

**Comment by bdougherty** [comment]
You can create it at a later time the same way that you'd create a player in js normally, but you don't have to pass options since it will read them from the element.

```html
<div id="59777392" data-vimeo-id="59777392" data-vimeo-loop="true" data-vimeo-defer></div>
```

```js
var player = new Vimeo.Player('59777392');
```

**Comment by rootion** [comment]
That makes sense. Thank you for the clarification!
