### ISSUE TITLE
Performance Google Lighthouse

### ISSUE THREAD

**Issue by Integral-design-marketing** [vimeo/player.js#630]
### Expected Behavior
Performance Google Lighthouse
### Actual Behavior
"Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance."
### Steps to Reproduce
https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools

**Comment by luwes** [comment]
Duplicate of #553
