### ISSUE TITLE
On Play: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by lookfwd** [vimeo/player.js#631]
### Expected Behavior

No exception on private video start.

### Actual Behavior

On a private video, I get `TypeError: Cannot read property 'classList' of undefined`. It's on `a.classList.remove("showfocus"),` because `a` is undefined. A is initialized as `a = i.querySelector(".vp-outro")` and it likely doesn't exist for private videos.

### Steps to Reproduce

Just open an iframe with a private video. Open the Console. Refresh the screen.

**Comment by luwes** [comment]
thanks for reporting, this is being worked on and should be resolved soon.

**Comment by luwes** [comment]
this is resolved in the mean time! cheers
