### ISSUE TITLE
Coming out of full screen on Chrome on iOS stops the player

### ISSUE THREAD

**Issue by neilgd** [vimeo/player.js#634]
### Expected Behavior
If a video is playing in full screen and then you exit full screen it should continue playing
### Actual Behavior
On Chrome and iOS it stops playing
### Steps to Reproduce
Play any video on Chrome in iOS. Make it full screen. come out of full screen.
It works fine on Chrome on Windows and Safari on iOS.

**Comment by dogukanakkaya** [comment]
I don't know what kind of video player you're using but i was having the same issue on youtube iframe.
Solved with playsinline parameter.
`
https://youtube.com/embed/{{ $streamLink }}?playsinline=1
`

Source: https://developers.google.com/youtube/player_parameters#playsinline

**Comment by bdougherty** [comment]
To my knowledge, the native iOS behavior when exiting the native full screen player is to stop playback. There have been a couple false starts, but Apple will be shipping the proper Fullscreen API sometime soon, and when that happens you'll see our full player in full screen which will not pause or stop the video when exiting.
