### ISSUE TITLE
Request: How to get video DOM elemen from iframe

### ISSUE THREAD

**Issue by OscarGutierrezT** [vimeo/player.js#638]
Hi, 
I need to get the <video> DOM element inside the iframe to send the frame image to a Unity WebGL "canvas element". I am using this code "GLctx.texImage2D(GLctx.TEXTURE_2D, 0, GLctx.RGBA, GLctx.RGBA, GLctx.UNSIGNED_BYTE, videoElement);", were the videoElement var is the video in the iframe, i tryed this:

var videoElement = iframe.contentWindow.document.getElementsByTagName("video")[0]; //Not Work
var videoElement = videoPlayer.element.getElementsByTagName("video")[0]; //Not Work

This page contains the method Syntax: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D 

Thanks!

**Comment by luwes** [comment]
@OscarGutierrezT thanks for the question. sorry, this is not possible. 
there is no way for you to access the video element in an iframe of another domain with javascript.

the only way is to use a 3rd party player with Vimeo's direct video links.
see https://vimeo.zendesk.com/hc/en-us/articles/224823567-Direct-links-to-video-files

**Comment by OscarGutierrezT** [comment]
Thanks for the reply, but this only works if the videos are mine, and I need this for live streaming and there nor have this option of a direct link, Are there another method? get the ArrayBufferView or anything?

**Comment by luwes** [comment]
sorry, no there is no way to do this.
would this be possible via https://github.com/vimeo/vimeo-unity-sdk?

**Comment by PaTiToMaSteR** [comment]
@luwes seriously, we lack in total access to the video element, access to functionality in the controls like airplay and chromecast... your answer cannot be "there is no way". Of course there is way, you already have onMessage funcionality to communicate with the iframe.

Why don't you put it in priority to implement it?
