### ISSUE TITLE
Browserify cannot find @vimeo/player

### ISSUE THREAD

**Issue by DanielKeeble** [vimeo/player.js#64]
### Expected Behavior
To be able to bundle assets containing the player.js package with browserify.

### Actual Behavior
Browserify is complaining that it cannot find the module @vimeo/player.

### Steps to Reproduce

1. require('@Vimeo/player')
2. Bundle assets via Browserify
3. See "Error: Cannot find module '@Vimeo/player'"

**Comment by bdougherty** [comment]
Maybe browserify needs something configured to work with scoped npm packages? I'm not very familiar with browserify, so you might have more success filing an issue with them.

**Comment by DanielKeeble** [comment]
Thanks for the reply @bdougherty. I appreciate I'll have to file an issue with browserify. Just out of curiosity, why does the npm package start with an @ symbol?

Cheers.

**Comment by DanielKeeble** [comment]
@bdougherty Just figured it out. Should be

`require('@vimeo/player')`

Not sure why on some systems care about the case sensitivity, and others not however.

**Comment by bdougherty** [comment]
It's a scoped package that belongs to our Vimeo organization on npm.
