### ISSUE TITLE
Feature Request: CSS classes option for dynamically created iframes.

### ISSUE THREAD

**Issue by regiside** [vimeo/player.js#640]
I'm using Player.js to create my iframes dynamically, but need to be able to add an additional css class to the iframe to make it work properly in my environment. It would be nice if there was a "classes" option that would accept a string that would be added to the iframe's css classes upon creation.

**Example:**
var options = {
        width: 640,
        classes: "full-width another-class"
    };

**Outputs:**
<iframe src="https://player.vimeo.com/..." class="iframe-embed full-width another-class"...

**Comment by luwes** [comment]
@regiside thanks for the suggestion but this is something we rather not add to the library to keep it  as lean and lightweight as possible. This snippet would give you a similar behavior:

CodeSandbox: https://codesandbox.io/s/vimeo-player-classes-dxcit?file=/index.html

```js
      var options = {
        id: 59777392,
        width: 640,
        loop: true,
        classes: "full-width another-class"
      };

      const player = createPlayerWithClasses(options);

      player.setVolume(0);

      player.on("play", function () {
        console.log("played the video!");
      });

      function createPlayerWithClasses(opts) {
        const player = new Vimeo.Player("made-in-ny", opts);

        player.ready().then(() => {
          player.element.classList.add(...opts.classes.split(" "));
        });

        return player;
      }
```

**Comment by aleehedl** [comment]
I would also like the option to add arbitrary styles to the created iframe element. The approach presented above works but may cause some unwanted visual effects because the iframe is loaded first and then the styles/classes are added a moment later. 

I have a use case where the iframe styles depend on the video dimensions and currently my only alternative is to manually create the iframe.
