### ISSUE TITLE
Option to disable picture-in-picture (PIP)

### ISSUE THREAD

**Issue by gpoole** [vimeo/player.js#642]
### Expected Behavior

Player API should have a boolean option such as `disablePictureInPicture: true` or `pip: false` to disable the browser's picture-in-picture feature via [`disablePictureInPicture`](https://w3c.github.io/picture-in-picture/#disable-pip).

### Actual Behavior

The player API does not seem to support disabling PIP.

**Comment by yanosh-igor** [comment]
Also looking for the same feature. It would be very useful.
Any idea when will it be implemented?

**Comment by elfanek** [comment]
+1. `disablePictureInPicture` would be a great enhancement!

**Comment by lucymca** [comment]
+1 disablePictureInPicture would be VERY handy

**Comment by lucymca** [comment]
Any idea when will it be implemented?

**Comment by Nautman** [comment]
Totally agree. This feature would be really useful!

**Comment by luwes** [comment]
thanks for the feedback, we're looking into this feature to release together with the PiP API methods. 

just to confirm, the use case would be to disable the PiP UI button currently shown in Safari?

**Comment by Nautman** [comment]
Yes, the use case is that I want to fully disable users from being able to use PiP in our iframe.

For Safari, this means that the button should be hidden.

For Chrome, I think this means that the `disablePictureInPicture` attribute should be added to the element, either with HTML or JavaScript (`videoElement.disablePictureInPicture = true`).

Unfortunately, Firefox doesn't currently support the `disablePictureInPicture` attribute. This is an [open issue on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1611831).

**Comment by suffering** [comment]
after some research, there is no configuration to disable pipline if you are using `DefaultUi` and `DefaultControls`.
https://github.com/vime-js/vime/blob/63fab3dcbed1dc9d2726cb6d73760a7b7ef8d30d/core/src/components/ui/controls/default-controls/default-controls.tsx#L156
the only solution is to custmize the UI by yourself:
`<Ui>
  <DblClickFullscreen />
  <ClickToPlay />
  <Poster />
  <Spinner />
  <LoadingScreen />
  <Controls
    pin='bottomRight'
    fullWidth
  >
    <ControlGroup>
      <ScrubberControl />
    </ControlGroup>
    <ControlGroup space='top'>
      <PlaybackControl tooltipDirection='right' />
      <VolumeControl />
      <TimeProgress />
      <SettingsControl />
      <ControlSpacer />
      <FullscreenControl tooltipDirection='left' />
    </ControlGroup>
  </Controls>
</Ui>`
notice that this snippets is only for desktop view, ignores the configures on live mode and mobile mode.

There is prop `disablePiP` on `Video` component, it is used to disable the pip button on fullscreen mode.

**Comment by luwes** [comment]
PiP is now disabled by default on all browsers. It can be enabled on Chrome and Safari by adding the `pip` option and setting it to true. Closing this as fixed.

**Comment by swaps-mayekar** [comment]
How to use `pip` option ?
If I open 'https://player.vimeo.com/video/76979871?pip=0' in Firefox, I still get PIP icon over video.

**Comment by Nautman** [comment]
I think it's not possible to disable PIP in firefox @swaps-mayekar.

> Unfortunately, Firefox doesn't currently support the `disablePictureInPicture` attribute. This is an [open issue on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1611831).

**Comment by swaps-mayekar** [comment]
> 
> 
> I think it's not possible to disable PIP in firefox @swaps-mayekar.
> 
> > Unfortunately, Firefox doesn't currently support the `disablePictureInPicture` attribute. This is an [open issue on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1611831).

Thanks for confirming Nautman (y)

**Comment by emmamy** [comment]
It appears that picture-in-picture is now the default again, and there's no way to disable it within embed presets?

**Comment by MladenJanjetovic** [comment]
I manage to remove it in Chrome with `&pip=0`

**Comment by Shubhankardubey** [comment]
@MladenJanjetovic where to put &pip=0 for disabling picture in picture?

**Comment by MladenJanjetovic** [comment]
@Shubhankardubey on the video link in the embed code

**Comment by DATEx2** [comment]
the PIP icon is still rendered even if pip="0" or disablePictureInPicture  attribute is present

**Comment by rkrishnan8594** [comment]
Note that Firefox doesn't support the Picture-in-Picture API, so unfortunately attempting to disable PIP using the embed option will have no effect in that browser. If you find yourself unable to disable PIP using the embed option in a different browser (Chrome, Safari, Edge, etc.), please file a new ticket.

**Comment by kodawah** [comment]
May I ask why people feel the urge to disable PiP? It's a basic video interaction, let the viewers watch the video how they want (unless I'm missing something ofc)

**Comment by kodawah** [comment]
@DATEx2 thanks for the reply, that does seem like a legit use case, along with 360 playback

To be honest this seems like a wrong default configuration on the background player -- the pip button should be disabled by default on those scenarios, rather than offering a site-wide options which could be misused and have unaffected consequences on the viewer

**Comment by kodawah** [comment]
@DATEx2 wait are your referring to chrome or firefox? firefox doesn't have any mean to hide the button, regardless of the player used - for other browsers the configuration buttons provided in the player settings work just fine

**Comment by DATEx2** [comment]
Chrome
*disablePictureInPicture *attribute is present as well as *&pip=0* in the
query string of the iframe

**Comment by tickstat** [comment]
Hello,
everybody, i still can see it in Firefox, it is not possible to disable this button in firefox ? I attach a screenshot where you can see the button that I can not disable. Thank you 
![screenshotToAsk](https://github.com/vimeo/player.js/assets/131240208/b1589b53-9703-45f6-aa85-7443e60f0d7c)

**Comment by kodawah** [comment]
> Hello, everybody, i still can see it in Firefox, it is not possible to disable this button in firefox ? I attach a screenshot where you can see the button that I can not disable. Thank you !

It is not possible, it's a browser limitation on Firefox
