### ISSUE TITLE
Player would pause if I use keyboard arrow keys to seek a specific time.

### ISSUE THREAD

**Issue by ZhonglinChen** [vimeo/player.js#643]
### Expected Behavior
According to the Vimeo Player Documentation(https://developer.vimeo.com/player/sdk/reference#set-the-playback-position-of-a-video)(https://developer.vimeo.com/player/sdk/reference#seeked),
the change of playback position would affect the play state. If the play is paused, it remains paused. If playing, video would keep playing after a new time position is selected.

### Actual Behavior
This works well when I drag and drop progress bar using mouse. 
However, when I used keyboard arrow keys and kept pressing arrow key so that I could reach some time position, player would become paused when the origin state was playing and no paused event was triggered.

**Comment by fisherinnovation** [comment]
Can you provide a code example and or more specific platform details around how to replicate this?

**Comment by luwes** [comment]
@ZhonglinChen this is how the HTML video element natively behaves, on seeking it will sometimes look like the video is paused or stalled (no data) but it will be still in the `playing` state. the video shouldn't fire any paused event while seeking
