### ISSUE TITLE
How to set the quality of the video via the API?

### ISSUE THREAD

**Issue by anatolzak** [vimeo/player.js#646]
I know I can set the quality of the video via URL search params as mentioned here https://help.vimeo.com/hc/en-us/articles/224983008-Setting-default-quality-for-embedded-videos?flash_digest=b98f58789298b3a141c74c634770d25c5bdfab46 but how can you set the quality with the API?

**Comment by fisherinnovation** [comment]
See https://github.com/vimeo/player.js#setqualityquality-string-promisestring-typeerrorerror
