### ISSUE TITLE
how to stop a video in iframe

### ISSUE THREAD

**Issue by ddancy** [vimeo/player.js#648]
### Steps to Reproduce

In our website, we can insert the vimeo embedded code with iframe. Then when switch tab in the page with ajax, we will stop the video by follow code.
$('iframe[src*="vimeo.com"]').each(function() {
var iframe = $jq(this)[0].contentWindow;
iframe.postMessage('{"method":"pause"}', '*');
});
It works fine for most situation. But some customers say that the code is not working. I guess the src in the iframe are different. maybe they use cdn url. Is it possible? And if yes, do you know any common code that we can judge that this is a vimeo embeded code, so we can use command to stop the video?

Thanks.

**Comment by fisherinnovation** [comment]
I reccomend holding reference to the Player(s) on your page and opt to call the `pause` method as it is documented in this project rather than execute calls on the postMessage object itself. See https://github.com/vimeo/player.js#pause-promisevoid-passworderrorprivacyerrorerror
