### ISSUE TITLE
Any recommended way to embed / play Vimeo videos in React Native

### ISSUE THREAD

**Issue by Aung-Myint-Thein** [vimeo/player.js#649]
We just started trying out vimeo service. As our app is React Native, would be nice if anyone can recommend a lib / way to embed / play vimeo videos in our project. The videos will be private and only available to certain users (limited permission).

Thanks!

**Comment by fisherinnovation** [comment]
You should be able to utilize this web player API via something like https://github.com/react-native-webview/react-native-webview

**Comment by mimi-uxui-dev** [comment]
I managed to do embed vimeo videos with react-native-webview but i can't figure away to get progress data of the day and/or if the video has ended? could you help me with this 

Thanks!

**Comment by fisherinnovation** [comment]
You are going to have issues using the API when the Player is in a webview. The alternative is to host your own page with the Vimeo Player embedded on it and wrap your code around that. Here is an (untested from my end) example someone has put together (https://github.com/Myagi/react-native-vimeo) for reference.
