### ISSUE TITLE
Allow Autoplay on iOS 10

### ISSUE THREAD

**Issue by andypillip** [vimeo/player.js#65]
### Expected Behavior

[iOS 10 allows HTML 5 autoplay of silent videos](https://webkit.org/blog/6784/new-video-policies-for-ios/)

The Vimeo player should behave respectively.

### Actual Behavior

Neither autoplay nor script-triggered play calls will play the video.

**Comment by bdougherty** [comment]
This is a feature request for the player itself, not this library, so please post on our forums (https://vimeo.com/forums/feature_requests) or contact support. Thanks!
