### ISSUE TITLE
Having multiple Vimeo videos a bit fiddely - here is my solution

### ISSUE THREAD

**Issue by Twoozy** [vimeo/player.js#652]
Hey everyone,

Today I spent quite some time getting an 'pause-all' function to work. I have a website for a client with multiple tabs with multiple embeded Vimeo videos. When you go to a different tab, the video should stop playing. Based on the documentation I could solve this with adding an separate ID for every video I add, but I wanted it to be automated for the future and with as little code as possible.

This if what I have now, if you know a better option please let me know. Otherwise could this be added to the instructions?

	$('a').click(function(){  // a works for me, but can be whatever

        var x = document.querySelectorAll("iframe");
        var nodelist = x.length;

        for (i = 0; i < nodelist; i++) {

            var player = new Vimeo.Player(x[i]);
			
			player.unload().then(function() {    		
			}).catch(function(error) {    		
			});		
        }
	});

Works perfect for my case, and is a nice short js code you can just add without changing <iFrame>'s in you html code.
(dont forget to add the player.js in your html)

**Comment by fisherinnovation** [comment]
Thanks for sharing your implementation.
