### ISSUE TITLE
Enhancement: allow title attribute support to be embed option, default is the video title string. 

### ISSUE THREAD

**Issue by MorganLKestner** [vimeo/player.js#654]
### Expected Behavior
Be able to pass a `string` for the `title` attribute on the `iframe`

### Actual Behavior
`iframe` elements need to have a title attribute to[ meet accessibility guidelines](https://dequeuniversity.com/rules/axe/4.1/frame-title?application=axeAPI). This can be done with embed code that is generated( i.e. <iframe title="how to make a site accessible" ), however, it's not possible when using [ReactPlayer](https://github.com/cookpete/react-player/issues/916) library. 

What would be great and eliminate several accessibility issues is to make the `title` attribute set to use the video title, and allow the user to update it with the options. 

`<iframe title="Default to be the video title" src="https://player.vimeo.com/video/3435454" width="640" height="640" frameborder="0"></iframe>`

**Comment by luwes** [comment]
@MorganLKestner thanks for the suggestion, `classes` can be replaced in the answer below with `title`. 

---

from https://github.com/vimeo/player.js/issues/640#issuecomment-708624074

this is something we rather not add to the library to keep it as lean and lightweight as possible. This snippet would give you a similar behavior:

CodeSandbox: https://codesandbox.io/s/vimeo-player-classes-dxcit?file=/index.html

```js
      var options = {
        id: 59777392,
        width: 640,
        loop: true,
        classes: "full-width another-class"
      };

      const player = createPlayerWithClasses(options);

      player.setVolume(0);

      player.on("play", function () {
        console.log("played the video!");
      });

      function createPlayerWithClasses(opts) {
        const player = new Vimeo.Player("made-in-ny", opts);

        player.ready().then(() => {
          player.element.classList.add(...opts.classes.split(" "));
        });

        return player;
      }
```

---

The setting of the iframe title could be with a js snippet like:

```js
        player.ready().then(async () => {
          player.element.title = await player.getVideoTitle();
        });
```

or even better is to use a pre-rendered iframe where you use progressive enhancement to create the player API. this is explained here: https://github.com/vimeo/player.js#pre-existing-player

with this method it's possible to set the iframe title or any attribute at the time of iframe creation.
