### ISSUE TITLE
Bug: Calling .destroy doesn't completely clean the DOM

### ISSUE THREAD

**Issue by balaurzor** [vimeo/player.js#656]
### Expected Behavior
On already initialized player, calling .destroy should destroy video and remove iframe + positioning div from DOM

### Actual Behavior
Video is not available anymore, including the iframe but the wrapping div of the iframe is still there and calling new Player() after .destroy() creates a stack containing the old div wrapping the iframe in order to position it + new iframe

### Steps to Reproduce
1. Create new player
2. Call .destroy
3. In success promise initialize a new player with different settings

![Screenshot_1](https://user-images.githubusercontent.com/4989776/102266064-3e2f8a00-3f18-11eb-9b52-357763ebfbf1.png)

**Comment by darkphen0m** [comment]
We have the same Issue. Will the problem be fixed soon?

**Comment by balaurzor** [comment]
You can work around it and cleanup the contents of the container yourself when calling .destroy
