### ISSUE TITLE
Hide "like", "watch later", "share" and Vimeo logo when using Vimeo.Player constructor 

### ISSUE THREAD

**Issue by justinmoon** [vimeo/player.js#657]
### Expected Behavior

I have a Pro account. I'm using the `Vimeo.Player` constructor. I would like to hide "like", "watch later", "share" and Vimeo logo on my videos.

### Actual Behavior

[I don't see embed options for these](https://github.com/vimeo/player.js#embed-options).

Here's what my player looks like

![image](https://user-images.githubusercontent.com/4335621/102314026-4f3bc380-3f37-11eb-830f-036ff19dec2a.png)

**Comment by fisherinnovation** [comment]
This feature is only for video owners and thus is not available in the public player API. To change the settings for your video, the controls can be located and toggled on the video settings page on vimeo.com.

eg, 
![Untitled](https://user-images.githubusercontent.com/306818/102359258-8bdedd80-3f7e-11eb-8aff-1008eb1f3588.png)

**Comment by justinmoon** [comment]
Thanks!
