### ISSUE TITLE
Firefox 47 won't load

### ISSUE THREAD

**Issue by DanielKeeble** [vimeo/player.js#66]
### Expected Behavior

To be able to watch a video in Firefox 47 that works in Chrome.
### Actual Behavior

Video does not load. See "Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead." in console log.

**Comment by DanielKeeble** [comment]
Exactly the same behaviour in Firefox 48.

**Comment by bdougherty** [comment]
Everything is working on the [api demo](https://player.vimeo.com/api/demo) page with Firefox 49, which is the latest. Do you have an example page where you're seeing the issue?

That CSP error shouldn't matter.

**Comment by bdougherty** [comment]
Everything seems to be working in Firefox 50, so I’m going to close this issue. Feel free to comment if you’re still seeing the original issue and I’ll reopen.
