### ISSUE TITLE
Full screen icon is not visible in Android WebView

### ISSUE THREAD

**Issue by rajeshembitel** [vimeo/player.js#660]
Vimeo player full screen icon is not visible and throwing below error:

The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features
t @ player.js:10

Tested with below embed code example with webview:
https://github.com/vimeo/player.js

**Comment by luwes** [comment]
thanks for the feedback @rajeshembitel 

do you have a screenshot of the player in that state? 
is it a small player width? 

have you enabled video fullscreen for the Android webview? I'm not so familiar with the webviews but it does seem that it requires some extra logic to get that working, probably for security reasons.

have you seen https://stackoverflow.com/questions/15768837/playing-html5-video-on-fullscreen-in-android-webview ?

**Comment by rajeshembitel** [comment]
Thanks for the quick response @luwes 

![landscape](https://user-images.githubusercontent.com/60956885/103612101-b43c7500-4f49-11eb-8775-c0995d5da6b5.jpeg)
![potrait](https://user-images.githubusercontent.com/60956885/103612107-b8689280-4f49-11eb-9179-d77b1b372520.jpeg)

I have attached both portrait and landscape mode. We can see full screen icon is missing in Vimeo player. (Ignore custom full screen icon in the screen shot)

 Yes, it's small player width (1080 x 2160 pixels).
 
 Tried all the below steps:
 
 1. Enabled full screen toggle in vimeo dashboard (https://vimeo.com/manage/488117928/embed#controls)
 2. Sent fake user-agent while loading webview (by doing this I can see volume controller but not full screen icon ).
 3. Tried with "playsinline" attribute.
 
 Below is the code which I am loading in Android webview
 
 `<!DOCTYPE html>
<html>
    <style type="text/css">
        html, body {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
            background-color: #<BACKGROUND_COLOR>;
            overflow: hidden;
            position: fixed;
            position: relative;
        }

        .flexbox {
            height: 100%;
            width: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <script src="https://player.vimeo.com/api/player.js"></script>
    </head>

    <body>
        <div class="flexbox">
            <div id="player"></div>
        </div>
    </body>



    <script type="text/javascript">
    var jsBridge = window.JsBridge;
    var player = null;

    function initVimeoPlayer(){
        var w = document.body.clientWidth;
        var h = document.body.clientHeight;

        var options = {
            url: '<VIDEO_URL>',
            autoplay: <AUTOPLAY>,
            playsinline: <PLAYSINLINE>,
            color: '<COLOR>',
            muted: <MUTED>,
            loop: <LOOP>,
            title: <TITLE>,
            quality: '<QUALITY>',
            portrait: true,
            byline: true,
            speed: true,
            transparent: true,
            width: w,
            height: h
        };
        player = new Vimeo.Player('player', options);

        player.on('timeupdate', function (data) {
            jsBridge.sendVideoCurrentTime(data.seconds)
        });

        player.on('play', function (data) {
            jsBridge.sendPlaying(data.duration)
        });

        player.on('pause', function (data) {
            jsBridge.sendPaused(data.seconds)
        });

        player.on('ended', function (data) {
            jsBridge.sendEnded(data.duration)
        });

        player.on('volumechange', function (data) {
            jsBridge.sendVolumeChange(data.volume)
        });

        player.on('texttrackchange', function (data) {
            jsBridge.sendTextTrackChange(data.kind,data.label,data.language)
        });

        player.on('error', function (data) {
            jsBridge.sendError(data.message,data.method,data.name)
        });

        player.ready().then(function () {
            player.getDuration().then(function(duration) {
                player.getVideoTitle().then(function(title) {
                    player.getTextTracks().then(function(tracks) {
                        var tracksJSON = JSON.stringify(tracks);
                        jsBridge.sendReady(title,duration,tracksJSON)
                    }).catch(function(error) {
                        jsBridge.sendInitFailed()
                        jsBridge.sendError('Init failed','init','init')
                    })
                }).catch(function(error) {
                    jsBridge.sendInitFailed()
                    jsBridge.sendError('Init failed','init','init')
                })
            }).catch(function(error) {
                jsBridge.sendInitFailed()
                jsBridge.sendError('Init failed','init','init')
            })
        }).catch(function (error) {
            jsBridge.sendInitFailed()
            jsBridge.sendError('Init failed','init','init')
        });
    }

    function seekTo(startSeconds) {
        player.setCurrentTime(startSeconds)
    }

    function pauseVideo() {
        player.pause()
    }

    function playVideo() {
        player.play()
    }

    function loadVideo(videoId) {
        player.loadVideo(videoId).then(function(id) {
            player.getDuration().then(function(duration) {
                player.getVideoTitle().then(function(title) {
                    jsBridge.sendReady(title,duration)
                }).catch(function(error) {
                    jsBridge.sendInitFailed()
                    jsBridge.sendError('Init failed','init','init')
                })
            }).catch(function(error) {
                jsBridge.sendInitFailed()
                jsBridge.sendError('Init failed','init','init')
            })
        })
    }

    function setVolume(volumePercent) {
        player.setVolume(volumePercent)
    }

    function destroyPlayer() {
        player.destroy()
    }

    function setColor(hexColor) {
        player.setColor(hexColor)
    }

    function setLoop(loop) {
        player.setLoop(loop)
    }

    function setPlaybackRate(playbackRate) {
        player.setPlaybackRate(playbackRate)
    }

    function playTwoStage() {
        player.play().then(function() {
            player.pause().then(function() {
                player.play()
            }).catch(function(error) {
                jsBridge.sendError(data.message,data.method,data.name)
            })
        }).catch(function(error) {
            jsBridge.sendError(data.message,data.method,data.name)
        })
    }

    function setCaptions(language) {
        player.enableTextTrack(language).then(function(track) {
            track.language = language
            track.kind = 'captions'
        }).catch(function(error) {
            jsBridge.sendError(error.name,error.name,error.name)
        })
    }

    function disableCaptions() {
        player.disableTextTrack()
    }

    </script>

</html>`

**Comment by luwes** [comment]
@rajeshembitel are you the owner of the above video? could you send the clip ID so I can double check the settings. this clip https://vimeo.com/488117928 is not the one in the screenshot

**Comment by rajeshembitel** [comment]
@luwes , Please check with this (https://vimeo.com/497154687) vimeo video ID.

**Comment by luwes** [comment]
I think this has to do with how the Android webview is created. are you using webchromeclient?

https://www.google.com/search?q=android+webview+fullscreen+video+webchromeclient&oq=android+webview+fullscreen+video+webchromeclient

**Comment by rajeshembitel** [comment]
Yes, I used WebChromeClient but it wasn't working.

However shared [link](https://www.google.com/search?q=android+webview+fullscreen+video+webchromeclient&oq=android+webview+fullscreen+video+webchromeclient) helped to resolved issue.

Now, I can see full screen icon but it's not much smooth as it is. Sometimes I needs to click 2 to3 times to make it work.

Thanks for your time
