### ISSUE TITLE
Progress Event is showing seemingly incorrect numbers

### ISSUE THREAD

**Issue by mattkenefick** [vimeo/player.js#661]
### Expected Behavior

Vimeo embedded player event for `progress` should return correct numbers for `seconds` and `percent`. 

### Actual Behavior

At beginning of video, `progress` event reports ranges of 20-40 seconds when actual time is between 1-15 seconds. Toward end of video, actual time is 11:11 but `progress` event reports "690" (11:30). Further, `progress` event reports complete 100% at the 11:21 mark out of 11:39 duration.

### Steps to Reproduce

Embed video on page and listen for progress event.

Video of the event happening:
https://www.youtube.com/watch?v=oVj_D9nayl4

**Comment by steve52** [comment]
@mattkenefick I believe this is the correct behavior of the `progress` event. The value it returns is how much of the video filed has loaded in the buffer, not what the current time in the video is. This is the same as the `progress` event in the `Media events` specifications.

https://developer.vimeo.com/player/sdk/reference#progress

If you're looking for events indicating what the `currentTime` in the video is, you are probably looking for the `timeupdate` event.
https://developer.vimeo.com/player/sdk/reference#timeupdate

Media events specs on MDN: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

**Comment by fisherinnovation** [comment]
Should be solved with the comment above, reopen if you are still having issues.

**Comment by mattkenefick** [comment]
Oof, good call. It's been quite the [never-ending] week.
