### ISSUE TITLE
setCurrentTime automatically triggers seeking event

### ISSUE THREAD

**Issue by AbhijitAQB** [vimeo/player.js#662]
### Expected Behavior
If I use `setCurrentTime` method to set the current time (> 0) of the player (after video is loaded and the player is instantiated) then `seeking` event should not be triggered automatically. I think `seeking` event should only be triggered when user manually seeks to a specific time.

### Actual Behavior
If I use `setCurrentTime` method to set the current time (> 0) of the player then automatically `seeking` event is triggered.
Due to this reason an issue is occuring in my project. Please suggest any solution for this.

### Steps to Reproduce
Check the fiddle:
https://jsfiddle.net/abhijitAQB10/5nhzd21s/16/

**Comment by fisherinnovation** [comment]
Technically any current time change that is requested from the player is considered a seek. The player doesn't see much difference between if that request was from the UI or from the API. 

You can test the HTML5 Media Event spec in this handy tool - https://www.w3.org/2010/05/video/mediaevents.html - You should see that current time changes are responded to with seek and seeked events.

There is however one difference that should be clear. In the case you are sharing, the seeking event is fired before playback begins. In the demo tool I shared, you will see that the seek event isn't surfaced until after playback begins. 

Given that this event configuration in the player is unlikely to change, feel free to share how this is negativly impacting your project and maybe we can help provide a solution.
