### ISSUE TITLE
thumbnail_url

### ISSUE THREAD

**Issue by davidkoberan** [vimeo/player.js#68]
please can you add functionality to get thumbnail url? it's already part of response from server.

**Comment by 153957** [comment]
Additionally, adding the`thumbnail_url_with_play_button` url would also be appreciated.

**Comment by svinkle** [comment]
I'd also like to see this feature added. Currently the thumbnail is included as a CSS background image. The issue with this is in Windows High Contrast mode, the thumbnail is not displayed. If I could get the `url` I could inject as a foreground `img` element.

**Comment by jeffsmith** [comment]
I'd also like to see this feature added to remedy the accessibility issue mentioned previously.

**Comment by luwes** [comment]
Sorry this is something that will not get added as an API method here.

It can easily be retrieved by making a request to the oEmbed API,
https://developer.vimeo.com/apis/oembed

There is a field `thumbnail_url_with_play_button` in that response as well.

**Comment by ffxsam** [comment]
@luwes I don't see a `thumbnail_url_with_play_button` field in the oEmbed response. And it's not documented as far as I can tell. Is there some way to retrieve the thumbnail image URL?
