### ISSUE TITLE
SSL Error : Video Thumbnail is not loading from vimeo

### ISSUE THREAD

**Issue by sarathnairck12** [vimeo/player.js#681]
### Expected Behavior

The image should be loaded without any ssl error

### Actual Behavior

The image url (eg: https://b.vimeocdn.com/ts/257/023/257023326_1280.jpg ) is throwing an SSL error on console

### Steps to Reproduce

See [here](https://jsfiddle.net/7p9cyvow/)

**Comment by fisherinnovation** [comment]
Can you provide insight as to how to allocated this image reference?

**Comment by sarathnairck12** [comment]
I think I got the embed link from _https://vimeo.com/37409842_

This is the embed code:

```
<iframe 
  allowfullscreen="" 
  description="Follow a paleontologist as he tries to find the first hunters of early animal life." \
  frameborder="0" 
  height="95%" 
  mozallowfullscreen="" 
  src="https://player.vimeo.com/video/37409842?title=0&amp;byline=0&amp;portrait=0&amp;color=fea239" 
  thumbnailurl="http://b.vimeocdn.com/ts/257/023/257023326_1280.jpg" 
  title="Traces of Early Animal Life" 
  uploaddate="2014-08-28 19:03:18"
  webkitallowfullscreen="" 
  width="95%"
 >
</iframe>
```

**Comment by fisherinnovation** [comment]
Ah yes, this is a old embed code which is out of date. You can find more details around working with these assets in our API at https://developer.vimeo.com/api/upload/thumbnails

Also these preview images should show in the player by default, so they should not be required as property in the iframe embed code.

More information about Player embedding can be found at https://developer.vimeo.com/player/sdk/embed
