### ISSUE TITLE
Iframe error - {"message": "We\u2019re having a little trouble.", "title": "Sorry", "view": 7}

### ISSUE THREAD

**Issue by i12code** [vimeo/player.js#683]
Sorry for trouble folks but I'm using c# to upload videos using `POST` to Vimeo with a redirect URL to the same page (asp.net blazor wasm page).  The upload aspect works great.  The redirect from vimeo passes the video URI as query string (`video_uri`) which I use that url in an iframe to show the video.  

However, when the redirect happens and I inject the `video_uri` query string var into the iframe,  I get

`{"message": "We\u2019re having a little trouble.", "title": "Sorry", "view": 7}`

which is not helpful at all in terms of debugging.  The iframe code was copied form the Vimeo site.  If I wrap the iframe code with html and body tags and view it in the browser, it works as expected.   The very same code doesn't work in the Blazor wasm app.  Any suggestions?  

### Expected Behavior
I would expect that the iframe would show the video.   
### Actual Behavior
iframe displays "{"message": "We\u2019re having a little trouble.", "title": "Sorry", "view": 7}"
### Steps to Reproduce

![image](https://user-images.githubusercontent.com/13510371/106394807-70575700-63b3-11eb-9156-506776b93c5e.png)

**Comment by luwes** [comment]
@i12code first thing I noticed is the URL of the Vimeo player. 
it should be `player.vimeo.com/video/506...` not `/videos/506...`

let me know if that fixes the issue.

**Comment by assal1601** [comment]
Thank you @luwes.  When the POST is done and Vimeo sends a redirect, why does the `video_url` query string says "/videos" with an "s?"  Please see the picture and notice the address bar.

**Comment by i12code** [comment]
[Signed with right account] 
Thank you @luwes. When the POST is done and Vimeo sends a redirect, why does the video_url query string says "/videos" with an "s?" Please see the picture and notice the address bar.

**Comment by luwes** [comment]
I agree it's a bit confusing but that's part of the data API, see here:
https://developer.vimeo.com/api/reference/videos#get_video

**Comment by i12code** [comment]
Thank you.  Resolved.
