### ISSUE TITLE
`fullscreenchange` event does not fire in iOS 14

### ISSUE THREAD

**Issue by timswalling** [vimeo/player.js#684]
### Steps to Reproduce

- Go to https://vimeo-player-bug.vercel.app/ on a device running iOS 14
- Interact with the video to verify that events other than `fullscreenchange` are being logged to the console
- Enter fullscreen
- Exit fullscreen

### Expected Behavior

The `fullscreenchange` events will be logged to the console when the video enters and exits fullscreen.

### Actual Behavior

The fullscreen event is not logged for either change.

### Notes

Tested on BrowserStack with an iPhone 12 running iOS 14 (UA `Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1`).

This does not appear to be an issue on earlier versions of iOS.

**Comment by bdougherty** [comment]
This seems to have been fixed at some point. Not seeing in Safari on iOS 17.4.1.
