### ISSUE TITLE
player.js and vimeo embeds have no option to disable fullscreen

### ISSUE THREAD

**Issue by eballeste** [vimeo/player.js#687]
### Expected Behavior
We want to disable users from using the fullscreen option but have no way to do so when embedding a video via js. Similarly there seems to be no option when doing regular html embeds.

### Actual Behavior
We get players with the option to go full-screen.
Also getting the following warning when embedding a video via js:
`player.js:2 Allow attribute will take precedence over 'allowfullscreen'.` which is annoying.

**Comment by luwes** [comment]
@eballeste it's possible to fix both issues when using the iframe embed directly explained here https://github.com/vimeo/player.js#pre-existing-player and removing `allowfullscreen` and `allow="fullscreen"` from the iframe embed code. 

Via JS which uses the oEmbed API it's unfortunately not possible but using the direct iframe gives you more control and is a little faster as well.

**Comment by Christophvh** [comment]
@luwes  the docs say that the embedded method is only a last resort. So it seems strange that this is the solution + that the 'worst' method is the fastest?
![Screenshot 2022-09-30 at 11 40 25](https://user-images.githubusercontent.com/9588070/193242274-d7e7890c-6c40-45c1-9b0b-a8a797d45099.png)
