### ISSUE TITLE
Error: Unknown player. Probably unloaded.

### ISSUE THREAD

**Issue by Benny739** [vimeo/player.js#688]
Create a player, destroy the player and then create a new player with a new video and then go in fullscreen mode. 
Fullscreen works, but it produces an annoying error in the console:
`Error: Unknown player. Probably unloaded.`

**Comment by KwehDev** [comment]
This has been an issue for us for several months as well. :+1: for a solution.

**Comment by anajuliabit** [comment]
I don't remember exactly how I solved it, but I think it was because I was reprocessing each video in a instance of the player. So I removed the `key` to make just a single instance of Vimeo and just change the source of the video when I move on to the next one.

**Comment by romanshvets** [comment]
+1

**Comment by houmark** [comment]
+1

**Comment by rkrishnan8594** [comment]
This bug should be fixed in `v2.16.1`.

**Comment by vishnu-Zysk** [comment]
I had a  query about In the mentioned vimeo package: @u-wave/react-vimeo is it possible to remove the user details like name shown on the video player ?
