### ISSUE TITLE
Add missing TypeScript definitions

### ISSUE THREAD

**Issue by peteyb** [vimeo/player.js#690]
### Expected Behavior
Calling `getChapters()` method should not throw a TypeScript warning

### Actual Behavior
`Property 'getChapters' does not exist on type 'Player'`

Whilst the method works and the chapter data is returned as per documentation it has resulted in me adding my own interface for a Chapter and extending the Player type definition

### Steps to Reproduce
```javascript
import Player, { VimeoChapter } from '@vimeo/player'

this.player = new Player(`{video_player}`, options)
this.player.getChapters().then(function (chapters: VimeoChapter[]) {
  ...
})
```

### Workaround (for vue.js)

```javascript
import Player from '@vimeo/player'
import { Chapter } from '~/api/models'

declare module '@vimeo/player' {
  interface Player {
    getChapters: VimeoPromise<Chapter[], Error>
  }
}
```

Low priority as the method works and a workaround is achievable but would be nice to not need to do this if the type definitions could be generated

**Comment by luwes** [comment]
@peteyb thanks for the feedback and potential solution. at the moment we don't officially support typescript. see here for more info and to upvote this potential feature https://github.com/vimeo/player.js/discussions/679
