### ISSUE TITLE
private video: not embeddable error

### ISSUE THREAD

**Issue by jonasfeige** [vimeo/player.js#691]
### Expected Behavior
Successfully embed private video on specific domain

### Actual Behavior
Receive a promise error: "https://vimeo.com/xxxxxxxxxx" is not embeddable.

### Steps to Reproduce
Embed a video that is hidden from Vimeo and restricted to specific domains using the player.js

This issue seems to be coming up again from time to time. In my case, I can successfully embed the videos on the front-end of the site I am working on, but – using almost exactly the same code – I get a "not embeddable" error in the admin afea of the same page.
The front-end and admin panel run on the same domain. There is also no other iframe being wrapped around the one rendered by `player.js`.
Any idea what might be causing this?

Also see:
#270 
#479 
#396

**Comment by luwes** [comment]
@jonasfeige thanks for your question. is it possible the admin area of the site is blocking the referrer? that is needed to determine the whitelisted domain.

**Comment by jonasfeige** [comment]
Thanks @luwes . There was indeed a global referrer policy from the admin panel blocking the iframe embedded by `player.js`.
For the admin panel, I have since switched to requesting an oEmbed from the Vimeo API, which allows me to send my own referrer header. This in combination with setting `referrerpolicy="strict-origin-when-cross-origin"` on the iframe has just solved this for me.
