### ISSUE TITLE
Muted Player hangs on iOS in browser when returning to page from other app

### ISSUE THREAD

**Issue by joostdekeijzer** [vimeo/player.js#695]
The context is a player that is muted or volume set to 0.

### Expected Behavior
When playing a video in a browser in iOS, changing app to eg. Home screen and then returning to the webpage I expect the video to continue (either automatically or by pressing the "play" button again).

### Actual Behavior
When playing a video in a browser in iOS (tested both Safari and Firefox on iOS 14), when returning to the page the video hangs: the play button changes to "playing" but the video does not continue nor is there progression in the timeline.

This happens both on vimeo.com as in my custom implementation based on player.js

This happens both when the video is playing when changing app or when you first press "pause".

Youtube videos on youtube.com do not have this issue, so the expected behaviour is "allowed" on iOS.

### Steps to Reproduce

1. Go to https://player.vimeo.com/api/demo in your iOS browser
2. Either set the video to "muted" or set the volume to 0 (zero) or both.
3. Play the video in the browser
4. Pause the video
5. Go to the iOS home screen
6. Return to your browser, your Vimeo page will be there
7. Press "Play"

And see nothing happens.

Pressing pause/play multiple times does not help.

**Comment by joostdekeijzer** [comment]
On https://player.vimeo.com/api/demo the issue **does not** exist, so I'll compare my implementation to that one.

**Comment by bdougherty** [comment]
I am not able to reproduce this now. If you're still having the issue, please open a discussion since this does not seem related to the Player API.
