### ISSUE TITLE
getQualities and setQuality not working with 'auto' on mobile only

### ISSUE THREAD

**Issue by daviddfm** [vimeo/player.js#700]
### Expected Behavior
getQualities() and setQuality() return and accept 'auto' which is the default setting on mobile not just on desktop

### Actual Behavior
getQualities() for mobile returns:
```
[
  {
    "id": "1080p",
    "label": "1080p",
    "active": false
  },
  {
    "id": "720p",
    "label": "720p",
    "active": false
  },
  {
    "id": "540p",
    "label": "540p",
    "active": false
  },
  {
    "id": "360p",
    "label": "360p",
    "active": false
  },
  {
    "id": "240p",
    "label": "240p",
    "active": false
  }
]
```
without auto which is the default and explains why no active is `active: true`
but on same video for desktop returns:
```
[
  {
    "id": "auto",
    "label": "Auto",
    "active": true
  },
  {
    "id": "1080p",
    "label": "1080p",
    "active": false
  },
  {
    "id": "720p",
    "label": "720p",
    "active": false
  },
  {
    "id": "540p",
    "label": "540p",
    "active": false
  },
  {
    "id": "360p",
    "label": "360p",
    "active": false
  },
  {
    "id": "240p",
    "label": "240p",
    "active": false
  }
]
```

### Steps to Reproduce
Watch this webinar replay which uses the player.  Quality button is on bottom-left of video.  Auto setting shows up on desktop but not mobile.

https://ilove.ewebinar.com/webinar/15-minute-ewebinar-walkthrough-and-demo-150/replay/111590

**Comment by luwes** [comment]
thanks for the feedback @daviddfm. on mobile there is no `auto` setting for the qualities I believe because it doesn't support adaptive bitrate switching but `getQuality()` shouldn't return `auto` and there might need to be a quality active, I'll have a look at this.

**Comment by derekcsm** [comment]
@luwes Any chance that the Vimeo team could add the ability to set quality explicitly (no auto) on mobile? I'm embedding the Vimeo player in a native app webview right now and we have the use case where we want to have different user-set data modes for everything. Having this feature would be super helpful!

**Comment by bdougherty** [comment]
It looks like the original bug here with the list of qualities is fixed, as `"auto"` appears in the list now.

Being able to set quality should work everywhere except for iOS right now. We will be moving to the new `ManagedMediaSource` sometime this year, which will enable setting quality there.
