### ISSUE TITLE
Ionic Capacitor - embedded private videos

### ISSUE THREAD

**Issue by ozimovski** [vimeo/player.js#701]
### Expected Behavior
Embedding private videos on hybrid mobile apps
 
### Actual Behavior
Video doesn't load (privacy issues of course) 

### Question
Is there a way to use vimeo player to embed video with specified domain setting?

**Comment by Gab-Metzger** [comment]
I'm having the same issue.
The privacy settings is set on a specific domain for my video on vimeo.
But as my capacitor host is `capacitor://localhost` it's not working.
Vimeo is not letting me change the protocol part of the host.
Capacitor is not letting me use `https` as protocol for the host.

Do you have any solution?

Thanks a lot,

**Comment by ozimovski** [comment]
Sadly, I am still without a good solution. 

My dirty fix is to make the video public (via an API) for 0.5 second, display the iframe and then make video private again. Luckily it is not a serious iPhone app, so I can afford a dirty fix.

**Comment by Gab-Metzger** [comment]
Not possible for me, I'm not the owner of the vimeo account but one of my customer 😢 
I thought of doing the oembed call with the native http plugin to avoid CORS issues and then display the video in an iframe but I don't know if it's possible.

**Comment by Gab-Metzger** [comment]
Hey @luwes ! Any idea of how we could manage that using hybrid mobile applications like cordova or capacitor?

**Comment by bianchinirick** [comment]
Any improvment on this? Any other solution?

**Comment by monurakkaya** [comment]
same here. 

```
const player = new VimeoPlayer(this.target.nativeElement, {
        controls: false,
        id: this.currentVideo.provider.id,
        responsive: true,
        playsinline: true
      });
```

player.ready() doesn't trigger. screen is empty.

**Comment by jarridlima** [comment]
To work on Android, the video owner need to add 'localhost' on domain field.

But this fix dont work on iOS. My customer is owner of the video on vimeo. What address he need to add on 'domain' field to work on iOS? Anyone knows?

**Comment by LorenzHope** [comment]
We have same problem, any solution are appreciated. on iOS, private videos are not showing also including ?h=<...> as full URL

**Comment by rkrishnan8594** [comment]
@LorenzHope What are the specific privacy setting (including any domain restrictions) that you have applied to the video that you're trying to embed?

**Comment by tamsel12** [comment]
Any solutions for this ? We have stuck on this past 1 week. Thanks

**Comment by bdougherty** [comment]
The domain-level privacy works on the referrer that the player embed page receives. For these apps that do not have an http referrer, I'd suggest setting the video to embeddable anywhere and then using the unlisted privacy setting. If you need more help, please [contact support](https://vimeo.com/help/contact).

**Comment by L422Y** [comment]
They do have a referrer, it's just prefixed with `capacitor://` and then the configured app domain (in our case anyway, it matches our web version of the app.
