### ISSUE TITLE
enterpictureinpicture event and getPictureInPicture method on Firefox

### ISSUE THREAD

**Issue by romain-w** [vimeo/player.js#708]
### Expected Behavior
The player should send a enterpictureinpicture event when entering into this mode on Firefox
The player should answer with a valid state when method getPictureInPicture is sent

### Actual Behavior
No event is returned when entering into PIP with Firefox self integreted button and the method getPictureInPicture cant detect if the player is a Pip (it sent false each time)

### Steps to Reproduce

Test on Firefox : 
[https://player.vimeo.com/api/demo/357274789](url)

Thanks in advance.

**Comment by GreenRecycleBin** [comment]
This is because Firefox doesn't yet support the Picture-in-Picture APIs [[0](https://caniuse.com/?search=pictureinpicture)].

**Comment by bdougherty** [comment]
Firefox still does not support the Picture-in-Picture API so our player doesn't know either. If they ever implement that API, it will start working properly through our Player API.
