### ISSUE TITLE
loadVideo doesn't allow custom options

### ISSUE THREAD

**Issue by shadle10** [vimeo/player.js#71]
### Expected Behavior

Would expect loadVideo to use the same options as the original player that was instantiated but it reverts to the default. I'm trying to make the title and the byline invisible on the player using the embedOptions to the initially instantiated player.
### Actual Behavior

The player isn't reflecting these options. If you click on each image it should bring up the associated video in the player above - which it does.  BUT, the title and byline are visible after clicking on multiple images (and they shouldn't be based on the options).
### Steps to Reproduce

You can view this at www.wplauncher.com/video-gallery.

**Comment by edgework** [comment]
I don't understand how this is an enhancement. Its clearly a bug.

**Comment by shadle10** [comment]
I totally agree with @edgework.  The only way that I could see to get around this is to not show the thumbnail version of the video and just play the videos once they've been clicked on (which isn't ideally how I would like to use it).

**Comment by Larzans** [comment]
I have the same problem, this does not make sense.
IMHO it is definitely a bug because it makes it impossible to use the custom settings with the new video as there are no getters and setters for those options, the only time when they can be set is during initialisation.

**Comment by 0xsven** [comment]
is this fixed? I don't see it in the docs?

**Comment by einwang** [comment]
Unfortunately I have the same problem, i also consider that as a bug. Interestingly it works for me one time to load a new video in a existing iframe with an initial video and video_id?.... options added to it but not a third time. When i try to load a third video it always resets all the options.
Are there any news on that? I really would appreciate your answer. Thank you!

**Comment by bortraws** [comment]
I'm having exactly the same issue. The first time player.loadVideo() is called, the player options are working fine but after a second loadVideo() the player simply ignores the options.

This is clearly a bug as it doesn't make sense at all.

**Comment by sergeycherevko** [comment]
+1. Within one year you are not fix this bug... guys, **# JUST DO IT**

**Comment by luwes** [comment]
This is fixed in the newest Vimeo player release. Thanks for your patience.

**Comment by FWDEsing** [comment]
It is not I am still ahving this issues!
