### ISSUE TITLE
How to get video id on live events

### ISSUE THREAD

**Issue by tcagkansokmen** [vimeo/player.js#711]
Hi there,

Trying to play my live event on player.js

But couldnt find "video id"

How to use it?

**Comment by fisherinnovation** [comment]
Live events can be made up of more than one video ID. So, you can use the event embed URL as the iframe src 

Example,
`<iframe src="https://vimeo.com/event/EVENT_ID/embed" width="640" height="360" frameborder="0" allowfullscreen allow="autoplay; encrypted-media"></iframe>`

Once you have that setup, you can call `getVideoId` https://github.com/vimeo/player.js#getvideoid-promisenumber-error which should return the ID of the video currently playing in the event.
