### ISSUE TITLE
Suddenly error message: An error occurred loading the video

### ISSUE THREAD

**Issue by dark1451** [vimeo/player.js#717]
hello 
The Contact function on the Vimeo homepage is blocked, so here.

I am using it by embedding it in my service using Vimeo Player.

From today, I suddenly noticed the following error message from player.js (Playback not possible)
>  Error: An error occurred loading the video.
>      at https://player.vimeo.com/api/player.js:2:8635
>      at Array.forEach (<anonymous>)
>      at _ (https://player.vimeo.com/api/player.js:2:8609)
>      at c._onMessage (https://player.vimeo.com/api/player.js:2:10375)

There wasn't a separate update and it's been going well.
I'm using Vimeo's custom plan, but due to an error, most of the customers on my site had difficulty playing the video.

What's wrong with suddenly?

thanks you

**Comment by fisherinnovation** [comment]
@dark1451 Can you provide a example of where you are seeing this issue so we can attempt to replicate?

**Comment by dark1451** [comment]
The problem seems to be solved now.

To explain the matter in more detail

1. There was a problem yesterday.
2. We replaced temporarily, from Vimeo player to our beta video system.
3. Yesterday was a holiday, so I'm going to check today.
4. I checked today's test account, and it looks like it's going well without yesterday's error.
  * Test account is set to play as a vimeo player.
5. From before the problem occurred until now, there have been no updates related to Vimeo players

**There is no error, so it is difficult for me to look deeply. Should I take a closer look? I'm worried.**

* We can share the problem page, but the page is for the payer and we need to deliver a test account. If you need a test account, please let us know by email and we can deliver it.

thank you

**Comment by dark1451** [comment]
close this for a while..

**Comment by blackmambahk** [comment]
FYI: This probably isn't that helpful but......

A few days ago we had clients reporting this exact same issue, similarly to above this is old code that hasn't changed in over a year. 

During loading several errors are thrown in sequence inside player.js


TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<DataView>'

TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Map>'

TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Promise>'

TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Set>'

TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<WeakMap>'

TypeError: Cannot read property 'state' of null

and then finally loadVideo rejects
Error: An error occurred loading the video.
    at player.js:2
    at Array.forEach (<anonymous>)
    at N (player.js:2)
    at l._onMessage (player.js:2)


We couldn't wait on a solution so we worked around the issue by no longer calling player.loadVideo and instead just rely on setting the frame src and listening for the load event. Some of the errors are still being thrown but it doesn't seem to stop the load event firing nor does it seem to have any impact on playback.

**Comment by dark1451** [comment]
@blackmambahk 
Oh, I too, after that situation happened, after a while, it happened again and I looked into the problem.

I had a similar implementation method, and I solved it in the same way.

The loadVideo function seems to have a problem in a particular situation.
