### ISSUE TITLE
Allow 'quality' setting on mobile

### ISSUE THREAD

**Issue by derekcsm** [vimeo/player.js#720]
When using the Vimeo player in a mobile web browser I would like to be able to instantiate the player with different quality modes e.g `options.quality = "360p"`

I'm aware that the player does not currently support "auto" mode on mobile, that's OK, I would just like to be able to explicitly set the player quality.

**Why I'm asking for this:**

Currently I'm working on a native mobile app where the client has a catalog of Vimeo videos that they want to be able to play. A major feature of the app is user set "data modes" that limit data usage throughout in different ways (this is a video chat app for large groups). Not being able to set the Vimeo video quality in the embedded webview is blocking us from offering the data modes as a complete feature to users.

> Note that I'm aware I could try to play the video by other means (not using the player.js library), but I would really like to use it since it keeps things simple and aside from this one thing it works great for our use case!

Thank you!

references: 
- https://help.vimeo.com/hc/en-us/articles/224983008-Setting-default-quality-for-embedded-videos
- https://github.com/vimeo/player.js/issues/248
- https://github.com/vimeo/player.js/issues/700#issuecomment-791485973

**Comment by derekcsm** [comment]
Turns out for a WebView on Android I can just trick the player into thinking it's on a desktop:

```webview.getSettings().setUserAgentString("Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/20 Safari/537.31");```

This solved my problem so I'll close the issue!

**Comment by fisherinnovation** [comment]
Great to hear, thanks for sharing the update @derekcsm
