### ISSUE TITLE
Disable fullscreen in ipad

### ISSUE THREAD

**Issue by rahulje9** [vimeo/player.js#729]
Is it possible to disable the video playing on fullscreen?
 When I press play on the player on the iOS, it is playing the video in fullscreen mode, whereas in android it is playing in the normal mode.

Sharing the code I'm using 

```
            <div>
            <iframe 
            src="https://player.vimeo.com/video/120061340?playsline=true" 
            frameborder="0" 
            allowfullscreen="false"
            allow="autoplay; encrypted-media"
            webkit-playsinline="true" 
            playsline="true"
            playsinline="true"
            style="position:absolute;top:0;left:0;width:100%;height:100%;" 
            controlsList="nofullscreen"
            title="Sample Video">
            </iframe>
            </div>
            <script src="https://player.vimeo.com/api/player.js">
            </script>

```

Please let me know if I'm missing something here

**Comment by bdougherty** [comment]
I believe the `allowfullscreen` attribute is a boolean, so you want to remove that attribute completely. The various playsinline attributes won't do anything either, nor will the `controlsList` attribute. Besides that, we fall back to the old WebKit fullscreen api that works on videos, so there is no way to prevent that without removing the fullscreen button from the embed settings of the video.
