### ISSUE TITLE
Set Thumbnail via Player API (Feature Request)

### ISSUE THREAD

**Issue by mattLummus** [vimeo/player.js#73]
We use Vimeo as an OVP and currently manage our source assets and images separately (via s3).
In order to use our poster images (thumbnails) with the Vimeo Embed, we will need to go through the [process of uploading through the API](https://developer.vimeo.com/api/upload/pictures) - which requires us to allocate picture resources, upload our thumbnails, and then set them.

For our use case and architecture, it would be cleaner/easier to just be able to pass the player an existing asset URL (s3) via the JS API and have it set client side.

**Comment by bdougherty** [comment]
Sorry, but we can't allow loading of arbitrary thumbnail urls for security reasons.
