### ISSUE TITLE
How to upload texttracks in vimeo using node js

### ISSUE THREAD

**Issue by webexpert123** [vimeo/player.js#730]
I have a Vimeo account and I have uploaded videos programmatically to vimeo using node js. Now I have to upload the texttracks(.srt,.vtt files) using node js. I got this link from Vimeo support : https://developer.vimeo.com/api/upload/texttracks? But this is not so helpful as I want to implement it using node js. Please help with the same. Thanks.

**Comment by bdougherty** [comment]
Hi @webexpert123, this repository is for a client-side library to control the Vimeo player embed. You'll find pretty extensive documentation on how to use the Vimeo API to upload text tracks on the page you linked to.
