### ISSUE TITLE
Disable player controls on Safari browser

### ISSUE THREAD

**Issue by ncham** [vimeo/player.js#731]
`
const playerOpts = {
   url: <video-url>,
   responsive: true,
   controls: false,
};
`
`const videoPlayer = new VimeoPlayer(<div element reference>, playerOpts);`

I've implemented vimeo player on my angular web app and it's working fine.
But MacBook Pro has a Touch Bar and when I play videos using Safari browser, player controls are visible on Touch Bar.
Since it's `controls: false`  , is there any way to hide that?

**Comment by MladenJanjetovic** [comment]
Yes this is not good since controls should be disabled

**Comment by bdougherty** [comment]
I am not aware of any way to hide those while a video is playing because the Touch Bar is controlled by the browser.
