### ISSUE TITLE
Fullscreen option now showing on Angular Application

### ISSUE THREAD

**Issue by luiza-avelino** [vimeo/player.js#733]
### Expected Behavior

To have a fullscreen button on the player.

### Actual Behavior
There is no option on the video bar
![image](https://user-images.githubusercontent.com/53008706/123463744-43098080-d5c2-11eb-8419-5588545be4a6.png)

It doesn't show any errors or warning. I tried a lot of things and none worked. When I was inspecting the generated iframe I realize that included these classes and attributes:

![printVimeo](https://user-images.githubusercontent.com/53008706/123465607-b6ac8d00-d5c4-11eb-956c-7304f4d92fe2.png)

### Steps to Reproduce

https://codesandbox.io/s/vimeo-code-361iu?file=/package.json

**Comment by luwes** [comment]
thanks for the feedback @luiza-avelino, the issue is that the parent iframe doesn't allow fullscreen.
hope this helps.

<img width="964" alt="Screen Shot 2021-06-25 at 2 41 54 PM" src="https://user-images.githubusercontent.com/360826/123477539-32f69e80-d5cc-11eb-9255-63c3bf16123e.png">

**Comment by luiza-avelino** [comment]
@luwes thanks for replying. This parent iframe it's from the codesandbox, on my project (outside the codesandbox) doesn't have this parent iframe and the issue is the same:

![image](https://user-images.githubusercontent.com/53008706/123557737-0330cd80-d769-11eb-8554-339a526aa917.png)

**Comment by luiza-avelino** [comment]
In case anyone had the same issue:

Our application it's a monolithic app and my backend was setup with 'Feature-Policy': self. 
I had to include https://player.vimeo.com in this configuration and it worked!
