### ISSUE TITLE
Player options not working when embedded as iframe?

### ISSUE THREAD

**Issue by camtez** [vimeo/player.js#735]
### Expected Behavior
Options such as controls="false" and title="false" should make them disappear on the embedded video player.

### Actual Behavior
They don't disappear.

### Steps to Reproduce
My iframe code within my website body:

`<iframe src="https://player.vimeo.com/video/570196134" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="autoplay"></iframe>`

My script within my website head:

```
<script src="https://player.vimeo.com/api/player.js"></script>

<script>

var Webflow = Webflow || [];
Webflow.push(function () {
  // DOMready has fired
  // May now use jQuery and Webflow API

  var options = {
    controls: "false",
    responsive: "true",
    title: "false",
    byline: "false",
    portrait: "false",
  };
  
  var iframe = document.querySelector('iframe');
  var player = new Vimeo.Player(iframe, options);
  
  $('#btnPlay').click(function() {
  	player.play();
	});
  
});

</script>

```

**Comment by fisherinnovation** [comment]
You can utilize these params in the embed URL used as your iFrame source. 

https://player.vimeo.com/video/570196134?title=0&controls=0

Keep in mind, as per the documentation (https://github.com/vimeo/player.js#embed-options) the `controls` option is only available to Plus, PRO, or Business members.
