### ISSUE TITLE
iOS full screen not capturing pause event

### ISSUE THREAD

**Issue by DanielKeeble** [vimeo/player.js#74]
### Expected Behavior
Capture pause event on iOS when video is full screen.

### Actual Behavior
Doesn't appear to be capturing the pause event (haven't checked to see if other events aren't working as well).

I'm guessing this is due to iOS opening it's "own" video player when full screen.

**Comment by bdougherty** [comment]
Not seeing this on the demo page (in the simulator at least). Do you have an example page where you're not seeing the pause event firing?

![nov-02-2016 11-55-41](https://cloud.githubusercontent.com/assets/15747/19936291/646b2282-a0f3-11e6-8882-fb53aca3b308.gif)

**Comment by DanielKeeble** [comment]
@bdougherty Closed in favour of #84
