### ISSUE TITLE
Take a screenshot of the embedded vimeo player

### ISSUE THREAD

**Issue by edoteee** [vimeo/player.js#740]
Is it possible to take a screenshot of the embedded vimeo player?

We currently embed vimeo livestreams on our website and a user would like to take a screenshot of video he/she is watching.

**Comment by fisherinnovation** [comment]
There is no built in functionallity in the Vimeo Player to accomplish this task. 

Depending on what you are attempting to accomplish with this image, you can look into maual solutions for this in either software of browser based solutions, or even something like https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API.
