### ISSUE TITLE
 Cannot set playsinline, autoplay and muted attributes for video on WebKit iOS

### ISSUE THREAD

**Issue by edgework** [vimeo/player.js#76]
For iOS, we would like to play Vimeo videos inline without them going full screen. Also we'd like to auto-play them muted. All of which is now possible.  https://webkit.org/blog/6784/new-video-policies-for-ios/

Can we get the ability to set these flags with the Vimeo player?

**Comment by bdougherty** [comment]
Please submit player feature requests in our [forums](https://vimeo.com/forums/feature_requests) or [contact support](https://vimeo.com/help/contact).

**Comment by SamPotts** [comment]
+1 for this
