### ISSUE TITLE
Vimeo SDK Video Play Error

### ISSUE THREAD

**Issue by akashsuresh** [vimeo/player.js#760]
### Expected Behavior

Video should play seamlessly

### Actual Behavior

Video stops and restarts from the beginning. Console shows error logs

![image](https://user-images.githubusercontent.com/5077344/134684050-144abb12-1652-465b-8474-776d92850d82.png)

### Steps to Reproduce

We have implemented the vimeo player sdk on our portal and we were facing the issue as shown in the error logs above. Kindly check

**Comment by bdougherty** [comment]
Looks like this was probably a temporary CDN issue. Please re-open with more details if you are still having this issue.
