### ISSUE TITLE
player.loadVideo failed to load with new video

### ISSUE THREAD

**Issue by nguyen-tam** [vimeo/player.js#761]
### Expected Behavior
video load successfully 
### Actual Behavior
message: video not exitst
### Steps to Reproduce
Upload a new video to Vimeo, the video now have id and ?h=SOME_HASH

player.loadVideo failed to load video because seem it's need hash to load video now.

**Comment by tomalabaster** [comment]
We are also facing this, we have references to the embedded URLs without the ?h=abc query param in hundreds of places... Can't see a way to sort this without going through and updating them all?

**Comment by nguyen-tam** [comment]
@tomalabaster you can call like this

player.loadVideo({
                    id: 76979871,
                    h:'37110065a5'
                })

They should update their documentation, but seem this team doesn't care about this sdk

**Comment by fisherinnovation** [comment]
Thanks for your responses and feedback. We have documented that the preferred method to embed videos when the video is set to a Private URL at https://github.com/vimeo/player.js#create-with-a-video-id-or-url
