### ISSUE TITLE
Player ignoring play() on iOS

### ISSUE THREAD

**Issue by andypillip** [vimeo/player.js#77]
### Expected Behavior

Calling `play()` inside a click-handler should make the video play.

First, the poster should get removed, the `progress` event should get triggered, then the video should be played.

### Actual Behavior

Nothing – not even an exception.

### Steps to Reproduce

http://codepen.io/andypillip/pen/BQBEVv

**Comment by bdougherty** [comment]
See https://github.com/vimeo/player.js/issues/31#issuecomment-234994118
