### ISSUE TITLE
player.on functions break when using vimeoRefresh

### ISSUE THREAD

**Issue by alex-kodr** [vimeo/player.js#771]
### Expected Behavior
Play/pause/end videos with CSS classes added/removed from the body and google tracking for video play amount time.

### Actual Behavior
I'm using a simple bit of jQuery to add/remove some CSS classes when a video is playing/paused/ended. Using the player.on function. This works fine. But When I try and integrate it into google tag manager and add the `setTimeout(function(){ window.__vimeoRefresh(); }, 3000);` function jQuery function breaks and no longer functions. With no errors in the console.

### Steps to Reproduce
Go here: https://limits.devweb.site/ and start playing the video, if you then pause the video, and look in the console you will notice CSS class 'paused' added to the body class. If you then play the video the 'paused' class is removed and 'playing' class is added. Press Vimeo play/pause button a few times and you will notice the add/remove class stops working.

If I remove:

`<script type="text/javascript" defer="defer" src="https://extend.vimeocdn.com/ga/97733245.js"></script>
    <script>setTimeout(function(){ window.__vimeoRefresh(); }, 3000);</script>`

It works perfectly fine, but then I can't track via google analytics. I've also tried re-positioning the above javascript file/tag to the footer etc. But still the same issue.

**Comment by bdougherty** [comment]
If the analytics script tag is after the embed on the page, I don't think you need to call `window.__vimeoRefresh()`. Feel free to reopen if you are still having issues here.
