### ISSUE TITLE
[Feature Request] Provide a way to remove the inline styles in the Vimeo player inside the iframe

### ISSUE THREAD

**Issue by ghost** [vimeo/player.js#776]
### Expected Behavior
Remove the inline styles in the element with an id of "player" inside the iframe
![image](https://user-images.githubusercontent.com/64056086/138978515-998b0302-314a-47b3-84bf-85d661657e9f.png)

### Actual Behavior
Currently, it has inline styles for width and height which makes the different videos not have the same dimensions. I have a fixed height and width for the video container, and I just want the Vimeo controls to be in full width, even if the video is not.
![image](https://user-images.githubusercontent.com/64056086/138978504-44d34c0f-585b-4a35-91b9-ea912a2ac760.png)

### Steps to Reproduce
I just copied and pasted this sample Vimeo code to JSFiddle:
https://github.com/vimeo/player.js#pre-existing-player

**Comment by lssamlyon** [comment]
Thanks for reporting this to us.  Let me enquire with the team about this issue and I will update this thread with more details.

**Comment by kredodevnicolas** [comment]
Thanks @lssamlyon . For clarification, I just need a way to remove the inline styles, not remove them by default.

**Comment by lssamlyon** [comment]
Great. Im going to promote this up to our discussions area for further consideration.
