### ISSUE TITLE
Private videos are not private anymore

### ISSUE THREAD

**Issue by gemp** [vimeo/player.js#778]
### Expected Behavior

Having an embedded video really private, not only hidden from Vimeo, which was guaranteed by the added final parameter in the URI that wasn't present in the embed code – until very recently and without notice.

### Actual Behavior

Since mid August or early September (when I discovered it with disbelief and dread as it broke my app) this private parameter, namely `h`, must be included in the embed code. Can anybody tell me how the video can be considered *private* now? Not Vimeo support which never answered my questions.

At first I thought it was a bug as I couldn't find any information about this change anywhere and even the embed code provided on Vimeo's website didn't include that change for about 3 to 4 weeks after it happened. Documentation about this behaviour here also changed only fairly recently: #758 & #775.

So, as Vimeo support plays dead about this, can anybody tell me WHY?

**Comment by fisherinnovation** [comment]
Beginning on Sept 14th, we added this additional parameter to all embed codes as an extra security measure for video owners. We apologize for any workflow disruptions this change might have caused but our customer's security is our top priority and we are constantly working on better ways to protect their content.

Please feel free to reach out to Vimeo cusomter support if more feedback is required here. https://vimeo.com/help/contact

**Comment by gemp** [comment]
It's not an "additional parameter", it's ***the*** parameter that actually did make a video private.

Now, hiding it from Vimeo and making it "private" is exactly the same.

And customer support, contacted not long ago after this change, _never_ answered my questions about this. Hence my message here.
