### ISSUE TITLE
after loadVideo player_id is not present in postMessage events anymore

### ISSUE THREAD

**Issue by sebastian-heinz** [vimeo/player.js#78]
### Expected Behavior
1) attached ?player_id=3 to video URL (https://player.vimeo.com/video/videoId?player_id=3)

2) First loaded event fires:
MessageEvent {isTrusted: true, data: "{"event":"loaded","data":{"id":102935595},"player_id":"3"}", origin: "https://player.vimeo.com", lastEventId: "", source: Window…}

4) after some time / video ended loadVideo(id) is called

5) Loaded even include player_id 
MessageEvent {isTrusted: true, data: "{"event":"loaded","data":{"id":116280524},"player_id":"3"}", origin: "https://player.vimeo.com", lastEventId: "", source: Window…}

### Steps to Reproduce
1) attached ?player_id=3 to video URL (https://player.vimeo.com/video/videoId?player_id=3)

2) First loaded event fires:
MessageEvent {isTrusted: true, data: "{"event":"loaded","data":{"id":102935595},"player_id":"3"}", origin: "https://player.vimeo.com", lastEventId: "", source: Window…}

4) after some time / video ended loadVideo(id) is called

5) Loaded event doesn't include player_id anymore.
MessageEvent {isTrusted: true, data: "{"event":"loaded","data":{"id":116280524}}", origin: "https://player.vimeo.com", lastEventId: "", source: Window…}

i use post message to send instructions to the Iframe and listen to them.

But after sending loadVideo(id) for the second time to the same iFrame it will stop telling me in its events which player_id it is.

**Comment by luwes** [comment]
I believe this was fixed recently. There was an issue where the iframe URL parameters were stripped after the 2nd loadVideo call. This is resolved. Please let us know if you see it behave differently. Thanks!

**Comment by sebastian-heinz** [comment]
I used the postMessage system to control the player, as the API was limited at that point in time.

https://gist.github.com/sebastian-heinz/4838c7b1c6100f878068bf823975c8e5
This is a gist of the vimeo controller I created a while ago. Please note as this is extracted from a project alot of references are not valid, but the general idea should be covered.

1) Attach a listener-method for the message events: 
```window.addEventListener('message', event => receiveMessage(event), false);```

2) Handle the received messages:
```
receiveMessage(messageEvent: any): SwPlayerState {

    let state: SwPlayerState = SwPlayerState.Undefined;

  const data = this.parseJson(messageEvent.data);
  let event = data.event;

    switch (event) {
      case 'ready': {
// When the player tells you hes ready, we need to let him know what events we want to subscribe to
        this.sendCommand('addEventListener', 'play');
        this.sendCommand('addEventListener', 'pause');
        this.sendCommand('addEventListener', 'finish');
        this.sendCommand('addEventListener', 'loaded');
        this.sendCommand('addEventListener', 'error');
        state = SwPlayerState.Ready;
        break;
      }
      case 'play': {
        state = SwPlayerState.Playing;
        break;
      }
      case 'pause': {
        state = SwPlayerState.Paused;
        break;
      }
      case 'finish': {
        state = SwPlayerState.Ended;
        break;
      }
      case 'error': {
        state = SwPlayerState.Error;
        break;
      }
      case 'loaded': {
        state = SwPlayerState.Loaded;
        if (this._player.AutoPlay) {
          this.play();
        }
        break;
      }
    }

    return state;
  }
```
Depending on the returned player state I then handled it.

If you have more specific questions feel free to ask.

For simply monitoring postMessage events, type the following in chrome dev tools:
`monitorEvents(window, "message");`

To test if its working type the following:

`window.postMessage("Hi window", "*"); `

result should look like this:
![capture](https://user-images.githubusercontent.com/7891178/38807338-d4e48b2c-41ae-11e8-85c2-dd0186780824.JPG)

Happy hacking!

**Comment by v3nt** [comment]
@sebastian-heinz - thanks! Will try that later in the week... D.
