### ISSUE TITLE
Intermittent Error Fetching embed code

### ISSUE THREAD

**Issue by colbyalbo** [vimeo/player.js#783]
### Expected Behavior
load player
### Actual Behavior
player fails to load
### Steps to Reproduce
Cannot reproduce, it happened to one user of our app that was using MS Edge/Windows 10

the error message reads: There was an error fetching the embed code from Vimeo.

We are using the CDN method to bring in the player.js, and We are currently rendering the iframe dynamically in an empty div.

screenshot from our error reporting tool below

![vimeo-error](https://user-images.githubusercontent.com/30237541/142009983-2532edfb-021f-4357-be8d-738c0722fb03.jpg)

![vimeo-cors](https://user-images.githubusercontent.com/30237541/142211115-c733d89e-799c-4300-84c5-c055c63b0163.jpg)

**Comment by colbyalbo** [comment]
Most users of our application are not experiencing this issue. And I cannot reproduce the exact error on my local environment either.

**Comment by lssamlyon** [comment]
Beginning on Sept 14th, we added this additional parameter to all embed codes as an extra security measure for video owners. We apologize for any workflow disruptions this change might have caused but our customer's security is our top priority and we are constantly working on better ways to protect their content.  Some more details about the hash and how it behaves with different privacy types is here in the [help article. ](https://vimeo.zendesk.com/hc/en-us/articles/224817847-Privacy-settings-overview)

Please feel free to reach out to Vimeo customer support if more feedback is required here. https://vimeo.com/help/contact

**Comment by colbyalbo** [comment]
@lssamlyon is there a mailing list i can join to be notified of this?

also, do you know if there is another way to get the hash code other than clicking the embed button?

**Comment by lssamlyon** [comment]
This repository is the best source of truth for functionality and updates,  we don't have any public facing changelog for the product as a whole.  

You can access the oEmbed endpoint, but both the video ID and Hash are required to retrieve videos with the Private/Unlisted status on Vimeo. [Some more details on this.](https://developer.vimeo.com/api/oembed/videos). They are also included in the response to /video for a content owner when using the authenticated endpoints in the main Vimeo API.
