### ISSUE TITLE
When embedding the player no volume control shown

### ISSUE THREAD

**Issue by rleinfellner** [vimeo/player.js#786]
### Expected Behavior
Player is embedded with
&muted=1&autoplay=1&loop=1&autopause=0&controls=1

Player is quite small on screen, so it may not display the bar due to size issues, but it means we cannot unmute autoplay video

### Actual Behavior

Play plays but  no volume control visible, play bar is shown

### Steps to Reproduce

Make a small play window and try to play

**Comment by eballeste** [comment]
I'm curious how you are getting autoplay to work with audio??? Most, if not all, major browsers will not autoplay a video if it has audio on.

**Comment by stefanfisk** [comment]
I'm also experiencing this issue. Is there any workaround?

**Comment by stefanfisk** [comment]
so it is by design that one cannot autoplay muted together with the volume control?

**Comment by pablosproject** [comment]
No idea, but it works for our project. Maybe a deep check in the lib code can help if you still experience the issue.

**Comment by rkrishnan8594** [comment]
@rleinfellner - In this instance, we would recommend that users use the up and down arrow keys to increase or decrease the volume. I'll pass along this feedback to our product team, though, as I recognize that this might not be intuitive for users.

@stefanfisk @pablosproject - We recommend that the `muted=1` param be applied alongside `autoplay=1`, as different browsers handle autoplaying videos with sound differently. They may either automatically mute the video or prevent autoplay altogether. Our player defers to the browser in this situation.

**Comment by stefanfisk** [comment]
@rkrishnan8594 I understand why autoplayed videos should be muted. But why is the volume control not rendered in this situation, and is there any way of enabling it?

**Comment by timbera** [comment]
@rkrishnan8594 volume icon is a part of a playbar. Checkout in your video setting if you have it enabled for your video.

**Comment by stefanfisk** [comment]
@timbera after contacting Vimeo's support I got help with fixing this, and the issue was indeed that the mute control was not enabled.

**Comment by ttvettuparambil** [comment]
So baseline as long as the Vimeo video is having autoplay with the help of mute attribute, there is no option at all for the user to have volume control correct?

**Comment by stefanfisk** [comment]
@ttvettuparambil the video just needs to have the control enabled. check out https://help.vimeo.com/hc/en-us/articles/12426259745937-Customize-the-video-player or contact Vimeo support to get help with enabling the mute control.

**Comment by ttvettuparambil** [comment]
@stefanfisk , so essentially you have to enable playbar->volume from inside vimeo video to embed in external website correct?. Can I add any attribute inside iframe to enable it.I tried using controls property to no avail.
