### ISSUE TITLE
We integrating Vimeo in flutter for LMS but video player into iframe the biggest challenge how to manage watch time for each user for that video

### ISSUE THREAD

**Issue by pankajit** [vimeo/player.js#788]
### Expected Behavior
We are looking at the behaviour of Vimeo watch time save for the video for each user.  please help me how to get that associate that user watch time for that video.

**Comment by fisherinnovation** [comment]
You can calculate how much of a video has been consumed by monitoring the video time (see https://github.com/vimeo/player.js#timeupdate).

Closing as this is not an issue report. Feel free to move future dicussions to https://github.com/vimeo/player.js/discussions
