### ISSUE TITLE
Video player gets in invalid paused state after skipping using arrow keys

### ISSUE THREAD

**Issue by remcohaszing** [vimeo/player.js#792]
### Expected Behavior

When skipping parts of a video, the video continues from the new position

### Actual Behavior

When skipping parts of a video, the video gets in a state where it’s sort of paused / frozen, but not really. Pressing the pause button, will put the player in a real paused state. Pressing play again sometimes works.

When skipping entirely to the end, the `ended` event isn’t fired.

### Steps to Reproduce

Based on this codepen: https://codepen.io/remcohaszing/pen/VwMEgdB

1. Watch the entire video
2. The text `Ended` appears

Now reload

1. Press play
2. Skip a significant amount using the right arrow key
3. The player is now in a weird state

**Comment by bdougherty** [comment]
I'm not able to replicate this. Are you still seeing the issue, @remcohaszing?
