### ISSUE TITLE
setMuted causing the video to pause when it's set to autoplay

### ISSUE THREAD

**Issue by trryan-nacpil** [vimeo/player.js#793]
We have a page that display a multiple video and they are set to mute, autoplay and in loop. but we got this problem on mobile phones when the controls is visible, the "tap to unmute" button is blocking the video. for us to fix that we found a workaround to toggle the mute and that works on some browser but not for safari. calling the "setMuted" method will pause the video. iv'e tried to call the "play" method right after the call and that kinda works but after a while some of the video will freeze/stuck (this does not happen when not calling the "setMuted" at all)

### Expected Behavior
setMuted should mute/unmute the video

### Actual Behavior
setMuted mute/unmute the video but it's pausing the video

### Steps to Reproduce
see it here
https://jsfiddle.net/y2dpofL8
just press the toggle mute button

(we found the issue on safari but i created the fiddle on chrome and it's also making the video to paused)

**Comment by benoitjoffre** [comment]
Hi, do you solved this problem ?, I have this same problem...

**Comment by trryan-nacpil** [comment]
Hello,
for this specific issue, nope.. but i made a workaround by disabling the controls if the video is muted and created a custom controls and use that instead whenever i need to pause and unpause the video

**Comment by mrdoinel** [comment]
Same issue here.
It seems the Vimeo Player is not working well with latest Chrome Policy regarding autoplay and muted videos.
The only way the video can be unmuted / muted without stoping it is to click into the video iframe first and then you can click on a button to mute / unmute.

**Comment by mrdoinel** [comment]
I am aware of the limitations introduced by jsfiddle and codepen : the code itself is inside an iframe which make it harder to test.
But I am still having the issue described above on a real domain on production for a new website.

The issue is not occurring in every domains. For example videos on vimeo.com will work fine because of Chrome Media Engagement Index. Chrome will allow mute/unmute video on these domain because the score is high (so unmute/mute is working on the Vimeo SDK demo).
https://developer.chrome.com/blog/autoplay/#media-engagement-index

**Comment by mrdoinel** [comment]
I created the exact same demo with CodeSandbox and now this is working well (because no iframe wrapping wrapping the code) : 
https://nw113u.csb.app/

**Comment by abdullahcel1k** [comment]
Hi do you find any solution ?

**Comment by Nikolai2** [comment]
We are having the same issue on iOS Safari.

**Comment by bdougherty** [comment]
Toggling mute on the example page is not pausing the video for me on iOS 17.4.1. @trryan-nacpil if you are still seeing the issue, feel free to re-open.
