### ISSUE TITLE
Safari looping stuck on iOS 14.4/14.7

### ISSUE THREAD

**Issue by pavsidhu** [vimeo/player.js#794]
### Expected Behavior

When using the Vimeo embed on iOS 14.4/14.7 and appending `loop=1`, I'd expect the video to loop around.

### Actual Behavior

The video flashes the first video frame, then the video preview image and repeats.

### Steps to Reproduce

https://pensight.com on iOS 14.4 or 14.7. I'm assuming versions between have the same issue.

**Comment by bdougherty** [comment]
I'm not seeing a video on that page anymore. If you're still seeing issues, please re-open this issue with an updated example.
