### ISSUE TITLE
Multiple videos control

### ISSUE THREAD

**Issue by GheorgheP** [vimeo/player.js#80]
### Expected Behavior
May be this can be done and I did not check out properly documentation, but here's my problem.
I have a page with mani videos, let's name it a gallery. By hovering on the video, I make a preview of the video, by setting the volume to 0. On mouse leave I stop the video. If the user clicks on the video continues playing, but already with volume up. Pretty cool.
### Actual Behavior
The problem is that when I click on video and it starts playing, then I hover on the other one, the playing ones stops. That means that I do not have separate control on each video.

**Comment by GheorgheP** [comment]
Ok, I begin to understand my problem. The problem is that you cannot play 2 videos at same time.

**Comment by bdougherty** [comment]
You can turn off autopause if you want: https://github.com/vimeo/player.js#setautopauseautopause-boolean-promiseboolean-unsupportederrorerror

It can also be a query string parameter on the iframe src url.
