### ISSUE TITLE
Expose fullscreen method (Feature Request)

### ISSUE THREAD

**Issue by another-novelty** [vimeo/player.js#806]
Hello!

Since the player is obviosly able to switch to fullscreen, it would be nice to expose this functionality.

This would make creating our own controls much more easy as well as taking advantage of native functionality, should it be available.

There was a [github issue](https://github.com/vimeo/player.js/issues/52) like this, but it is closed without actually adressing it.

**Comment by Marcdj-02** [comment]
+1; It would also be nice to capture this event and cancel it in order to create a implementation yourself, with still using the button in the control bar.

**Comment by ocripps24** [comment]
I agree, it is frustrating that this has not been addressed yet.

**Comment by JulienPradet** [comment]
This is actually exposed. What you have to do is:

* iframe has `allow="fullscreen"`  (in my case it was `allow="autoplay, fullscreen"`)
* iframe has attribute `allowfullscreen`
* URL has `&allowfullscreen=1` (ex: `https://player.vimeo.com/video/{{ videoId }}?autoplay=1&loop=1&autopause=0&background=1&muted=1&allowfullscreen=true`)

Source: https://www.allowfullscreen.com/vimeo

Then when you run `player.requestFullscreen()`, it enters fullscreen mode.

**Comment by bdougherty** [comment]
This was implemented in #562.
