### ISSUE TITLE
 [in IOS] stopped video when come back from background

### ISSUE THREAD

**Issue by ParkDongJo** [vimeo/player.js#813]
### Expected Behavior
set muted, loop option as true and move to background
player should be play when come back foreground

### Actual Behavior
set muted, loop option as true and move to background
player stopped when come back foreground

### Steps to Reproduce

URL : https://player.vimeo.com/video/681188991?h=0c5ae6247f&controls=0&loop=1&background=1&quality=720p&app_id=122963

**test Device Info**
- iPhone 12 mini / iPhone SE 
- IOS 15.0 / IOS 14.6

**Step**
1. open this [url](https://player.vimeo.com/video/681188991?h=0c5ae6247f&controls=0&loop=1&background=1&quality=720p&app_id=122963) on safari
2. move to background
3. come back foreground of safari
4. then player will stop

https://user-images.githubusercontent.com/16081624/157157717-3995135b-4ec4-4236-904d-d15ed68c8067.mov

**Comment by bdougherty** [comment]
@ParkDongJo could you please let us know if you are still seeing this issue in #1002?
