### ISSUE TITLE
How can I dynamically using the first frame as poster in vimeo video. 

### ISSUE THREAD

**Issue by jayeshcspl** [vimeo/player.js#818]
I display vimeo video using player.js in my home page. but it takes too much time to load video. So I want to display video first frame as a poster image. So user can see image until video load. How can i do that using player.js is there any optiion for that?

**Comment by lssamlyon** [comment]
Inside of the video settings you can set the thumbnail to a custom image or select an image from the video itself. The thumbnail button is on the top left of the manage/video page as an owner.  You can read more about how to set customizations to your video in this article.  https://vimeo.zendesk.com/hc/en-us/articles/224818047-Video-settings-overview#h_01FPB3Z0J66DTWXC6NXKVNP0S4 

Once you set the thumbnail image, when the player loads that video asset it will load that thumbnail by default, prior to initializing playback.
