### ISSUE TITLE
Error: There was an error fetching the embed code from Vimeo.

### ISSUE THREAD

**Issue by edgework** [vimeo/player.js#82]
This just started happening today.  Not on all videos but many/most.

### Expected Behavior

No errors

### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/5122883/20501502/010723a2-afef-11e6-8d84-075e0c6cae07.png)

Here's the text:
`
player.js:2GET https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F137280814&id=137280814&width=100%25&loop=false&byline=false&title=false (anonymous function) @ player.js:2l @ player.js:2(anonymous function) @ player.js:2Player @ player.js:2(anonymous function) @ vimeoFrame?video=137280814&playerId=2:51fire @ jquery.js:2863fireWith @ jquery.js:2975ready @ jquery.js:398completed @ jquery.js:93
vimeoFrame?video=137280814&playerId=2:1 XMLHttpRequest cannot load https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F137280814&id=137280814&width=100%25&loop=false&byline=false&title=false. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 503.
vimeoFrame?video=137280814&playerId=2:295 Vimeo Exception Error: There was an error fetching the embed code from Vimeo.(…)vimeoException @ vimeoFrame?video=137280814&playerId=2:295
vimeoFrame?video=137280814&playerId=2:296 Error: There was an error fetching the embed code from Vimeo.
    at XMLHttpRequest.a.onerror (player.js:2)
player.js:2 Uncaught (in promise) Error: There was an error fetching the embed code from Vimeo.(…)a.onerror @ player.js:2
player.js:2 Uncaught (in promise) Error: There was an error fetching the embed code from Vimeo.(…)a.onerror @ player.js:2
player.js:2 Uncaught (in promise) Error: There was an error fetching the embed code from Vimeo.(…)a.onerror @ player.js:2
player.js:2 Uncaught (in promise) Error: There was an error fetching the embed code from Vimeo.(…)
`

**Comment by bdougherty** [comment]
We've been having issues with the site today. Please see http://www.vimeostatus.com.
