### ISSUE TITLE
Vimeo player show's vimeo main page.

### ISSUE THREAD

**Issue by MaxNvk** [vimeo/player.js#823]
Hi there guys!

I have a question: in some cases users on platform which i develop have a trouble with Vimeo player. It shows vimeo main page instead of vimeo video. This trouble disappears hard reset of the page. But i can't reproduce this bug myself.

Can anyone hint me what it causes? And how i can fix it?

**Comment by lssamlyon** [comment]
I believe this behavior was related to an outage https://www.vimeostatus.com/incidents/zn2nhp99vqyr. This should be resolved now. Closing off this ticket, if you need further assistance feel free to raise a support ticket through your account settings.
