### ISSUE TITLE
Fullscreen mode: API can only be initiated by a user gesture

### ISSUE THREAD

**Issue by ps-victor** [vimeo/player.js#824]
We trying to implement the functionality of entering the fullscreen mode in case the user has turned the phone horizontally. The freshly load page crashes when we try to use `fullscreen.enter()` due to the following browser API requirement `API can only be initiated by a user gesture`. So, in fact we can use `fullscreen.enter()` only after the first interaction of the user with page, and it's normal, it's how the browser works to provide users safe behaviour.

However `fullscreen.enter()` functionality doesn't provide the ability to handle failed promise. So, the workaround is to switch to the original browser API, which is `requestFullscreen` (returns `Promise`)

### Expected Behavior

`fullscreen.enter()` should return Promise to have ability of handling it's failure with `catch`

### Actual Behavior

`fullscreen.enter()` crashes in case there were not interactions with a page

### Steps to Reproduce

run `fullscreen.enter()` right after the page is loaded (without touching it)

**Comment by bdougherty** [comment]
Is this an external library? Are you able to call `player.requestFullscreen()` on the Player API object? Please re-open if you are having trouble with the `requestFullscreen()` function in this library.
