### ISSUE TITLE
Error when loading new video after changing subtitle/caption

### ISSUE THREAD

**Issue by mikeamarkey** [vimeo/player.js#827]
### Overview
We've encountered an issue where changing the subtitle/caption of a video makes it so that another video cannot be loaded without throwing an error.
For our use cases, we load another video after the first one ends. However, we found that if we change the subtitle/caption during or before playing the video, that it causes an error when trying to load the next.
This only happens with the subittle/caption, and nothing else causes such an error.

### Steps to Reproduce
See the sandbox for barebones reproduction of issue:
https://codesandbox.io/s/vimeo-player-subtitle-issue-un4w44?file=/src/index.ts

1. Press play on the video
2. Change the subtitle/caption on the video to something (anything)
3. When the video ends you will see the "An error occurred loading the video" error

**Comment by mikeamarkey** [comment]
Update:

1. It seems that the actual error message that Vimeo shows in the embed is "Unhandled privacy error."
2.  It seems that the above error can be reproduced without even changing the subtitle/caption, but just by clicking on the "CC" button in the Vimeo controls menu

I'm having a hard time coming up with ideas on how to solve this... it seems strange to me that just clicking on a button and displaying a menu would have an effect on the loading of another video 🤔

**Comment by rkrishnan8594** [comment]
Hi @mikeamarkey - thanks for reporting this issue and including a CodeSandbox link. I'm able to reproduce this consistently but not currently sure of what would be causing this behavior. I'll take a longer look and follow up with more insight.

**Comment by rkrishnan8594** [comment]
We have a fix ready for this bug that will be deployed sometime within the next 1-2 days (I'll share an update here when it's out). This is a player bug, so it won't require updating the version of this library.

**Comment by rkrishnan8594** [comment]
This issue should now be fixed.

**Comment by mikeamarkey** [comment]
@rkrishnan8594 Thanks so much for the quick followup... just confirmed that it's fixed. Really appreciate it! ✌️
