### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by bobpies** [vimeo/player.js#836]
### Expected Behavior
no errors

### Actual Behavior

SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
    at E (player.js:2:6653)
    at player.js:2:20089

### Steps to Reproduce

Just embedding the Vimeo player.js on our pages I get the Syntax error above
I'm running ruby on rails server

**Comment by Stefano1964** [comment]
https://github.com/vimeo/player.js/issues/833
