### ISSUE TITLE
iOS Fullscreen getPaused() always returns true

### ISSUE THREAD

**Issue by DanielKeeble** [vimeo/player.js#84]
### Expected Behavior
To show the correct paused state of the video.

### Actual Behavior
As described in title.

### Steps to Reproduce
See this [Codepen](http://codepen.io/anon/pen/bBqPMg?editors=1010).

**Comment by DanielKeeble** [comment]
cc @bdougherty

**Comment by DanielKeeble** [comment]
@bdougherty Has there been a server side change in relation to this? I suspect it may have recently been fixed.

**Comment by bdougherty** [comment]
@DanielKeeble yes, sorry I forgot to update this ticket when we pushed out the fix in the player.

**Comment by DanielKeeble** [comment]
@bdougherty No worries! Thanks for the update, and especially the fix.
