### ISSUE TITLE
'Playing' event firing prematurely?

### ISSUE THREAD

**Issue by AVTPJ** [vimeo/player.js#841]
### Expected Behavior
'Playing' event should fire when actual video frames are being played, not before. Thumbnail should not be seen.

### Actual Behavior
Video thumbnail is displayed for a fraction of a second, and then video plays.

### Steps to Reproduce
1. Initialise Vimeo player hidden (visibility etc.)
2. Toggle play
3. Display video when 'playing' event fires
4. You can see video thumbnail for a fraction of a second

Example:
https://jsfiddle.net/avt_pj/hqgtram0/31/

**Comment by rkrishnan8594** [comment]
The [`playing` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playing_event) is fired by the `<video>` element itself, so we don't control the timing of that in our player.
