### ISSUE TITLE
Can change video quality settings for some videos only

### ISSUE THREAD

**Issue by tharwi** [vimeo/player.js#844]
Some of my videos rendered in the iOS web view show the quality settings to toggle between different qualities. But in other videos, I can only see 360p quality. Is there any specific reason for this behavior?

I'm using a React Native Web View to render the Vimeo player.

**Comment by rkrishnan8594** [comment]
Hi @tharwi - can you share the clips you're looking at and the device + device OS that you're using to view these clips within the RN app?

**Comment by tharwi** [comment]
[This](https://vimeo.com/731420165) is a video where I can only see 360p quality in the iOS Web view, But in the Android Web View, I can see other qualities as well.

Device - iPhone SE, OS - iOS 15.5

**Comment by tharwi** [comment]
@rkrishnan8594 

![IMG_0151](https://user-images.githubusercontent.com/108951960/179824860-45b2b4c0-b1d7-4f98-b132-1488369d1ab2.PNG)
![IMG_0152](https://user-images.githubusercontent.com/108951960/179824905-f7cf1383-2e1e-4254-bc37-0db935fa07ec.PNG)

**Comment by rkrishnan8594** [comment]
Hi @tharwi - we will be making updates to the logic that dictates progressive MP4 quality options available on players utilizing the HLS format (most often iOS). I will follow up on this issue when those updates have been made.

**Comment by tharwi** [comment]
Hi @rkrishnan8594, thanks for the reply. Waiting for the update.

**Comment by nunnun** [comment]
@rkrishnan8594 I'm also facing this issue. Could you please let us know any updates?

**Comment by mrcogollor** [comment]
Hi @rkrishnan8594 I'm also facing this issue.

When I'm broswering my site in mobile iOS (Iphone) using the vimeo debugger its always giving 360p quality, but if I do in an Android device its giving more qualities

Why this is happening? Any solution?

This is the quality that I'm getting with an Android device and Chrome for the same ID Vimeo Video

![Captura de Pantalla 2023-04-12 a las 17 38 06](https://user-images.githubusercontent.com/1006242/231509210-140dcd2a-deb8-47a7-a319-8ab27ad020aa.png)

and this is the quality from an Iphone Device with Chrome

![Captura de Pantalla 2023-04-12 a las 17 36 37](https://user-images.githubusercontent.com/1006242/231509598-db9e3cf4-fd39-4ec5-877f-5a17973151ef.png)

**Comment by bdougherty** [comment]
What's happening here is that on Android, we are using the `MediaSource` API to play back the videos, so all qualities are available to select because we have control over playback. On iOS, we are using the built-in HTTP Live Streaming, which the browser controls the selection logic and we do not have a way to change that. The 360p file is available as the only other option because we do not allow playback of any other progressive videos.

We will be switching to the new `ManagedMediaSource` on iOS sometime this year, at which point all browsers will show the same options for quality.
