### ISSUE TITLE
player js is not working on streaming videos, why you dont actualice if you have new options this falls?

### ISSUE THREAD

**Issue by rubendarioCTO** [vimeo/player.js#848]
Hi,
The multimedia department tells us that from September the streamings will change and become recurring events. What is our surprise in the IT department that when testing the new events they appear with an "event" in front and therefore the streaming is not displayed with its component. So, do you have any component updates to support streaming from September? Thank you

![image](https://user-images.githubusercontent.com/111990779/186433801-aa4e89ea-3adc-47cb-82b9-bb5431ed36b7.png)

![image](https://user-images.githubusercontent.com/111990779/186433580-0fc2976e-d0d9-494e-91dd-19d2262f044b.png)

**Comment by rkrishnan8594** [comment]
Hi @rubendarioCTO - you will want to ensure that you're supplying the full URL to the `data-video-url` or `data-video-id` attribute on your element, i.e `https://vimeo.com/event/2374315` and **not** `event/2374315`.

**Comment by rubendarioCTO** [comment]
OK, Thanks
