### ISSUE TITLE
Refused to execute script from 'https://player.vimeo.com/api/player.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by mbacon40** [vimeo/player.js#85]
https://player.vimeo.com/api/player.js is a broken link that is redirecting to vimeo.com. Please update your documentation with an updated URL.

**Comment by ron666** [comment]
Yeah I'm experiencing the same issue. Can you indicate the updated URL or fix the one you already have, please?

**Comment by bdougherty** [comment]
Sorry about that! Should be working again now.

**Comment by ron666** [comment]
Thank you very much

**Comment by JCMais** [comment]
@bdougherty this is happening again, can you verify it?
![image](https://cloud.githubusercontent.com/assets/1041647/21330301/02153824-c624-11e6-9283-7fc1ed13371f.png)

**Comment by ron666** [comment]
@bdougherty Yes it is redirecting to http://vimeo.com

**Comment by pieterjandesmedt** [comment]
I'm experiencing the same issue.

**Comment by bdougherty** [comment]
Ugh sorry again. It's fixed now.

**Comment by kennygfunk** [comment]
This is still happening for me

**Comment by JCMais** [comment]
@kennygfunk clear your cache, the redirect is probably cached.

**Comment by kennygfunk** [comment]
@JCMais you were right, seems to work now. Thanks!

**Comment by wesjones** [comment]
@bdougherty this is showing up again now. So everyone is broken.

**Comment by sulym-roman** [comment]
I confirm. Have the same problem atm.

**Comment by berkandirim** [comment]
I have the same problem.

**Comment by williambout** [comment]
Still happening

**Comment by bdougherty** [comment]
Fixed again. Sorry about that. We should have a permanent fix in place soon that will prevent this from happening again.

**Comment by joshnorwich** [comment]
This error has started occurring again sometime within the last 20 minutes.

**Comment by fchicken** [comment]
I encounter the same problem today.

**Comment by jollycic** [comment]
I'm experiencing the same issue right now.

**Comment by saldan** [comment]
Me, too. `https://player.vimeo.com/api/player.js` is not reachable

**Comment by purts** [comment]
I have the same problem.

**Comment by saldan** [comment]
I switched to the local version, downloaded via
`bower install vimeo-player-js`
Here it is for your convenience:
[player.js.zip](https://github.com/vimeo/player.js/files/833562/player.js.zip)

**Comment by jonathannew** [comment]
same problem for us too

**Comment by lexcode** [comment]
Same here, for speed I just made a copy of player.min.js from dist into my local.

**Comment by pramodgadekar** [comment]
<add name="X-Content-Type-Options" value="nosniff" /> remove this form response header
