### ISSUE TITLE
Warning: Allow attribute will take precedence over 'allowfullscreen'.

### ISSUE THREAD

**Issue by Toast1** [vimeo/player.js#851]
Is there a way to get rid of this warning on embedded video with js? I can't seem to find any real solution on this error and whatever I try, doesn't seem to work.
I don't wanna use the direct iframe method.
This is the warning:
![AllowFullscreen](https://user-images.githubusercontent.com/16019836/190110385-2451f647-7cf0-4952-b826-bd41992b470c.png)

**Comment by ocripps24** [comment]
The Vimeo devs should either remove the 'allowfullscreen' attribute or place it before the 'allow' attribute.

**Comment by Meuss** [comment]
Been waiting for a fix for this for a long time now :-/

**Comment by jdreetz** [comment]
We've updated our embed code generation on Vimeo.com to only include the `allow` attribute, so you shouldn't see the warning anymore when using the update embed code. 

If you have existing embeds, you can remove the `allowfullscreen` attribute if your target browser's don't require it.
