### ISSUE TITLE
I get error on getPlayed() when using in apple systems

### ISSUE THREAD

**Issue by leonioron** [vimeo/player.js#861]
### Expected Behavior
At the end of the video I use the getPlayed() function to calculate the percentage of the video watched by the user and generate a score for the user.
Ex:

percentage_watched == 100% => 5 stars,
80% < percentage_watched < 100% => 4 stars, ...

`this.videoPlayer.on('loaded', this.readyCallback)`
`this.videoPlayer.on('ended', this.endedCallback)`

`readyCallback = () => {`
`        this.videoPlayer.getDuration().then((duration) => {`
`            this.videoFullTime = duration`
`            this.loaded()`
`        }).catch(() => { })`
`    }`

`endedCallback = () => {`
`        this.videoPlayer.getPlayed().then((played) => {`
`            console.log(played,'getPlayed result')`
`            console.log(this.calculateWatchedPerc(played),'perc_watched')`
`            this.courseService.videoConclusion(this.oda.match, this.calculateWatchedPerc(played)).subscribe(() => {`
`                this.finished.emit()`
`            })`
`        }).catch(() => { }) `    
`     }`

### Actual Behavior
Some tests done on apple systems (macOS, IOS) showed that the getPlayed() function returned an empty array, that is, the percentage_watched returned 0% even when we had watched the entire video.

**Comment by bdougherty** [comment]
Do you happen to remember any of the details from the devices that didn't work? This API is just passing back the value we read from the `<video>`, so it's possible certain browsers and versions do not track that. As far as I know, support should be pretty universal these days, but please re-open if you are still seeing issues here.
