### ISSUE TITLE
Remove share and like button using embed options

### ISSUE THREAD

**Issue by Ellathet** [vimeo/player.js#865]
When using the iframe, `https://player.vimeo.com/video/`. I can using embed options like: color, title and others. I want remove like and share buttons from right side of player. Have any option to do this?

![image](https://user-images.githubusercontent.com/76699403/199258670-d7430a82-624b-4253-b836-86c58819dde7.png)

**Comment by rkrishnan8594** [comment]
We don't currently support removing those buttons via the SDK, but you can control whether they're displayed or not on vimeo.com:

<img width="399" alt="Screen Shot 2022-11-02 at 9 36 51 AM" src="https://user-images.githubusercontent.com/5016823/199504073-0a9a0b69-649f-4364-9ca6-c6707a322479.png">
