### ISSUE TITLE
Tap to unmute button is shown even when controls=0 or background=1 on mobile devices

### ISSUE THREAD

**Issue by emidaniele** [vimeo/player.js#867]
### Expected Behavior
No controls should be shown when using `controls=0` or `background=1`

### Actual Behavior

The `Tap to unmute` button is shown 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/9386448/199352590-ba289a5e-81f8-43f7-9a10-1c03bfb24cad.png">

### Steps to Reproduce
1. Embed a vimeo player.
2. Add `controls=0` or `background=1`
3. Load the player on a mobile device
4. The `tap to unmute` button is shown.

Codepen to reproduce (load it in a mobile device or enable a mobile view in the dev tools): https://codepen.io/emidaniele/pen/yLEeZvP

**Comment by rkrishnan8594** [comment]
Thanks for reporting. We'll take a look at this issue tonight with the goal of having a fix released tomorrow.

**Comment by ellafitz** [comment]
+1 same issue here

**Comment by ianjwhitmore** [comment]
Same issue here.

**Comment by dikod** [comment]
any updates?

**Comment by janwouter** [comment]
Same here, any updates?

**Comment by rkrishnan8594** [comment]
We're working on deploying a fix this morning - will share an update when that is fully deployed and confirmed.

**Comment by rkrishnan8594** [comment]
The fix has been deployed. Thanks for your patience.

I'll leave this thread open for a bit longer - please follow up in a comment if you're still experiencing this bug. For unrelated bugs, please file a new issue.

**Comment by liamcrean** [comment]
Fixed here. Thanks.

**Comment by ellafitz** [comment]
Fixed here, thanks rkrishnan!

**Comment by dikod** [comment]
Fixed here as well. thank you!
