### ISSUE TITLE
Playback Rate display in Player doesn't change when i use Player.setPlaybackRate

### ISSUE THREAD

**Issue by chidimi** [vimeo/player.js#872]
### Expected Behavior
When using Player.setPlaybackRate, Playback Rate display in Player should change.

![image](https://user-images.githubusercontent.com/39594940/200501143-a1310c0a-e8fa-4487-a740-4028ed80e44d.png)

### Actual Behavior
when using Player.setPlaybackRate, playback rate actually changes, but display in player doesn't change.

### Steps to Reproduce

1. Go to https://player.vimeo.com/api/demo
2. Use set playback rate.
3. Check playback rate display in player.

**Comment by rkrishnan8594** [comment]
Thanks for reporting. We'll be investigating this issue today and will follow up once we have a timeline for resolution.

**Comment by rkrishnan8594** [comment]
This issue has now been fixed.
