### ISSUE TITLE
[Help] Force Vimeo player to fill the entire div

### ISSUE THREAD

**Issue by viny-movember** [vimeo/player.js#878]
I'm having a hard time making the Vimeo player display in the dimensions I want. I need the video to stretch to take the entire div (notice the red background of the div). This is the code for the embedded video;

```
<Container>
    <iframe 
    src={`https://player.vimeo.com/video/76979871?h=8272103f6e&autoplay=true&controls=false&loop=true&muted=true`} 
    frameBorder="0" allow="autoplay; fullscreen" allowFullScreen 
    ></iframe>
</Container>

```
![Screenshot from 2022-12-02 14-22-30](https://user-images.githubusercontent.com/104042423/205403770-3d300320-cdee-42d9-85be-e8369fffa1e9.png)

**Comment by oliviaoddo** [comment]
```
<Container>
  <StyledVideoWrapper>
    <iframe src="https://player.vimeo.com/video/76979871?h=8272103f6e&autoplay=true&background=true&loop=true" />
  </StyledVideoWrapper>
</Container>
```

```
const Container = styled.div`
  width: 269px;
  height: 182px;
`;

const StyledVideoWrapper = styled.div`
  width: 100%;
  height: 100%;
  border-radius: 8px;
  > iframe {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 147.8%;
    height: 100%;
  }
`;
```

To get the width percentage for the iframe, divide the width of your container by the height of your container times 100.

`269 / 182 * 100 = 147.8%`
