### ISSUE TITLE
doNotTrack is not defined

### ISSUE THREAD

**Issue by ocripps24** [vimeo/player.js#885]
**Expected Behaviour**
No errors in console 

**Actual Behaviour**
Uncaught SyntaxError: Unexpected end of input (at {video_id}?h={hidden_vid_ref}&dnt=1&app_id={app_id}:1:64281)

Uncaught ReferenceError: doNotTrack is not defined
    at {video_id}?h={hidden_vid_ref}&dnt=1&app_id={app_id}:1:83581
    at {video_id}?h={hidden_vid_ref}&dnt=1&app_id={app_id}:1:83926

**Steps to Reproduce**
The error appears to happen on load, videos are set with the dnt option set to true but disabling it has no effect on the error.

I've not noticed this before and it appears to be cross-browser

I'm using "@vimeo/player": "^2.18.0",

**Comment by oliviaoddo** [comment]
@ocripps24 having the same issue. Please keep me updated if you find a solution!

**Comment by rkrishnan8594** [comment]
Thanks for the report. This is a known issue with one of the player's monitoring dependencies that we expect to have resolved early next week. There should be no impact to player or player.js functionality.

**Comment by rkrishnan8594** [comment]
This issue is now resolved.

**Comment by JulieCardinale** [comment]
Thanks a lot !
