### ISSUE TITLE
Missing { after function body

### ISSUE THREAD

**Issue by RBN2208** [vimeo/player.js#887]
### Expected Behavior
No errors in console

### Actual Behavior
Uncaught SyntaxError: missing } after function body
note: { opened at line 1, column 184

On the page are serveral videos, only one video throwing this error (almost of the end of site). The video is configured as all the other ones. 
It seems that the request from that video throws this error?! 
Any idea / tipps ?

**Comment by rkrishnan8594** [comment]
Thanks for reporting. Can you provide a link to where this error can be reproduced?
