### ISSUE TITLE
Video not loading/Playing on Safari

### ISSUE THREAD

**Issue by martijn-megabite** [vimeo/player.js#888]
### Expected Behavior
When pressing the button, the getpause() checks if the video is playing or not (adding a css overlay on pause).
if video is paused, remove the css overlay and play the video.

### Actual Behavior
On Chrome, Firefox, Edge and Opera the overlay is removed and video is loaded and played when pressing the button.
On Safari (16.1) the css overlay is removed, but video is not loaded. -> console shows a bad request, (failed to load recourse, the server responded with ..url..status 400
I can get the video title, I can check the pause, it says its ready.
This only happens in Safari. => when using Safari's development tools, you can pick a user-agent, selecting Edge, Chrome or Firefox there will also not have this issue and play the video. 

### Steps to Reproduce
I can provide link in a PM or something. It should not be public yet.

**Comment by rkrishnan8594** [comment]
Thanks for the report @martijn-megabite. In order to investigate this issue, we will need some method to reproduce it.

**Comment by martijn-megabite** [comment]
@rkrishnan8594 Can I send you the link directly? We can't have it on a public forum yet.

**Comment by rkrishnan8594** [comment]
Sure.

**Comment by martijn-megabite** [comment]
@rkrishnan8594 Any news on this?

**Comment by rkrishnan8594** [comment]
Thank for your patience - this issue should now b resolved.
