### ISSUE TITLE
Breaks Isomorphic React/Redux build

### ISSUE THREAD

**Issue by reidblomquist** [vimeo/player.js#89]
### Expected Behavior
Including package makes things work

### Actual Behavior
Bundle crashes and burns

### Steps to Reproduce
1. Clone https://github.com/kriasoft/react-starter-kit
2. npm install @vimeo/player
3. add `Import Vimeo from '@vimeo/player'` to any active component (for my test I chose header)
4. see resulting crash - basically dumps the whole contents of dist and exits with a code 1

Hoping you might have some insight into this issue - kind of stumped right now!

Cheers.

**Comment by reidblomquist** [comment]
After a bit more review/asking peers it seems this package makes assumptions about window. Might be handy to note that in the registry/readme as it makes the npm package kind of worthless in modern react/redux configs. Would you be open to a PR outlining that info?

**Comment by bdougherty** [comment]
Sure. Also open to modifications to make it work. Going to close this issue though, because it seems like it's basically the same thing as #32.

**Comment by reidblomquist** [comment]
@bdougherty awesome thank you!
