### ISSUE TITLE
RangeError: Seconds must be a positive number less than the duration of the video

### ISSUE THREAD

**Issue by wesbos** [vimeo/player.js#890]
I'm seeing this error continually pop up when trying to re-instate the currentTime of a video.

I was initially doing this:

```js
player.on('loaded', () => {
  player.setCurrentTime(progressTime);
});
```

The error its giving me is that the progressTime is larger than the duration of the video. It would say things like 2 minutes of an 11 min video is too high.

So  thought - maybe I have to wait for the player to know the entire duration?

```js
player.on('loaded', async () => {
  const duration = await player.getDuration();
  player.setCurrentTime(progressTime);
});
```

But even then, the `duration` variable is not the real length of the video, much smaller than the actual duration.

Anyone else getting this? It's littering my Sentry and I want to resolve it. I imagine many users aren't having their videos re-instated at the correct position

**Comment by rkrishnan8594** [comment]
Thanks for reporting @wesbos -- we'll take look and follow up on this issue with more information.

**Comment by rkrishnan8594** [comment]
Can you share a clip ID that can be used to reproduce this issue?

**Comment by wesbos** [comment]
Its happening on all my videos, but here is one:

Video ID 174357530 

When trying to setCurrentTime(317)I get  Error: `seconds must be a positive number less than the duration of the video (235).`. Confirmed that the duration from `await player.getDuration()` is `235` 

Now that I explain this, I'm wondering if the player is giving me duration data from a previous video, because this function happens once we change the video ID.

Let me investigate on my end a bit more

**Comment by wesbos** [comment]
Yeah, it seems that player.on('loaded') is fired twice after calling player.loadVideo(ID)` - once for the previous video, one for the next video. 

I can fix this easily by checking if event.id if the one I'm expecting - but Ill leave this open in case this is a bug on your end

**Comment by rkrishnan8594** [comment]
@wesbos Thanks for the additional information. Unfortunately, I'm not able to reproduce this issue - when calling `loadVideo` after an `ended` event, I get a single `loaded` event that includes in the payload the correct `id` of the newly loaded clip.

Here's a JSFiddle I put together to demonstrate: https://jsfiddle.net/rowankrishnan/83wyq6rg/14/

Let me know if I'm missing a detail here.

**Comment by wesbos** [comment]
Thank you for looking into it. Must be something on my end then - Ill dig deeper!
