### ISSUE TITLE
Intermittent "Sorry This video does not exist" on public, embedded videos

### ISSUE THREAD

**Issue by gintermaggio-am** [vimeo/player.js#891]
### Expected Behavior
Public, embeddable videos load consistently

### Actual Behavior
Intermittently, the error "Sorry This video does not exist." appears. Refreshing the page solves the problem.
![image](https://user-images.githubusercontent.com/97045741/216148189-03d6236d-230d-4bcb-9b1b-4df40550a9cb.png)

Also seeing `Failed to load resource: the server responded with a status of 404 (Not Found)` in the console 

### Steps to Reproduce
1. Visit https://www.adaptedmind.com/next/lp/parent-invite
2. Refresh the page multiple times. This issue appears to occur approximately once every 5 page loads.

This appears to affect many or all of our videos.

**Comment by rkrishnan8594** [comment]
Thanks for reporting. We suspect this may be related to a recent platform update and will follow up when we have more information.

**Comment by gintermaggio-am** [comment]
@rkrishnan8594 We have determined that the issue occurs only when URLs have a trailing slash prior to URL params eg:

`https://player.vimeo.com/video/729484447/?autoplay=false&byline=true&controls=false&loop=false&title=false&background=false&responsive=true&dnt=true&quality=auto&` exhibits the behavior but
`https://player.vimeo.com/video/729484447?autoplay=false&byline=true&controls=false&loop=false&title=false&background=false&responsive=true&dnt=true&quality=auto&` does not.

As far as we know, this behavior only started occurring recently- we have had the slash in our code for a while and would have certainly noticed an issue with this frequency.

**Comment by rkrishnan8594** [comment]
Thanks for sharing this detail. We have a patch that should be released this week, but until then the way to avoid this error would be to build the embed URL without the trailing slash before the query string.

**Comment by rkrishnan8594** [comment]
This issue should now be fixed. Thanks again for reporting.
