### ISSUE TITLE
Embedded password protected videos intermittently will not accept password

### ISSUE THREAD

**Issue by erikt9** [vimeo/player.js#892]
May be related to #891

In the vimeo iframe holding the password protected field, sometimes the password form is:

`<form action="https://player.vimeo.com/video/779340354/check-password?referrer=https://filmfreeway.com/" method="post" novalidate=""><div class="vp-validation-bubble hidden"><div class="vp-validation-bubble-arrow-clipper"><div class="vp-validation-bubble-arrow"></div></div><div class="vp-validation-bubble-message"></div></div><input class="js-password" type="password" name="password" placeholder="Password" required="" aria-required="true" aria-label="Password"><input type="submit" value="Watch Video"></form>`

and sometimes(with the same video) it is:

`<form action="https:///video/779340354/check-password?referrer=https://filmfreeway.com/" method="post" novalidate=""><div class="vp-validation-bubble hidden"><div class="vp-validation-bubble-arrow-clipper"><div class="vp-validation-bubble-arrow"></div></div><div class="vp-validation-bubble-message"></div></div><input class="js-password" type="password" name="password" placeholder="Password" required="" aria-required="true" aria-label="Password"><input type="submit" value="Watch Video"></form>`

Note that the host is missing in the form url of the second example.  This produces **Uh oh! There was a problem.**

![Screenshot 2023-02-02 at 4 09 53 PM](https://user-images.githubusercontent.com/49534735/216479593-2a23dfed-7a62-469c-9823-e963aa34c291.png)

**Comment by rkrishnan8594** [comment]
Thanks for reporting this issue - I'm able to reproduce and agree that this seems similar to #891. We'll have someone on our side investigate further tomorrow.

**Comment by rkrishnan8594** [comment]
This issue should now be fixed. Thanks again for reporting.
