### ISSUE TITLE
Disabling pip control

### ISSUE THREAD

**Issue by Adverbly** [vimeo/player.js#895]
### Expected Behavior

I expected one of these to disable the pip button in the player:
- `pip: 0`
- `pip: '0'`
- `pip: false`
- `pip: 'false'`
- `pip: 'None'`

### Actual Behavior

I'm coming from https://github.com/cookpete/react-player, and I'm having no luck changing the vimeo `playerOptions`.

I have also tried manually updating the query params in the `iframe` to `&pip={false | 0 | None | 1}`, and seem to get somewhat inconsistent results. Is this perhaps a bug on the hosting side?  

### Steps to Reproduce

https://codepen.io/adverbly/pen/rNrgPOV

**Comment by rkrishnan8594** [comment]
This issue is fixed.
