### ISSUE TITLE
oEmbed video can't adjust sound when muted or background set

### ISSUE THREAD

**Issue by MindlessPixie** [vimeo/player.js#896]
### Expected Behavior
Vimeo embed set to background and mute to be able to autoplay reliably, and then manually be able to adjust the volume.
This has been working.

### Actual Behavior
When background or mute is set, autoplay works but the volume cannot be adjusted.
The player reports that the volume has changed with getVolume but no sound is played.

### Steps to Reproduce

$oembed_endpoint = 'https://vimeo.com/api/oembed';

Original oembed url that was working.
https://mastersandsavant.com/
`$xml_url = $oembed_endpoint . '.json?url=' . rawurlencode($video_url) . '&width=640&height=480'.($autoplay ? '&background=true&autoplay=true&controls=false' : '&controls=false').'&muted=true'.($loop ? '&loop=true' : '');`
$xml_url generated with these parameters:  &width=640&height=480&background=true&autoplay=true&controls=false&muted=true&loop=true

Behavior with background and mute parameters not set
https://masters.wearedevoir.com/
`$xml_url = $oembed_endpoint . '.json?url=' . rawurlencode($video_url) . '&width=640&height=480'.($autoplay ? '&autoplay=true&controls=false' : '&controls=false').'&muted=false'.($loop ? '&loop=true' : '');`
$xml_url generated with these parameters: &width=640&height=480&autoplay=true&controls=false&loop=true

Not sure if something in the API or embedding has changed. tried multiple combinations but can't get the background and volume working together.

Thank you in advanced

**Comment by rkrishnan8594** [comment]
Thanks for reporting @MindlessPixie. I can confirm that this is a recent regression. We have a fix prepared internally that we will hopefully deploy to production early next week.

**Comment by ptomislav** [comment]
@MindlessPixie 

I had the same issue...

What worked for me today after spending few hours figuring out the issue and trying solutions is setting the `setMuted` method to `false`, which will allow you to set the volume at whatever level you want. 

With that, you can now have background and mute set to true at the start to enable the autoplay. 

Hope it helps!

**Comment by MindlessPixie** [comment]
@rkrishnan8594 Thank you! 

@ptomislav Thanks for the advice, I was thinking something like that could work but didn't see anything muted related in the Player SDK reference

**Comment by ptomislav** [comment]
@MindlessPixie 

Yes, unfortunately it is not mentioned in the reference docs anywhere.
I got the idea from the demo playground - https://player.vimeo.com/api/demo

**Comment by rkrishnan8594** [comment]
This issue should now be fixed.
