### ISSUE TITLE
Video keeps loading on first page visit

### ISSUE THREAD

**Issue by Marcdj-02** [vimeo/player.js#897]
### Expected Behavior
Video should always start when pressed on play.

### Actual Behavior
When Vimeo player is loaded for the first time is keeps loading indefinitely. After a reload the Vimeo player will start immediately. 

### Steps to Reproduce
Load a page with a vimeo player for the first time and press play
Both in Chrome and Firefox

**Comment by rkrishnan8594** [comment]
Can you provide a link where this is reproducible?
