### ISSUE TITLE
requestPictureInPicture() is not working for me 

### ISSUE THREAD

**Issue by piyushacko** [vimeo/player.js#898]
I would like the vimeo video to go in Picture In Picture mode as soon as user scrolls it like it happens in facebook. Currently the user can only go with the controls provided by the vimeo player.

requestPictureInPicture()
which according to the documentation would make the vimeo player go in Picture in Picture Mode. This method I am using in next js front end application but its not working.

Request you to present some examples in the next js application how this method works or what are the parameters I should ensure are there to make this method work

**Comment by bdougherty** [comment]
A couple notes here:

* A user action is required for PiP, so it cannot be done on scroll
* Firefox does not provide the PiP API, so it won't work at all in that browser.

We can't investigate if there is not an example. Feel free to re-open if you can provide one.
