### ISSUE TITLE
On Safari iOS `player.setVolume(0)` does not mute

### ISSUE THREAD

**Issue by JulienPradet** [vimeo/player.js#899]
Hi,

First thanks for any input you may have on this issue. The player served us well for a while now but there's this new issue that happened that I can't really explain.

### Expected Behavior

If volume is managed externally (a custom button), `player.setVolume(0)` should mute the video on Safari iOS (tested on an ipad). Works fine on Chrome.

### Actual Behavior

`player.setVolume(0.7)` successfully unmutes, but when it's `0` it doesn't.

### Steps to Reproduce

https://portfoliold.julienpradet.fr/test/index.html

```
<iframe
    class="video-player__iframe js-video-player-iframe"
    src="https://player.vimeo.com/video/687861885?autoplay=1&loop=1&autopause=0&background=1&muted=1"
    frameborder="0"
    allow="autoplay"
></iframe>
<button>Mute/Unmute</button>

<script src="https://player.vimeo.com/api/player.js"></script>
<script>
    const iframe = document.querySelector('iframe');
    const player = new Vimeo.Player(iframe);

    let muted = true;
    player.on('loaded', function () {
        document.querySelector('button').addEventListener('click', function () {
            if (muted) {
                player.setVolume(0.7);
                muted = false;
            } else {
                player.setVolume(0);
                muted = true;
            }
        });
    });
</script>
```

In case it might help, I've also noticed an error when executing the following code:

```
    const iframe = document.querySelector('iframe');
    const player = new Vimeo.Player(iframe);

    player.on('loaded', function () {
        player.setVolume(0);
    });
```

It throws `NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.` in Safari (iOS and macOS).

The errors seems to exist only since monday 13 feb 2023 with no changes in our code.

**Comment by rkrishnan8594** [comment]
Hi @JulienPradet - my recommendation would be to call `setMuted(true)` instead of `setVolume(0)`, because setting volume is not possible on all devices (the reason why `setVolume(0.7)` works is because we're just unmuting the player under the hood), but we're looking into an internal change that mutes the player when calling `setVolume(0)`.

**Comment by rkrishnan8594** [comment]
This issue should now be fixed.
