### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Dibbledeedoo** [vimeo/player.js#90]

**Comment by bdougherty** [comment]
Going to assume this isn't an issue anymore.

**Comment by Dibbledeedoo** [comment]
Using the example code, but modified for RequireJS, it is erroring out at the line Vimeo.Player(iframe):


>     <iframe src="https://player.vimeo.com/video/76979871" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
>     <script>
>         require(['https://player.vimeo.com/api/player.js'], function (Vimeo) {
>             var iframe = document.querySelector('iframe');
>             var player = new Vimeo.Player(iframe);
> 
>             player.on('play', function() {
>                 console.log('played the video!');
>             });
> 
>             player.getVideoTitle().then(function(title) {
>                 console.log('title:', title);
>             });
>         });
>     </script>

It is loading the video but throwing the error _Uncaught TypeError: Vimeo.Player is not a constructor(…)_ and not loading the functions which follow that line.

**Comment by Dibbledeedoo** [comment]
Sorry, was just updating the issue.

**Comment by bdougherty** [comment]
This is basically a duplicate of #81. See [my comment](https://github.com/vimeo/player.js/issues/81#issuecomment-261575499) there.

**Comment by Dibbledeedoo** [comment]
Cheers. Apologies for the dupe. Not sure why that didn't come up when I searched for require.
