### ISSUE TITLE
Failed to load Vimeo SDK library

### ISSUE THREAD

**Issue by hetalsureshpatel** [vimeo/player.js#904]
### Expected Behaviour
Within our page we have this script tag.
`<script id="vimeo-sdk" src="//player.vimeo.com/api/player.js" onerror="console.error('Failed to load Vimeo sdk')"></script>`

This should load the Vimeo SDK.

### Actual Behaviour
Going through our Sentry logs we see a lot messages `Failed to load Vimeo sdk`.

![image](https://user-images.githubusercontent.com/1858744/223408136-a6e7f2c0-27a1-4728-90e4-90d4b5c7264b.png)

As you can see from the above image. It looks like a Safari issue but we do have other logs that it also users on Windows.

### Steps to Reproduce
We cannot reproduce this error, we have tried on our own devices. The url to test is `https://www.foxtons.co.uk/properties-for-sale/sw1w/chpk2171723`. This is publicly accessible site.

**Comment by rkrishnan8594** [comment]
We will plan to investigate this issue once it's reproducible.

**Comment by bdougherty** [comment]
Without more details, there's really nothing that we can do here. The only thing I can suggest here is that you host the library yourself, or bundle it as part of your build process.
