### ISSUE TITLE
Thumbnail URL unavailable for unlisted videos

### ISSUE THREAD

**Issue by Redmon-JeffHoward** [vimeo/player.js#915]
We have been using the https://vimeo.com/api/oembed.json call to get the thumbnail URL for our "Unlisted" videos to display on our menu for many months.  We noticed today that this call is no longer providing thumbnail information in the JSON return for out "Unlisted" videos.  If I change the privacy setting of a video to something other than "Unlisted", it still works fine.  Is this a new change to the Vimeo system?  Can I no longer use "Unlisted" videos if I want to get the thumbnails dynamically?  Am I doing this wrong?

### Expected Behavior
Privacy set to "Hide from Vimeo".  Thumbnail info returned.
https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/814385915&width=480&height=360

Return JSON:
{
  "type": "video",
  "version": "1.0",
  "provider_name": "Vimeo",
  "provider_url": "https://vimeo.com/",
  "title": "Map - F",
  "author_name": "Douglas Billings",
  "author_url": "https://vimeo.com/user163417920",
  "is_plus": "0",
  "account_type": "pro",
  "html": "<iframe src=\"https://player.vimeo.com/video/814385915?h=06fc1c0a52&amp;app_id=122963\" width=\"480\" height=\"360\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture\" allowfullscreen title=\"Map - F\"></iframe>",
  "width": 480,
  "height": 360,
  "duration": 66,
  "description": "",
  "thumbnail_url": "https://i.vimeocdn.com/video/1647651041-b5be5e8a219ed78eb6940a832fd6c2ca7bbc8eb62e016165263e6f82289f2300-d_295x166",
  "thumbnail_width": 295,
  "thumbnail_height": 166,
  "thumbnail_url_with_play_button": "https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F1647651041-b5be5e8a219ed78eb6940a832fd6c2ca7bbc8eb62e016165263e6f82289f2300-d_295x166&src1=http%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png",
  "upload_date": "2023-04-03 16:22:39",
  "video_id": 814385915,
  "uri": "/videos/814385915"
}

### Actual Behavior
Privacy set to "Unlisted".  Thumbnail info omitted.
https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/814386193/913cb168eb&width=480&height=360

Return JSON:
{
  "type": "video",
  "version": "1.0",
  "provider_name": "Vimeo",
  "provider_url": "https://vimeo.com/",
  "html": "<iframe src=\"https://player.vimeo.com/video/814386193?h=913cb168eb&amp;app_id=122963\" width=\"480\" height=\"360\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture\" allowfullscreen></iframe>",
  "width": 480,
  "height": 360,
  "video_id": 814386193,
  "uri": "/videos/814386193:913cb168eb"
}

### Steps to Reproduce
https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/814386193/913cb168eb&width=480&height=360
Put above link into Chrome browser.

**Comment by rkrishnan8594** [comment]
Closing, as this issue seems to no longer be reproducible.
