### ISSUE TITLE
IE10: iframe not created when using new Vimeo.Player('dom-id', ...);

### ISSUE THREAD

**Issue by jbourassa** [vimeo/player.js#92]
### Expected Behavior
Given:

```html
<div id="made-in-ny"></div>

<script src="https://player.vimeo.com/api/player.js"></script>
<script>
  var madeInNy = new Vimeo.Player('made-in-ny', { id: 59777392 });
</script>
```
The video should load in IE10 just like it does in other browser.

### Actual Behavior
In IE10, the iframe isn't inserted in the DOM

### Steps to Reproduce

Visit this jsbin with IE10: http://output.jsbin.com/wometexeti

**Comment by jbourassa** [comment]
There are two issues to make this work in IE 10 properly:

1. The `const a of b` construct gets transpiled to something that has references to `Symbol.iterator`, but the polyfill isn't included in the build.
2. Doing a cross-origin request on `https://` from a page that is in `http` breaks.

I fixed 1. by replacing this `const a of b` construct but `forEach` (in all cases the loop is over Arrays), and 2. by using `//vimeo.com`. I fiddled with the build to get babel to also inject the polyfills but I ran into issues w/ Rollup.

In the end, I think getting rid of `for of` makes more sense in this context than adding extra polyfills just for 3 simple array loops.

Interested in a PR?

**Comment by jbourassa** [comment]
Hey @bdougherty, thanks for looking into it.

Any thoughts on point 2?

**Comment by bdougherty** [comment]
I'm not really sure about that because we are 100% https, so using a protocol-relative url is going to redirect to https anyway.

**Comment by jbourassa** [comment]
Apparently the protocol-changing redirect doesn't trigger IE10's odd behaviour.

I understand that `//` isn't great because it means taxing all non-HTTPS traffic with an extra request. But otherwise IE10 (and lower?) will not work on non-encrypted website. Meh. Not in big deal in the end since all our production traffic is encrypted, I just noticed when I was debugging locally.

If you're curious, try loading http://jsbin.com/wometexeti/1/edit and https://jsbin.com/wometexeti/1/edit in an old IE, you should be able to reproduce.

Cheers,

**Comment by Med-All** [comment]
Is this was resolved? Somehow I'm not able to get iframe spawned on IE10 using the same method.
