### ISSUE TITLE
cross-site tracking cookies enabled despite `dnt=1` 

### ISSUE THREAD

**Issue by tvercaut** [vimeo/player.js#927]
I haven't found a fix for the issue described below but I believe this is a bug with `dnt=1`.

### Discussed in https://github.com/vimeo/player.js/discussions/889

<div type='discussions-op-text'>

<sup>Originally posted by **tvercaut** January 24, 2023</sup>
Hi,

I am trying to embed a vimeo histed video in a webpage without needing an opt-in cookie policy. I understood that the "do not track", `dnt=1` parameter was designed for that purpose:
https://complianz.io/embedding-vimeo-videos-privacy-friendly/

However, firefox reports that the vimeo player makes use of cross-site tracking cookies despite the DoNotTrack request. As one can see on https://complianz.io/embedding-vimeo-videos-privacy-friendly/ when the browser is configured to block cross-site tracking, the console reports the following:
```
Request to access cookie or storage on “https://player.vimeo.com/video/643915247?title=0&byline=0&portrait=0&badge=0&quality=1080p&dnt=1” was blocked because it came from a tracker and content blocking is enabled.
```

Am I misunderstanding the dnt=1` parameter or is there something else that needs to be done to prevent vimeo from requesting such cross-site tracking cookies.

Many thanks,
Tom </div>

**Comment by georgebid** [comment]
I have also been having issues with dnt not working. I can clearly see it in my URL, as ?dnt=1 but Vimeo cookies are still appearing on my site. More info on this would be great.

**Comment by bdougherty** [comment]
Closing this issue in favor of the existing discussion because this is not an API or API library issue.

**Comment by DATEx2** [comment]
This is still an issue
Cookies are still injected although Chrome is blocking third party cookies - but this is causing weird warnings in console
