### ISSUE TITLE
Update breaking CSP Policies

### ISSUE THREAD

**Issue by slaweknaczynski** [vimeo/player.js#933]
### Expected Behavior
Video loads and works

### Actual Behavior
Getting CSP policy errors since player.js was updated:
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive
Should be working without 'unsafe-eval'

### Steps to Reproduce
Apply CSP policy and don't allow 'unsafe-eval'. This behaviour started since this update - wasn't an issue before. Allow 'unsafe-eval' is bad for security and player.js shouldn't rely on it.

**Comment by pjaws** [comment]
Suffering broken pages today as a result of this update 😢

**Comment by rkrishnan8594** [comment]
We're aware of this issue and are working on a fix - if possible, please use version 2.19.0 until a patch is published.
