### ISSUE TITLE
Embedding with background=1 returns uncaught promise

### ISSUE THREAD

**Issue by klase** [vimeo/player.js#94]
In the previous version, embedding a video with the background=1 option on iOS would display the poster image, but now it just returns a black screen and an uncaught promise:

DOMException: The play() request was interrupted by a call to pause().

Edit: I get this exception only in Chrome dev tools using any iPhone user agent, not on the actual Phone so not sure it's related or if Vimeo just changed the background=1 behaviour.

**Comment by bdougherty** [comment]
This doesn't sound like a bug with the API library. Could you please [contact support](https://vimeo.com/help/contact) instead?

**Comment by Rrrapture** [comment]
@klase Did you get any resolution on this?

**Comment by klase** [comment]
@Rrrapture nope, contacted Vimeo support (see https://vimeo.com/forums/help/topic:286862) but they've been "looking into it" for a over a month now..

**Comment by Rrrapture** [comment]
Thanks @klase !
