### ISSUE TITLE
Frequent `PlaybackError` occurrences

### ISSUE THREAD

**Issue by soulprovidr** [vimeo/player.js#943]
We are embedding Vimeo `<iframe>`s into our product and using the Vimeo Player SDK  to prevent skipping to the end/force users to watch a certain % of our videos.

The full list of functionality our player is using is as follows:

**Methods:**
- `getVideoId`
- `getDuration`
- `setCurrentTime`
- `pause`

**Events:**
- `loaded`
- `seeking`
- `timeupdate`

### Expected Behavior

I would expect our private, embedded videos to play without errors.

### Actual Behavior

This works for the majority of users and in our own testing. However, many users are reporting that the video player either doesn't load, or they encounter an error playing the video. We've added logging via `Sentry` for the `error` event and are seeing a lot of these:

```json
{
  "message": "An error occurred during playback.",
  "name": "PlaybackError"
}
```

This almost exclusively happens in the latest version of Chrome on Macs.

### Steps to Reproduce

We have not been able to reproduce this issue in our own testing and are looking to the Vimeo team for guidance.

Thanks!

**Comment by rkrishnan8594** [comment]
@soulprovidr This error could be thrown under many different circumstances, so reproduction steps would be very helpful in narrowing things down. We could check our logs as well, though, if you provided the clip ID.

**Comment by soulprovidr** [comment]
@rkrishnan8594 Thanks for your quick response! It's difficult for me to provide steps to reproduce the error for two reasons: 1) we don't have videos on any public-facing pages, and 2) we haven't been able to reproduce the error ourselves in our testing.

From our logs I can see that this error recently occurred at July 14, 2023 17:15:58:000 UTC on the video ID 817479741. In this instance, it seems like the user had the page open for ~an hour before attempting to play the video, which [I've read](https://help.vimeo.com/hc/en-us/articles/12425812280081-Troubleshoot-player-error-messages#h_01FZGYD97HNGT9E6N413E3EABK) could be a potential cause of this error.

Do you think that is the case here?

**Comment by soulprovidr** [comment]
We are now working around this by providing a "Reload Player" button when a `PlaybackError` is caught.

**Comment by edwinsp94** [comment]
> We are now working around this by providing a "Reload Player" button when a `PlaybackError` is caught.


I am having the same problem with this specific video ID 860360406, when calling the function play()  @soulprovidr  could you share the solution, thank you.
