### ISSUE TITLE
Enable, disable Transcript

### ISSUE THREAD

**Issue by Fegi** [vimeo/player.js#947]
### Expected Behavior

I need to be able to enable and disable the transcript via javascript as cc.

### Actual Behavior

I cannot find the API info for transcript.

**Comment by rkrishnan8594** [comment]
This feature hasn't been added yet to our SDK, but we're expecting this to introduce support soon.

**Comment by rkrishnan8594** [comment]
The transcript feature can now be disabled via query param. Example: https://player.vimeo.com/video/76979871?transcript=0
