### ISSUE TITLE
Just created video oembed request cached.

### ISSUE THREAD

**Issue by AndreyTepaykin** [vimeo/player.js#955]
### Expected Behavior
Valid resposne from https://vimeo.com/api/oembed.json
### Actual Behavior
Cached response
### Steps to Reproduce
For videos just created on vimeo, oembed request return 404 not found, because video rendering some time. But when video rendered, this request still continue return 404. The problem in cached response. Just need to add some unique param to the url request, for example &anticache=Date.now()

**Comment by rkrishnan8594** [comment]
Thanks for the report @AndreyTepaykin. I'll followup on this issue internally and provide an update to this thread with more information.

**Comment by rkrishnan8594** [comment]
The responses to the oEmbed endpoint are cached for 5 minutes. If you anticipate that some users will be making oEmbed requests prior to the completed upload of the video and want to shorten the expiration time, my suggestion would be to do what you mentioned in your reproduction steps and apply a bunk query param to the request to bust the cache.

**Comment by AndreyTepaykin** [comment]
Sure I did this. Just wanted to note an issue and suggest solution.
