### ISSUE TITLE
NotAllowedError: The play method is not allowed by the user agent

### ISSUE THREAD

**Issue by ilyessr** [vimeo/player.js#956]
Hi everyone,

I recently added a play button overlay to enhance the aesthetics of my video player. When the button is clicked, it triggers vimeo.play, but I'm encountering an error message: "notAllowedError: The play method is not allowed by the user agent."

As far as I understand, a click should be considered a direct user interaction, so I'm a bit puzzled by this error. Has anyone else experienced this issue, and do you have any suggestions for a workaround or solution? Your insights would be greatly appreciated!

Thanks in advance !

**Comment by rkrishnan8594** [comment]
Hey @ilyessr, do you mind providing steps for reproduction?

**Comment by bdougherty** [comment]
Closing this issue for now. @ilyessr please re-open if you can provide us with some more details about your environment so we can reproduce and debug.
