### ISSUE TITLE
Feature Request: Set class on iframe generated by Vimeo API.

### ISSUE THREAD

**Issue by regiside** [vimeo/player.js#958]
It would be nice if there was an "class" option that would add a class to the generated iframe. Or at least an event that fired as soon as the iframe was created. I had a situation where i needed the iframe to have a class but since it was generated programmatically I was having a tough time figuring out how to add it.

For now I'm using this workaround:

```
vimeoPlayer.on('loaded',function() {
             jQuery('.video-wrapper iframe').addClass("skip-nectar-video-size");
         });
```

**Comment by rkrishnan8594** [comment]
@regiside Thanks for the feature request. Out of curiosity, what's the downside of the approach that you have now? Is it that there's a delay in styles that are applied to the iframe?

**Comment by regiside** [comment]
Yeah, the on.loaded event is working fine in my case but it’s adding a class which tells another JavaScript function (which I don’t have access to) to skip processing on this iframe. So it’s possible it could cause a race condition where the other JavaScript applies before the on.load fires. It’s also just not very intuitive to have to write your own JavaScript to be able to target the generated iframe in css. Thanks!

**Comment by rkrishnan8594** [comment]
Thanks for the explanation. I've added this feature request to our backlog.
