### ISSUE TITLE
OpenAPI  video custom metadata (= free-form field)

### ISSUE THREAD

**Issue by drzraf** [vimeo/player.js#959]
(NB: Vimeo supports redirected me here. I previously posted in https://github.com/vimeo/openapi/ but said repository is deprecated.)

The current specifications makes clear that every field has a determined purpose from the PoV of Vimeo system (storage, frontend, player, metadata, administration, ...)

But there is no user-defined metadata : A metadata field (or set of fields, possibly prefixed or nested), which can be set and queried, usable from the API (at least) and not necessarily public but would contain arbitrary content (4 kB blob/string/...)

The point is to let a user convey additional data alongside video instead of having to use a 3rd-party storage backend/listing/table/...

A common and obvious use-case come to mind:

- A user coming from Youtube wants to store the original ID/URL/... of my YT videos alongside Vimeo videos in order to mirror, then transition efficiently away from the YT channel

Custom field could hold internal UUID, or something more complex related to a specific video (regarding ads, a/b testing, IA, versions, ...)
Considering custom metadata as 4kB of free private "metadata storage" alongside each video would be useful !

**Comment by rkrishnan8594** [comment]
Hi @drzraf - thanks for the feedback. This project (Player.js) is unrelated to the Vimeo API, but I'll forward your suggestion to our API team for consideration.
