### ISSUE TITLE
mp4 url in the source code on mouse right click

### ISSUE THREAD

**Issue by webprus** [vimeo/player.js#96]
Hi~ I'm vimeo Pro user.
We are make a commercial site for selling mp4 video.
But. Mouse right click on the play bar on the Vimeo player to see the source code view.
and You can download it directly by clicking on the mp4 url.(Oh my god)
I can't no way to stop mouse right click.
Why do not vimeo block the right mouse button?

**Comment by bdougherty** [comment]
This question is not related to the player api library. Please contact support: https://vimeo.com/help
