### ISSUE TITLE
User Access Token

### ISSUE THREAD

**Issue by zardasht-jazaa** [vimeo/player.js#960]
### Expected Behavior
userToken should upload Video
### Actual Behavior
userToken Scope is Always Public.
as In Vimeo Authentication Documentation says:  You can't use the access token from the client credentials grant to get anything other than public data, even if you specify additional scopes. 
### Issue
 can I use userToken For uploading Video, like creating Token From my app credentials and client Secret to generate token, then use this token to my users upload video by it ?

**Comment by jdreetz** [comment]
Hey @zardasht-jazaa, you might want to contact Vimeo directly - http://www.vimeo.com/help/contact . This repo mostly deals with the Vimeo Player SDK. Sounds like you have a question about the [Vimeo API](https://developer.vimeo.com/api/authentication).
