### ISSUE TITLE
DateTime property `uploadDate` is missing a timezone - in VideoObject JSON-LD schema markup

### ISSUE THREAD

**Issue by rr-it** [vimeo/player.js#964]
The embedded iframe players source URL contains VideoObject JSON-LD schema markup.
This markup can be improved.

E.g. embed code:

```html
<iframe src="https://player.vimeo.com/video/185774192?h=62f66b8437" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
```

Schema markup:

```html
<script type="application/ld+json">
{
   "embedUrl":"https://player.vimeo.com/video/185774192?h=62f66b8437",
   "thumbnailUrl":"https://i.vimeocdn.com/video/595625605-32c9d7cad3f376eecefcc010efa34db816e61b167e0214ccc341810f01e466d0-d_640?f=webp",
   "name":"…",
   "description":"…",
   "duration":"PT599S",
   "uploadDate":"2016-10-06 04:59:57",
   "@context":"https://schema.org/",
   "@type":"VideoObject"
}
</script>
```

### Expected Behavior

`uploadDate` is of type `DateTime` and must include a timezone.

* See [Google Search Central --> Video structured data: VideoObject properties](https://developers.google.com/search/docs/appearance/structured-data/video?hl=en#video-object)

* See [Schema.org --> DateTime](https://schema.org/DateTime):
> A combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm] (see Chapter 5.4 of ISO 8601).

Either add `Z`:

```html
<script type="application/ld+json">
{
   "uploadDate":"2016-10-06 04:59:57Z"
}
</script>
```
or  add `+00:00`:

```html
<script type="application/ld+json">
{
   "uploadDate":"2016-10-06 04:59:57+00:00"
}
</script>
```

### Actual Behavior

`uploadDate` has no timezone set:

```html
<script type="application/ld+json">
{
   "uploadDate":"2016-10-06 04:59:57"
}
</script>
```

#### In Google Rich Results Test

https://search.google.com/test/rich-results/result?id=FvBtMHg6zZkUrRTeq0pYdg&hl=en

![grafik](https://github.com/vimeo/player.js/assets/29690343/e25bd809-c060-4eb8-a4c0-cc23b6d31d84)

#### In Google Search Console

1. Embed an iframe on your own website - e.g.:
  ```html
<iframe src="https://player.vimeo.com/video/185774192?h=62f66b8437" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
```

2. Get a notice for your own domain (not `vimeo.com`) in Google Search Console:

![grafik](https://github.com/vimeo/player.js/assets/29690343/cb0b10cb-af1d-4c21-bcd2-41d3d61f61a2)

 **More details from Google Search Console:**

```html
[…]
<div class="embed-responsive embed-responsive-16by9">

<!--@ inlined-iframe <iframe data-src="https://player.vimeo.com/video/[…]?dnt=1&amp;title=0&amp;byline=0&amp;portrait=0" allowfullscreen="" width="1050" class="lazyload-transition lazyloaded" title="[…]" allow="fullscreen" src="https://player.vimeo.com/video/[…]?dnt=1&amp;title=0&amp;byline=0&amp;portrait=0"> @-->

<DIV>

[…]

<div id="player" class="player player-[…] js-player-fullscreen with-fullscreen with-sticky-custom-logo touch-support is-google-bot mobile player-normal player-xs app-xs right-content-area-open right-content-area-supported">[…]

[…]

<script type="application/ld+json">
{
   "embedUrl":"https://player.vimeo.com/video/…?h=…",
   "thumbnailUrl":"https://i.vimeocdn.com/video/…-d_640?f=webp",
   "name":"…",
   "description":"…",
   "duration":"PT585S",
   "uploadDate":"2023-10-29 16:06:40",
   "@context":"https://schema.org/",
   "@type":"VideoObject"
}
</script>

[…]

<!--@ end-inlined-iframe @-->

</div>
[…]
```

**Comment by hubgittering** [comment]
Just commenting to add that I to have been receiving the same Google Search Console error since November 4 2023:
"Datetime property "uploadDate" is missing a timezone"

As documented above, the error is from the embedded iframe player's source URL (player.vimeo.com) which contains VideoObject JSON-LD schema markup with "uploadDate" missing the timezone.

**Comment by rkrishnan8594** [comment]
@rr-it @hubgittering Thanks for the report. We're aware of this warning by the GSC and will work on deploying an update soon that should resolve the issue. Please note that the timezone is optional and will not impact the indexing of your embedded video.

**Comment by SachinthaI** [comment]
@rkrishnan8594 Any update on this? I'm having the same issue.

**Comment by rkrishnan8594** [comment]
Hey all - this issue has been fixed as of last week. You should now see a timezone string appended to the upload date string.

**Comment by rr-it** [comment]
Looks good! We can now start the validation in Google Search Console -> Enhancements -> Videos:

![grafik](https://github.com/vimeo/player.js/assets/29690343/7b80dfb0-fb1d-41d0-8edd-72b1aec78edf)
