### ISSUE TITLE
Video Embed as a Background Inconsistent Looping

### ISSUE THREAD

**Issue by npruzaniec** [vimeo/player.js#965]
### Expected Behavior
Background video will loop infinitely.

### Actual Behavior
Video stops without looping or stops looping at some later moment. Can take 5 or 6 loops sometimes.

### Steps to Reproduce
Possibly related to #349 

The video loops most of the time fine - but will stop at the end sometimes on the first play - sometimes on subsequent loops. I have also tried with only background=1 set with the same result. This may be an account or video level setting as a video from another account with this same code (`290546510`) does not have an issue looping.

Here is my embed code:

```
<iframe
  src="https://player.vimeo.com/video/894658804?background=1&autoplay=1&loop=1&autopause=0&muted=1"
  class="o-video-autoplay__iframe"
  width="100%"
  height="100%"
  frameborder="0"
  allow="autoplay; encrypted-media"
  role="presentation"
  loading="lazy"
></iframe>
```

Local dev environment.
M1 MacBook Pro
Chrome 120.0.6099.216

### Demo
https://codepen.io/npruzaniec/pen/rNRMyBw

**Comment by rkrishnan8594** [comment]
Thanks for reporting this bug @npruzaniec. We've identified the issue internally and have a fix prepared. I'll follow up when it has been deployed, after which point you will be able to re-upload your video to eliminate the issue.

**Comment by rkrishnan8594** [comment]
Our fix for this issue has been deployed. Let us know if you're still encountering this bug upon re-upload.

**Comment by npruzaniec** [comment]
Can confirm – after a re-upload of the video – the embed code now properly loops the video indefinitely. Thanks @rkrishnan8594!
