### ISSUE TITLE
Background parameter doesn't load the player.module.js

### ISSUE THREAD

**Issue by DowleyDeveloped** [vimeo/player.js#967]
### Expected Behavior
When loading a video player.module.js and player.css should be loading

### Actual Behavior
When using the background=true or background=1 parameter the loading of the module JS and CSS is intermittent. Which is causing some display issues.

### Steps to Reproduce
https://player.vimeo.com/video/76979871?autoplay=1&loop=1&muted=1 <- Always loads the module js and css
https://player.vimeo.com/video/76979871?autoplay=1&loop=1&muted=1&background=1 <- Loading is intermittent (may need some refeshes)

Can this be fixed so the module always loads?

**Comment by rkrishnan8594** [comment]
Hi @DowleyDeveloped - thanks for filing an issue. We're currently trialing a new version of our background mode player with the aim of improving performance, which is why in some cases you may see `background.js` and in others, `player.module.js`. That being said, there should not be any display issues in either version. Do you mind elaborating on what you're noticing?

**Comment by DowleyDeveloped** [comment]
Hi @rkrishnan8594 

It's causing all videos to be super zoomed in due to parent CSS around the iframe (due to the object-fit="cover:" on the video. We can't do anything as the html keeps changing when you refresh.

This has been happening for the past few weeks, so we really need something consistent to work against.

**Comment by jdreetz** [comment]
@DowleyDeveloped can you share the markup you're using to embed background iframe?

**Comment by DowleyDeveloped** [comment]
Hi @jdreetz 

We use the Plyr library which uses Vimeo's player.js

https://toward.studio/work/cardiff-city-fc

There's a video here which I've had to hack using CSS (incredibly messy) on `plyr__video-embed__container` to stop the zoom.

Kind regards,
Charlie

**Comment by rkrishnan8594** [comment]
@DowleyDeveloped Do you mind sharing a JSFiddle or Codepen where the issue can be reproduced?

**Comment by DowleyDeveloped** [comment]
@rkrishnan8594 Here you go: https://codepen.io/Charlie-Dowley/pen/XWGEzwd

It may take a few refreshes. But it only zooms when the vimeo module js isn't used.

**Comment by jdreetz** [comment]
@DowleyDeveloped thanks for providing that test page. We've turned off the new background player for now while we investigate the issue. So you should only be getting the previous background player now. Let us know if you still see that issue occurring.

**Comment by DowleyDeveloped** [comment]
Hi @jdreetz 

Thanks so much, been a huge help!
