### ISSUE TITLE
Deprecated methods in Chrome for Android

### ISSUE THREAD

**Issue by sashasushko** [vimeo/player.js#99]
Deprecated methods in Javascript API only in Android Chrome:
![deprecated-methods-mobile-chrome](https://cloud.githubusercontent.com/assets/4469056/21638905/7277760c-d27e-11e6-9f54-5e66ba42b046.png)

- deviceorientation
- webkitSupportFullscreen
- webkitEnterFullscreen
- webkitDisplayingFullscreen

There isn't warnings in desktop Chrome and mobile Firefox or Safari.

**Comment by sashasushko** [comment]
With `DOMExeption` I have not yet figured out.

**Comment by bdougherty** [comment]
We use those older apis in older WebKit, so we can't remove the calls to them. Once they are removed from Chrome, you'll stop seeing those messages.

Closing this because it's not actually related to the player api library.
